// app/src/copy/en.ts — English UI copy. Keys must match ko.ts exactly.
export const en = {
  appName: 'Niunnaeun',
  tagline: 'Your AI compass for understanding yourself and others',
  // 홈 카드 개인화 티저 — ko 와 동일 키(계산=homeTeaser.ts). ※ newyear.keyword 값 자체는 엔진이 한국어로 산출(기존 티저 전반과 동일).
  teaser: {
    career: 'Founder {{biz}}% · Employee {{org}}%',
    newyear: "This year's keyword · {{keyword}}",
    flow: 'Phase {{n}} now · {{turns}} turning points',
    crush: '{{year}} · month {{months}} — attraction rises',
    reunion: '{{year}} · month {{months}} — good to reconnect',
    job: '{{years}} — doors open',
    raw: '{{text}}', // image·talent·mission — text is engine-generated Korean (same approach as newyear.keyword), same value across locales
  },
  onb: {
    skip: 'Skip', next: 'Next', start: 'Start my analysis',
    t1: "The AI that analyzes 'you'",
    b1: 'Niunnaeun is not a horoscope app. It uses Saju as its engine to analyze who you are — a self-understanding tool.',
    t2: 'We compute your own chart',
    b2: 'Your birth data is calculated with a precise perpetual-calendar engine (true solar time, historical corrections) — an analysis that is yours alone.',
    t3: "What you'll understand",
    l1: 'Who you are — traits & strengths', l2: 'Why your relationships repeat', l3: 'What work fits you', l4: 'What to prepare this year',
    t4: "Here's how we analyze you", pvBadge: 'Sample', pvType: 'Teto type', pvScale: 'Teto 63%', pvLine: 'Decisive and driven — though a little rest now and then is your real strength.', pvNote: 'Just enter your birth details for your own analysis',
  },
  // ★App Store 4.3 (spam/duplicate) — surface that results are COMPUTED (used by ComputedNote).
  //   Reviewer sees the app in English, so this block must read clearly on its own.
  computed: {
    title: 'Computed from your exact birth data',
    body: 'A perpetual-calendar engine (true solar time, longitude, historical DST) builds your individual chart, then 40+ codified classical rules are applied to it — no two people get the same result.',
    badge: 'Computed from your birth data',
    more: 'It also computes hidden stems, clashes/combinations/punishments, sinsal, and luck cycles, then cross-validates two traditions — Saju and Zi Wei Dou Shu.',
  },
  menu: {
    relationmap: 'Relationship Map', relationmapDesc: 'Everyone you saved, and what they are to you — on one page',
    'taemong': 'Conception Dream', 'taemongDesc': 'Reading the dream that came while waiting for a child', 'taemongTileDesc': 'Dragon, tiger, carp… conception-dream symbols, free',
    'egenteto': 'Egen vs Teto',
    lookback: 'Look back', lookbackDesc: 'Your notes next to that day\'s reading',
    myeongsik: 'Register Chart', myeongsikDesc: 'Add & manage your chart',
    manse: 'Manseryeok', manseDesc: 'Calendar charts & management', timeResolve: 'Find Your Hour', timeResolveDesc: 'Infer your birth hour from life events',
    ziwei: 'Zi Wei Dou Shu', ziweiDesc: 'Palaces & stars reading',
    taro: 'Tarot', taroDesc: "Today's card",
    today: 'Daily Fortune', todayDesc: 'Changes every day', month: 'Monthly Fortune', monthDesc: "This month by area",
    compat: 'Compatibility', compatDesc: 'Deep relationship analysis',
    premium: 'Premium Reading', premiumDesc: 'Deep reading · all areas', premiumTag: 'Premium',
    timeline: 'Life Timeline', timelineDesc: 'Decade-by-decade, age 10–100',
    pet: 'My Pet', petDesc: "Your companion's nature", love: 'My Love Flow', loveDesc: 'Ideal type & who you meet, in detail',
    lifegraph: 'Life Graph', lifegraphDesc: 'Your life-flow curve & turning points by decade',
    newyear: 'New Year', newyearDesc: 'Year overview · monthly · samjae',
    roots: 'Roots', rootsDesc: 'Shown self · hidden strength · true power',
    image: 'How You Appear', imageDesc: 'First impression & vibe to others',
    impression: 'How Others See You', impressionDesc: 'From first impression to a deep bond',
    mission: 'My Calling', missionDesc: 'What you were born to do',
    persona: 'Personality', personaDesc: 'Your 16 saju personality types', egen: 'Egen vs Teto', attach: 'Attachment', mbti: 'Saju MBTI', traits: 'My Traits', selfAnalysis: 'My Analysis', selfAnalysisDesc: 'Personality, temperament & element balance at a glance', relationPattern: 'Relationship Pattern', relationPatternDesc: 'Why your relationships repeat — your innate relational nature', personal: 'Personal Element', personalDesc: 'Colors, style, makeup & car colors for your element', gem: 'My Saju Gemstone', gemDesc: 'Your birthstone may not fit you — the gem that truly lifts you', sokgunghap: 'Intimate Match', sokgunghapDesc: 'Sexual compatibility of two people (adult · fun)', community: 'Community', communityDesc: 'Share saju, love & life questions together', joseonjob: 'Joseon Job', lovestyle: 'Love Style', bok: 'Your Fortune', pastlife: 'Past Life', healing: 'My Healing',
    taegil: 'Lucky Days', country: 'My Best Place', countryDesc: 'Countries that fit your energy', taegilDesc: 'Best days for wedding · moving · contracts',
    luck: "Today's Luck", luckDesc: 'Lucky color · direction · number',
    zodiac: 'Zodiac', zodiacDesc: 'Daily Chinese & star sign',
    name: 'Name Reading', nameDesc: 'The five elements in your name',
    dream: 'Dream Guide', dreamDesc: 'Search by dream keyword',
    dayPillar: 'Day Pillar', dayPillarDesc: 'Your nature by your birth day', career: 'Founder or Employee', careerDesc: 'Your two paths: business vs job', gaeun: 'Lucky Boost', gaeunDesc: 'Lift your luck for this cycle', followupDesc: 'Ask one more about your reading', talent: 'My Innate Talent', celeb: 'Celebrities Like Me', celebDesc: 'Compare your chart with actors and idols', talentDesc: 'Your gifts, drive, and money style', numerology: 'Numerology', numerologyDesc: 'Your life path and talents by number', astrology: 'Zodiac & Astrology', astrologyDesc: 'Your star sign + full natal chart',
    child: 'Children', childDesc: 'Your bond, their nature, you as a parent', future10: 'Me in 10 Years', future10Desc: 'Your life 10 years on, by luck cycles', reunion: 'Reunion', reunionDesc: 'When & whether an old love may reopen', crisis: 'Rough patches', crisisDesc: 'Shaky seasons read as structure — seats and forces, not fortune-telling', crush: 'Crush & Attraction', crushDesc: 'Whether it can bloom · who is drawn to you · when to approach', job: 'Job & Career Move', jobDesc: 'When hiring, a move, or an exam is likely to land', jobfit: 'Careers That Fit', jobfitDesc: 'Which careers suit your nature — desire vs ability gap', wealth: 'Wealth Deep Report', wealthDesc: 'Your wealth capacity & type, when it flows in, and how to keep it', reunionAsk: 'Can we reunite?', reunionAskDesc: 'Free: reunion odds & best months to reach out', crushAsk: 'Will it bloom?', crushAskDesc: 'Free: your charm & when the spark ripens', jobAsk: 'When will I land it?', jobAskDesc: 'Free: when hiring & exams open up',
    saju: 'Saju', sajuDesc: 'Reading · timeline · compatibility', ziweiHub: 'Zi Wei', ziweiHubDesc: 'Chart · luck · compatibility',
    secLove: 'Love', secLoveDesc: 'Compatibility, bonds, and timing',
    secToday: 'Fortune', secTodayDesc: 'Today, this month, this year',
    secSelf: 'About Me', secSelfDesc: 'Personality and how others see you',
    secWork: 'Work & Wealth', secWorkDesc: 'Aptitude, jobs, and money',
    secHidden: 'More', secHiddenDesc: 'Found through recommendations',
    chipLove: 'Love', chipToday: 'Fortune', chipSelf: 'Me', chipWork: 'Work', chipHidden: 'More',
    secLife: 'Life', secLifeDesc: 'Tarot, Zi Wei, and lighter reads',
    secTool: 'Tools', secToolDesc: 'Look it up yourself in the almanac',
    chipLife: 'Life', chipTool: 'Tools',
    chipAll: 'All',
    secContent: 'Popular', // ★shortcut row (outside the topic axis)
    // (legacy) price-axis labels — unused after the topic rework; kept for an easy revert.
    secFree: 'Today & Chart', secPremium: 'Understand Yourself', secSpecial: 'Special', secDeep: 'Know Yourself', secLight: 'For Fun',
    viewCard: 'Cards', viewList: 'List', // home view toggle
    todayTileDesc: "Today's flow", monthTileDesc: "This month's flow", newyearTileDesc: "This year's keyword & 12 months", personaTileDesc: 'Saju personality type', taegilTileDesc: 'Pick a good day', luckTileDesc: "Today's luck", zodiacTileDesc: 'Zodiac & star sign', nameTileDesc: "Name's sound energy", dreamTileDesc: 'Dream meaning', egenTileDesc: 'Are you Egen or Teto?', attachDesc: 'Your chart next to a survey', mbtiTileDesc: 'Your MBTI by saju', joseonjobTileDesc: 'Your job in old Korea', lovestyleTileDesc: 'Your love cells?', bokTileDesc: 'Your innate fortune?', pastlifeTileDesc: 'Who were you?', healingTileDesc: 'Your way to rest?',
    secPremiumDesc: 'Who you are — in depth via Saju & Zi Wei', secContentDesc: 'AI-crafted deep readings', secHotDesc: 'What people are looking at most right now', secDeepDesc: 'Look deeper into who you are', secLightDesc: 'Light daily fun',
  },
  bug: {
    title: 'Report a Bug', send: 'Send',
    desc: 'Tell us what felt off or went wrong. If you note which screen you were on and what you did, we can fix it much faster.',
    what: 'What happened?',
    placeholder: 'e.g. I tapped Compatibility and the screen just kept spinning',
    contact: 'Where to reply (optional)', contactHint: 'Email or similar — feel free to leave blank',
    autoInfo: 'Your app version and device type are sent along (used only to track down the problem).',
    doneTitle: 'Thank you for the report',
    doneBody: 'A developer reads every report. We will get this fixed within a few days.',
    failTitle: "Couldn't send",
    failBody: 'Please try again shortly. If it keeps failing, you can email us at the address below.',
  },
  relmapCard: { title: 'Relationship Map', lead: '{{name}} is {{role}}', more: 'See the whole map ›' },
  relmap: {
    mapCap: 'The map shows the closest {{n}} across every role — the other {{r}} are listed below.',
    joinedTitle: 'Someone joined', joinedBody: '{{n}} new on your map.',
    invite: 'Send an invite link', inviting: 'Making a link…',
    inviteNote: 'Your friend opens the link, enters their birth date, and takes a place on your map. Links close after 7 days.',
    shareMsg: 'Take a spot on my relationship map — just your birth date',
    needLoginTitle: 'Sign in first',
    needLoginBody: 'What your friends enter arrives through your account, so invite links need you signed in.',
    title: 'Relationship Map', me: 'me', count: '{{n}} people', hint: 'the closer, the better the chemistry',
    list: 'Best fit first', summary: 'This is the shape of your map',
    emptyOthers: 'It is just you so far. Add a birth date for family or a friend and you will see what kind of presence they are to you.',
    emptyMe: 'Register your own chart first — that is the reference every relationship is read against.',
    addFriend: 'Add someone', addMe: 'Register my chart',
    giving: 'You are the one pouring out more often. That care is worth something, but keep at least one place where you receive.',
    taking: 'Plenty of people fill you up. Make somewhere for it to flow onward so the energy does not pool.',
    balanced: 'Give and take run evenly here. Nothing tips too far one way, so relationships rarely drain you.',
    lacking: 'Your chart has no {{el}} energy — people carrying it are especially precious to you.',
    adjusted: 'Their day sign is {{from}}, but {{to}} dominates the whole chart — so we read them as {{to}}.',
    caution: 'Watch for', advice: 'What helps',
    more: 'To fill the map out',
    moreBody: 'The more people on it, the clearer the grain of your relationships. A birth date is all it takes to place someone.',
  },
  common: { save: 'Save',
    'more': 'More',
    retryLaterNoCharge: 'Please try again shortly. No woon was used.',
    'add': 'Add',
    'confirm': 'OK',
    'delete': 'Delete',
    'edit': 'Edit',
    'retry': 'Try again',
    'retryLater': 'Please try again in a moment.',
    'tapToClose': 'Tap to close',
    back: '← Back', login: 'Log in', signup: 'Sign up', logout: 'Log out', loggingOut: 'Logging out…',
    comingSoon: 'Coming soon.', error: 'Error', loginOptional: 'Log in / Sign up (for paid & saving — optional)',
    cancel: 'Cancel', none: 'None',
    llmBusy: 'Readings are temporarily unavailable right now. Please try again in a little while.',
    llmMaking: 'This reading is already being prepared. Please check back in a moment.',
    genFailed: 'Could not load the reading. Please try again in a little while.',
  },
  auth: {
    'login': 'Log in',
    signin: 'Log in', signupTitle: 'Sign up', email: 'Email', password: 'Password (6+ chars)',
    toSignup: "Don't have an account?  Sign up", toSignin: 'Already have an account?  Log in',
    needInput: 'Enter your email and password.', signupDone: 'Verification email sent. Verify, then log in.',
    or: 'or', google: 'Continue with Google', apple: 'Continue with Apple', naver: 'Continue with Naver', processing: 'Signing in…',
  },
  register: {
    'pickCategory': 'Choose a category',
    'catDelHint': 'Deleting a category moves its charts to “Other”. “Other” cannot be deleted.',
    'catDeleteTitle': 'Delete category',
    'editDone': 'Done',
    'exactTime': 'I know the exact time (corrected to true solar time by birthplace longitude)',
    'hour24': 'Hour (0-23)', 'hourHint': '{{h}}:00 = {{hint}}',
    'invalidDateTitle': 'Please check the birth date',
    'minute': 'Min',
    'newCategory': 'New category',
    'newCategoryPh': 'New category name',
    'orSijin': 'Or if you only know the 2-hour period',
    'placeSearchBlocked': 'Place search is limited for a moment. Please try again in about 30 seconds.',
    'placeSearchFailed': 'Couldn\'t load place search. Please check your connection.',
    name: 'Name / Alias', namePh: 'e.g. John / Me',
    birthDate: 'Birth date (YYYY-MM-DD)', birthDatePh: '1990-03-15',
    birthTime: 'Birth time (HH:mm, blank if unknown)', birthTimePh: '07:10',
    calendar: 'Solar / Lunar', solar: 'Solar', lunar: 'Lunar', normalMonth: 'Regular', leapMonth: 'Leap',
    sex: 'Sex', male: 'M', female: 'F',
    birthPlace: 'Birthplace', birthPlacePh: 'Tap to search city',
    relation: 'Relation', submit: 'Calculate · Register',
    birthTimeSijin: 'Birth time (Sijin)', timeUnknown: 'Unknown', selfLabel: 'Self', makeRep: 'Set as main chart',
    relationCustom: 'Custom', relationCustomPh: 'Enter relation (e.g. my boss)',
    ctxTitle: 'Tell us about you (optional)', ctxDesc: "Helps make this chart's readings more accurate. You can leave it blank.",
    ctxSit: 'What best describes you now?', ctxSitDesc: 'Readings will speak to this situation',
    sitStudy: 'Student', sitWork: 'Employed', sitBiz: 'Business owner', sitFree: 'Freelance',
    sitHome: 'At home / parenting', sitSeek: 'Job seeking', sitRetire: 'Retired', sitEtc: 'Other',
    ctxJob: 'Occupation', ctxJobPh: 'e.g. designer / self-employed / student',
    ctxRel: 'Relationship', ctxRelSingle: 'Single', ctxRelDating: 'Dating', ctxRelMarried: 'Married', ctxRelOther: 'Other',
    ctxConcern: 'Current focus', ctxConcernPh: 'e.g. career change, new relationship, health',
    ctxNote: 'Note', ctxNotePh: 'Anything you want the reading to consider',
    selfExistsTitle: 'You already have a self chart', selfExistsMsg: "Only one self chart is allowed. Move the current self chart to 'Other' and set this one as your self chart?", selfReplace: 'Set as self',
    birthPlaceSearch: 'Search city/region', birthPlaceSearchPh: 'e.g. Seoul, Tokyo', useAsIs: "Use '{{q}}'",
    limitTitle: 'Free registration limit', limitMsg: 'The free plan lets you register up to {{limit}} charts.\nWatch an ad to add one more, or upgrade to Pro for unlimited.',
    upgrade: 'Upgrade to Pro', usage: 'Charts {{count}}/{{limit}}',
    watchAdAdd: 'Watch ad, add 1', adNotFinished: 'Finish the ad to add a chart.',
  },
  myeongsik: {
    palja: 'Four Pillars', dayMaster: 'Day Master', strength: 'Strength index', pattern: 'Pattern', patternRevealed: 'revealed', patternHidden: 'latent',
    stages: '12 Stages', interactions: 'Combos/Clashes', sinsal: 'Sinsal/Void', gongmang: 'Void',
    noHit: 'no natal hit', ziwei: 'Zi Wei', lifePalace: 'Life Palace',
    readingBtn: 'See area readings →', noChart: 'No chart data.',
    root: 'Root', hidden: 'Hidden stems',
    luck: 'Luck cycles', daewoon: 'Decade', sewoon: 'Year', elements: 'Five elements',
    합: 'Combine', 충: 'Clash', 형: 'Punish', 해: 'Harm', 파: 'Break', 극: 'Control',
    sinsalHint: '✓ (pillar) if the branch is in the natal chart; otherwise it activates in luck cycles', ssLuck: 'in luck', dayPillar: 'Day pillar',
    sinsalDetail: 'Sinsal & Void in detail →',
  },
  reading: {
    'lockedNote': 'Open with the button above to see it all.',
    'lockedTitle': 'Readings for this chart open with Luck',
    'pastYearBadge': 'This reading was written for the {{y}} annual cycle — regenerate it to reflect this year\'s flow.',
    'recommend': 'You might like these too',
    'renew': '🔄 Regenerate with the latest reading',
    'sajuTitle': 'Saju Reading',
    title: 'Full Reading · Premium', sub: 'All 16 areas in one deep, precise reading. (Chart is free)',
    runAll: 'See full reading ({{count}})', progress: 'Reading ‘{{current}}’… ({{done}}/{{total}})', generating: 'Crafting your reading…', saveFail: 'Failed to save chart. Please try again.', refreshStale: 'Update to latest reading', refreshDeniedTitle: 'Refresh limit', refreshDenied: 'This reading can be refreshed up to {{cap}} times.',
    ziweiTitle: 'Zi Wei · 12 Palaces · Premium', ziweiSub: 'All 12 palaces interpreted together. (Chart is free)',
    timelineTitle: 'Life Timeline · Premium', timelineSub: 'Age 10–100, one decade at a time — what each phase holds.',
    bannerPremium: 'Subscribed — unlimited readings', bannerTrial: '🎁 First reading free!',
    bannerGated: 'Pick an area to unlock via ad or subscription',
    base: 'Core', past: 'The road so far', overlay: 'Now', future: 'The road ahead', remedy: 'Advice',
    premiumAlert: 'Premium Reading', premiumAlertMsg: 'Pay {{price}} for the deep reading.',
    payPerUse: 'Pay {{price}}', bannerPerUse: '✨ Only the first area is a preview — unlock all for {{price}}', bannerUnlocked: '✨ Unlocked — generate the full reading',
    askTitle: 'Ask a follow-up', askPh: 'Ask anything more about this reading',
    askSend: 'Ask', askFree: '{{n}} free question(s) left', askPaid: "Free questions used up — {{price}} per extra question",
    askPremiumTitle: 'Premium only', askPremiumMsg: 'With Premium you get 2 free follow-up questions per area.',
    askPremiumCta: 'Ask more with Premium', askPayTitle: 'Follow-up', askPayMsg: "You've used your free questions. Ask one more for {{price}}?",
    askPayBtn: 'Pay {{price}}', payPending: 'Coming soon',
  },
  compat: {
    'stillMaking': 'Almost there — we will show it the moment it arrives.',
    'comeBackLater': 'Still being written. Reopen this screen in a bit and your reading will be here.',
    'genConfirm': 'Create',
    'genCta': 'Create this relationship reading',
    'genTitle': 'Create reading',
    'otherPick': 'Pick a person · Add someone new',
    'scoreHarmony': 'Harmony',
    'scoreTension': 'Tension',
    'step1': '① Who shall we look at?',
    'step2': '② What\'s your relationship?',
    'step3year': '③ Which year?',
    'wizPickShort': 'Tap to choose',
    'yearPick': 'Choose a year',
    otherInfo: "Partner info (consent required)", otherDatePh: "Partner birth date 1992-07-03",
    otherTimePh: 'Birth time (blank if unknown)',
    dayRelation: 'Day-master relation', harmonyTension: 'Harmony {{h}} · Tension {{t}}',
    usefulGod: 'Useful-god support', crossInter: 'Cross combos/clashes',
    needChart: 'Register your chart first to see compatibility.', registerMyChart: 'Register chart',
    mySlot: 'My chart', otherSlot: 'Their chart', change: 'Change', orDirect: 'Or enter them directly',
    registerOther: 'Register partner chart', registerOtherTitle: 'Register partner', registerOtherSubmit: 'See compatibility with this chart',
    yearAll: 'Overall',
    analyze: 'See compatibility', generating: 'Reading your compatibility…', noReading: "Couldn't generate. Please try again.",
    secBase: 'How you two mesh', secDynamic: 'Where you click · where you clash', secAdvice: 'How to nurture it',
    detailToggle: 'Show character interactions',
    premiumTitle: 'Premium only', premiumMsg: 'Premium gives you 5 free compatibility readings.',
    payTitle: 'Another reading', payMsg: "You've used your 5 free readings. See this one for ₩2,500?", payBtn: 'Pay ₩2,500',
    rel: { friend: 'Friend', family: 'Family', crush: 'Crush', love: 'Dating', marriage: 'Marriage', coworker: 'Coworker', senior: 'Mentor/Senior', business: 'Business', staff: 'Staff', invest: 'Investing' },
  },
  category: {
    성격내면: 'Personality', 취업운: 'Job-seeking', 직장운: 'Career', 사업운: 'Business',
    금전소득운: 'Income', 투자편재운: 'Investment', 재물손재: 'Money/Loss', 연애운: 'Love',
    결혼배우자운: 'Marriage', 대인사회성: 'Social', 부모운: 'Parents', 형제운: 'Siblings',
    자식운: 'Children', 건강: 'Health', 학업자기계발: 'Study', 이동환경: 'Relocation',
  },
  today: { hourTitle: 'Hour by hour', hourSub: 'The same day reads differently hour to hour', hourBest: 'Runs smoothest · {{ko}} {{range}}', hourCare: 'Worth slowing down · {{ko}} {{range}}', hourNow: 'now', hourFoot: 'Computed from today\u2019s day pillar and your chart — not a verdict on good or bad. A low stretch simply means there is no need to rush it.', 
    'areaSoon': 'Readings for this area start from the next fortune.',
    today: 'Today', tomorrow: 'Tomorrow', energyTomorrow: "Tomorrow's Energy", weekdaysShort: 'Sun,Mon,Tue,Wed,Thu,Fri,Sat',
    dayPillar: "Today's Energy", note: "Changes daily at midnight, read against your own chart — deeper readings in Premium.",
    areas: 'Readings by area', area_general: 'Overall', area_work: 'Work', area_money: 'Wealth', area_invest: 'Investing', area_love: 'Love', area_health: 'Health',
    needChart: 'Register your chart to get today personalized for you, area by area.', registerBtn: 'Register chart',
    more: 'See it area by area →',
    genFail: "We couldn't create your reading. Please try again in a moment.", title: "Today's Fortune", heroSub: 'How your day is shaping up today', generating: "Reading today's flow for you…", gateTitle: "See Today's Fortune", gateDesc: "Combining who you are with your bigger picture right now, this year, and today's mood, we'll walk you through what might come up today and how to handle it.", seePremium: "See Today's Fortune", seeAd: 'Watch an ad to view for free', adFail: "Couldn't load the ad. Please try again later, or go ad-free with Premium.",
  },
  settings: { community: 'Community', nickPh: 'Nickname (2–12 chars, empty = auto handle)', nickBad: 'That word can\'t be used.', nickLen: 'Nickname must be 2–12 characters.', nickDone: 'Saved', showIlju: 'Show my day-pillar badge', iljuHint: 'Only the two characters of your birth day show next to posts. Your birth date can\'t be derived.',
    'accent': 'Background Tone',
    'accentAuto': 'Auto (day master)',
    'accentDesc': 'The background tone follows your chart’s day-stem element. You can pick one yourself.',
    'accentGold': 'Gold',
    'coins': 'Luck',
    'loadingOff': 'Off',
    'loadingScreen': 'Loading screen',
    'loadingVideoOff': '八字 characters',
    'loadingVideoOn': 'Tiger video',
    'loginBenefit': 'Log in and the content you bought carries over to other devices and reinstalls (optional)',
    'notif': 'Notifications',
    'notifDaily': 'Daily fortune notification',
    'notifDenied': 'Off · Tap to enable in device settings',
    'notifDeniedMsg': 'To receive notifications, enable Niunnaeun notifications in your device settings.',
    'notifNA': 'Not available on this device',
    'notifOff': 'Off · Tap to turn on',
    'notifOn': 'On · Every day at 9 AM',
    'notifOnMsg': 'Notifications are on. You can turn them off in your device settings.',
    'notifUnavailable': 'Notifications aren\'t available on this device.',
    'openSettings': 'Open settings',
    'readingVideo': 'Reading loading video',
    'readingVideoOff': 'Simple (no video)',
    'readingVideoOn': 'Themed video',
    'restore': 'Restore purchases',
    'restoreDone': 'Your purchases have been restored.',
    'restoreFail': 'Couldn\'t restore purchases. Please try again in a moment.',
    'restoreNone': 'There are no purchases to restore.',
    'restorePending': 'Your purchase is confirmed. It may take a moment to reach our server — please check again shortly.',
    'restoring': 'Restoring…',
    'themeRestart': 'It\'ll apply the next time you open the app.',
    homeOrder: 'Home layout order', homeOrderNote: 'The order shown on your home screen. Move items up or down.', homeOrderReset: 'Reset to default order',
    account: 'Account', loginCta: 'Log in / Sign up', premium: 'Premium',
    premiumActive: '✓ Premium active', premiumBuy: 'Lifetime Premium', premiumDesc: 'All premium content — now & future — free · no ads · one-time, yours forever · 30% off yearly re-readings (10% for others)', 
    premiumOkTitle: 'Premium', premiumOk: 'Premium is now active.', premiumTitle: 'Premium',
    deleteAccount: 'Delete account',
    delTitle: 'Delete account', delMsg: 'Your account and all data (charts, readings, passes) will be permanently deleted. This cannot be undone.', delConfirm: 'Continue',
    delTitle2: 'Are you sure?', delMsg2: 'This action cannot be undone.', delFinal: 'Delete permanently',
    delFail: 'Deletion failed. Please try again later.', delDoneTitle: 'Deleted', delDone: 'Your account and data have been deleted.', deleting: 'Deleting your account…',
    fontSize: 'Text size', size_sm: 'Small', size_md: 'Medium', size_lg: 'Large', size_xl: 'X-Large',
    appInfo: 'App Info', version: 'Version', terms: 'Terms of Service', privacy: 'Privacy Policy', license: 'Open Source Licenses', bugReport: 'Report a Bug · Contact', bugReportFail: "Couldn't open your mail app. Please email us at:",
    preview: 'Preview — readings appear at this size. It applies to reading, daily fortune, and compatibility text.',
    language: 'Language', 
    coupon: 'Enter coupon', couponPh: 'Enter coupon code', couponRedeem: 'Redeem', couponHave: 'Your passes',
    couponOkTitle: 'Redeemed', couponOk: 'Free pass applied. You can use that feature for free.',
    couponFailTitle: 'Failed',
    couponErr_invalid: 'Invalid code.', couponErr_expired: 'This coupon has expired.',
    couponErr_exhausted: 'This coupon is used up.', couponErr_already: 'Already redeemed.', couponErr_auth: 'Please log in.',
  },
  timeline: {
    'readThis': 'Read this period',
    decades: 'By decade', years: 'By year', pickDecade: 'Pick a period', pickYear: 'Pick a year', thisYear: 'This year', now: 'Now',
    catGeneral: 'Overall', catWork: 'Work', catMoney: 'Money', catLove: 'Love', catHealth: 'Health',
    catSocial: 'People', catGrowth: 'Growth', catMove: 'Change', months: 'Month by month', monthUnit: '',
    generating: 'Reading this period…', tapToRead: 'Pick a period or year to read its flow.',
    premiumTitle: 'Premium only', premiumMsg: 'The Life Timeline reads each period in Premium.',
    lockedTitle: 'Locked period', lockedSub: 'Your current decade and this year are free; open other periods with a pass for a category-by-category reading.',
    unlock: 'Open this period', unlockTitle: 'Open this period',
    unlockMsg: 'A timeline pass opens this period with a detailed category reading. (Get passes via coupons in Settings · per-use payment coming soon)',
    buy5: '5 yearly readings {{price}}', buy10: 'Full decade · 10 yrs {{price}}', // yearly (세운) bundles — lock-card buy buttons (daniel 07-23)
    freeBadge: 'Free', usedCredit: 'Opened with a pass',
  },
  premiumHub: {
    sub: 'What would you like to see?',
    sajuReading: 'Saju reading', sajuReadingDesc: 'Deep reading across 16 areas — personality, money, love, work…',
    ziweiReading: 'Chart reading', ziweiReadingDesc: '12 palaces + decade luck & transformations over time',
  },
  pet: {
    title: 'My Pet', sub: "A light look at your companion's natural temperament.",
    add: 'New pet', name: 'Name', namePh: 'e.g. Kong', typeLabel: 'What kind?',
    birth: 'Birth date (YYYY-MM-DD)', time: 'Birth time', timeOptional: "— optional",
    timePick: 'Pick a time period', timeUnknownChk: "Time unknown",
    timeHint: "Without a time we read only the broad strokes (no time-of-day reading).",
    save: 'See traits', empty: 'No pet added yet.',
    delete: 'Delete chart', deleteTitle: 'Delete', deleteMsg: 'Delete this chart?',
    invalidTitle: 'Please check', invalidDate: 'Enter the birth date as YYYY-MM-DD.',
    type: { dog: 'Dog', cat: 'Cat', rabbit: 'Rabbit', hamster: 'Hamster', bird: 'Bird', fish: 'Fish', reptile: 'Reptile', other: 'Other' },
  },
  love: {
    'genDelayed': 'Your reading is taking longer than usual. Please try again in a moment.',
    'needZiwei': 'We can\'t read love flow for this chart. The exact birth time is required for the Zi Wei cross-analysis.',
    title: 'My Love Flow', sub: 'Cross-reading Saju and Zi Wei together — from your ideal type to the person you actually meet, in rich detail.',
    generating: 'Cross-reading both charts for your love story…',
    gateDesc: 'Your ideal type, and the real person you meet — their first impression, personality, behavior and habits, how you meet and when — cross-read from Saju and Zi Wei in fine detail.',
    see: 'See it for {{price}}', cacheNote: 'Once unlocked it stays saved (no re-charge).',
    gateTitle: 'My Love Flow', gateMsg: 'No pass yet. Redeem a coupon in Settings, or payment is coming soon. ({{price}})',
    idealType: 'Your ideal type', appearance: 'First impression & image of who you meet', personality: 'Their personality & inner world',
    behavior: 'Their behavior, speech & habits', ageGap: 'Their age relative to yours', howWeMeet: 'How & where you’ll meet', elementMatch: 'Best-matched energy types, ranked', dynamic: 'The chemistry between you', iLoveMore: 'When you love them more', theyLoveMore: 'When they love you more',
    timing: 'When love ripens', cautionPartner: 'Types to be especially mindful of', caution: 'What to watch for', advice: 'How to nurture a good connection', needPay: 'You need a pass to continue. Please try again.',
  },
  month: {
    'aiDesc': 'We add your bigger picture, this year, and this month\'s energy to the saju you were born with — then AI goes deeper into what may come up this month and how to handle it.',
    'aiLogin': 'Log in and AI will go deeper into this month\'s flow.',
    'aiTitle': 'AI in-depth reading',
    'thisMonth': '이번 달', title: 'Monthly Fortune', monthPillar: "This month's energy", flowTitle: "This month's flow (early · mid · late)", note: "The broad flow for this month. For specific days, see the Daily Fortune.", heroSub: "The flow of this month's energy", generating: "Reading this month's flow…", gateTitle: "View This Month's Fortune", gateDesc: "We combine the nature you were born with, the big flow you're in now, this year, and this month's energy to share what may come up this month and how to handle it.", seePremium: "View This Month's Fortune" },
  nav: { home: 'Home', contents: 'Readings', community: 'Community', coach: 'Guide', market: 'Market' },
  lookback: { title: 'Look back', sub2: 'The days you did your one thing.', needLogin: 'Sign in to save your notes and revisit them here.', empty2: 'No records yet. Do your one thing under today\'s reading and check it off.', goToday: "See today's reading", summary: 'You marked {{hit}} of {{rated}} rated days as accurate', streak: "You've done your one thing on {{n}} days", myNote: 'My note', missionDone: '✓ Did that day\'s one thing' },
  contents: {
    sub: 'Pick a topic you want to explore',
    searchPlaceholder: 'What are you curious about?',
    searchResult: '{{n}} result(s)',
    searchEmpty: 'Nothing matched.\nTry another word.',
  },
  todayEnergy: { kicker: "Today's energy", point: 'pts', more: "See today's reading" },
  persona120: {
    kicker: 'My personality type', count: 'of 120', more: 'See details',
    title: 'My personality type', sub: '10 day stems × 12 month branches = 120 types',
    empty: 'Register your chart to see which of the 120 types you are.',
    axisStem: 'What I am made of', axisSeason: 'The season I was born into', axisGyeok: 'Where my life leans',
  },
  market: {
    'emptyTopic': 'Content for this topic is on the way. Try another topic.',
    'hotSection': '🔥 Popular',
    'open': 'Open',
    'retentionNote': 'Purchased readings are kept for one year from the purchase date and are deleted automatically after that. To view one again later, you\'ll need to buy it again.',
    'sectionIncluded': '✦ Open with Luck',
    'sectionIncludedSub': 'You can open the readings below one at a time with Luck. Each chart opens separately.',
    'sectionIndividual': '◆ Individual purchase only',
    'sectionIndividualSub': '아래 항목은 하나씩 따로 구매해요.', intro: 'Pick the chart to apply to, then tap a reading.', applyTo: 'Apply to', openApply: 'Open', noChart: 'No saved chart', have: 'You have {{n}}', owned: 'Owned', notOwned: 'Not owned', buy: 'Buy', note: 'Readings are saved per chart. Redeem free passes (coupons) below.', doneTitle: 'Purchased', doneMsg: 'Your pass has been added.', payPending: 'Payment not ready', buyFailTitle: 'Purchase failed' },
  dayPillar: {
    'fullChartNote': '※ Day-pillar theory reads one broad tendency from the day you were born. A precise reading needs your whole chart.',
    's_match': 'Day pillars that suit you',
    's_stress': 'Relieving stress',
    title: 'Day Pillar', sub: 'Your innate nature, seen through your birth-day pillar (ilju).',
    male: 'Male', female: 'Female', mine: 'My Day Pillar', browseAll: 'All 60 Day Pillars', dayGroup: 'day', tapHint: 'Tap a pillar to expand its full reading.', mineList: 'My Day Pillars', noChart: 'No saved charts. Register a chart first.',
    s_overview: 'Overview', s_personality: 'Personality', s_love: 'Love & Marriage', s_career: 'Career & Wealth', s_male: 'For Men', s_female: 'For Women', s_advice: 'Advice', s_live: 'Life Tips',
    disclaimer: "The day pillar is only one facet of your nature. A precise reading needs your whole chart — the year, month and hour pillars plus combinations, clashes and the useful god — not the day pillar alone.",
  },
  purchase: {
    loginTitle: 'Sign in required', loginMsg: 'Signing in saves your purchases to your account, so they carry over to other devices and reinstalls. Sign in now?', loginCta: 'Sign in',
    restore: 'Restore purchases', restored: 'Purchases restored.', restoreNone: 'No purchases to restore.', restorePending: 'Purchase confirmed. It may take a moment to apply — please check again shortly.', preparing: 'Payments are coming soon.',
  },
  offline: { title: 'Offline', msg: "You're not connected to the internet. You can view saved content, but new readings need a connection.", banner: 'Offline — saved content only' },
  taro: { draw: 'Draw a card', reshuffle: 'Reshuffle', reversed: 'Reversed' },
  manse: {
    'catDeleteTitle': 'Delete category',
    'newCategoryPh': 'New category name',
    'catDelNote': 'Deleting a category does not delete the charts — they move to “Other”.',
    'deleteTitle': 'Delete chart',
    'viewManse': '만세력 보기', empty: 'No saved chart.', myChart: 'Chart', searchChart: 'Search by name' },
  sinsal: { 도화: 'Peach Blossom', 역마: 'Travel Horse', 화개: 'Canopy', 천을귀인: 'Nobleman', 문창: 'Academic', 양인: 'Blade', 홍염: 'Romance', 괴강: 'Goegang', 백호: 'White Tiger' },
  special: {
    'freeBasics2': 'Start free — the Big 3 + your life-giving element',
    'goMarketBtn': 'Go to store ›',
    'ownedBoughtV2': 'Purchased · You can revisit it anytime',
    'ownedResumeSub': 'Creation was interrupted. We\'ll finish it with no extra charge.',
    'ownedResumeTitle': 'Payment is done — only the reading is left',
    'ownedTitle': 'This reading is already open',
    'preparingPayment': 'Preparing payment…',
    'priceMissing': 'This content can\'t be opened right now. Please try again in a moment.',
    'resumeCta': 'Finish creating the reading',
    'viewCta': 'View reading',
    'working': '진행 중…', previewHead: "What you'll get", unlock: 'Unlock with woon', couponHint: 'Open with woon', couponOnly: 'Open with woon. You can top up in the market.', needPay: 'You need woon. Please try again.', needPayMsg: 'You need woon. Open it with woon now, or top up in the market.', buyNow: 'Buy now', goMarket: 'Go to market', unlockCta: 'Buy & view', unlockHint: 'Opens with woon' },
  roots: { title: 'Roots of Your Chart', sub: 'Your visible self, hidden strengths, and what truly holds firm', generating: 'Tracing your roots…', summary: 'At a glance', surface: 'Visible you', depth: 'Hidden strength', strength: 'What truly holds', gap: 'Surface vs depth', advice: 'How to grow it' },
  image: { title: 'How You Appear', sub: 'Your first impression, vibe, and how you come across with others', generating: 'Drawing your impression…', summary: 'At a glance', firstImpression: 'First impression', persona: 'Outward image', inRelationship: 'In relationships', charm: 'Your charm', gap: 'Surface vs inner', advice: 'How to show up' },
  mission: { title: 'My Calling', sub: 'What you were born to do — your gifts and role in this world', generating: 'Reading your calling…', summary: 'At a glance', coreNature: 'Core nature', calling: 'Your calling', strengths: 'Your gifts', howToRealize: 'How to realize it', successWay: 'How You Succeed', careers: 'Fitting work', environment: 'Where you shine', lifeTheme: 'Life theme', crossInsight: 'Converging direction', advice: 'Living your calling' },
  talent: { title: 'My Innate Talent', sub: 'What you were born with, where you shine — doing what you love or what you must — and how to handle money', generating: 'Reading your innate talent…', summary: 'At a glance', talent: 'Your innate talent', drive: 'Passion vs duty', money: 'How you handle money', howToUse: 'How to use your talent', careers: 'Where you shine', advice: 'A word' },
  numerology: {
    'birthday': 'Birthday number — your innate talent',
    'empty': 'Register a chart and we\'ll show your numerology from your birth date.',
    'master': '✦ You carry a master number (11·22·33) — great potential, but harder to handle.',
    'note': '※ Calculated with Pythagorean numerology (the Western standard). Name-based numbers (expression, soul urge) are coming later.',
    'personalYear': '개인해 — 올해 흐름', title: 'Numerology', sub: 'Your life direction, talents, and this year — by the numbers in your birth date', generating: 'Reading your numbers…', summary: 'At a glance', lifePath: 'Life Path — your direction', innerYou: 'Inner self & outer image', talent: 'Your talents', thisYear: 'This year', advice: 'A word' },
  astrology: {
    'numCore': 'Me, by the numbers',
    'numGroup': '🔢 Numerology — who you are by your birth date',
    'numLove': 'Relationships by numerology',
    'numYear': 'This year\'s number',
    'sub2': '별자리(태양)·점성술(네이탈)·수비학(생명수)을 한 번에 — 세 관점으로 깊이 풀이', title: 'Zodiac & Astrology', sub: 'Your star sign + full natal chart — two views in one', generating: 'Reading your stars…', signGroup: '⭐ Star Sign — by your Sun sign', signSummary: 'Your Sun Sign', signTraits: 'Personality', signLove: 'Love style', signStrength: 'Strengths', natalGroup: '🔭 Astrology — by your natal chart', big3: 'Sun·Moon·Rising', natalLove: 'Love & desire', natalWork: 'Work', strength: 'Strengths', challenge: 'Challenge', advice: 'A word' },
  future10: { title: 'Me in 10 Years', sub: 'Who you become in 10 years — seen through your luck cycles — and how to prepare now', gen: 'Picturing your next 10 years…', bigPicture: 'The big picture in 10 years', career: 'Career & achievement', wealth: 'Wealth & assets', relation: 'Relationships & home', health: 'Health to manage', growth: 'Growth & inner change', prepare: 'What to prepare now' },
  child: { title: 'Children', sub: 'Your bond with your children, their nature, and you as a parent — from your chart', gen: 'Reading your bond with your children…', solo: 'Just me', couple: 'With spouse', pickSpouse: 'Pick spouse chart', coupleHint: "Pick your spouse's chart to read your bond with children from both charts", needSpouse: "Please register your spouse's chart first", bigPicture: 'The big picture of your bond', childNature: "Your child's nature", asParent: 'You as a parent', coupleCross: "The couple's bond with children", communication: 'Communication', timing: 'Timing & flow', talent: "Your child's talents", health: 'Health to manage', remedy: 'Ways to boost fortune' },
  life: { genFail: 'Something went wrong. Please try again in a moment.', gateTitle: 'Life Graph', generating: 'Drawing your life journey…', yongsin: 'The energy you need', focus: 'Focus', hint: 'Tap a point on the curve to see that period in detail.', peak: 'Your brightest years', caution: 'Time to build up and take care', advice: 'A lifelong guide', gateDesc: "We go deep on why each period rises or falls, what to do in the season you're in now, how to make the most of your brightest years, and how to get through the harder stretches.", pv1: 'Why each period rises and falls', pv2: "What to do in the season you're in now", pv3: 'How to make the most of your brightest years', pv4: 'How to get through the tougher times', pv5: 'A direction to keep for life', see: 'View Life Graph', seePaid: 'View Life Graph (₩3,900)' },
  newyear: {
    'remedy': 'Lifting your luck this year',
    'strategy': 'Your strategy for the year',
    'thisYearSelf': 'You this year',
    'timing': 'Good timing this year',
    'yearNature': '올해는 어떤 해', title: 'New Year Fortune', generating: 'Reading your whole year…', heroSub: 'See the big picture of your year at a glance', keyword: "This Year's Keyword", lucky: "This Year's Lucky Points", halves: 'First Half · Second Half', months: 'Monthly Calendar', samjaeAdvice: 'What to Watch This Year', resolution: 'Make This Year Count', gateDesc: 'From your keyword for the year to fortune by area, a twelve-month calendar, and your New Year resolutions — all in one place.', pv1: "This year's keyword", pv2: 'Fortune across 8 areas', pv3: 'Twelve-month calendar', pv4: 'First and second half trends', pv5: 'What to focus on and your New Year resolutions', see: 'View New Year Fortune', seePaid: 'View New Year Fortune (₩9,900)', },
  taegil: { title: 'Pick a Day — Find the Right Date', sub: "Choose what you're planning, and we'll highlight the dates over the next three months that suit you best.", best: 'Great', good: 'Good', tapHint: 'Tap a highlighted day', },  zodiac: { title: "Today's Zodiac & Star Sign", animal: 'Zodiac Animal', sign: 'Star Sign', mine: 'My Fortune', },
  name: { title: 'Name Reading', sub: 'We read the vibe of your name through the energy in its sounds.', placeholder: 'Enter your name in Korean', noHangul: 'Please enter your name in Korean.', },
  taemong: {
    'secSymbols': 'What appeared in the dream',
    'secStory': 'What this dream is saying',
    'secChild': 'As it has been told',
    'secKeep': 'How to keep this dream',
    'secTradition': 'There is also this story',
    'title': 'Conception Dream',
    'sub': 'Reading the dream that came while waiting for a child',
    'guard': 'Conception dreams are a long-told tradition. They do not tell you a child\'s sex or health — that belongs to medicine.',
    'dictTitle': 'What appeared in the dream?',
    'dictPh': 'Dragon · Tiger · Carp · Peach …',
    'noHit': 'That symbol is not in our dictionary. Shall we look it up for free?',
    'lookup': 'Look up “{{kw}}” (free)',
    'aiTitle': 'AI conception-dream reading',
    'aiSub': 'Tell the whole dream as a story — even if several symbols mix, or none are in the dictionary, we read them together.',
    'aiPh': 'Who dreamt it, what appeared, and what happened …',
    'aiCta': 'Get the reading',
    'tooShort': 'Please write a little more of the dream.',
    'fail': "Couldn't load the reading. Please try again in a moment.",
  },
  dream: {
    'aiBtn': 'Get an AI reading (₩300)',
    'aiPh': 'What you saw or went through in the dream, in detail…',
    'aiSub': 'For a complex dream, just tell it as a story — we\'ll read it even if it isn\'t in the dictionary or mixes several symbols.',
    'aiTitle': 'AI dream reading',
    'buy5': 'Use Luck',
    'buyBundle': 'Read this dream for 5 Luck?',
    'needCredit': '지금은 열 수 없어요. 잠시 후 다시 시도해 주세요.', fail: "We couldn't load the dream meaning. Please try again in a moment.", title: 'Dream Meanings', sub: 'Search for what appeared in your dream.', placeholder: 'e.g. pig, snake, water…', generating: 'AI is interpreting your dream…', notInDict: "This dream isn't in our list. Get an AI interpretation instead.", aiSee: 'See AI Interpretation', history: 'Past Dream Readings' },
  luck: { title: "Today's Luck", todayEnergy: "Today's Vibe", color: 'Lucky Color', direction: 'Lucky Direction', numbers: 'Lucky Numbers', item: 'Lucky Item', weakHead: 'A Color That Supports You', weakTail: ' — this is an energy you tend to be short on, so keeping it close helps you feel more balanced.', },
  renewal: { title: 'Get an updated reading', msg: "It's been a year since this reading.\n\nFor {{coins}} woon ({{pct}}% off) we'll read it again for where you are now. (You have {{have}})", later: 'Later', go: 'Read again', needTitle: 'Not enough woon', needMsg: 'This needs {{need}} woon. You have {{have}}.' },
  assist: { title: 'Wooni', sub: "Tell me what you want to see — I'll take you straight there.", label: 'Guide', hello: 'What would you like to look at? Pick one of the three, or just tell me in your own words.', egLabel: 'You can also say things like', miss: "I didn't catch that yet. Pick one below and I'll take you there.", placeholder: 'What would you like to see?', reset: '↺ Start over', send: 'Send', },
  coach: { title: 'AI Self-Understanding Coach', sub: 'Ask anything about yourself — we answer from your Saju chart.', coachLabel: 'Coach', thinking: 'Reading your chart…', placeholder: 'Ask about yourself', send: 'Send', needChart: 'Please register your chart first.', registerBtn: 'Register chart', loadFail: "Couldn't load your chart. Please try again in a moment.", gateTitle: "You've used today's free questions", gateDesc: 'You can ask up to {{count}} times a day for free. With Premium, chat with the coach without limits.', gateCta: 'See Premium', q1: 'What kind of person am I?', q2: 'Why do my relationships keep repeating?', q3: 'How can I make the most of my strengths?', q4: "How's my current flow?" },
  selfHero: { kicker: 'Who am I', emptyTitle: 'Let us analyze you', emptySub: 'Enter your birth details and the Saju engine analyzes your character, temperament, and strengths', emptyCta: '+ Analyze me', more: 'See full personality analysis ›' },
  personal: {
    'toneCap': '나의 퍼스널 컬러', title: 'Personal Element', sub: 'Colors, style, makeup & car colors for your element', activate: 'Colors that bring you alive', balance: 'Colors worth adding', yongsin: ' (the energy you need)', cody: 'Style', makeup: 'Makeup', car: 'Car color', empty: 'Register a chart to find colors for your element', emptyCta: '+ Add chart', expertNote: '* Personal Five Elements are a reference based on your saju — for real personal-color or styling, consult a professional.' },
  // R-GEM v0.1 — My Saju Gemstone (★daniel review slot: sub·note copy)
  gem: { title: 'My Saju Gemstone', birthstoneTitle: 'What your birthstone means', sub: 'Your birthstone may not fit you — the gem that truly lifts you', empty: 'Register a chart to find gems that fit you', emptyCta: '+ Add chart' },
  timeResolve: {
    'title': '태어난 시 찾기', yearRange: 'Please check the year again (e.g., 1990–this year).', yearFuture: 'You can’t enter a future year.', removeEvent: 'Remove event' },
  sok: { title: 'Intimate Match', sub: 'Sexual compatibility by saju — an adult, just-for-fun read', gateTitle: 'Adult (19+) content', gateDesc: 'Intimate Match reads two people’s sexual compatibility through saju. For fun only.', gateConfirm: 'I’m 19 or older · Start', pickPartner: 'Pick partner', newPartner: 'New partner', registerSubmit: 'See intimate match', spouseLabel: 'Spouse-palace chemistry', adviceLabel: 'How to make it better', kiss: 'Kiss match', bed: 'Bed match', styleLabel: 'Your chemistry style', pickHint: 'Tap to pick partner', noPartner: 'No saved partner. Please add a new one.', disclaimer: '※ A for-fun saju read. Real relationships are built by two people. Adults (19+) only.' },
  community: { daily: 'Today\'s Day Energy', dailyTalk: 'Join the talk', p1: 'Great', p2: 'Good', p3: 'Okay', p4: 'Meh', p5: 'Rough', pollMine: 'Voted! Stats appear once more people join.', pollStat: '{{total}} voted · top pick {{top}}%', all: 'All', cat: { free: 'Free talk', love: 'Love', saju: 'Saju Q&A', review: 'Reviews', question: 'Advice' }, empty: 'Be the first to post.', profanity: 'Contains inappropriate language. Please edit and try again.', write: 'Write', post: 'Post', titlePh: 'Title', bodyPh: 'Write your message (no abuse, hate, or sexual content)', eulaTitle: 'Community Guidelines', eulaBody: 'Abuse, hate, harassment, illegal, or sexual/obscene content is prohibited. Violations may be removed and access restricted. Reported content is reviewed and acted on within 24 hours. You can block abusive users.', eulaAgree: 'Agree & write', comments: 'Comments', noComments: 'Be the first to comment.', commentPh: 'Add a comment (be respectful)', send: 'Send', report: 'Report', block: 'Block', reportTitle: 'Report', reportDesc: 'Choose a reason. Reported content is reviewed within 24 hours.', rAbuse: 'Abuse / hate / harassment', rSexual: 'Sexual / illegal content', rSpam: 'Spam / ads', reported: 'Report received', reportedDesc: 'We’ll review and act. Thank you.', reportFail: 'Failed to report.', blockTitle: 'Block this user', blockDesc: 'Blocking hides this user’s posts and comments from you.', blocked: 'Blocked', blockFail: 'Failed to block.', delTitle: 'Delete?', gone: 'This post was deleted or is unavailable.', loginTitle: 'Sign in required', loginDesc: 'Posting requires sign-in. Reading stays open without an account.', goLogin: 'Sign in', attach: 'Attach my chart', attachNone: 'No chart saved as “myself”. You can still post without attaching one.', attachOff: 'No chart', attachLuck: 'Also share luck cycle & year', attachWarn: 'Your four pillars will be visible to everyone who reads this post. A birth date can be worked back from them, so please check before posting.', needTitle: 'Please enter a title.', needBody: 'Please enter some content.', posting: 'Posting…', errSession: 'Please sign in again and retry.', errNet: 'Check your connection and try again.', errPost: 'Couldn’t post. Please try again shortly.' },
  egen: { title: 'Egen vs Teto', heroSub: 'Your egen/teto vibe, read from your saju', tetoPower: 'Teto Power', typeTeto: 'Teto Type', typeEgen: 'Egen Type', typeBalanced: 'Balanced', scaleEgen: 'Egen', scaleTeto: 'Teto', secPersonality: 'Your Nature', secRelationship: 'In Love & Relationships', secNowTrend: 'Lately', needChart: 'Please register your chart first.', registerBtn: 'Register chart', gateTitle: 'See your vibe explained', gateDesc: 'We explain how your vibe shows up in everyday life, love, and your current flow — matched to your score.', seeAd: 'Watch an ad to see it free', seePremium: 'See explanation', generating: 'Reading your vibe…', genFail: "We couldn't load the explanation. Please try again in a moment.", adFail: "We couldn't load the ad. Please try again, or go Premium to view without ads.", },
  crisis: { title: 'Rough patches', heroSub: 'Shaky seasons read as structure — seats and forces, not fortune-telling', frameTitle: 'We do not tell you whether it ends', frameBody: 'This is not a screen that guesses whether a relationship ends. It reads which force sits on the spouse seat of your chart, where it comes from, and which years move that seat. The decision comes after, and it belongs to two people, not to a chart.', needChart: 'Register a chart and this screen fills in.', chartFail: "We couldn't compute this chart.", secStrength: '① Where the shaking comes from', gungLine: 'Spouse seat = day branch {{gung}}', chungFrom: ' · it lands from the {{from}} pillar', gradeBreaking: 'A heavy clash sits right next to it. When this seat is shaken, the shaking shows.', gradeShaking: 'It gets shaken, but the seat itself is not pushed aside.', gradeEven: 'The two sides weigh the same, so neither clearly wins.', gradeNone: 'No force in the natal chart shakes this seat.', remedyBreaking: 'Redefining the relationship while it shakes only shakes it more. Postpone decisions and protect daily rhythm first.', remedyEven: 'Neither side wins this tug, so pushing to win only stretches it. Whoever speaks first comes out ahead.', remedyCalm: 'There is no fire to put out in this structure. You do not need to manufacture a test for the relationship now.', secRivalry: '② Is there a contested shape', rivalryWealth: 'Two identical stems contend over one, and that one is a wealth star. Whenever something hard to split enters the relationship, the grain shows.', rivalryYes: 'Two identical stems contend over one. It does not mean someone cuts in — it means the structure itself splits force over a single thing.', rivalryNo: 'No contested shape sits in the natal chart. If things shake, they shake from elsewhere.', rivalryRemedy: 'Reading this as "because of that person" is always wrong. Decide up front what cannot be split and the ground for quarrel shrinks.', rivalryRemedyNo: 'This is not a chart to pre-worry a triangle over.', secBond: '③ Bound close, or in name only', bondYes: 'The spouse seat is bound to the pillar right beside it. That grain does not snap easily even at a distance.', bondNo: 'No neighbouring character holds the spouse seat in place. Continuity here is built by two people more than by structure.', frictionYes: 'A friction (刑) also sits here, so closeness brings recurring snags.', frictionRemedy: 'If the snag is always the same spot, it is a grain, not an incident. Make a rule for that one thing and the rest goes quiet.', bondRemedy: 'The weaker the holding force, the more promises and routine stand in for it.', secTiming: '④ Which years move that seat', timingQuiet: 'No year in the next eight touches the spouse seat. This is a quiet stretch.', yOpen: 'the seat opens — a year movement enters', yBond: 'the seat binds — a year that ties a knot', yFriction: 'a year friction circles', timingRemedy: '"Opens" does not mean it ends. It means movement enters that seat, and meeting and parting come through the same door. Simply not stacking big decisions into that year carries most of it through.', disclaimer: 'This screen is a reference for structure and timing; it does not predict how a relationship ends. If things are heavy right now, please talk to someone close or to a professional before consulting a chart.' },
  attach: { title: 'Attachment — chart next to survey', heroSub: 'The same relational pattern in two languages', frameTitle: 'The two results measure different things', frameBody: 'The survey measures where you are right now; your chart shows the grain of what you were born with. So the two can differ — and the difference is the interesting part. If your structure leans toward keeping distance but you feel at ease today, you learned something along the way.', secChart: '① What your chart leans toward', secSurvey: '② You right now (12 items)', secCompare: '③ The two side by side', axisAnx: 'Anxiety — watching for distance', axisAvo: 'Avoidance — keeping distance', axisAnxShort: 'Anxiety', axisAvoShort: 'Avoidance', anxLow: 'Steady', anxHigh: 'Watchful', avoLow: 'At ease up close', avoHigh: 'Keeps distance', capTitle: 'Can the day master carry {{target}}?', capFrame: 'How much distance you keep depends on whether you have room to carry the relationship. A man’s chart is read from the 正財 seat, a woman’s from the 正官 seat.', capAxis: 'Capacity', capLow: 'Stretched · keeps distance', capHigh: 'Room to spare · at ease', capEdge: 'The further out toward either end, the more easily a relationship wobbles. Where exactly that begins is not yet settled, so we show a position rather than a type name.', capAbsent: 'This chart has no visible {{target}}. How to read such a chart is still being checked, so treat the position above as a loose reference.', sideSelf: 'room', sideLoad: 'load', cmpAnxNone: 'The anxiety row shows survey results only. The chart side speaks up to “is there room to carry this”; turning that into anxiety is not something we have verified.', basisHead: 'What pushed this score', basisNone: 'No clear structure pushes this axis.', needChart: 'Register a chart and this part appears too. You can take the survey first.', chartFail: "We couldn't compute this chart.", surveySub: 'Think of someone close to you. There are no right answers.', progress: '{{n}} / {{total}} answered', compareLocked: 'Answer all 12 items and we will show them side by side here.', soloGap: 'Your “I prefer being alone” answers ran high while “closeness feels uncomfortable” ran low. Strong self-reliance can also look like this, so it helps to read the two strands separately.', hypo: 'The seat we read (正財 for men, 正官 for women) and how we read it come straight from a counselling expert. What “carrying it” should be measured by is still being checked, so every basis item is weighted equally (v1). We will recompute once that is settled.', disclaimer: 'This is a reference for self-understanding, not a psychological diagnosis. If difficulties in relationships or mood are affecting your daily life, please talk with a professional.', consent: 'I agree to let this response be used anonymously in research to improve the attachment model (optional — you can see your result either way)', consentNote: 'Only your survey answers and indicators computed from your chart are sent. Your birth date and time never leave this device.', saveBtn: 'Send my response', saving: 'Sending…', saved: 'Sent. Thank you', saveFail: "Couldn't send. Try again", },
  joseonjob: { shareLead: 'My Joseon-era job', traits: 'Your strengths', share: 'Share my job', detail: 'Explore my saju in depth (Premium)' },
  lovestyle: { shareLead: 'My love style', inLove: 'In a relationship', tip: 'Add just this', share: 'Share my love style', detail: 'Explore my love-life flow' },
  bok: { shareLead: 'My fortune', how: 'How to grow it', share: 'Share my fortune', detail: 'Explore my saju in depth (Premium)' },
  pastlife: { shareLead: 'My past life', hint: 'For you, now', share: 'Share my past life', detail: 'Explore my saju in depth (Premium)' },
  healing: {
    'deficit': '가장 적은 기운(참고)', shareLead: 'My healing', recharge: 'How you recharge', nourish: 'Energy to fill', release: 'Energy to release', color: 'Healing color', place: 'Healing space', food: 'Goes well with', mind: 'A word for your heart', elemLead: 'My energy', share: 'Share my healing', },
  bio: {
    'kicker': 'Biorhythm',
    'note': '※ A reference rhythm unrelated to saju. Near zero is a turning day when your condition shifts.',
    'sub': 'Your physical, emotional & intellectual rhythms today',
  },
  career: {
    'gateDesc': 'How you shine on each path, where you get stuck, and the natural weighting and timing behind it.',
    'generating': 'Reading both paths…',
    'sub': 'From your chart and luck cycles, we look at two paths — going independent and working within an organization',
    'title': 'You as a founder vs you as an employee',
  },
  celeb: {
    'compare': 'Day master · element comparison',
    'funNote': 'Just for fun',
    'matchHead': 'What you share',
    'myTenGod': 'My ten-god structure at a glance',
    'reasons': 'Shared structure',
    'sub': 'Find the figures whose chart resembles yours',
    'title': 'Celebrities Like Me',
    'topLabel': 'The figure most like you',
  },
  coins: { failTitle: "Couldn't add woon",
    spendMsg: 'Use {{cost}} woon to start this reading?\nYou have {{have}} → {{after}} after',
    'balFail': 'Couldn\'t load your balance',
    'balance': 'Your Luck',
    'charge': 'Top up Luck',
    'chargeCta': 'Top up Luck',
    'donePending': 'Payment complete. It may take a moment for your balance to update.',
    'doneTitle': 'Topped up',
    'needLoginDesc': 'Luck you top up is kept with your account. Log in so it stays with you when you change devices.',
    'needLoginTitle': 'You need to log in',
    'needTitle': 'Not enough Luck',
    'note': '· Luck works for every paid reading.\n· Luck you top up is kept with your account — it stays when you change devices.\n· Luck never expires.',
    'packs': 'Top up Luck',
    'spend': 'Use Luck',
  },
  country: {
    'needChart': 'Please register a chart first.',
    'sub': 'We point to countries whose climate and direction balance the energy you were born with',
    'title': 'Where I\'d thrive',
  },
  crush: {
    'caution': 'What to watch for',
    'generating': 'Reading the pull and the flow of connection…',
    'howToApproach': 'How to make your move',
    'myCharm': 'Your charm right now',
    'sub': 'Your charm right now, when a crush is ripest, and how to make your move',
    'timing': 'When a crush ripens',
    'title': 'Crush & connection',
    'whoLikesMe': 'Who\'ll be drawn to you',
  },
  crushAsk: {
    'cta': 'See the in-depth crush reading',
    'q': 'Will it work out with them?',
    'sub': 'We\'ll point out, for free, the months when a crush is most likely to become mutual',
  },
  gaeun: {
    'gateDesc': 'See what your current cycle brings, plus practical steps and remedies for wealth, relationships and health.',
    'generating': 'Finding remedies that fit your current cycle…',
    'sub': 'Concrete ways to lift your luck, tuned to the cycle you\'re in now',
    'title': 'Your personal luck remedies',
  },
  home: {
    'lightCta': 'Quick look',
    'manseSub': 'See your full saju chart',
    'noChartCta': '+ Register a chart',
    'noChartSub2': 'Just your birth date shows your personality type and day pillar right away. No sign-up, nothing saved.',
    'noChartTitle': 'You, analyzed by AI — start here',
    'quickRegister': 'Register a chart',
    'quickRegisterSub': 'Add charts for family, partners and friends',
  },
  impression: {
    'gapBig': 'How you come across and how you are once known differ quite a bit. There\'s a side to you people don\'t see at first.',
    'gapSmall': 'How you come across and who you are inside stay fairly consistent. You\'re someone people can take at face value.',
    'inner': 'Once they know you — the real you',
    'note': '※ The flow of the heavenly stems (energy shown outward) is the image others see; the month branch (the seat you were born into) is who you are once known.',
    'outer': 'How you come across',
    'sub': 'How you come across, and the real you underneath',
    'title': 'The impression people have of you',
  },
  job: {
    'bestField': 'Fields & settings that suit you',
    'flow': 'Hiring & career-move flow',
    'generating': 'Reading the energy and flow around hiring and passing…',
    'passLuck': 'Exams & getting accepted',
    'sub': 'When hiring, career moves, exams and acceptances go well — plus fields that suit you and how to prepare',
    'timing': 'Good timing',
    'tips': 'Preparation tips',
    'title': 'Hiring & career moves',
  },
  jobAsk: {
    'cta': 'See the in-depth hiring reading',
    'q': 'When will hiring or a career move go well?',
    'sub': 'We\'ll point out, for free, when the door to hiring, a career move or acceptance tends to open',
  },
  jobfit: {
    'ability': 'What you\'re actually good at',
    'archetype': 'Your work archetype',
    'gap': 'The gap between pull and ability',
    'generating': 'Reading your innate aptitude and the work that fits…',
    'jobs': 'Work that fits',
    'luckMap': 'Career flow across your life',
    'preference': 'What draws you (not ability)',
    'recognition': 'How and where you get recognized',
    'sub': 'Which work fits your innate aptitude, and the gap between what draws you and what you\'re good at',
    'title': 'Work that suits you',
    'workEnv': 'Workplaces that suit you',
    'workMode': 'How you work',
    'yongsinFit': 'The direction that fits',
  },
  login: {
    'go': 'Log in',
    'needContentMsg': 'Please log in to see this content. Logging in keeps your purchases and readings safely tied to your account.',
    'needTitle': 'You need to log in',
  },
  mbti: {
    'empty': 'Register a chart and we\'ll show your MBTI as read from your saju.',
    'note': '※ This reads your tendencies from your saju structure (including hidden stems and your current cycle), so it shifts a little over time. It may differ from a psychological MBTI test.',
    'sub': 'Your tendency type, read from your saju structure',
    'title': 'Your MBTI by saju',
  },
  mod: {
    'empty': 'No reported content.',
    'hide': 'Hide',
    'restore': 'Restore',
    'sub': 'Review reported content and hide or restore it. (5+ reports are hidden automatically)',
    'title': 'Report management',
  },
  net: {
    'errMsg': 'Please try again in a moment. If it keeps happening, close and reopen in a little while.',
    'errTitle': 'There\'s a connection problem',
  },
  relPattern: {
    'attraction': 'Density of charm & connection',
    'compatCta': 'Curious about a specific person? →',
    'drawnTo': 'The kind of person you keep being drawn to',
    'dynamic': 'Your relationship dynamics',
    'footNote': '※ An on-device analysis computing your chart structure — spouse palace (day branch), relationship stars, peach blossom — with the saju engine. Not a prophecy, but a reference for understanding yourself.',
    'kicker': 'Relationship psychology by the saju engine',
    'myStyle': 'How you show up in relationships',
    'sub': 'Why do similar relationships repeat? Not a compatibility horoscope — we read the relational grain that recurs in the saju structure you were born with.',
    'title': 'Your relationship pattern',
    'titleSuffix': '\'s relationship pattern',
  },
  reunion: {
    'addDesc': 'Add your past partner\'s chart and what\'s on your mind now, and we\'ll read both charts together, tuned to your situation. Leave it blank and we\'ll read your flow alone.',
    'addTitle': 'Read them together (optional)',
    'afterReunion': 'If you meet again',
    'caution': 'Worth looking back on',
    'changeBuy': 'Buy and change',
    'changeConfirmBuy': 'Changing the person means a new reading, which needs Luck. Go ahead?',
    'changeConfirmCredit': 'We\'ll use one reunion reading you have to change the person and read again. Change?',
    'changeConfirmPremium': 'Changing the person means a fresh reading for them. Change?',
    'changeGo': 'Change',
    'concernLabel': 'What\'s on your mind',
    'concernPh': 'Tell us your situation or what\'s weighing on you and we\'ll read it together',
    'generating': 'Reading the flow of a connection that may come back…',
    'otherAdd': 'Enter your past partner\'s birth date',
    'otherAnon': 'Past connection',
    'otherChange': 'Change person (new reading)',
    'otherLabel': 'Your past partner\'s chart',
    'otherLockedNote': 'Changing the person requires a new reading.',
    'otherPrivacy2': '※ Their details are used only for this reunion reading. Until you change it, it stays locked on this device only and never appears in your chart list. Please enter it only with their consent.',
    'possibility': 'Whether you\'ll reconnect',
    'registerOtherSubmit': 'Read with this chart',
    'registerOtherTitle': 'Enter your past partner\'s chart',
    'remedy': 'Opening the way back',
    'sub': 'The chance of reconnecting with a past partner, and when reaching out lands well',
    'theirResponse': 'How they felt back then',
    'timing': 'When reaching out lands well',
    'title': 'Reunion reading',
  },
  reunionAsk: {
    'cta': 'See the in-depth reunion reading',
    'q': 'Will we get back together?',
    'sub': 'We\'ll point out, for free, the chance, timing and direction of reconnecting with a past partner',
  },
  selfAnalysis: {
    'elements': 'Element balance — the five energies that make you',
    'footNote': '※ All computed on-device with the saju engine (perpetual calendar). Not a prophecy, but a reference for understanding yourself.',
    'kicker': 'You, analyzed by the saju engine',
    'more': 'See details ›',
    'strengths': 'Strengths & temperament in detail',
    'sub': 'A five-part self-analysis computed from the saju you were born with — an index for understanding yourself, not a fortune.',
    'title': 'My analysis',
    'titleSuffix': '\'s analysis',
  },
  signup: {
    'body': 'The passes and readings you bought are tied to the temporary account you\'re using now. If you delete the app or change devices, they\'re hard to get back. Link an account and they carry over.',
    'cta': 'Link an account',
    'note': 'You can keep using the app as you are without linking.',
    'title': 'The readings you\'ve seen live only on this device',
  },
  signupPrompt: {
    'cta': 'Link account',
    'later': 'Later',
    'msg': 'You\'re on a temporary account, so if you delete the app or change devices, the passes and readings you bought are hard to get back. You can keep viewing without linking.',
    'title': 'Link an account and this reading stays safe',
  },
  spouseDual: {
    'ageHint': 'Age-range hint',
    'ageNote': '※ A tendency only. If you have their actual chart, compatibility takes priority.',
    'funnel': 'For a more specific ideal type, real connections and timing, see the love reading below.',
    'gap': 'Contrast',
    'idealTag': 'The type you\'re drawn to',
    'ignite': 'Attraction (ignition)',
    'match': 'Match',
    'noFlow': 'Over the next eight years, signals of the spouse seat opening and closing are weak. It\'s a time for consolidating rather than big shifts.',
    'realDesc': 'The substance of married life — the seat that always comes first (day branch)',
    'realTag': 'Who actually stays beside you',
    'settle': 'Stability (settling)',
    'sub': 'We read the spouse seat you were born with along two axes — the type you\'re drawn to, and who actually stays.',
    'timeline': 'Attraction vs stability — the flow of connection',
    'title': 'Your ideal type and your real connection',
  },
  traits: {
    'detail': 'Go deeper into my saju',
  },
  wealth: {
    'flow': 'Wealth flow across your life',
    'generating': 'Reading the wealth vessel and flow you were born with…',
    'howEarn': 'How money comes to you',
    'partner': 'Alone vs together',
    'remedy': 'Protecting & lifting wealth',
    'sub': 'The wealth vessel and type you were born with, when it comes in big, and how to keep it',
    'timing': 'Wealth timing',
    'title': 'Wealth deep report',
    'type': 'Wealth type',
    'vessel': 'Wealth vessel',
  },
  yieojim: {
    'express': 'Years when feelings stir but settling is weak',
    'mine': 'Years when reaching out first tends to connect',
    'mineNone': 'It\'s weak over the next ten years — the force to express and reach out first (output stars) is thin in your chart, so it concentrates in specific periods (when that energy arrives).',
    'note': '※ A reference tendency. Real connections depend on who you meet. Either way, the key to it lasting is a year when the connection seat opens.',
    'popular': 'Years with attention and popularity but weak settling',
    'sub': 'Whether it\'s a crush or making a move, for it to actually connect the \'connection seat\' (spouse palace) has to be open then.',
    'theirs': 'Years when a good connection comes to you and lasts',
    'theirsNone': 'Over the next ten years, there\'s no clear period where a connection comes and settles.',
    'title': 'When connections take hold',
  },
};
