// app/src/copy/en.ts — English UI copy. Keys must match ko.ts exactly.
export const en = {
  appName: 'Niunnaeun',
  tagline: 'Your AI compass for understanding yourself and others',
  // 홈 카드 개인화 티저 — ko 와 동일 키(계산=homeTeaser.ts). ※ newyear.keyword 값 자체는 엔진이 한국어로 산출(기존 티저 전반과 동일).
  teaser: {
    career: 'Founder {{biz}}% · Employee {{org}}%',
    newyear: "This year's keyword · {{keyword}}",
    flow: 'Phase {{n}} now · {{turns}} turning points',
    crush: '{{year}} · month {{months}} — attraction rises',
    reunion: '{{year}} · month {{months}} — good to reconnect',
    job: '{{years}} — doors open',
    raw: '{{text}}', // image·talent·mission — text is engine-generated Korean (same approach as newyear.keyword), same value across locales
  },
  onb: {
    skip: 'Skip', next: 'Next', start: 'Start my analysis',
    t1: "The AI that analyzes 'you'",
    b1: 'Niunnaeun is not a horoscope app. It uses Saju as its engine to analyze who you are — a self-understanding tool.',
    t2: 'We compute your own chart',
    b2: 'Your birth data is calculated with a precise perpetual-calendar engine (true solar time, historical corrections) — an analysis that is yours alone.',
    t3: "What you'll understand",
    l1: 'Who you are — traits & strengths', l2: 'Why your relationships repeat', l3: 'What work fits you', l4: 'What to prepare this year',
    t4: "Here's how we analyze you", pvBadge: 'Sample', pvType: 'Teto type', pvScale: 'Teto 63%', pvLine: 'Decisive and driven — though a little rest now and then is your real strength.', pvNote: 'Just enter your birth details for your own analysis',
  },
  // ★App Store 4.3 (spam/duplicate) — surface that results are COMPUTED (used by ComputedNote).
  //   Reviewer sees the app in English, so this block must read clearly on its own.
  computed: {
    title: 'Computed from your exact birth data',
    body: 'A perpetual-calendar engine (true solar time, longitude, historical DST) builds your individual chart, then 40+ codified classical rules are applied to it — no two people get the same result.',
    badge: 'Computed from your birth data',
    more: 'It also computes hidden stems, clashes/combinations/punishments, sinsal, and luck cycles, then cross-validates two traditions — Saju and Zi Wei Dou Shu.',
  },
  menu: {
    'egenteto': '에겐·테토 성향',
    lookback: 'Look back', lookbackDesc: 'Your notes next to that day\'s reading',
    myeongsik: 'Register Chart', myeongsikDesc: 'Add & manage your chart',
    manse: 'Manseryeok', manseDesc: 'Calendar charts & management', timeResolve: 'Find Your Hour', timeResolveDesc: 'Infer your birth hour from life events',
    ziwei: 'Zi Wei Dou Shu', ziweiDesc: 'Palaces & stars reading',
    taro: 'Tarot', taroDesc: "Today's card",
    today: 'Daily Fortune', todayDesc: 'Changes every day', month: 'Monthly Fortune', monthDesc: "This month by area",
    compat: 'Compatibility', compatDesc: 'Deep relationship analysis',
    premium: 'Premium Reading', premiumDesc: 'Deep reading · all areas', premiumTag: 'Premium',
    timeline: 'Life Timeline', timelineDesc: 'Decade-by-decade, age 10–100',
    pet: 'My Pet', petDesc: "Your companion's nature", love: 'My Love Flow', loveDesc: 'Ideal type & who you meet, in detail',
    lifegraph: 'Life Graph', lifegraphDesc: 'Your life-flow curve & turning points by decade',
    newyear: 'New Year', newyearDesc: 'Year overview · monthly · samjae',
    roots: 'Roots', rootsDesc: 'Shown self · hidden strength · true power',
    image: 'How You Appear', imageDesc: 'First impression & vibe to others',
    impression: 'How Others See You', impressionDesc: 'From first impression to a deep bond',
    mission: 'My Calling', missionDesc: 'What you were born to do',
    persona: 'Personality', personaDesc: 'Your 16 saju personality types', egen: 'Egen vs Teto', mbti: 'Saju MBTI', traits: 'My Traits', selfAnalysis: 'My Analysis', selfAnalysisDesc: 'Personality, temperament & element balance at a glance', relationPattern: 'Relationship Pattern', relationPatternDesc: 'Why your relationships repeat — your innate relational nature', personal: 'Personal Element', personalDesc: 'Colors, style, makeup & car colors for your element', gem: 'My Saju Gemstone', gemDesc: 'Your birthstone may not fit you — the gem that truly lifts you', sokgunghap: 'Intimate Match', sokgunghapDesc: 'Sexual compatibility of two people (adult · fun)', community: 'Community', communityDesc: 'Share saju, love & life questions together', joseonjob: 'Joseon Job', lovestyle: 'Love Style', bok: 'Your Fortune', pastlife: 'Past Life', healing: 'My Healing',
    taegil: 'Lucky Days', country: 'My Best Place', countryDesc: 'Countries that fit your energy', taegilDesc: 'Best days for wedding · moving · contracts',
    luck: "Today's Luck", luckDesc: 'Lucky color · direction · number',
    zodiac: 'Zodiac', zodiacDesc: 'Daily Chinese & star sign',
    name: 'Name Reading', nameDesc: 'The five elements in your name',
    dream: 'Dream Guide', dreamDesc: 'Search by dream keyword',
    dayPillar: 'Day Pillar', dayPillarDesc: 'Your nature by your birth day', career: 'Founder or Employee', careerDesc: 'Your two paths: business vs job', gaeun: 'Lucky Boost', gaeunDesc: 'Lift your luck for this cycle', followupDesc: 'Ask one more about your reading', talent: 'My Innate Talent', celeb: 'Celebrities Like Me', celebDesc: 'Compare your chart with actors and idols', talentDesc: 'Your gifts, drive, and money style', numerology: 'Numerology', numerologyDesc: 'Your life path and talents by number', astrology: 'Zodiac & Astrology', astrologyDesc: 'Your star sign + full natal chart',
    child: 'Children', childDesc: 'Your bond, their nature, you as a parent', future10: 'Me in 10 Years', future10Desc: 'Your life 10 years on, by luck cycles', reunion: 'Reunion', reunionDesc: 'When & whether an old love may reopen', crush: 'Crush & Attraction', crushDesc: 'Whether it can bloom · who is drawn to you · when to approach', job: 'Job & Career Move', jobDesc: 'When hiring, a move, or an exam is likely to land', jobfit: 'Careers That Fit', jobfitDesc: 'Which careers suit your nature — desire vs ability gap', wealth: 'Wealth Deep Report', wealthDesc: 'Your wealth capacity & type, when it flows in, and how to keep it', reunionAsk: 'Can we reunite?', reunionAskDesc: 'Free: reunion odds & best months to reach out', crushAsk: 'Will it bloom?', crushAskDesc: 'Free: your charm & when the spark ripens', jobAsk: 'When will I land it?', jobAskDesc: 'Free: when hiring & exams open up',
    saju: 'Saju', sajuDesc: 'Reading · timeline · compatibility', ziweiHub: 'Zi Wei', ziweiHubDesc: 'Chart · luck · compatibility',
    secLove: 'Love', secLoveDesc: 'Compatibility, bonds, and timing',
    secToday: 'Fortune', secTodayDesc: 'Today, this month, this year',
    secSelf: 'About Me', secSelfDesc: 'Personality and how others see you',
    secWork: 'Work & Wealth', secWorkDesc: 'Aptitude, jobs, and money',
    secHidden: 'More', secHiddenDesc: 'Found through recommendations',
    chipLove: 'Love', chipToday: 'Fortune', chipSelf: 'Me', chipWork: 'Work', chipHidden: 'More',
    secLife: 'Life', secLifeDesc: 'Tarot, Zi Wei, and lighter reads',
    secTool: 'Tools', secToolDesc: 'Look it up yourself in the almanac',
    chipLife: 'Life', chipTool: 'Tools',
    chipAll: 'All',
    secContent: 'Popular', // ★shortcut row (outside the topic axis)
    // (legacy) price-axis labels — unused after the topic rework; kept for an easy revert.
    secFree: 'Today & Chart', secPremium: 'Understand Yourself', secSpecial: 'Special', secDeep: 'Know Yourself', secLight: 'For Fun',
    viewCard: 'Cards', viewList: 'List', // home view toggle
    todayTileDesc: "Today's flow", monthTileDesc: "This month's flow", newyearTileDesc: "This year's keyword & 12 months", personaTileDesc: 'Saju personality type', taegilTileDesc: 'Pick a good day', luckTileDesc: "Today's luck", zodiacTileDesc: 'Zodiac & star sign', nameTileDesc: "Name's sound energy", dreamTileDesc: 'Dream meaning', egenTileDesc: 'Are you Egen or Teto?', mbtiTileDesc: 'Your MBTI by saju', joseonjobTileDesc: 'Your job in old Korea', lovestyleTileDesc: 'Your love cells?', bokTileDesc: 'Your innate fortune?', pastlifeTileDesc: 'Who were you?', healingTileDesc: 'Your way to rest?',
    secPremiumDesc: 'Who you are — in depth via Saju & Zi Wei', secContentDesc: 'AI-crafted deep readings', secHotDesc: 'What people are looking at most right now', secDeepDesc: 'Look deeper into who you are', secLightDesc: 'Light daily fun',
  },
  common: { save: 'Save',
    'more': 'More',
    retryLaterNoCharge: 'Please try again shortly. No woon was used.',
    'add': '추가',
    'confirm': '확인',
    'delete': '삭제',
    'edit': '수정',
    'retry': '다시 시도',
    'retryLater': '잠시 후 다시 시도해 주세요.',
    'tapToClose': '탭하여 닫기',
    back: '← Back', login: 'Log in', signup: 'Sign up', logout: 'Log out', loggingOut: 'Logging out…',
    comingSoon: 'Coming soon.', error: 'Error', loginOptional: 'Log in / Sign up (for paid & saving — optional)',
    cancel: 'Cancel', none: 'None',
    llmBusy: 'Readings are temporarily unavailable right now. Please try again in a little while.',
    llmMaking: 'This reading is already being prepared. Please check back in a moment.',
    genFailed: 'Could not load the reading. Please try again in a little while.',
  },
  auth: {
    'login': '로그인',
    signin: 'Log in', signupTitle: 'Sign up', email: 'Email', password: 'Password (6+ chars)',
    toSignup: "Don't have an account?  Sign up", toSignin: 'Already have an account?  Log in',
    needInput: 'Enter your email and password.', signupDone: 'Verification email sent. Verify, then log in.',
    or: 'or', google: 'Continue with Google', apple: 'Continue with Apple', naver: 'Continue with Naver', processing: 'Signing in…',
  },
  register: {
    'catDeleteTitle': '카테고리 삭제',
    'catHint': '카테고리를 길게 누르면 삭제돼요 (그 명식들은 기타로 이동)',
    'editDone': '완료',
    'exactTime': '정확한 시각을 알아요 (출생지 경도로 진태양시 보정)',
    'hour12': '시(1~12)',
    'invalidDateTitle': '생년월일을 확인해 주세요',
    'minute': '분',
    'newCategory': '새 카테고리',
    'newCategoryPh': '새 카테고리 이름',
    'orSijin': '또는 시진(2시간)만 알 때',
    'placeSearchBlocked': '지역 검색이 잠시 제한됐어요. 30초쯤 뒤에 다시 시도해 주세요.',
    'placeSearchFailed': '지역 검색을 불러오지 못했어요. 연결을 확인해 주세요.',
    name: 'Name / Alias', namePh: 'e.g. John / Me',
    birthDate: 'Birth date (YYYY-MM-DD)', birthDatePh: '1990-03-15',
    birthTime: 'Birth time (HH:mm, blank if unknown)', birthTimePh: '07:10',
    calendar: 'Solar / Lunar', solar: 'Solar', lunar: 'Lunar', normalMonth: 'Regular', leapMonth: 'Leap',
    sex: 'Sex', male: 'M', female: 'F',
    birthPlace: 'Birthplace', birthPlacePh: 'Tap to search city',
    relation: 'Relation', submit: 'Calculate · Register',
    birthTimeSijin: 'Birth time (Sijin)', timeUnknown: 'Unknown', selfLabel: 'Self', makeRep: 'Set as main chart',
    relationCustom: 'Custom', relationCustomPh: 'Enter relation (e.g. my boss)',
    ctxTitle: 'Tell us about you (optional)', ctxDesc: "Helps make this chart's readings more accurate. You can leave it blank.",
    ctxSit: 'What best describes you now?', ctxSitDesc: 'Readings will speak to this situation',
    sitStudy: 'Student', sitWork: 'Employed', sitBiz: 'Business owner', sitFree: 'Freelance',
    sitHome: 'At home / parenting', sitSeek: 'Job seeking', sitRetire: 'Retired', sitEtc: 'Other',
    ctxJob: 'Occupation', ctxJobPh: 'e.g. designer / self-employed / student',
    ctxRel: 'Relationship', ctxRelSingle: 'Single', ctxRelDating: 'Dating', ctxRelMarried: 'Married', ctxRelOther: 'Other',
    ctxConcern: 'Current focus', ctxConcernPh: 'e.g. career change, new relationship, health',
    ctxNote: 'Note', ctxNotePh: 'Anything you want the reading to consider',
    selfExistsTitle: 'You already have a self chart', selfExistsMsg: "Only one self chart is allowed. Move the current self chart to 'Other' and set this one as your self chart?", selfReplace: 'Set as self',
    birthPlaceSearch: 'Search city/region', birthPlaceSearchPh: 'e.g. Seoul, Tokyo', useAsIs: "Use '{{q}}'",
    limitTitle: 'Free registration limit', limitMsg: 'The free plan lets you register up to {{limit}} charts.\nWatch an ad to add one more, or upgrade to Pro for unlimited.',
    upgrade: 'Upgrade to Pro', usage: 'Charts {{count}}/{{limit}}',
    watchAdAdd: 'Watch ad, add 1', adNotFinished: 'Finish the ad to add a chart.',
  },
  myeongsik: {
    palja: 'Four Pillars', dayMaster: 'Day Master', strength: 'Strength index', pattern: 'Pattern', patternRevealed: 'revealed', patternHidden: 'latent',
    stages: '12 Stages', interactions: 'Combos/Clashes', sinsal: 'Sinsal/Void', gongmang: 'Void',
    noHit: 'no natal hit', ziwei: 'Zi Wei', lifePalace: 'Life Palace',
    readingBtn: 'See area readings →', noChart: 'No chart data.',
    root: 'Root', hidden: 'Hidden stems',
    luck: 'Luck cycles', daewoon: 'Decade', sewoon: 'Year', elements: 'Five elements',
    합: 'Combine', 충: 'Clash', 형: 'Punish', 해: 'Harm', 파: 'Break', 극: 'Control',
    sinsalHint: '✓ (pillar) if the branch is in the natal chart; otherwise it activates in luck cycles', ssLuck: 'in luck', dayPillar: 'Day pillar',
    sinsalDetail: 'Sinsal & Void in detail →',
  },
  reading: {
    'lockedNote': '위 버튼으로 열어 전부 보실 수 있어요.',
    'lockedTitle': '이 명식의 풀이는 운으로 열려요',
    'pastYearBadge': '이 풀이는 {{y}}년 운(세운) 기준으로 쓰였어요 — 올해 흐름은 재통변하면 새로 반영돼요.',
    'recommend': '이런 콘텐츠도 좋아하실 거예요',
    'renew': '🔄 최신 통변으로 재통변',
    'sajuTitle': '사주 풀이',
    title: 'Full Reading · Premium', sub: 'All 16 areas in one deep, precise reading. (Chart is free)',
    runAll: 'See full reading ({{count}})', progress: 'Reading ‘{{current}}’… ({{done}}/{{total}})', generating: 'Crafting your reading…', saveFail: 'Failed to save chart. Please try again.', refreshStale: 'Update to latest reading', refreshDeniedTitle: 'Refresh limit', refreshDenied: 'This reading can be refreshed up to {{cap}} times.',
    ziweiTitle: 'Zi Wei · 12 Palaces · Premium', ziweiSub: 'All 12 palaces interpreted together. (Chart is free)',
    timelineTitle: 'Life Timeline · Premium', timelineSub: 'Age 10–100, one decade at a time — what each phase holds.',
    bannerPremium: 'Subscribed — unlimited readings', bannerTrial: '🎁 First reading free!',
    bannerGated: 'Pick an area to unlock via ad or subscription',
    base: 'Core', past: 'The road so far', overlay: 'Now', future: 'The road ahead', remedy: 'Advice',
    premiumAlert: 'Premium Reading', premiumAlertMsg: 'Pay {{price}} for the deep reading.',
    payPerUse: 'Pay {{price}}', bannerPerUse: '✨ Only the first area is a preview — unlock all for {{price}}', bannerUnlocked: '✨ Unlocked — generate the full reading',
    askTitle: 'Ask a follow-up', askPh: 'Ask anything more about this reading',
    askSend: 'Ask', askFree: '{{n}} free question(s) left', askPaid: "Free questions used up — {{price}} per extra question",
    askPremiumTitle: 'Premium only', askPremiumMsg: 'With Premium you get 2 free follow-up questions per area.',
    askPremiumCta: 'Ask more with Premium', askPayTitle: 'Follow-up', askPayMsg: "You've used your free questions. Ask one more for {{price}}?",
    askPayBtn: 'Pay {{price}}', payPending: 'Coming soon',
  },
  compat: {
    'genConfirm': '생성',
    'genCta': '이 관계 풀이 만들기',
    'genTitle': '풀이 만들기',
    'otherPick': '상대 선택 · 새 상대 등록',
    'scoreHarmony': '조화',
    'scoreTension': '긴장',
    'step1': '① 누구와 볼까요?',
    'step2': '② 어떤 사이인가요?',
    'step3year': '③ 언제로 볼까요?',
    'wizPickShort': '탭해서 선택',
    'yearPick': '년도 선택',
    otherInfo: "Partner info (consent required)", otherDatePh: "Partner birth date 1992-07-03",
    otherTimePh: 'Birth time (blank if unknown)',
    dayRelation: 'Day-master relation', harmonyTension: 'Harmony {{h}} · Tension {{t}}',
    usefulGod: 'Useful-god support', crossInter: 'Cross combos/clashes',
    needChart: 'Register your chart first to see compatibility.', registerMyChart: 'Register chart',
    mySlot: 'My chart', otherSlot: 'Their chart', change: 'Change', orDirect: 'Or enter them directly',
    registerOther: 'Register partner chart', registerOtherTitle: 'Register partner', registerOtherSubmit: 'See compatibility with this chart',
    yearAll: 'Overall',
    analyze: 'See compatibility', generating: 'Reading your compatibility…', noReading: "Couldn't generate. Please try again.",
    secBase: 'How you two mesh', secDynamic: 'Where you click · where you clash', secAdvice: 'How to nurture it',
    detailToggle: 'Show character interactions',
    premiumTitle: 'Premium only', premiumMsg: 'Premium gives you 5 free compatibility readings.',
    payTitle: 'Another reading', payMsg: "You've used your 5 free readings. See this one for ₩2,500?", payBtn: 'Pay ₩2,500',
    rel: { friend: 'Friend', family: 'Family', crush: 'Crush', love: 'Dating', marriage: 'Marriage', coworker: 'Coworker', senior: 'Mentor/Senior', business: 'Business', staff: 'Staff', invest: 'Investing' },
  },
  category: {
    성격내면: 'Personality', 취업운: 'Job-seeking', 직장운: 'Career', 사업운: 'Business',
    금전소득운: 'Income', 투자편재운: 'Investment', 재물손재: 'Money/Loss', 연애운: 'Love',
    결혼배우자운: 'Marriage', 대인사회성: 'Social', 부모운: 'Parents', 형제운: 'Siblings',
    자식운: 'Children', 건강: 'Health', 학업자기계발: 'Study', 이동환경: 'Relocation',
  },
  today: {
    'areaSoon': '이 분야 풀이는 다음 운세부터 채워져요.',
    today: 'Today', tomorrow: 'Tomorrow', energyTomorrow: "Tomorrow's Energy", weekdaysShort: 'Sun,Mon,Tue,Wed,Thu,Fri,Sat',
    dayPillar: "Today's Energy", note: "Changes daily at midnight, read against your own chart — deeper readings in Premium.",
    areas: 'Readings by area', area_general: 'Overall', area_work: 'Work', area_money: 'Wealth', area_invest: 'Investing', area_love: 'Love', area_health: 'Health',
    needChart: 'Register your chart to get today personalized for you, area by area.', registerBtn: 'Register chart',
    more: 'See it area by area →',
    genFail: "We couldn't create your reading. Please try again in a moment.", title: "Today's Fortune", heroSub: 'How your day is shaping up today', generating: "Reading today's flow for you…", gateTitle: "See Today's Fortune", gateDesc: "Combining who you are with your bigger picture right now, this year, and today's mood, we'll walk you through what might come up today and how to handle it.", seePremium: "See Today's Fortune", seeAd: 'Watch an ad to view for free', adFail: "Couldn't load the ad. Please try again later, or go ad-free with Premium.",
  },
  settings: { community: 'Community', nickPh: 'Nickname (2–12 chars, empty = auto handle)', nickBad: 'That word can\'t be used.', nickLen: 'Nickname must be 2–12 characters.', nickDone: 'Saved', showIlju: 'Show my day-pillar badge', iljuHint: 'Only the two characters of your birth day show next to posts. Your birth date can\'t be derived.',
    'accent': 'Background Tone',
    'accentAuto': '자동(일간)',
    'accentDesc': 'The background tone follows your chart’s day-stem element. You can pick one yourself.',
    'accentGold': '골드',
    'coins': '운',
    'loadingOff': '끄기',
    'loadingScreen': '로딩 화면',
    'loadingVideoOff': '八字 한자',
    'loadingVideoOn': '호랑이 영상',
    'loginBenefit': '로그인하면 구매한 콘텐츠가 다른 기기·재설치에서도 이어져요 (선택)',
    'notif': '알림',
    'notifDaily': '매일 오늘의 운세 알림',
    'notifDenied': '꺼짐 · 눌러서 기기 설정에서 켜기',
    'notifDeniedMsg': 'To receive notifications, enable Niunnaeun notifications in your device settings.',
    'notifNA': '이 기기에서 사용 불가',
    'notifOff': '꺼짐 · 눌러서 켜기',
    'notifOn': '켜짐 · 매일 오전 9시',
    'notifOnMsg': '알림이 켜져 있어요. 끄려면 기기 설정에서 바꿀 수 있어요.',
    'notifUnavailable': '이 기기에서는 알림을 사용할 수 없어요.',
    'openSettings': '설정 열기',
    'readingVideo': '풀이 로딩 영상',
    'readingVideoOff': '심플(영상 없이)',
    'readingVideoOn': '테마 영상',
    'restore': '구매 복원',
    'restoreDone': '구매가 복원되었습니다.',
    'restoreFail': '구매 복원에 실패했어요. 잠시 후 다시 시도해 주세요.',
    'restoreNone': '복원할 구매 내역이 없습니다.',
    'restorePending': '구매가 확인됐어요. 서버 반영까지 잠시 걸릴 수 있어요 — 잠시 후 다시 확인해 주세요.',
    'restoring': '복원 중…',
    'themeRestart': '앱을 다시 켜면 적용돼요.',
    homeOrder: 'Home layout order', homeOrderNote: 'The order shown on your home screen. Move items up or down.', homeOrderReset: 'Reset to default order',
    account: 'Account', loginCta: 'Log in / Sign up', premium: 'Premium',
    premiumActive: '✓ Premium active', premiumBuy: 'Lifetime Premium', premiumDesc: 'All premium content — now & future — free · no ads · one-time, yours forever · 30% off yearly re-readings (10% for others)', 
    premiumOkTitle: 'Premium', premiumOk: 'Premium is now active.', premiumTitle: 'Premium',
    deleteAccount: 'Delete account',
    delTitle: 'Delete account', delMsg: 'Your account and all data (charts, readings, passes) will be permanently deleted. This cannot be undone.', delConfirm: 'Continue',
    delTitle2: 'Are you sure?', delMsg2: 'This action cannot be undone.', delFinal: 'Delete permanently',
    delFail: 'Deletion failed. Please try again later.', delDoneTitle: 'Deleted', delDone: 'Your account and data have been deleted.', deleting: 'Deleting your account…',
    fontSize: 'Text size', size_sm: 'Small', size_md: 'Medium', size_lg: 'Large', size_xl: 'X-Large',
    appInfo: 'App Info', version: 'Version', terms: 'Terms of Service', privacy: 'Privacy Policy', license: 'Open Source Licenses', bugReport: 'Report a Bug · Contact', bugReportFail: "Couldn't open your mail app. Please email us at:",
    preview: 'Preview — readings appear at this size. It applies to reading, daily fortune, and compatibility text.',
    language: 'Language', 
    coupon: 'Enter coupon', couponPh: 'Enter coupon code', couponRedeem: 'Redeem', couponHave: 'Your passes',
    couponOkTitle: 'Redeemed', couponOk: 'Free pass applied. You can use that feature for free.',
    couponFailTitle: 'Failed',
    couponErr_invalid: 'Invalid code.', couponErr_expired: 'This coupon has expired.',
    couponErr_exhausted: 'This coupon is used up.', couponErr_already: 'Already redeemed.', couponErr_auth: 'Please log in.',
  },
  timeline: {
    'readThis': '이 시기 풀이 보기',
    decades: 'By decade', years: 'By year', pickDecade: 'Pick a period', pickYear: 'Pick a year', thisYear: 'This year', now: 'Now',
    catGeneral: 'Overall', catWork: 'Work', catMoney: 'Money', catLove: 'Love', catHealth: 'Health',
    catSocial: 'People', catGrowth: 'Growth', catMove: 'Change', months: 'Month by month', monthUnit: '',
    generating: 'Reading this period…', tapToRead: 'Pick a period or year to read its flow.',
    premiumTitle: 'Premium only', premiumMsg: 'The Life Timeline reads each period in Premium.',
    lockedTitle: 'Locked period', lockedSub: 'Your current decade and this year are free; open other periods with a pass for a category-by-category reading.',
    unlock: 'Open this period', unlockTitle: 'Open this period',
    unlockMsg: 'A timeline pass opens this period with a detailed category reading. (Get passes via coupons in Settings · per-use payment coming soon)',
    buy5: '5 yearly readings {{price}}', buy10: 'Full decade · 10 yrs {{price}}', // yearly (세운) bundles — lock-card buy buttons (daniel 07-23)
    freeBadge: 'Free', usedCredit: 'Opened with a pass',
  },
  premiumHub: {
    sub: 'What would you like to see?',
    sajuReading: 'Saju reading', sajuReadingDesc: 'Deep reading across 16 areas — personality, money, love, work…',
    ziweiReading: 'Chart reading', ziweiReadingDesc: '12 palaces + decade luck & transformations over time',
  },
  pet: {
    title: 'My Pet', sub: "A light look at your companion's natural temperament.",
    add: 'New pet', name: 'Name', namePh: 'e.g. Kong', typeLabel: 'What kind?',
    birth: 'Birth date (YYYY-MM-DD)', time: 'Birth time', timeOptional: "— optional",
    timePick: 'Pick a time period', timeUnknownChk: "Time unknown",
    timeHint: "Without a time we read only the broad strokes (no time-of-day reading).",
    save: 'See traits', empty: 'No pet added yet.',
    delete: 'Delete chart', deleteTitle: 'Delete', deleteMsg: 'Delete this chart?',
    invalidTitle: 'Please check', invalidDate: 'Enter the birth date as YYYY-MM-DD.',
    type: { dog: 'Dog', cat: 'Cat', rabbit: 'Rabbit', hamster: 'Hamster', bird: 'Bird', fish: 'Fish', reptile: 'Reptile', other: 'Other' },
  },
  love: {
    'genDelayed': '풀이 생성이 지연되고 있어요. 잠시 후 다시 시도해 주세요.',
    'needZiwei': '이 명식으로는 애정 흐름을 풀 수 없어요. 태어난 시가 정확해야 자미 교차 분석이 가능합니다.',
    title: 'My Love Flow', sub: 'Cross-reading Saju and Zi Wei together — from your ideal type to the person you actually meet, in rich detail.',
    generating: 'Cross-reading both charts for your love story…',
    gateDesc: 'Your ideal type, and the real person you meet — their first impression, personality, behavior and habits, how you meet and when — cross-read from Saju and Zi Wei in fine detail.',
    see: 'See it for {{price}}', cacheNote: 'Once unlocked it stays saved (no re-charge).',
    gateTitle: 'My Love Flow', gateMsg: 'No pass yet. Redeem a coupon in Settings, or payment is coming soon. ({{price}})',
    idealType: 'Your ideal type', appearance: 'First impression & image of who you meet', personality: 'Their personality & inner world',
    behavior: 'Their behavior, speech & habits', ageGap: 'Their age relative to yours', howWeMeet: 'How & where you’ll meet', elementMatch: 'Best-matched energy types, ranked', dynamic: 'The chemistry between you', iLoveMore: 'When you love them more', theyLoveMore: 'When they love you more',
    timing: 'When love ripens', cautionPartner: 'Types to be especially mindful of', caution: 'What to watch for', advice: 'How to nurture a good connection', needPay: 'You need a pass to continue. Please try again.',
  },
  month: {
    'aiDesc': '타고난 사주에 지금의 큰 흐름·올해·이번 달 기운을 더해, 이달 생길 수 있는 일과 대처까지 AI가 더 깊게 풀어 드려요.',
    'aiLogin': '로그인하면 AI가 이번 달 흐름을 더 깊게 풀어 드려요.',
    'aiTitle': 'AI 정밀 풀이',
    'thisMonth': '이번 달', title: 'Monthly Fortune', monthPillar: "This month's energy", flowTitle: "This month's flow (early · mid · late)", note: "The broad flow for this month. For specific days, see the Daily Fortune.", heroSub: "The flow of this month's energy", generating: "Reading this month's flow…", gateTitle: "View This Month's Fortune", gateDesc: "We combine the nature you were born with, the big flow you're in now, this year, and this month's energy to share what may come up this month and how to handle it.", seePremium: "View This Month's Fortune" },
  nav: { home: 'Home', contents: 'Readings', community: 'Community', coach: 'Guide', market: 'Market' },
  lookback: { title: 'Look back', sub2: 'The days you did your one thing.', needLogin: 'Sign in to save your notes and revisit them here.', empty2: 'No records yet. Do your one thing under today\'s reading and check it off.', goToday: "See today's reading", summary: 'You marked {{hit}} of {{rated}} rated days as accurate', streak: "You've done your one thing on {{n}} days", myNote: 'My note', missionDone: '✓ Did that day\'s one thing' },
  contents: {
    sub: 'Pick a topic you want to explore',
    searchPlaceholder: 'What are you curious about?',
    searchResult: '{{n}} result(s)',
    searchEmpty: 'Nothing matched.\nTry another word.',
  },
  todayEnergy: { kicker: "Today's energy", point: 'pts', more: "See today's reading" },
  persona120: {
    kicker: 'My personality type', count: 'of 120', more: 'See details',
    title: 'My personality type', sub: '10 day stems × 12 month branches = 120 types',
    empty: 'Register your chart to see which of the 120 types you are.',
    axisStem: 'What I am made of', axisSeason: 'The season I was born into', axisGyeok: 'Where my life leans',
  },
  market: {
    'emptyTopic': '이 주제의 콘텐츠가 준비 중이에요. 다른 주제를 골라 보세요.',
    'hotSection': '🔥 인기',
    'open': '열기',
    'retentionNote': '구매한 풀이는 구매일로부터 1년간 보유되며, 1년이 지나면 자동 삭제됩니다. 이후 다시 보려면 재구매가 필요해요.',
    'sectionIncluded': '✦ 운으로 열기',
    'sectionIncludedSub': '아래 풀이는 운으로 하나씩 열 수 있어요. 명식마다 따로 열립니다.',
    'sectionIndividual': '◆ 개별 구매 전용',
    'sectionIndividualSub': '아래 항목은 하나씩 따로 구매해요.', intro: 'Pick the chart to apply to, then tap a reading.', applyTo: 'Apply to', openApply: 'Open', noChart: 'No saved chart', have: 'You have {{n}}', owned: 'Owned', notOwned: 'Not owned', buy: 'Buy', note: 'Readings are saved per chart. Redeem free passes (coupons) below.', doneTitle: 'Purchased', doneMsg: 'Your pass has been added.', payPending: 'Payment not ready', buyFailTitle: 'Purchase failed' },
  dayPillar: {
    'fullChartNote': '※ 일주론은 ‘태어난 날(일주)’ 하나로 보는 큰 경향이에요. 정확한 풀이는 사주 전체(원국)를 함께 봐야 해요.',
    's_match': '잘 맞는 일주',
    's_stress': '스트레스 해소',
    title: 'Day Pillar', sub: 'Your innate nature, seen through your birth-day pillar (ilju).',
    male: 'Male', female: 'Female', mine: 'My Day Pillar', browseAll: 'All 60 Day Pillars', dayGroup: 'day', tapHint: 'Tap a pillar to expand its full reading.', mineList: 'My Day Pillars', noChart: 'No saved charts. Register a chart first.',
    s_overview: 'Overview', s_personality: 'Personality', s_love: 'Love & Marriage', s_career: 'Career & Wealth', s_male: 'For Men', s_female: 'For Women', s_advice: 'Advice', s_live: 'Life Tips',
    disclaimer: "The day pillar is only one facet of your nature. A precise reading needs your whole chart — the year, month and hour pillars plus combinations, clashes and the useful god — not the day pillar alone.",
  },
  purchase: {
    loginTitle: 'Sign in required', loginMsg: 'Signing in saves your purchases to your account, so they carry over to other devices and reinstalls. Sign in now?', loginCta: 'Sign in',
    restore: 'Restore purchases', restored: 'Purchases restored.', restoreNone: 'No purchases to restore.', restorePending: 'Purchase confirmed. It may take a moment to apply — please check again shortly.', preparing: 'Payments are coming soon.',
  },
  offline: { title: 'Offline', msg: "You're not connected to the internet. You can view saved content, but new readings need a connection.", banner: 'Offline — saved content only' },
  taro: { draw: 'Draw a card', reshuffle: 'Reshuffle', reversed: 'Reversed' },
  manse: {
    'deleteTitle': '명식 삭제',
    'viewManse': '만세력 보기', empty: 'No saved chart.', myChart: 'Chart', searchChart: 'Search by name' },
  sinsal: { 도화: 'Peach Blossom', 역마: 'Travel Horse', 화개: 'Canopy', 천을귀인: 'Nobleman', 문창: 'Academic', 양인: 'Blade', 홍염: 'Romance', 괴강: 'Goegang', 백호: 'White Tiger' },
  special: {
    'freeBasics2': '먼저 무료로 — 빅3 + 생명수',
    'goMarketBtn': '상점으로 이동 ›',
    'ownedBoughtV2': '구매 완료 · 언제든 다시 볼 수 있어요',
    'ownedResumeSub': '생성이 중단됐어요. 추가 결제 없이 이어서 만들어 드려요',
    'ownedResumeTitle': '결제는 끝났어요 — 풀이만 남았어요',
    'ownedTitle': '이미 열려 있는 풀이예요',
    'preparingPayment': '결제 준비 중…',
    'priceMissing': '지금은 이 콘텐츠를 열 수 없어요. 잠시 후 다시 시도해 주세요.',
    'resumeCta': '이어서 풀이 만들기',
    'viewCta': '풀이 보기',
    'working': '진행 중…', previewHead: "What you'll get", unlock: 'Unlock with woon', couponHint: 'Open with woon', couponOnly: 'Open with woon. You can top up in the market.', needPay: 'You need woon. Please try again.', needPayMsg: 'You need woon. Open it with woon now, or top up in the market.', buyNow: 'Buy now', goMarket: 'Go to market', unlockCta: 'Buy & view', unlockHint: 'Opens with woon' },
  roots: { title: 'Roots of Your Chart', sub: 'Your visible self, hidden strengths, and what truly holds firm', generating: 'Tracing your roots…', summary: 'At a glance', surface: 'Visible you', depth: 'Hidden strength', strength: 'What truly holds', gap: 'Surface vs depth', advice: 'How to grow it' },
  image: { title: 'How You Appear', sub: 'Your first impression, vibe, and how you come across with others', generating: 'Drawing your impression…', summary: 'At a glance', firstImpression: 'First impression', persona: 'Outward image', inRelationship: 'In relationships', charm: 'Your charm', gap: 'Surface vs inner', advice: 'How to show up' },
  mission: { title: 'My Calling', sub: 'What you were born to do — your gifts and role in this world', generating: 'Reading your calling…', summary: 'At a glance', coreNature: 'Core nature', calling: 'Your calling', strengths: 'Your gifts', howToRealize: 'How to realize it', successWay: 'How You Succeed', careers: 'Fitting work', environment: 'Where you shine', lifeTheme: 'Life theme', crossInsight: 'Converging direction', advice: 'Living your calling' },
  talent: { title: 'My Innate Talent', sub: 'What you were born with, where you shine — doing what you love or what you must — and how to handle money', generating: 'Reading your innate talent…', summary: 'At a glance', talent: 'Your innate talent', drive: 'Passion vs duty', money: 'How you handle money', howToUse: 'How to use your talent', careers: 'Where you shine', advice: 'A word' },
  numerology: {
    'birthday': '생일수 — 타고난 재능',
    'empty': '명식을 등록하면 생년월일로 수비학을 보여드려요.',
    'master': '✦ 마스터수(11·22·33) 보유 — 잠재력이 큰 대신 다루기 까다로운 수예요.',
    'note': '※ 피타고리안 수비학(서양 표준)으로 산출했어요. 이름 기반 수(표현·영혼수)는 추후 추가됩니다.',
    'personalYear': '개인해 — 올해 흐름', title: 'Numerology', sub: 'Your life direction, talents, and this year — by the numbers in your birth date', generating: 'Reading your numbers…', summary: 'At a glance', lifePath: 'Life Path — your direction', innerYou: 'Inner self & outer image', talent: 'Your talents', thisYear: 'This year', advice: 'A word' },
  astrology: {
    'numCore': '수로 본 나',
    'numGroup': '🔢 수비학 — 생년월일의 수로 보는 나',
    'numLove': '수비학으로 본 관계',
    'numYear': '올해의 수',
    'sub2': '별자리(태양)·점성술(네이탈)·수비학(생명수)을 한 번에 — 세 관점으로 깊이 풀이', title: 'Zodiac & Astrology', sub: 'Your star sign + full natal chart — two views in one', generating: 'Reading your stars…', signGroup: '⭐ Star Sign — by your Sun sign', signSummary: 'Your Sun Sign', signTraits: 'Personality', signLove: 'Love style', signStrength: 'Strengths', natalGroup: '🔭 Astrology — by your natal chart', big3: 'Sun·Moon·Rising', natalLove: 'Love & desire', natalWork: 'Work', strength: 'Strengths', challenge: 'Challenge', advice: 'A word' },
  future10: { title: 'Me in 10 Years', sub: 'Who you become in 10 years — seen through your luck cycles — and how to prepare now', gen: 'Picturing your next 10 years…', bigPicture: 'The big picture in 10 years', career: 'Career & achievement', wealth: 'Wealth & assets', relation: 'Relationships & home', health: 'Health to manage', growth: 'Growth & inner change', prepare: 'What to prepare now' },
  child: { title: 'Children', sub: 'Your bond with your children, their nature, and you as a parent — from your chart', gen: 'Reading your bond with your children…', solo: 'Just me', couple: 'With spouse', pickSpouse: 'Pick spouse chart', coupleHint: "Pick your spouse's chart to read your bond with children from both charts", needSpouse: "Please register your spouse's chart first", bigPicture: 'The big picture of your bond', childNature: "Your child's nature", asParent: 'You as a parent', coupleCross: "The couple's bond with children", communication: 'Communication', timing: 'Timing & flow', talent: "Your child's talents", health: 'Health to manage', remedy: 'Ways to boost fortune' },
  life: { genFail: 'Something went wrong. Please try again in a moment.', gateTitle: 'Life Graph', generating: 'Drawing your life journey…', yongsin: 'The energy you need', focus: 'Focus', hint: 'Tap a point on the curve to see that period in detail.', peak: 'Your brightest years', caution: 'Time to build up and take care', advice: 'A lifelong guide', gateDesc: "We go deep on why each period rises or falls, what to do in the season you're in now, how to make the most of your brightest years, and how to get through the harder stretches.", pv1: 'Why each period rises and falls', pv2: "What to do in the season you're in now", pv3: 'How to make the most of your brightest years', pv4: 'How to get through the tougher times', pv5: 'A direction to keep for life', see: 'View Life Graph', seePaid: 'View Life Graph (₩3,900)' },
  newyear: {
    'remedy': '올해 개운법',
    'strategy': '올해의 대응전략',
    'thisYearSelf': '올해의 나',
    'timing': '올해 좋은 시기',
    'yearNature': '올해는 어떤 해', title: 'New Year Fortune', generating: 'Reading your whole year…', heroSub: 'See the big picture of your year at a glance', keyword: "This Year's Keyword", lucky: "This Year's Lucky Points", halves: 'First Half · Second Half', months: 'Monthly Calendar', samjaeAdvice: 'What to Watch This Year', resolution: 'Make This Year Count', gateDesc: 'From your keyword for the year to fortune by area, a twelve-month calendar, and your New Year resolutions — all in one place.', pv1: "This year's keyword", pv2: 'Fortune across 8 areas', pv3: 'Twelve-month calendar', pv4: 'First and second half trends', pv5: 'What to focus on and your New Year resolutions', see: 'View New Year Fortune', seePaid: 'View New Year Fortune (₩9,900)', },
  taegil: { title: 'Pick a Day — Find the Right Date', sub: "Choose what you're planning, and we'll highlight the dates over the next three months that suit you best.", best: 'Great', good: 'Good', tapHint: 'Tap a highlighted day', },  zodiac: { title: "Today's Zodiac & Star Sign", animal: 'Zodiac Animal', sign: 'Star Sign', mine: 'My Fortune', },
  name: { title: 'Name Reading', sub: 'We read the vibe of your name through the energy in its sounds.', placeholder: 'Enter your name in Korean', noHangul: 'Please enter your name in Korean.', },
  dream: {
    'aiBtn': 'AI 해몽 받기 (₩300)',
    'aiPh': '꿈에서 보거나 겪은 일을 자세히…',
    'aiSub': '복잡한 꿈은 이야기로 적어 보세요 — 사전에 없어도, 여러 상징이 섞여도 풀어 드려요.',
    'aiTitle': 'AI 꿈해몽',
    'buy5': '운 사용',
    'buyBundle': '꿈해몽을 5 운으로 볼까요?',
    'needCredit': '지금은 열 수 없어요. 잠시 후 다시 시도해 주세요.', fail: "We couldn't load the dream meaning. Please try again in a moment.", title: 'Dream Meanings', sub: 'Search for what appeared in your dream.', placeholder: 'e.g. pig, snake, water…', generating: 'AI is interpreting your dream…', notInDict: "This dream isn't in our list. Get an AI interpretation instead.", aiSee: 'See AI Interpretation', history: 'Past Dream Readings' },
  luck: { title: "Today's Luck", todayEnergy: "Today's Vibe", color: 'Lucky Color', direction: 'Lucky Direction', numbers: 'Lucky Numbers', item: 'Lucky Item', weakHead: 'A Color That Supports You', weakTail: ' — this is an energy you tend to be short on, so keeping it close helps you feel more balanced.', },
  renewal: { title: 'Get an updated reading', msg: "It's been a year since this reading.\n\nFor {{coins}} woon ({{pct}}% off) we'll read it again for where you are now. (You have {{have}})", later: 'Later', go: 'Read again', needTitle: 'Not enough woon', needMsg: 'This needs {{need}} woon. You have {{have}}.' },
  assist: { title: 'Wooni', sub: "Tell me what you want to see — I'll take you straight there.", label: 'Guide', hello: 'What would you like to look at? Pick one of the three, or just tell me in your own words.', egLabel: 'You can also say things like', miss: "I didn't catch that yet. Pick one below and I'll take you there.", placeholder: 'What would you like to see?', reset: '↺ Start over', send: 'Send', },
  coach: { title: 'AI Self-Understanding Coach', sub: 'Ask anything about yourself — we answer from your Saju chart.', coachLabel: 'Coach', thinking: 'Reading your chart…', placeholder: 'Ask about yourself', send: 'Send', needChart: 'Please register your chart first.', registerBtn: 'Register chart', loadFail: "Couldn't load your chart. Please try again in a moment.", gateTitle: "You've used today's free questions", gateDesc: 'You can ask up to {{count}} times a day for free. With Premium, chat with the coach without limits.', gateCta: 'See Premium', q1: 'What kind of person am I?', q2: 'Why do my relationships keep repeating?', q3: 'How can I make the most of my strengths?', q4: "How's my current flow?" },
  selfHero: { kicker: 'Who am I', emptyTitle: 'Let us analyze you', emptySub: 'Enter your birth details and the Saju engine analyzes your character, temperament, and strengths', emptyCta: '+ Analyze me', more: 'See full personality analysis ›' },
  personal: {
    'toneCap': '나의 퍼스널 컬러', title: 'Personal Element', sub: 'Colors, style, makeup & car colors for your element', activate: 'Colors that bring you alive', balance: 'Colors worth adding', yongsin: ' (the energy you need)', cody: 'Style', makeup: 'Makeup', car: 'Car color', empty: 'Register a chart to find colors for your element', emptyCta: '+ Add chart', expertNote: '* Personal Five Elements are a reference based on your saju — for real personal-color or styling, consult a professional.' },
  // R-GEM v0.1 — My Saju Gemstone (★daniel review slot: sub·note copy)
  gem: { title: 'My Saju Gemstone', birthstoneTitle: 'What your birthstone means', sub: 'Your birthstone may not fit you — the gem that truly lifts you', empty: 'Register a chart to find gems that fit you', emptyCta: '+ Add chart' },
  timeResolve: {
    'title': '태어난 시 찾기', yearRange: 'Please check the year again (e.g., 1990–this year).', yearFuture: 'You can’t enter a future year.', removeEvent: 'Remove event' },
  sok: { title: 'Intimate Match', sub: 'Sexual compatibility by saju — an adult, just-for-fun read', gateTitle: 'Adult (19+) content', gateDesc: 'Intimate Match reads two people’s sexual compatibility through saju. For fun only.', gateConfirm: 'I’m 19 or older · Start', pickPartner: 'Pick partner', newPartner: 'New partner', registerSubmit: 'See intimate match', spouseLabel: 'Spouse-palace chemistry', adviceLabel: 'How to make it better', kiss: 'Kiss match', bed: 'Bed match', styleLabel: 'Your chemistry style', pickHint: 'Tap to pick partner', noPartner: 'No saved partner. Please add a new one.', disclaimer: '※ A for-fun saju read. Real relationships are built by two people. Adults (19+) only.' },
  community: { daily: 'Today\'s Day Energy', dailyTalk: 'Join the talk', p1: 'Great', p2: 'Good', p3: 'Okay', p4: 'Meh', p5: 'Rough', pollMine: 'Voted! Stats appear once more people join.', pollStat: '{{total}} voted · top pick {{top}}%', all: 'All', cat: { free: 'Free talk', love: 'Love', saju: 'Saju Q&A', review: 'Reviews', question: 'Advice' }, empty: 'Be the first to post.', profanity: 'Contains inappropriate language. Please edit and try again.', write: 'Write', post: 'Post', titlePh: 'Title', bodyPh: 'Write your message (no abuse, hate, or sexual content)', eulaTitle: 'Community Guidelines', eulaBody: 'Abuse, hate, harassment, illegal, or sexual/obscene content is prohibited. Violations may be removed and access restricted. Reported content is reviewed and acted on within 24 hours. You can block abusive users.', eulaAgree: 'Agree & write', comments: 'Comments', noComments: 'Be the first to comment.', commentPh: 'Add a comment (be respectful)', send: 'Send', report: 'Report', block: 'Block', reportTitle: 'Report', reportDesc: 'Choose a reason. Reported content is reviewed within 24 hours.', rAbuse: 'Abuse / hate / harassment', rSexual: 'Sexual / illegal content', rSpam: 'Spam / ads', reported: 'Report received', reportedDesc: 'We’ll review and act. Thank you.', reportFail: 'Failed to report.', blockTitle: 'Block this user', blockDesc: 'Blocking hides this user’s posts and comments from you.', blocked: 'Blocked', blockFail: 'Failed to block.', delTitle: 'Delete?', gone: 'This post was deleted or is unavailable.', loginTitle: 'Sign in required', loginDesc: 'Posting requires sign-in. Reading stays open without an account.', goLogin: 'Sign in', attach: 'Attach my chart', attachNone: 'No chart saved as “myself”. You can still post without attaching one.', attachOff: 'No chart', attachLuck: 'Also share luck cycle & year', attachWarn: 'Your four pillars will be visible to everyone who reads this post. A birth date can be worked back from them, so please check before posting.', needTitle: 'Please enter a title.', needBody: 'Please enter some content.', posting: 'Posting…', errSession: 'Please sign in again and retry.', errNet: 'Check your connection and try again.', errPost: 'Couldn’t post. Please try again shortly.' },
  egen: { title: 'Egen vs Teto', heroSub: 'Your egen/teto vibe, read from your saju', tetoPower: 'Teto Power', typeTeto: 'Teto Type', typeEgen: 'Egen Type', typeBalanced: 'Balanced', scaleEgen: 'Egen', scaleTeto: 'Teto', secPersonality: 'Your Nature', secRelationship: 'In Love & Relationships', secNowTrend: 'Lately', needChart: 'Please register your chart first.', registerBtn: 'Register chart', gateTitle: 'See your vibe explained', gateDesc: 'We explain how your vibe shows up in everyday life, love, and your current flow — matched to your score.', seeAd: 'Watch an ad to see it free', seePremium: 'See explanation', generating: 'Reading your vibe…', genFail: "We couldn't load the explanation. Please try again in a moment.", adFail: "We couldn't load the ad. Please try again, or go Premium to view without ads.", },
  joseonjob: { shareLead: 'My Joseon-era job', traits: 'Your strengths', share: 'Share my job', detail: 'Explore my saju in depth (Premium)' },
  lovestyle: { shareLead: 'My love style', inLove: 'In a relationship', tip: 'Add just this', share: 'Share my love style', detail: 'Explore my love-life flow' },
  bok: { shareLead: 'My fortune', how: 'How to grow it', share: 'Share my fortune', detail: 'Explore my saju in depth (Premium)' },
  pastlife: { shareLead: 'My past life', hint: 'For you, now', share: 'Share my past life', detail: 'Explore my saju in depth (Premium)' },
  healing: {
    'deficit': '가장 적은 기운(참고)', shareLead: 'My healing', recharge: 'How you recharge', nourish: 'Energy to fill', release: 'Energy to release', color: 'Healing color', place: 'Healing space', food: 'Goes well with', mind: 'A word for your heart', elemLead: 'My energy', share: 'Share my healing', },
  bio: {
    'kicker': '바이오리듬',
    'note': '※ 사주와 무관한 참고용 리듬이에요. 0 부근은 컨디션이 바뀌는 전환일.',
    'sub': '오늘의 신체·감정·지성 리듬',
  },
  career: {
    'gateDesc': '두 길에서 어떻게 빛나고 어디서 막히는지, 타고난 무게추와 시기까지 풀어 드려요.',
    'generating': '두 길을 풀어내는 중…',
    'sub': '명식과 대운·세운으로, 독립과 조직 두 길을 짚어 드려요',
    'title': '사업가의 나 vs 직장인의 나',
  },
  celeb: {
    'compare': '일간·오행 비교',
    'funNote': '재미로 보기',
    'matchHead': '닮은 점',
    'myTenGod': '내 십신 구조 요약',
    'reasons': '공통 구조',
    'sub': 'Find the figures whose chart resembles yours',
    'title': 'Celebrities Like Me',
    'topLabel': '나와 가장 닮은 인물',
  },
  coins: {
    spendMsg: 'Use {{cost}} woon to start this reading?\nYou have {{have}} → {{after}} after',
    'balFail': '잔액을 불러오지 못했어요',
    'balance': '보유 운',
    'charge': '운 충전하기',
    'chargeCta': '운 충전하기',
    'donePending': '결제가 완료됐어요. 잔액 반영이 잠시 걸릴 수 있어요.',
    'doneTitle': '충전됐어요',
    'needLoginDesc': '충전한 운은 계정에 보관돼요. 로그인해야 기기를 바꿔도 그대로 남습니다.',
    'needLoginTitle': '로그인이 필요해요',
    'needTitle': '운이 부족해요',
    'note': '· 운은 모든 유료 풀이에 쓸 수 있어요.\\n· 충전한 운은 계정에 보관돼요 — 기기를 바꿔도 그대로예요.\\n· 운은 사용 기한이 없어요.',
    'packs': '운 충전하기',
    'spend': '운 사용',
  },
  country: {
    'needChart': '먼저 명식을 등록해 주세요.',
    'sub': '타고난 기운(조후)을 보완해 줄 기후·방위의 나라를 짚어 드려요',
    'title': '내가 살기 좋은 곳',
  },
  crush: {
    'caution': '조심할 점',
    'generating': '끌림의 기운과 인연의 흐름을 읽는 중…',
    'howToApproach': '다가가는 법',
    'myCharm': '지금 나의 매력',
    'sub': '지금 나의 매력과, 짝사랑·썸이 무르익기 좋은 시기, 다가가는 법을 짚어 드려요',
    'timing': '썸이 무르익는 시기',
    'title': '짝사랑 인연운',
    'whoLikesMe': '나에게 끌릴 사람',
  },
  crushAsk: {
    'cta': '깊은 짝사랑 풀이 보기',
    'q': '그 사람과 이어질까?',
    'sub': '짝사랑·썸이 무르익어 마음이 통하기 좋은 달을 무료로 미리 짚어 드려요',
  },
  gaeun: {
    'gateDesc': '지금 운에 무엇이 오는지 보고, 재물·관계·건강을 살리는 실천과 살풀이까지 짚어 드려요.',
    'generating': '지금 운에 맞는 개운법을 찾는 중…',
    'sub': '지금 운(대운·세운)에 맞춰 운을 살리는 구체적인 방법을 짚어 드려요',
    'title': '맞춤 개운법',
  },
  home: {
    'lightCta': '가볍게 보기',
    'manseSub': '내 사주 명식 전체 보기',
    'noChartCta': '+ 명식 등록',
    'noChartSub2': '생년월일만 넣으면 성격유형과 일주를 바로 볼 수 있어요. 가입도, 저장도 안 해요.',
    'noChartTitle': 'AI가 분석하는 나 — 여기서 시작',
    'quickRegister': '명식 등록',
    'quickRegisterSub': '가족·연인·친구의 명식을 추가해요',
  },
  impression: {
    'gapBig': '겉으로 비치는 모습과 알고 난 뒤의 모습이 꽤 달라요. 처음엔 몰랐던 반전 매력이 있는 사람이에요.',
    'gapSmall': '겉으로 비치는 모습과 속이 비교적 한결같아요. 보이는 그대로 믿음이 가는 사람이에요.',
    'inner': '막상 알고 보면 — 진짜 내 모습',
    'note': '※ 천간(밖으로 드러나는 기운)의 흐름이 남에게 비치는 이미지, 월지(타고난 자리)의 기운이 알고 보면 진짜 모습이에요.',
    'outer': '겉으로 비치는 나',
    'sub': '겉으로 비치는 모습과 알고 보면 다른 진짜 나',
    'title': '사람들이 보는 나의 인상',
  },
  job: {
    'bestField': '맞는 직종·환경',
    'flow': '취업·이직 흐름',
    'generating': '취업·합격의 기운과 흐름을 읽는 중…',
    'passLuck': '합격·시험운',
    'sub': '취업·이직·합격·시험이 잘 풀리는 흐름과 시기, 맞는 직종·준비 법을 짚어 드려요',
    'timing': '좋은 시기',
    'tips': '준비 팁',
    'title': '취업·이직운',
  },
  jobAsk: {
    'cta': '깊은 취업 풀이 보기',
    'q': '취업·이직, 언제 잘 풀릴까?',
    'sub': '취업·이직·합격의 문이 열리기 좋은 시기를 무료로 미리 짚어 드려요',
  },
  jobfit: {
    'ability': '실제 잘하는 것',
    'archetype': '나의 직업 유형',
    'gap': '끌림과 능력의 간극',
    'generating': '타고난 적성과 어울리는 직업을 읽는 중…',
    'jobs': '어울리는 일',
    'luckMap': '직업 인생 흐름',
    'preference': '끌리는 것 (능력 아님)',
    'recognition': '인정받는 법·무대',
    'sub': '타고난 적성으로 어떤 직업이 어울리는지, 끌림과 능력의 간극까지 짚어 드려요',
    'title': '나에게 어울리는 직업',
    'workEnv': '잘 맞는 일터',
    'workMode': '일하는 결·모드',
    'yongsinFit': '알맞은 방향',
  },
  login: {
    'go': '로그인',
    'needContentMsg': '이 콘텐츠를 보려면 로그인해 주세요. 로그인하면 구매·풀이가 계정에 안전하게 저장돼요.',
    'needTitle': '로그인이 필요해요',
  },
  mbti: {
    'empty': '명식을 등록하면 사주로 본 MBTI를 보여드려요.',
    'note': '※ 사주 구조(지장간·현재 운 포함)로 본 성향이라 시기에 따라 조금씩 달라져요. 심리검사 MBTI와 다를 수 있어요.',
    'sub': '내 사주 구조로 풀어본 성향 유형',
    'title': '사주로 보는 내 MBTI',
  },
  mod: {
    'empty': '신고된 콘텐츠가 없어요.',
    'hide': '숨기기',
    'restore': '복원',
    'sub': '신고된 콘텐츠를 검토하고 숨기거나 복원하세요. (신고 5회 이상은 자동 숨김)',
    'title': '신고 관리',
  },
  net: {
    'errMsg': '잠시 후 다시 시도해 주세요. 계속되면 잠시 뒤에 다시 열어 주세요.',
    'errTitle': '연결에 문제가 있어요',
  },
  relPattern: {
    'attraction': '매력·인연의 밀도',
    'compatCta': '특정 상대와의 궁합이 궁금하다면 →',
    'drawnTo': '반복해 끌리는 사람의 결',
    'dynamic': '나의 관계 역학',
    'footNote': '※ 배우자궁(일지)·인연星·도화 등 원국 구조를 사주 엔진으로 계산한 온디바이스 분석이에요. 예언이 아니라 나를 이해하는 참고예요.',
    'kicker': '사주 엔진으로 보는 관계 심리',
    'myStyle': '관계에서 나의 방식',
    'sub': '왜 비슷한 관계가 반복될까요? 궁합 운세가 아니라, 타고난 사주 구조에서 반복되는 관계의 결을 읽어요.',
    'title': '나의 관계 패턴',
    'titleSuffix': '님의 관계 패턴',
  },
  reunion: {
    'addDesc': '옛 인연의 명식과 지금의 고민을 더하면, 두 사람의 사주를 함께 보고 고민에 맞춰 풀어드려요. 비워 두면 나의 흐름만으로 봐요.',
    'addTitle': '함께 풀어드려요 (선택)',
    'afterReunion': '다시 만난다면',
    'caution': '되돌아보면 좋은 점',
    'changeBuy': '구매하고 바꾸기',
    'changeConfirmBuy': '상대를 바꾸려면 새로 풀어야 하고, 운이 필요해요. 진행할까요?',
    'changeConfirmCredit': '가진 재회운 1회분으로 상대를 바꿔 새로 풀어요. 바꾸시겠어요?',
    'changeConfirmPremium': '상대를 바꾸면 그 사람으로 새로 풀어요. 바꾸시겠어요?',
    'changeGo': '바꾸기',
    'concernLabel': '지금의 고민',
    'concernPh': '지금 어떤 상황·고민인지 적어주시면 함께 풀어드려요',
    'generating': '다시 이어질 인연의 흐름을 읽는 중…',
    'otherAdd': '옛 인연 생년월일 입력',
    'otherAnon': '옛 인연',
    'otherChange': '상대 바꾸기(새로 풀기)',
    'otherLabel': '옛 인연의 명식',
    'otherLockedNote': '상대를 바꾸려면 새로 풀어야 해요.',
    'otherPrivacy2': '※ 상대 정보는 이 재회 풀이에만 쓰여요. 바꾸기 전까지 이 기기에만 잠겨 보관되고, 명식 목록엔 남지 않아요. 동의를 얻은 경우에만 입력해 주세요.',
    'possibility': '다시 이어질 인연인지',
    'registerOtherSubmit': '이 명식으로 함께 풀기',
    'registerOtherTitle': '옛 인연 명식 입력',
    'remedy': '재회를 여는 법',
    'sub': '옛 인연과 다시 이어질 가능성과, 연락이 닿기 좋은 시기를 짚어 드려요',
    'theirResponse': '그때 상대의 마음',
    'timing': '연락이 닿기 좋은 시기',
    'title': '재회운',
  },
  reunionAsk: {
    'cta': '깊은 재회 풀이 보기',
    'q': '재회, 다시 이어질까?',
    'sub': '옛 인연과 다시 이어질 가능성·시기·방향을 무료로 짚어 드려요',
  },
  selfAnalysis: {
    'elements': '오행 밸런스 — 나를 이루는 다섯 기운',
    'footNote': '※ 모두 사주 엔진(만세력)으로 계산한 온디바이스 분석이에요. 예언이 아니라 나를 이해하는 참고예요.',
    'kicker': '사주 엔진이 분석한 나',
    'more': '자세히 보기 ›',
    'strengths': '강점과 기질 자세히',
    'sub': '타고난 사주를 엔진으로 계산한 다섯 갈래 자기분석 — 운세가 아니라 나를 이해하는 지표예요.',
    'title': '나 분석',
    'titleSuffix': '님 분석',
  },
  signup: {
    'body': '구매한 이용권과 풀이는 지금 쓰는 임시 계정에 묶여 있어요. 앱을 지우거나 기기를 바꾸면 되찾기 어려워요. 계정을 연결해 두면 그대로 이어서 볼 수 있어요.',
    'cta': '계정 연결하기',
    'note': '연결하지 않아도 지금처럼 계속 이용할 수 있어요.',
    'title': '지금 본 풀이, 이 기기에만 남아 있어요',
  },
  signupPrompt: {
    'cta': '계정 연결',
    'later': '나중에',
    'msg': '지금은 임시 계정이라 앱을 지우거나 기기를 바꾸면 구매한 이용권과 풀이를 되찾기 어려워요. 연결하지 않아도 계속 보실 수 있어요.',
    'title': '계정을 연결하면 이 풀이가 안전하게 보관돼요',
  },
  spouseDual: {
    'ageHint': '나이대 힌트',
    'ageNote': '※ 경향일 뿐이에요. 실제 상대 사주가 있으면 궁합이 우선해요.',
    'funnel': '더 구체적인 이상형·실제 인연·시기 통변은 아래 애정 리딩에서 확인해요.',
    'gap': '대비',
    'idealTag': '끌리는 이상형',
    'ignite': '끌림(발동)',
    'match': '일치',
    'noFlow': '다음 8년간은 배우자 자리가 크게 열리고 닫히는 신호가 약해요. 큰 변동보다 다지는 시기예요.',
    'realDesc': '결혼생활의 실질 — 늘 최우선인 자리(일지)',
    'realTag': '진짜 곁에 남는 사람',
    'settle': '안정(안착)',
    'sub': '타고난 배우자 자리를 두 축으로 봐요 — 끌리는 이상형과, 실제로 곁에 남는 사람.',
    'timeline': '끌림 vs 안정 — 인연 흐름',
    'title': '이상형과 진짜 인연',
  },
  traits: {
    'detail': '내 사주 깊이 보기',
  },
  wealth: {
    'flow': '재물 인생 흐름',
    'generating': '타고난 재물 그릇과 흐름을 읽는 중…',
    'howEarn': '돈이 들어오는 결',
    'partner': '혼자 vs 함께',
    'remedy': '재물 지킴·개운',
    'sub': '타고난 재물 그릇과 유형, 언제 크게 들어오고 어떻게 지키는지까지 짚어 드려요',
    'timing': '재물 시기',
    'title': '재물 딥리포트',
    'type': '재물 유형',
    'vessel': '재물 그릇',
  },
  yieojim: {
    'express': '마음은 이는데 정착까진 약한 해',
    'mine': '내가 먼저 다가가 이어지기 좋은 해',
    'mineNone': '다음 10년엔 약해요 — 내가 먼저 표현해 다가가는 힘(식상)이 원국에 옅어, 특정 시기(그 기운이 들어올 때)에 집중돼요.',
    'note': '※ 참고 경향이에요. 실제 인연은 만나는 사람에 따라 달라져요. 어느 쪽이든 최종적으로 이어지려면 ‘인연 자리’가 열리는 해가 열쇠예요.',
    'popular': '관심·인기는 오지만 정착까진 약한 해',
    'sub': '짝사랑이든 대시든, 실제로 이어지려면 ‘인연 자리(배우자궁)’가 그때 열려 있어야 해요.',
    'theirs': '좋은 인연이 다가와 이어지기 좋은 해',
    'theirsNone': '다음 10년엔 인연이 다가와 정착까지 이어지는 뚜렷한 시기가 약해요.',
    'title': '인연이 이어지는 시기',
  },
};
