// app/src/copy/ja.ts — 日本語 UI 文言。キーは ko.ts と一致させること。
export const ja = {
  appName: 'ニウンネウン',
  tagline: '自分と他人を理解するAIの羅針盤',
  // 홈 카드 개인화 티저 — ko 와 동일 키(계산=homeTeaser.ts). ※ newyear.keyword 값 자체는 엔진이 한국어로 산출.
  teaser: {
    career: '事業家型 {{biz}}% · 組織型 {{org}}%',
    newyear: '今年のキーワード · {{keyword}}',
    flow: '現在 {{n}}番目の区間 · 転換点 {{turns}}回',
    crush: '{{year}}年 {{months}}月 · 惹かれる流れ',
    reunion: '{{year}}年 {{months}}月 · 連絡が届きやすい',
    job: '{{years}}年 · 門が開く年',
    raw: '{{text}}', // image·talent·mission — 文言はエンジン(lib/content/elementPhrases)が韓国語で算出しそのまま挿入(既存 newyear.keyword と同方式・3言語同値)
  },
  onb: {
    skip: 'スキップ', next: '次へ', start: '私の分析を始める',
    t1: 'AIが分析する「私」',
    b1: 'ニウンネウンは占いアプリではありません。四柱推命をエンジンに、あなたがどんな人かを分析する自己理解ツールです。',
    t2: 'あなただけの命式を計算します',
    b2: '生年月日時を精密な万歳暦（真太陽時・時代補正）で計算し、誰とも同じでないあなただけの分析を作ります。',
    t3: 'こんなことがわかります',
    l1: '私はどんな人か — 性格・強み', l2: 'なぜ関係が繰り返すのか', l3: 'どんな仕事が合うか', l4: '今年何を準備するか',
    t4: 'こんなふうに分析します', pvBadge: '例', pvType: 'テト型', pvScale: 'テト 63%', pvLine: '決断力があり主導的。ただ、時には休む余裕が大きな力になります。', pvNote: '生年月日時を入れるだけであなただけの分析が出ます',
  },
  // ★App Store 4.3(スパム/重複)対応 — 「計算されている(computed)」を可視化(ComputedNote が参照)。
  computed: {
    title: 'あなたの生年月日から計算した個人の命式',
    body: '真太陽時・経度・歴史的なサマータイムまで補正して万歳暦を計算し、40あまりの古典ルールをこの命式に適用します。誰とも同じでない結果です。',
    badge: '私の生年月日から計算',
    more: '蔵干・冲・合・刑、神殺、大運(運の流れ)まで計算し、四柱推命と紫微斗数の二つの伝統を照らし合わせて検証します。',
  },
  menu: {
    'egenteto': '에겐·테토 성향',
    lookback: '振り返り', lookbackDesc: 'その日の運勢と自分の記録を並べて',
    myeongsik: '命式登録', myeongsikDesc: '命式の登録·管理',
    manse: '万歳暦', manseDesc: '日付別四柱·チャート管理', timeResolve: '生まれた時刻さがし', timeResolveDesc: '時刻不明でも出来事から推論',
    ziwei: '紫微斗数', ziweiDesc: '命盤·12宮の星',
    taro: 'タロット', taroDesc: '今日のカード',
    today: '今日の運勢', todayDesc: '毎日変わる日運', month: '今月の運勢', monthDesc: '今月の分野別の流れ',
    compat: '相性', compatDesc: '関係力学の深い分析',
    premium: 'プレミアム鑑定', premiumDesc: '深い通変·全領域', premiumTag: 'プレミアム',
    timeline: '人生タイムライン', timelineDesc: '10〜100歳の時期別の流れ',
    pet: 'うちの子', petDesc: 'うちの子の生まれもった特徴', love: '私の恋愛の流れ', loveDesc: '理想のタイプ·出会う人を詳しく',
    lifegraph: '人生グラフ', lifegraphDesc: '大運別の人生の流れ曲線·転換点',
    newyear: '新年運勢', newyearDesc: '今年の総合·月別·三災',
    roots: '命式の根', rootsDesc: '表に出た自分·秘めた力·本当の強さ',
    image: '映る自分', imageDesc: '他人に見える第一印象·雰囲気',
    impression: '人が見る私', impressionDesc: '第一印象から深い仲まで映る私',
    mission: '私の使命', missionDesc: '何のために生まれたか',
    persona: '性格タイプ', personaDesc: '四柱で見る私の16タイプ', egen: 'エゲン vs テト', mbti: '四柱MBTI', traits: '私の特徴', selfAnalysis: '自己分析', selfAnalysisDesc: '性格·気質·五行バランスをまとめて分析', relationPattern: '関係パターン', relationPatternDesc: 'なぜ関係が繰り返すか — 生まれ持った関係の質', personal: 'パーソナル五行', personalDesc: '五行に合うカラー·コーデ·メイク·車の色', gem: '私の四柱宝石', gemDesc: '誕生石は実はあなたに合わない — あなたを活かす本当の宝石', sokgunghap: '相性(夜)', sokgunghapDesc: '二人の性的相性 (成人·遊び)', community: 'コミュニティ', communityDesc: '四柱·恋愛·悩みを分かち合う場所', joseonjob: '朝鮮時代の職業', lovestyle: '恋愛スタイル', bok: '生まれ持つ福', pastlife: '前世物語', healing: '私の癒し方',
    taegil: '択日', country: '私が暮らしやすい場所', countryDesc: '気運に合う国·気候', taegilDesc: '結婚・引越し・契約の吉日',
    luck: '今日の幸運', luckDesc: '幸運の色·方角·数字',
    zodiac: '干支·星座', zodiacDesc: '今日の干支·星座運勢',
    name: '名前占い', nameDesc: '名前の五行の流れ',
    dream: '夢占い', dreamDesc: 'キーワードで探す',
    dayPillar: '日柱論', dayPillarDesc: '生まれた日でみる気質', career: '起業家の私 vs 会社員の私', careerDesc: '独立と組織、二つの道', gaeun: 'あなたの開運法', gaeunDesc: '今の運に合わせて運を活かす', followupDesc: '占いにもう一つ質問', talent: '私の生まれ持った才能', celeb: '世界の人物マッチング', celebDesc: '有名人の四柱と比べる楽しみ', talentDesc: '才能·向く道·お金の扱い方', numerology: '数秘術', numerologyDesc: '数で見る人生の方向·才能', astrology: '星座·占星術', astrologyDesc: '星座 + ネイタルチャート、二つの視点',
    child: '子どもの縁', childDesc: '子との縁·気質·親としての私', future10: '10年後の私', future10Desc: '大運·歳運で描く10年後', reunion: '復縁', reunionDesc: '元の縁が再び開く時期·可能性', crush: '片思い·ご縁運', crushDesc: '想いが届くか·惹かれる人の質·近づく時期', job: '就職·転職運', jobDesc: '就職·転職·合格·試験が動きやすい時期', jobfit: '私に合う職業', jobfitDesc: '生まれ持った適性で合う職業·惹かれと能力の差', wealth: '財運ディープレポート', wealthDesc: '生まれ持った財の器·タイプ·大きく入る時期と守り方', reunionAsk: '復縁できる？', reunionAskDesc: '無料で見る復縁の可能性·連絡に良い月', crushAsk: 'あの人と結ばれる？', crushAskDesc: '無料で見る魅力·ご縁が高まる月', jobAsk: '就職はいつ？', jobAskDesc: '無料で見る就職·合格運が開く時期',
    saju: '四柱推命', sajuDesc: '鑑定·タイムライン·相性', ziweiHub: '紫微斗数', ziweiHubDesc: '命盤·運限·相性',
    secLove: '恋愛', secLoveDesc: '相性・縁・心が通じる時期',
    secToday: '運勢', secTodayDesc: '今日・今月・今年の流れ',
    secSelf: '自己分析', secSelfDesc: '性格・気質・人からの見え方',
    secWork: '仕事・財', secWorkDesc: '適性・就職・財の器',
    secHidden: 'もっと見る', secHiddenDesc: 'おすすめから出会うコンテンツ',
    chipLove: '恋愛', chipToday: '運勢', chipSelf: '自分', chipWork: '仕事', chipHidden: 'もっと',
    secLife: 'ライフ', secLifeDesc: 'タロット・紫微・気軽な読み物',
    secTool: 'ツール', secToolDesc: '万年暦で自分で調べる',
    chipLife: 'ライフ', chipTool: 'ツール',
    chipAll: 'すべて',
    secContent: '人気', // ★ショートカット行(テーマ軸の外)
    // (旧)価格軸のラベル — テーマ軸再編で未使用。戻せるように残す。
    secFree: '今日・命式', secPremium: '自分を理解する', secSpecial: 'スペシャル', secDeep: '自分を知る', secLight: '気軽に',
    viewCard: 'カード', viewList: 'リスト', // ホーム表示切替
    todayTileDesc: '今日一日の流れ', monthTileDesc: '今月の流れ', newyearTileDesc: '今年のキーワード・12か月', personaTileDesc: '性格タイプ', taegilTileDesc: '良い日選び', luckTileDesc: '今日の幸運', zodiacTileDesc: '干支・星座', nameTileDesc: '名前の響き', dreamTileDesc: '夢占い', egenTileDesc: '私はエゲン？テト？', mbtiTileDesc: '四柱で見るMBTI', joseonjobTileDesc: '四柱で見る朝鮮の職業', lovestyleTileDesc: '私の恋愛細胞は？', bokTileDesc: '私の福は？', pastlifeTileDesc: '私の前世は？', healingTileDesc: '私に合う休み方は？',
    secPremiumDesc: 'あなたはどんな人か — 四柱·紫微で深く', secContentDesc: 'AIが丁寧に解く深い鑑定', secHotDesc: '最近よく見られているものだけ', secDeepDesc: '自分をより深く見つめる', secLightDesc: '気軽に楽しむ運勢',
  },
  common: { save: '保存',
    'more': '詳しく',
    retryLaterNoCharge: 'しばらくしてからもう一度お試しください。woon は消費されていません。',
    'add': '추가',
    'confirm': '확인',
    'delete': '삭제',
    'edit': '수정',
    'retry': '다시 시도',
    'retryLater': '잠시 후 다시 시도해 주세요.',
    'tapToClose': '탭하여 닫기',
    back: '← 戻る', login: 'ログイン', signup: '新規登録', logout: 'ログアウト', loggingOut: 'ログアウト中…',
    comingSoon: '準備中です。', error: 'エラー', loginOptional: 'ログイン / 新規登録（有料·保存機能用 — 任意）',
    cancel: 'キャンセル', none: 'なし',
    llmBusy: '今は鑑定の生成が一時的に難しいようです。しばらくしてからもう一度お試しください。',
    llmMaking: '同じ鑑定をただいま作成中です。少し経ってからご確認ください。',
    genFailed: '鑑定を読み込めませんでした。しばらくしてからもう一度お試しください。',
  },
  auth: {
    'login': '로그인',
    signin: 'ログイン', signupTitle: '新規登録', email: 'メール', password: 'パスワード（6文字以上）',
    toSignup: 'アカウントがありませんか？  新規登録', toSignin: 'すでにアカウントをお持ちですか？  ログイン',
    needInput: 'メールとパスワードを入力してください。', signupDone: '確認メールを送信しました。認証後にログインしてください。',
    or: 'または', google: 'Googleで続ける', apple: 'Appleで続ける', naver: 'Naverで続ける', processing: 'ログイン処理中…',
  },
  register: {
    'catDeleteTitle': '카테고리 삭제',
    'catHint': '카테고리를 길게 누르면 삭제돼요 (그 명식들은 기타로 이동)',
    'editDone': '완료',
    'exactTime': '정확한 시각을 알아요 (출생지 경도로 진태양시 보정)',
    'hour12': '시(1~12)',
    'invalidDateTitle': '생년월일을 확인해 주세요',
    'minute': '분',
    'newCategory': '새 카테고리',
    'newCategoryPh': '새 카테고리 이름',
    'orSijin': '또는 시진(2시간)만 알 때',
    'placeSearchBlocked': '지역 검색이 잠시 제한됐어요. 30초쯤 뒤에 다시 시도해 주세요.',
    'placeSearchFailed': '지역 검색을 불러오지 못했어요. 연결을 확인해 주세요.',
    name: '名前·愛称', namePh: '例：キムOO / 本人',
    birthDate: '生年月日 (YYYY-MM-DD)', birthDatePh: '1990-03-15',
    birthTime: '出生時刻 (HH:mm、不明なら空欄)', birthTimePh: '07:10',
    calendar: '新暦 / 旧暦', solar: '新暦', lunar: '旧暦', normalMonth: '平月', leapMonth: '閏月',
    sex: '性別', male: '男', female: '女',
    birthPlace: '出生地', birthPlacePh: 'タップして都市検索',
    relation: '関係', submit: '命式計算 · 登録',
    birthTimeSijin: '出生時刻（時辰）', timeUnknown: '不明', selfLabel: '本人', makeRep: 'メイン命式に設定',
    relationCustom: '直接入力', relationCustomPh: '関係を入力（例：上司）',
    ctxTitle: 'あなたの状況（任意）', ctxDesc: '入力するとこの命式の鑑定がより正確になります。空欄でも構いません。',
    ctxSit: '今の状況は？', ctxSitDesc: '選ぶとその状況の言葉で鑑定されます',
    sitStudy: '受験・学生', sitWork: '会社員', sitBiz: '事業・自営', sitFree: 'フリーランス',
    sitHome: '主婦・育児', sitSeek: '求職中', sitRetire: '退職', sitEtc: 'その他',
    ctxJob: '職業', ctxJobPh: '例：デザイナー／自営業／学生／会社員',
    ctxRel: '交際状況', ctxRelSingle: '未婚', ctxRelDating: '交際中', ctxRelMarried: '既婚', ctxRelOther: 'その他',
    ctxConcern: '最近の関心·悩み', ctxConcernPh: '例：転職、新しい縁、健康管理',
    ctxNote: 'メモ', ctxNotePh: '鑑定に反映してほしいことを自由に',
    selfExistsTitle: '本人の命式が既にあります', selfExistsMsg: '本人の命式は1つだけです。今の本人の命式を「その他」に移し、この命式を本人として登録しますか？', selfReplace: '本人にする',
    birthPlaceSearch: '都市·地域を検索', birthPlaceSearchPh: '例：ソウル、東京', useAsIs: "'{{q}}' をそのまま使用",
    limitTitle: '無料登録の上限', limitMsg: '無料プランは命式を{{limit}}件まで登録できます。\n広告を見れば1件追加、プロにアップグレードすれば無制限です。',
    upgrade: 'プロにアップグレード', usage: '命式 {{count}}/{{limit}}',
    watchAdAdd: '広告を見て1件追加', adNotFinished: '広告を最後まで見ると1件追加されます。',
  },
  myeongsik: {
    palja: '八字', dayMaster: '日干', strength: '身強弱指標', pattern: '格局', patternRevealed: '顕現', patternHidden: '潜伏',
    stages: '十二運星', interactions: '合冲刑害', sinsal: '神殺·空亡', gongmang: '空亡',
    noHit: '原局hitなし', ziwei: '紫微斗数', lifePalace: '命宮',
    readingBtn: '領域別鑑定を見る →', noChart: 'チャート情報がありません。',
    root: '通根', hidden: '蔵干',
    luck: '大運·歳運', daewoon: '大運', sewoon: '歳運', elements: '五行分布',
    합: '合', 충: '冲', 형: '刑', 해: '害', 파: '破', 극: '剋',
    sinsalHint: '基準の地支が原局にあれば✓(柱)、なければ大運·歳運で作動', ssLuck: '運で', dayPillar: '日柱',
    sinsalDetail: '神殺·空亡をくわしく →',
  },
  reading: {
    'lockedNote': '위 버튼으로 열어 전부 보실 수 있어요.',
    'lockedTitle': '이 명식의 풀이는 운으로 열려요',
    'pastYearBadge': '이 풀이는 {{y}}년 운(세운) 기준으로 쓰였어요 — 올해 흐름은 재통변하면 새로 반영돼요.',
    'recommend': '이런 콘텐츠도 좋아하실 거예요',
    'renew': '🔄 최신 통변으로 재통변',
    'sajuTitle': '사주 풀이',
    title: '全領域鑑定 · プレミアム', sub: '16領域すべてを一度に深く精密な通変。（命式は無料）',
    runAll: '全体を見る（{{count}}件）', progress: '‘{{current}}’ 鑑定中… ({{done}}/{{total}})', generating: '鑑定をていねいに描いています…', saveFail: 'チャートの保存に失敗しました。', refreshStale: '最新の解釈に更新', refreshDeniedTitle: '更新の上限', refreshDenied: 'この鑑定は最大{{cap}}回まで更新できます。',
    ziweiTitle: '紫微斗数 十二宮 · プレミアム', ziweiSub: '十二宮を一度に統合通変。（命盤は無料）',
    timelineTitle: '人生タイムライン · プレミアム', timelineSub: '10〜100歳を10年ごとに、各時期の流れを読み解きます。',
    bannerPremium: '購読中 — 無制限通変', bannerTrial: '🎁 初回鑑定が無料！',
    bannerGated: '領域選択で広告または購読により通変が開きます',
    base: '本質', past: 'これまで', overlay: '現在', future: 'これから', remedy: '処方',
    premiumAlert: 'プレミアム通変', premiumAlertMsg: '{{price}}決済で深い通変を見られます。',
    payPerUse: '{{price}} 決済', bannerPerUse: '✨ 最初の分野のみプレビューです — 全体は{{price}}', bannerUnlocked: '✨ 購入済み — 全体の鑑定を生成できます',
    askTitle: 'もっと質問する', askPh: 'この鑑定についてもっと聞いてみましょう',
    askSend: '質問', askFree: '無料質問あと{{n}}回', askPaid: '無料質問を使い切りました — 追加は1回{{price}}',
    askPremiumTitle: 'プレミアム限定', askPremiumMsg: 'プレミアムなら領域ごとに2回まで無料で追加質問できます。',
    askPremiumCta: 'プレミアムでもっと聞く', askPayTitle: '追加質問', askPayMsg: '無料質問を使い切りました。1回{{price}}で追加しますか？',
    askPayBtn: '{{price}} 決済', payPending: '準備中',
  },
  compat: {
    'genConfirm': '생성',
    'genCta': '이 관계 풀이 만들기',
    'genTitle': '풀이 만들기',
    'otherPick': '상대 선택 · 새 상대 등록',
    'scoreHarmony': '조화',
    'scoreTension': '긴장',
    'step1': '① 누구와 볼까요?',
    'step2': '② 어떤 사이인가요?',
    'step3year': '③ 언제로 볼까요?',
    'wizPickShort': '탭해서 선택',
    'yearPick': '년도 선택',
    otherInfo: '相手情報（同意が必要）', otherDatePh: '相手の生年月日 1992-07-03',
    otherTimePh: '出生時刻（不明なら空欄）',
    dayRelation: '日干関係', harmonyTension: '調和 {{h}} · 緊張 {{t}}',
    usefulGod: '用神相補', crossInter: '交差合冲',
    needChart: '相性を見るにはまず命式を登録してください。', registerMyChart: '命式を登録',
    mySlot: '私の命式', otherSlot: '相手の命式', change: '変更', orDirect: 'または相手を直接入力',
    registerOther: '相手の命式を登録', registerOtherTitle: '相手の命式を登録', registerOtherSubmit: 'この命式で相性を見る',
    yearAll: '全体',
    analyze: '相性を見る', generating: 'お二人の相性を読み解き中…', noReading: '生成できませんでした。もう一度お試しください。',
    secBase: '二人の基本的な噛み合い', secDynamic: '合うところ · ぶつかるところ', secAdvice: 'こう育てましょう',
    detailToggle: '文字の作用をくわしく',
    premiumTitle: 'プレミアム限定', premiumMsg: '相性鑑定はプレミアムで5名まで無料です。',
    payTitle: '相性を追加', payMsg: '無料5名を使い切りました。この方との相性を1回₩2,500で見ますか？', payBtn: '₩2,500 決済',
    rel: { friend: '知人·友達', family: '家族', crush: '片思い·脈あり', love: '恋愛', marriage: '結婚', coworker: '職場の同僚', senior: '目上·メンター', business: '共同事業', staff: '部下·社員', invest: '投資パートナー' },
  },
  category: {
    성격내면: '性格·内面', 취업운: '就職運', 직장운: '職場運', 사업운: '事業運',
    금전소득운: '金銭·収入', 투자편재운: '投資運', 재물손재: '財物·損失', 연애운: '恋愛運',
    결혼배우자운: '結婚·配偶者', 대인사회성: '対人関係', 부모운: '両親運', 형제운: '兄弟運',
    자식운: '子女運', 건강: '健康', 학업자기계발: '学業·自己啓発', 이동환경: '移動·環境',
  },
  today: {
    'areaSoon': '이 분야 풀이는 다음 운세부터 채워져요.',
    today: '今日', tomorrow: '明日', energyTomorrow: '明日の気運', weekdaysShort: '日,月,火,水,木,金,土',
    dayPillar: '今日の気運', note: '毎日0時に変わる今日の流れを、あなたの命式と合わせて読み解きます — より深い鑑定はプレミアムで。',
    areas: '分野別の運勢', area_general: '総合', area_work: '仕事', area_money: '財運', area_invest: '投資', area_love: '恋愛', area_health: '健康',
    needChart: '命式を登録すると、今日の流れをあなたに合わせて分野別に読み解きます。', registerBtn: '命式を登録',
    more: '分野別にくわしく見る →',
    genFail: '占い結果の作成に失敗しました。しばらくしてからもう一度お試しください。', title: '今日の運勢', heroSub: '今日一日の流れを見てみましょう', generating: '今日の流れを読み解いています…', gateTitle: '今日の運勢を見る', gateDesc: 'あなたの生まれ持った性質に、今の大きな流れ・今年・今日の雰囲気を重ねて、今日起こりそうなことと対処法をお伝えします。', seePremium: '今日の運勢を見る', seeAd: '広告を見て無料で見る', adFail: '広告を読み込めませんでした。しばらくして再度お試しいただくか、プレミアムで広告なしでご覧いただけます。',
  },
  settings: { community: 'コミュニティ', nickPh: 'ニックネーム (2~12字、空欄=自動匿名)', nickBad: '使用できない単語があります。', nickLen: 'ニックネームは2~12字です。', nickDone: '保存済み', showIlju: '日柱バッジを表示', iljuHint: '投稿の横に生まれた日の二文字だけ表示されます。生年月日は分かりません。',
    'accent': '테마 강조색',
    'accentAuto': '자동(일간)',
    'accentDesc': '대표명식 일간의 오행 색으로 앱을 물들여요. 직접 고를 수도 있어요.',
    'accentGold': '골드',
    'coins': '운',
    'loadingOff': '끄기',
    'loadingScreen': '로딩 화면',
    'loadingVideoOff': '八字 한자',
    'loadingVideoOn': '호랑이 영상',
    'loginBenefit': '로그인하면 구매한 콘텐츠가 다른 기기·재설치에서도 이어져요 (선택)',
    'notif': '알림',
    'notifDaily': '매일 오늘의 운세 알림',
    'notifDenied': '꺼짐 · 눌러서 기기 설정에서 켜기',
    'notifDeniedMsg': '通知を受け取るには、端末の設定でニウンネウンの通知をオンにしてください。',
    'notifNA': '이 기기에서 사용 불가',
    'notifOff': '꺼짐 · 눌러서 켜기',
    'notifOn': '켜짐 · 매일 오전 9시',
    'notifOnMsg': '알림이 켜져 있어요. 끄려면 기기 설정에서 바꿀 수 있어요.',
    'notifUnavailable': '이 기기에서는 알림을 사용할 수 없어요.',
    'openSettings': '설정 열기',
    'readingVideo': '풀이 로딩 영상',
    'readingVideoOff': '심플(영상 없이)',
    'readingVideoOn': '테마 영상',
    'restore': '구매 복원',
    'restoreDone': '구매가 복원되었습니다.',
    'restoreFail': '구매 복원에 실패했어요. 잠시 후 다시 시도해 주세요.',
    'restoreNone': '복원할 구매 내역이 없습니다.',
    'restorePending': '구매가 확인됐어요. 서버 반영까지 잠시 걸릴 수 있어요 — 잠시 후 다시 확인해 주세요.',
    'restoring': '복원 중…',
    'themeRestart': '앱을 다시 켜면 적용돼요.',
    homeOrder: 'ホームの並び順', homeOrderNote: 'ホーム画面に表示される順番です。上下に移動できます。', homeOrderReset: '既定の順番に戻す',
    account: 'アカウント', loginCta: 'ログイン / 新規登録', premium: 'プレミアム',
    premiumActive: '✓ プレミアム適用中', premiumBuy: '買い切りプレミアム', premiumDesc: '今後追加分も含む全プレミアムコンテンツが無料 · 広告なし · 一度の購入で永久 · 有料コンテンツの再鑑定30%割引(一般10%)', 
    premiumOkTitle: 'プレミアム', premiumOk: 'プレミアムが適用されました。', premiumTitle: 'プレミアム',
    deleteAccount: 'アカウント削除',
    delTitle: 'アカウント削除', delMsg: 'アカウントと全データ（命式・鑑定・パス）が永久に削除されます。元に戻せません。', delConfirm: '続ける',
    delTitle2: '本当に削除しますか？', delMsg2: 'この操作は元に戻せません。', delFinal: '完全に削除',
    delFail: '削除に失敗しました。後ほど再試行してください。', delDoneTitle: '削除完了', delDone: 'アカウントとデータを削除しました。', deleting: 'アカウントを削除中…',
    fontSize: '文字サイズ', size_sm: '小', size_md: '中', size_lg: '大', size_xl: '特大',
    appInfo: 'アプリ情報', version: 'バージョン', terms: '利用規約', privacy: 'プライバシーポリシー', license: 'オープンソースライセンス', bugReport: 'バグ報告 · お問い合わせ', bugReportFail: 'メールアプリを開けませんでした。下記アドレスにお送りください。',
    preview: 'プレビュー — 通変はこのサイズで表示されます。鑑定·今日の運勢·相性の本文に反映されます。',
    language: '言語', 
    coupon: 'クーポン入力', couponPh: 'クーポンコード入力', couponRedeem: '登録', couponHave: '保有利用券',
    couponOkTitle: '登録完了', couponOk: '無料利用券が適用されました。その機能を無料でご利用いただけます。',
    couponFailTitle: '登録失敗',
    couponErr_invalid: '無効なコードです。', couponErr_expired: '期限切れのクーポンです。',
    couponErr_exhausted: '利用上限に達したクーポンです。', couponErr_already: '使用済みのクーポンです。', couponErr_auth: 'ログインが必要です。',
  },
  timeline: {
    'readThis': '이 시기 풀이 보기',
    decades: '10年ごと', years: '年ごと', pickDecade: '時期を選ぶ', pickYear: '年を選ぶ', thisYear: '今年', now: '現在',
    catGeneral: '総合', catWork: '仕事', catMoney: '金運', catLove: '恋愛', catHealth: '健康',
    catSocial: '人間関係', catGrowth: '学び', catMove: '移動', months: '月別の流れ', monthUnit: '月',
    generating: 'この時期を読み解き中…', tapToRead: '時期や年を選ぶと、その流れを読み解きます。',
    premiumTitle: 'プレミアム限定', premiumMsg: '人生タイムラインはプレミアムで時期ごとに読み解きます。',
    lockedTitle: 'ロック中の時期', lockedSub: '現在の大運と今年は無料、ほかの時期はパスでカテゴリ別に詳しく読み解きます。',
    unlock: 'この時期を開く', unlockTitle: 'この時期を開く',
    unlockMsg: 'タイムラインパスでこの時期をカテゴリ別に詳しく読み解きます。(パスは設定のクーポンで取得・都度課金は準備中)',
    buy5: '歳運5回 {{price}}', buy10: 'この大運まるごと(10年) {{price}}', // 歳運(세운) バンドル — ロックカードの購入ボタン(daniel 07-23)
    freeBadge: '無料', usedCredit: 'パスで開きました',
  },
  premiumHub: {
    sub: '何を見ますか?',
    sajuReading: '原局の鑑定', sajuReadingDesc: '性格·金運·恋愛·仕事など16領域の深い通変',
    ziweiReading: '命盤の鑑定', ziweiReadingDesc: '十二宮 + 運限(大限)·四化で見る時期ごとの流れ',
  },
  pet: {
    title: 'うちの子', sub: 'うちの子の生まれもった結を軽く見てみましょう。',
    add: '新しい子', name: '名前', namePh: '例: コン', typeLabel: 'どんな子ですか?',
    birth: '生年月日 (YYYY-MM-DD)', time: '生まれた時刻', timeOptional: '— 不明でもOK',
    timePick: '時辰を選ぶ（子の刻·丑の刻…）', timeUnknownChk: '時刻不明',
    timeHint: '時刻が不明なら大きな結だけ見ます(時間帯の鑑定は省きます)。',
    save: '特徴を見る', empty: 'まだ登録された子がいません。',
    delete: '命式を削除', deleteTitle: '削除', deleteMsg: 'この命式を削除しますか?',
    invalidTitle: 'ご確認ください', invalidDate: '生年月日を YYYY-MM-DD で入力してください。',
    type: { dog: '犬', cat: '猫', rabbit: 'うさぎ', hamster: 'ハムスター', bird: '鳥', fish: '魚', reptile: '爬虫類', other: 'その他' },
  },
  love: {
    'genDelayed': '풀이 생성이 지연되고 있어요. 잠시 후 다시 시도해 주세요.',
    'needZiwei': '이 명식으로는 애정 흐름을 풀 수 없어요. 태어난 시가 정확해야 자미 교차 분석이 가능합니다.',
    title: '私の恋愛の流れ', sub: '四柱推命と紫微斗数を両方クロスして、理想のタイプから実際に出会う人まで詳しく読み解きます。',
    generating: '二つの命盤をクロスして恋愛の結を読み解き中…',
    gateDesc: '理想のタイプ、実際に出会う人の第一印象·性格·行動·習慣、出会い方と時期まで — 四柱推命と紫微斗数のクロスで詳細に。',
    see: '{{price}}で詳しく見る', cacheNote: '一度見ればずっと保存されます（再課金なし）。',
    gateTitle: '私の恋愛の流れ', gateMsg: 'まだパスがありません。設定でクーポンを登録するか、決済機能は近日公開です。({{price}})',
    idealType: '私の理想のタイプ', appearance: '出会う人の第一印象·イメージ', personality: 'その人の性格·内面',
    behavior: 'その人の行動·話し方·習慣', ageGap: 'その人との年の差', howWeMeet: 'どこで·どう出会うか', elementMatch: '相性の良い気の順位', dynamic: '二人の惹かれ合いと相性', iLoveMore: '私がより好きな恋愛', theyLoveMore: '相手がより好きな恋愛',
    timing: '恋が深まる時期', cautionPartner: '特に気をつけたい相手', caution: '気をつけること', advice: '良い縁を育てる方法', needPay: 'woon が必要です。もう一度お試しください。',
  },
  month: {
    'aiDesc': '타고난 사주에 지금의 큰 흐름·올해·이번 달 기운을 더해, 이달 생길 수 있는 일과 대처까지 AI가 더 깊게 풀어 드려요.',
    'aiLogin': '로그인하면 AI가 이번 달 흐름을 더 깊게 풀어 드려요.',
    'aiTitle': 'AI 정밀 풀이',
    'thisMonth': '이번 달', title: '今月の運勢', monthPillar: '今月の気', flowTitle: '今月の流れ（上旬·中旬·下旬）', note: '今月の大きな流れです。具体的な日は今日の運勢で。', heroSub: '今月のめぐりで読む流れ', generating: '今月の流れを読み解いています…', gateTitle: '今月の運勢を見る', gateDesc: '生まれ持った気質に、いまの大きな流れ・今年・今月のめぐりを重ねて、今月起こりそうなことと対処の仕方をお伝えします。', seePremium: '今月の運勢を見る' },
  nav: { home: 'ホーム', contents: '占い', community: 'コミュニティ', coach: 'ガイド', market: 'マーケット' },
  lookback: { title: '振り返り', sub2: '今日の一つを実行した日々です。', needLogin: 'ログインすると記録が保存され、ここで見返せます。', empty2: 'まだ記録がありません。今日の運勢の下の「今日の一つ」を実行してチェックしてみてください。', goToday: '今日の運勢を見る', summary: '評価した{{rated}}日のうち{{hit}}日を「当たった」とされました', streak: 'これまで{{n}}日、今日の一つを実行しました', myNote: '私の記録', missionDone: '✓ その日の一つを実行しました' },
  contents: {
    sub: '見たいテーマを選んでください',
    searchPlaceholder: '何が気になりますか？',
    searchResult: '検索結果 {{n}}件',
    searchEmpty: '見つかりませんでした。\n別の言葉でお試しください。',
  },
  todayEnergy: { kicker: '今日の気運', point: '点', more: '今日の運勢を詳しく' },
  persona120: {
    kicker: '私の性格タイプ', count: '120種のうち', more: '詳しく見る',
    title: '私の性格タイプ', sub: '日干10 × 月支12 = 120タイプのうち私は',
    empty: '命式を登録すると120タイプの中からあなたのタイプをお見せします。',
    axisStem: '私という素材', axisSeason: '私が置かれた季節', axisGyeok: '人生の重心',
  },
  market: {
    'emptyTopic': '이 주제의 콘텐츠가 준비 중이에요. 다른 주제를 골라 보세요.',
    'hotSection': '🔥 인기',
    'open': '열기',
    'retentionNote': '구매한 풀이는 구매일로부터 1년간 보유되며, 1년이 지나면 자동 삭제됩니다. 이후 다시 보려면 재구매가 필요해요.',
    'sectionIncluded': '✦ 운으로 열기',
    'sectionIncludedSub': '아래 풀이는 운으로 하나씩 열 수 있어요. 명식마다 따로 열립니다.',
    'sectionIndividual': '◆ 개별 구매 전용',
    'sectionIndividualSub': '아래 항목은 하나씩 따로 구매해요.', intro: '適用する命式を選んでから、見たい鑑定をタップしてください。', applyTo: '適用する命式', openApply: '開く', noChart: '保存された命式がありません', have: '保有 {{n}}枚', owned: '保有', notOwned: '未保有', buy: '購入', note: '鑑定は命式ごとに保存されます。無料チケット（クーポン）は下で登録。', doneTitle: '購入完了', doneMsg: 'チケットが付与されました。', payPending: '決済準備中', buyFailTitle: '購入失敗' },
  dayPillar: {
    'fullChartNote': '※ 일주론은 ‘태어난 날(일주)’ 하나로 보는 큰 경향이에요. 정확한 풀이는 사주 전체(원국)를 함께 봐야 해요.',
    's_match': '잘 맞는 일주',
    's_stress': '스트레스 해소',
    title: '日柱論', sub: '生まれた日の干支（日柱）でみる、生まれもった気質です。',
    male: '男性', female: '女性', mine: '私の日柱', browseAll: '日柱60すべて', dayGroup: '日', tapHint: '日柱をタップすると詳しい解説が開きます。', mineList: '私の命式の日柱', noChart: '登録された命式がありません。先に命式を登録してください。',
    s_overview: '概要', s_personality: '性格', s_love: '恋愛·結婚', s_career: '仕事·財運', s_male: '男性', s_female: '女性', s_advice: 'アドバイス', s_live: '人生のコツ',
    disclaimer: '日柱論は生まれもった気質の一面にすぎません。正確な鑑定は日柱だけでなく、年·月·時の柱や合冲·用神まで、命式全体を合わせてみる必要があります。',
  },
  purchase: {
    loginTitle: 'ログインが必要です', loginMsg: '購入履歴をアカウントに保存すると、別の端末や再インストール後もそのまま使えます。ログインしますか？', loginCta: 'ログイン',
    restore: '購入を復元', restored: '購入を復元しました。', restoreNone: '復元する購入がありません。', restorePending: '購入を確認しました。反映まで少しかかることがあります — しばらくしてからもう一度ご確認ください。', preparing: '決済はまもなく公開されます。',
  },
  offline: { title: 'オフライン', msg: 'インターネットに接続されていません。保存済みは見られますが、新しい鑑定は接続後に可能です。', banner: 'オフライン — 保存済みのみ' },
  taro: { draw: 'カードを引く', reshuffle: '引き直す', reversed: '逆位置' },
  manse: {
    'deleteTitle': '명식 삭제',
    'viewManse': '만세력 보기', empty: '登録された命式がありません。', myChart: '命式', searchChart: '名前で探す' },
  sinsal: { 도화: '桃花', 역마: '駅馬', 화개: '華蓋', 천을귀인: '天乙貴人', 문창: '文昌', 양인: '羊刃', 홍염: '紅艶', 괴강: '魁罡', 백호: '白虎' },
  special: {
    'freeBasics2': '먼저 무료로 — 빅3 + 생명수',
    'goMarketBtn': '상점으로 이동 ›',
    'ownedBoughtV2': '구매 완료 · 언제든 다시 볼 수 있어요',
    'ownedResumeSub': '생성이 중단됐어요. 추가 결제 없이 이어서 만들어 드려요',
    'ownedResumeTitle': '결제는 끝났어요 — 풀이만 남았어요',
    'ownedTitle': '이미 열려 있는 풀이예요',
    'preparingPayment': '결제 준비 중…',
    'priceMissing': '지금은 이 콘텐츠를 열 수 없어요. 잠시 후 다시 시도해 주세요.',
    'resumeCta': '이어서 풀이 만들기',
    'viewCta': '풀이 보기',
    'working': '진행 중…', previewHead: 'こんなことが分かります', unlock: 'woonで開く', couponHint: 'woonで開けます', couponOnly: 'woonで開けます。マーケットでチャージできます。', needPay: 'woon が必要です。もう一度お試しください。', needPayMsg: 'woon が必要です。今すぐ woon で開くか、マーケットでチャージできます。', buyNow: '今すぐ購入', goMarket: 'マーケットで見る', unlockCta: '購入して見る', unlockHint: 'woonで開けます' },
  roots: { title: '命式の根', sub: '表に出た自分·秘めた力·本当に揺るがない強さを読み解きます', generating: '根をたどっています…', summary: 'ひと目で', surface: '表に出た自分', depth: '秘めた力', strength: '本当の強さ', gap: '表と内の違い', advice: '伸ばし方' },
  image: { title: '映る自分', sub: '他人に映る第一印象·雰囲気·関係の中の自分', generating: '映る印象を描いています…', summary: 'ひと目で', firstImpression: '第一印象', persona: '表に出るイメージ', inRelationship: '関係の中の自分', charm: '魅力ポイント', gap: '表と内', advice: '見せ方' },
  mission: { title: '私の使命', sub: '生まれ持った器と才能で見る、何のために生まれたか', generating: '使命を読んでいます…', summary: 'ひと目で', coreNature: '生まれ持った本質', calling: '私の使命', strengths: '才能·武器', howToRealize: '実現の道', successWay: '成功の仕方', careers: '向く仕事·職務', environment: '輝く環境', lifeTheme: '人生のテーマ', crossInsight: '共に示す方向', advice: '使命の生き方' },
  talent: { title: '私の生まれ持った才能', sub: '何を持って生まれたか、好きな事·すべき事のどちらで輝くか、お金をどう扱うか', generating: '才能を読んでいます…', summary: 'ひと目で', talent: '生まれ持った才能', drive: '好きな事 vs すべき事', money: 'お金の扱い方', howToUse: '才能の活かし方', careers: '輝く分野', advice: 'ひとこと' },
  numerology: {
    'birthday': '생일수 — 타고난 재능',
    'empty': '명식을 등록하면 생년월일로 수비학을 보여드려요.',
    'master': '✦ 마스터수(11·22·33) 보유 — 잠재력이 큰 대신 다루기 까다로운 수예요.',
    'note': '※ 피타고리안 수비학(서양 표준)으로 산출했어요. 이름 기반 수(표현·영혼수)는 추후 추가됩니다.',
    'personalYear': '개인해 — 올해 흐름', title: '数秘術', sub: '生年月日の数で見る人生の方向·才能·今年の流れ', generating: '数を読んでいます…', summary: 'ひと目で', lifePath: '生命数 — 人生の方向', innerYou: '内面と外見', talent: '才能', thisYear: '今年の流れ', advice: 'ひとこと' },
  astrology: {
    'numCore': '수로 본 나',
    'numGroup': '🔢 수비학 — 생년월일의 수로 보는 나',
    'numLove': '수비학으로 본 관계',
    'numYear': '올해의 수',
    'sub2': '별자리(태양)·점성술(네이탈)·수비학(생명수)을 한 번에 — 세 관점으로 깊이 풀이', title: '星座·占星術', sub: '星座(太陽星座)とネイタルチャートを一度に — 二つの視点で', generating: '星を読んでいます…', signGroup: '⭐ 星座 — 太陽星座で見る私', signSummary: '私の太陽星座', signTraits: '性格', signLove: '恋愛スタイル', signStrength: '強み', natalGroup: '🔭 占星術 — ネイタルで見る私', big3: '太陽·月·上昇', natalLove: '愛·欲求', natalWork: '仕事', strength: '強み', challenge: '課題', advice: 'ひとこと' },
  future10: { title: '10年後の私', sub: '大運·歳運で見る10年後の私と、今からの準備', gen: '10年後を描いています…', bigPicture: '10年後の全体像', career: 'キャリア·成果', wealth: '金運·資産の流れ', relation: '関係·家庭', health: '健康の管理軸', growth: '成長·内面の変化', prepare: '今から備えること' },
  child: { title: '子どもの縁', sub: '命式で見る子との縁·気質·親としての私', gen: '子との縁を見ています…', solo: '私だけ', couple: '配偶者と', pickSpouse: '配偶者を選択', coupleHint: '配偶者の命式を選ぶと、二人の命式で子との縁を一緒に見ます', needSpouse: '先に配偶者の命式を登録してください', bigPicture: '子との縁の全体像', childNature: '子どもの気質', asParent: '親としての私', coupleCross: '夫婦の子との縁', communication: 'コミュニケーション', timing: '時期の流れ', talent: '子どもの才能', health: '健康の管理軸', remedy: '開運·処方' },
  life: { genFail: '作成に失敗しました。少し時間をおいてからもう一度お試しください。', gateTitle: '人生グラフ', generating: '人生の流れを描いています…', yongsin: 'あなたに必要なエネルギー', focus: 'フォーカス', hint: '曲線上の点をタップすると、その時期を詳しく見られます。', peak: '最も輝く時期', caution: '足場を固めて気をつける時期', advice: '一生を通じての心がけ', gateDesc: '上の曲線の各時期がなぜそうなるのか、今どう動けばいいか、輝く時期の活かし方と厳しい時期の乗り越え方まで深くお伝えします。', pv1: '各時期がなぜ上下するのか', pv2: '今の時期に何をすればいいか', pv3: '最も輝く時期の活かし方', pv4: '気をつける時期の乗り越え方', pv5: '一生を通じて守る人生の方向', see: '人生グラフを見る', seePaid: '人生グラフを見る（₩3,900）' },
  newyear: {
    'remedy': '올해 개운법',
    'strategy': '올해의 대응전략',
    'thisYearSelf': '올해의 나',
    'timing': '올해 좋은 시기',
    'yearNature': '올해는 어떤 해', title: '新年の運勢', generating: '今年一年を読み解いています…', heroSub: '今年一年の大きな流れをひと目で', keyword: '今年のキーワード', lucky: '今年のラッキーポイント', halves: '上半期・下半期', months: '月ごとのカレンダー', samjaeAdvice: '今年とくに気をつけたいこと', resolution: '今年はこんなふうに', gateDesc: '今年のキーワードから分野ごとの運勢、12か月のカレンダー、新年の抱負まで、まとめてお届けします。', pv1: '今年のキーワード', pv2: '分野ごとの運勢8つ', pv3: '12か月のカレンダー', pv4: '上半期・下半期の流れ', pv5: '今年固めたいこと・新年の抱負', see: '新年の運勢を見る', seePaid: '新年の運勢を見る（₩9,900）', },
  taegil: { title: '日取り — 良い日を探す', sub: '予定していることを選ぶと、これからの3か月のカレンダーから、あなたにぴったりの日を色で示します。', best: 'とても良い', good: '良い', tapHint: '色のついた日をタップしてみてください', },  zodiac: { title: '干支・星座の今日の運勢', animal: '干支', sign: '星座', mine: 'あなたの運勢', },
  name: { title: '名前占い', sub: '名前の音が持つ響きから、あなたの雰囲気を読み解きます。', placeholder: 'ハングルで名前を入力してください', noHangul: 'ハングルで名前を入力してください。', },
  dream: {
    'aiBtn': 'AI 해몽 받기 (₩300)',
    'aiPh': '꿈에서 보거나 겪은 일을 자세히…',
    'aiSub': '복잡한 꿈은 이야기로 적어 보세요 — 사전에 없어도, 여러 상징이 섞여도 풀어 드려요.',
    'aiTitle': 'AI 꿈해몽',
    'buy5': '운 사용',
    'buyBundle': '꿈해몽을 5 운으로 볼까요?',
    'needCredit': '지금은 열 수 없어요. 잠시 후 다시 시도해 주세요.', fail: '夢の意味を読み込めませんでした。しばらくしてからもう一度お試しください。', title: '夢占い', sub: '夢に出てきたものを検索してみましょう。', placeholder: '例：豚、ヘビ、水…', generating: 'AIが夢を読み解いています…', notInDict: '辞書にない夢です。AIの夢占いを受けてみましょう。', aiSee: 'AIの夢占いを見る', history: '過去の夢占い' },
  luck: { title: '今日の幸運', todayEnergy: '今日の気分', color: 'ラッキーカラー', direction: 'ラッキーな方角', numbers: 'ラッキーナンバー', item: 'ラッキーアイテム', weakHead: 'あなたを支えてくれる色', weakTail: ' — あなたに不足しがちな気分なので、そばに置くとバランスが整いますよ。', },
  renewal: { title: '最新の内容で読み直す', msg: 'この占いから1年が過ぎました。\n\n{{pct}}%割引の{{coins}} woonで、今の時点で読み直します。（保有{{have}} woon）', later: 'あとで', go: '読み直す', needTitle: 'woonが足りません', needMsg: '読み直しには{{need}} woon必要です。現在{{have}} woonです。' },
  assist: { title: 'ウォニ', sub: '見たいものを教えてください。そこまでご案内します。', label: 'ガイド', hello: '何をご覧になりますか？ 三つから選んでも、そのまま話しかけても大丈夫です。', egLabel: 'こんな風に言っても大丈夫', miss: 'まだその言葉は分かりませんでした。下から選んでいただければすぐご案内します。', placeholder: '何を見たいですか？', reset: '↺ 最初から', send: '送信', },
  coach: { title: 'AI自己理解コーチ', sub: '自分について気になることを聞いてください。あなたの四柱で答えます。', coachLabel: 'コーチ', thinking: 'あなたの四柱を見ています…', placeholder: '自分について聞く', send: '送信', needChart: 'まず命式を登録してください。', registerBtn: '命式を登録', loadFail: '命式を読み込めませんでした。少し時間をおいてお試しください。', gateTitle: '今日の無料質問を使い切りました', gateDesc: '無料では1日{{count}}回まで聞けます。プレミアムなら制限なくコーチと話せます。', gateCta: 'プレミアムを見る', q1: '私はどんな人ですか？', q2: 'なぜ私の関係は似たように繰り返すのでしょう？', q3: '私の強みをどう活かせばいいですか？', q4: '最近の私の流れはどうですか？' },
  selfHero: { kicker: '私はどんな人か', emptyTitle: 'あなたを分析します', emptySub: '生年月日時を入れると四柱エンジンが性格·気質·強みを分析します', emptyCta: '+ 私を分析する', more: '性向分析を詳しく見る ›' },
  personal: {
    'toneCap': '나의 퍼스널 컬러', title: 'パーソナル五行', sub: '五行に合うカラー·コーデ·メイク·車の色', activate: '私を活かす色', balance: '補うと良い色', yongsin: '（私に必要な気）', cody: 'コーデ', makeup: 'メイク', car: '車の色', empty: '命式を登録すると五行に合う色を見つけます', emptyCta: '+ 命式登録', expertNote: '※ パーソナル五行は四柱の五行をもとにした参考提案です。実際のパーソナルカラー診断やスタイリングは専門家にご相談ください。' },
  // R-GEM v0.1 — 私の四柱宝石(★daniel 検収スロット: sub·note 文言)
  gem: { title: '私の四柱宝石', birthstoneTitle: '誕生石にはどんな意味が', sub: '誕生石は実はあなたに合わない — あなたを活かす本当の宝石', empty: '命式を登録すると合う宝石を見つけます', emptyCta: '+ 命式登録' },
  timeResolve: {
    'title': '태어난 시 찾기', yearRange: '年をもう一度ご確認ください（例：1990〜今年）。', yearFuture: '未来の年は入力できません。', removeEvent: '出来事を削除' },
  sok: { title: '相性(夜)', sub: '二人の性的相性を四柱で — 大人の遊び', gateTitle: '成人(19歳以上)コンテンツ', gateDesc: '二人の性的相性を四柱で読み解く成人向けコンテンツです。遊びとしてお楽しみください。', gateConfirm: '19歳以上です · 開始', pickPartner: '相手を選ぶ', newPartner: '新しい相手', registerSubmit: 'この相手で見る', spouseLabel: '配偶者宮の相性', adviceLabel: 'もっと良くする方法', kiss: 'キス相性', bed: '夜の相性', styleLabel: '二人のケミスタイル', pickHint: 'タップして相手を選択', noPartner: '保存された相手がいません。新しい相手を入力してください。', disclaimer: '※ 四柱で見る遊びコンテンツです。実際の関係は二人が作ります。成人(19歳以上)限定。' },
  community: { daily: '今日の日運', dailyTalk: '話に加わる', p1: 'とても良い', p2: '良い', p3: '普通', p4: 'いまいち', p5: 'つらい', pollMine: '投票完了！人が集まると統計が見えます。', pollStat: '{{total}}人参加 · 最多選択 {{top}}%', all: '全体', cat: { free: '自由', love: '恋愛', saju: '四柱Q&A', review: 'レビュー', question: '相談' }, empty: '最初の投稿をどうぞ。', profanity: '不適切な表現が含まれています。修正して再投稿してください。', write: '投稿', post: '投稿', titlePh: 'タイトル', bodyPh: '内容を入力 (暴言·差別·性的表現は禁止)', eulaTitle: 'コミュニティ利用規約', eulaBody: '暴言·差別·嫌がらせ·違法·性的/わいせつなコンテンツは禁止です。違反時は投稿削除·利用制限されることがあります。通報されたコンテンツは24時間以内に確認·対応します。不適切なユーザーはブロックできます。', eulaAgree: '同意して投稿', comments: 'コメント', noComments: '最初のコメントをどうぞ。', commentPh: 'コメント入力 (マナーを守って)', send: '登録', report: '通報', block: 'ブロック', reportTitle: '通報する', reportDesc: '理由を選択してください。通報は24時間以内に確認します。', rAbuse: '暴言·差別·嫌がらせ', rSexual: '性的/違法コンテンツ', rSpam: 'スパム·広告', reported: '通報を受付', reportedDesc: '確認して対応します。ありがとうございます。', reportFail: '通報に失敗しました。', blockTitle: 'このユーザーをブロック', blockDesc: 'ブロックするとこのユーザーの投稿·コメントが表示されなくなります。', blocked: 'ブロックしました', blockFail: 'ブロックに失敗しました。', delTitle: '削除しますか？', gone: '削除されたか表示できない投稿です。', loginTitle: 'ログインが必要です', loginDesc: '投稿はログイン後に利用できます。閲覧はログインなしでそのまま可能です。', goLogin: 'ログイン', attach: '自分の命式を添付', attachNone: '「本人」として登録された命式がありません。添付なしで投稿できます。', attachOff: '添付しない', attachLuck: '大運・歳運も一緒に公開', attachWarn: '原局の八文字がこの投稿を見る全員に公開されます。八文字から生年月日を逆算できるため、確認のうえ投稿してください。', needTitle: 'タイトルを入力してください。', needBody: '内容を入力してください。', posting: '投稿中…', errSession: 'ログインが必要です。再ログイン後にお試しください。', errNet: '通信環境を確認して再度お試しください。', errPost: '投稿できませんでした。しばらくして再度お試しください。' },
  egen: { title: 'エゲン vs テト', heroSub: '四柱で見るエゲン·テト傾向', tetoPower: 'テト力', typeTeto: 'テト型', typeEgen: 'エゲン型', typeBalanced: 'バランス型', scaleEgen: 'エゲン', scaleTeto: 'テト', secPersonality: '生まれ持った傾向', secRelationship: '恋愛·関係で', secNowTrend: '最近の流れ', needChart: 'まず命式を登録してください。', registerBtn: '命式を登録', gateTitle: '私の傾向の解説を見る', gateDesc: 'スコアに合わせて、あなたの傾向が普段·恋愛·今の流れでどう表れるかを気軽に解説します。', seeAd: '広告を見て無料で見る', seePremium: '解説を見る', generating: '傾向を分析しています…', genFail: '解説を読み込めませんでした。しばらくしてからもう一度お試しください。', adFail: '広告を読み込めませんでした。しばらくしてからもう一度お試しいただくか、プレミアムで広告なしでご覧いただけます。', },
  joseonjob: { shareLead: '朝鮮時代の私の職業', traits: '生まれ持った強み', share: '私の職業をシェア', detail: '私の四柱をくわしく見る（プレミアム）' },
  lovestyle: { shareLead: '私の恋愛スタイル', inLove: '恋愛では', tip: 'これを足すと', share: '恋愛スタイルをシェア', detail: '私の恋愛の流れをくわしく見る' },
  bok: { shareLead: '私の福', how: '福を育てる方法', share: '福をシェア', detail: '私の四柱をくわしく見る（プレミアム）' },
  pastlife: { shareLead: '私の前世', hint: '今のあなたへ', share: '前世をシェア', detail: '私の四柱をくわしく見る（プレミアム）' },
  healing: {
    'deficit': '가장 적은 기운(참고)', shareLead: '私の癒し方', recharge: '私の充電方法', nourish: '満たすと良い気', release: '手放すと良い気', color: '癒しの色', place: '癒しの空間', food: '添えると良い', mind: '心への一言', elemLead: '私の気', share: '癒し方をシェア', },
  bio: {
    'kicker': '바이오리듬',
    'note': '※ 사주와 무관한 참고용 리듬이에요. 0 부근은 컨디션이 바뀌는 전환일.',
    'sub': '오늘의 신체·감정·지성 리듬',
  },
  career: {
    'gateDesc': '두 길에서 어떻게 빛나고 어디서 막히는지, 타고난 무게추와 시기까지 풀어 드려요.',
    'generating': '두 길을 풀어내는 중…',
    'sub': '명식과 대운·세운으로, 독립과 조직 두 길을 짚어 드려요',
    'title': '사업가의 나 vs 직장인의 나',
  },
  celeb: {
    'compare': '일간·오행 비교',
    'funNote': '재미로 보기',
    'matchHead': '닮은 점',
    'myTenGod': '내 십신 구조 요약',
    'reasons': '공통 구조',
    'sub': '내 사주와 유명인의 사주를 견주는 재미 — 일간·오행·십신 구조로 닮은꼴을 찾아요',
    'title': '세계를 움직이는 사람들',
    'topLabel': '나와 가장 닮은 인물',
  },
  coins: {
    spendMsg: '{{cost}} woon を使って鑑定を始めますか？\n保有 {{have}} → 使用後 {{after}}',
    'balFail': '잔액을 불러오지 못했어요',
    'balance': '보유 운',
    'charge': '운 충전하기',
    'chargeCta': '운 충전하기',
    'donePending': '결제가 완료됐어요. 잔액 반영이 잠시 걸릴 수 있어요.',
    'doneTitle': '충전됐어요',
    'needLoginDesc': '충전한 운은 계정에 보관돼요. 로그인해야 기기를 바꿔도 그대로 남습니다.',
    'needLoginTitle': '로그인이 필요해요',
    'needTitle': '운이 부족해요',
    'note': '· 운은 모든 유료 풀이에 쓸 수 있어요.\\n· 충전한 운은 계정에 보관돼요 — 기기를 바꿔도 그대로예요.\\n· 운은 사용 기한이 없어요.',
    'packs': '운 충전하기',
    'spend': '운 사용',
  },
  country: {
    'needChart': '먼저 명식을 등록해 주세요.',
    'sub': '타고난 기운(조후)을 보완해 줄 기후·방위의 나라를 짚어 드려요',
    'title': '내가 살기 좋은 곳',
  },
  crush: {
    'caution': '조심할 점',
    'generating': '끌림의 기운과 인연의 흐름을 읽는 중…',
    'howToApproach': '다가가는 법',
    'myCharm': '지금 나의 매력',
    'sub': '지금 나의 매력과, 짝사랑·썸이 무르익기 좋은 시기, 다가가는 법을 짚어 드려요',
    'timing': '썸이 무르익는 시기',
    'title': '짝사랑 인연운',
    'whoLikesMe': '나에게 끌릴 사람',
  },
  crushAsk: {
    'cta': '깊은 짝사랑 풀이 보기',
    'q': '그 사람과 이어질까?',
    'sub': '짝사랑·썸이 무르익어 마음이 통하기 좋은 달을 무료로 미리 짚어 드려요',
  },
  gaeun: {
    'gateDesc': '지금 운에 무엇이 오는지 보고, 재물·관계·건강을 살리는 실천과 살풀이까지 짚어 드려요.',
    'generating': '지금 운에 맞는 개운법을 찾는 중…',
    'sub': '지금 운(대운·세운)에 맞춰 운을 살리는 구체적인 방법을 짚어 드려요',
    'title': '맞춤 개운법',
  },
  home: {
    'lightCta': '가볍게 보기',
    'manseSub': '내 사주 명식 전체 보기',
    'noChartCta': '+ 명식 등록',
    'noChartSub2': '생년월일만 넣으면 성격유형과 일주를 바로 볼 수 있어요. 가입도, 저장도 안 해요.',
    'noChartTitle': 'AI가 분석하는 나 — 여기서 시작',
    'quickRegister': '명식 등록',
    'quickRegisterSub': '가족·연인·친구의 명식을 추가해요',
  },
  impression: {
    'gapBig': '겉으로 비치는 모습과 알고 난 뒤의 모습이 꽤 달라요. 처음엔 몰랐던 반전 매력이 있는 사람이에요.',
    'gapSmall': '겉으로 비치는 모습과 속이 비교적 한결같아요. 보이는 그대로 믿음이 가는 사람이에요.',
    'inner': '막상 알고 보면 — 진짜 내 모습',
    'note': '※ 천간(밖으로 드러나는 기운)의 흐름이 남에게 비치는 이미지, 월지(타고난 자리)의 기운이 알고 보면 진짜 모습이에요.',
    'outer': '겉으로 비치는 나',
    'sub': '겉으로 비치는 모습과 알고 보면 다른 진짜 나',
    'title': '사람들이 보는 나의 인상',
  },
  job: {
    'bestField': '맞는 직종·환경',
    'flow': '취업·이직 흐름',
    'generating': '취업·합격의 기운과 흐름을 읽는 중…',
    'passLuck': '합격·시험운',
    'sub': '취업·이직·합격·시험이 잘 풀리는 흐름과 시기, 맞는 직종·준비 법을 짚어 드려요',
    'timing': '좋은 시기',
    'tips': '준비 팁',
    'title': '취업·이직운',
  },
  jobAsk: {
    'cta': '깊은 취업 풀이 보기',
    'q': '취업·이직, 언제 잘 풀릴까?',
    'sub': '취업·이직·합격의 문이 열리기 좋은 시기를 무료로 미리 짚어 드려요',
  },
  jobfit: {
    'ability': '실제 잘하는 것',
    'archetype': '나의 직업 유형',
    'gap': '끌림과 능력의 간극',
    'generating': '타고난 적성과 어울리는 직업을 읽는 중…',
    'jobs': '어울리는 일',
    'luckMap': '직업 인생 흐름',
    'preference': '끌리는 것 (능력 아님)',
    'recognition': '인정받는 법·무대',
    'sub': '타고난 적성으로 어떤 직업이 어울리는지, 끌림과 능력의 간극까지 짚어 드려요',
    'title': '나에게 어울리는 직업',
    'workEnv': '잘 맞는 일터',
    'workMode': '일하는 결·모드',
    'yongsinFit': '알맞은 방향',
  },
  login: {
    'go': '로그인',
    'needContentMsg': '이 콘텐츠를 보려면 로그인해 주세요. 로그인하면 구매·풀이가 계정에 안전하게 저장돼요.',
    'needTitle': '로그인이 필요해요',
  },
  mbti: {
    'empty': '명식을 등록하면 사주로 본 MBTI를 보여드려요.',
    'note': '※ 사주 구조(지장간·현재 운 포함)로 본 성향이라 시기에 따라 조금씩 달라져요. 심리검사 MBTI와 다를 수 있어요.',
    'sub': '내 사주 구조로 풀어본 성향 유형',
    'title': '사주로 보는 내 MBTI',
  },
  mod: {
    'empty': '신고된 콘텐츠가 없어요.',
    'hide': '숨기기',
    'restore': '복원',
    'sub': '신고된 콘텐츠를 검토하고 숨기거나 복원하세요. (신고 5회 이상은 자동 숨김)',
    'title': '신고 관리',
  },
  net: {
    'errMsg': '잠시 후 다시 시도해 주세요. 계속되면 잠시 뒤에 다시 열어 주세요.',
    'errTitle': '연결에 문제가 있어요',
  },
  relPattern: {
    'attraction': '매력·인연의 밀도',
    'compatCta': '특정 상대와의 궁합이 궁금하다면 →',
    'drawnTo': '반복해 끌리는 사람의 결',
    'dynamic': '나의 관계 역학',
    'footNote': '※ 배우자궁(일지)·인연星·도화 등 원국 구조를 사주 엔진으로 계산한 온디바이스 분석이에요. 예언이 아니라 나를 이해하는 참고예요.',
    'kicker': '사주 엔진으로 보는 관계 심리',
    'myStyle': '관계에서 나의 방식',
    'sub': '왜 비슷한 관계가 반복될까요? 궁합 운세가 아니라, 타고난 사주 구조에서 반복되는 관계의 결을 읽어요.',
    'title': '나의 관계 패턴',
    'titleSuffix': '님의 관계 패턴',
  },
  reunion: {
    'addDesc': '옛 인연의 명식과 지금의 고민을 더하면, 두 사람의 사주를 함께 보고 고민에 맞춰 풀어드려요. 비워 두면 나의 흐름만으로 봐요.',
    'addTitle': '함께 풀어드려요 (선택)',
    'afterReunion': '다시 만난다면',
    'caution': '되돌아보면 좋은 점',
    'changeBuy': '구매하고 바꾸기',
    'changeConfirmBuy': '상대를 바꾸려면 새로 풀어야 하고, 운이 필요해요. 진행할까요?',
    'changeConfirmCredit': '가진 재회운 1회분으로 상대를 바꿔 새로 풀어요. 바꾸시겠어요?',
    'changeConfirmPremium': '상대를 바꾸면 그 사람으로 새로 풀어요. 바꾸시겠어요?',
    'changeGo': '바꾸기',
    'concernLabel': '지금의 고민',
    'concernPh': '지금 어떤 상황·고민인지 적어주시면 함께 풀어드려요',
    'generating': '다시 이어질 인연의 흐름을 읽는 중…',
    'otherAdd': '옛 인연 생년월일 입력',
    'otherAnon': '옛 인연',
    'otherChange': '상대 바꾸기(새로 풀기)',
    'otherLabel': '옛 인연의 명식',
    'otherLockedNote': '상대를 바꾸려면 새로 풀어야 해요.',
    'otherPrivacy2': '※ 상대 정보는 이 재회 풀이에만 쓰여요. 바꾸기 전까지 이 기기에만 잠겨 보관되고, 명식 목록엔 남지 않아요. 동의를 얻은 경우에만 입력해 주세요.',
    'possibility': '다시 이어질 인연인지',
    'registerOtherSubmit': '이 명식으로 함께 풀기',
    'registerOtherTitle': '옛 인연 명식 입력',
    'remedy': '재회를 여는 법',
    'sub': '옛 인연과 다시 이어질 가능성과, 연락이 닿기 좋은 시기를 짚어 드려요',
    'theirResponse': '그때 상대의 마음',
    'timing': '연락이 닿기 좋은 시기',
    'title': '재회운',
  },
  reunionAsk: {
    'cta': '깊은 재회 풀이 보기',
    'q': '재회, 다시 이어질까?',
    'sub': '옛 인연과 다시 이어질 가능성·시기·방향을 무료로 짚어 드려요',
  },
  selfAnalysis: {
    'elements': '오행 밸런스 — 나를 이루는 다섯 기운',
    'footNote': '※ 모두 사주 엔진(만세력)으로 계산한 온디바이스 분석이에요. 예언이 아니라 나를 이해하는 참고예요.',
    'kicker': '사주 엔진이 분석한 나',
    'more': '자세히 보기 ›',
    'strengths': '강점과 기질 자세히',
    'sub': '타고난 사주를 엔진으로 계산한 다섯 갈래 자기분석 — 운세가 아니라 나를 이해하는 지표예요.',
    'title': '나 분석',
    'titleSuffix': '님 분석',
  },
  signup: {
    'body': '구매한 이용권과 풀이는 지금 쓰는 임시 계정에 묶여 있어요. 앱을 지우거나 기기를 바꾸면 되찾기 어려워요. 계정을 연결해 두면 그대로 이어서 볼 수 있어요.',
    'cta': '계정 연결하기',
    'note': '연결하지 않아도 지금처럼 계속 이용할 수 있어요.',
    'title': '지금 본 풀이, 이 기기에만 남아 있어요',
  },
  signupPrompt: {
    'cta': '계정 연결',
    'later': '나중에',
    'msg': '지금은 임시 계정이라 앱을 지우거나 기기를 바꾸면 구매한 이용권과 풀이를 되찾기 어려워요. 연결하지 않아도 계속 보실 수 있어요.',
    'title': '계정을 연결하면 이 풀이가 안전하게 보관돼요',
  },
  spouseDual: {
    'ageHint': '나이대 힌트',
    'ageNote': '※ 경향일 뿐이에요. 실제 상대 사주가 있으면 궁합이 우선해요.',
    'funnel': '더 구체적인 이상형·실제 인연·시기 통변은 아래 애정 리딩에서 확인해요.',
    'gap': '대비',
    'idealTag': '끌리는 이상형',
    'ignite': '끌림(발동)',
    'match': '일치',
    'noFlow': '다음 8년간은 배우자 자리가 크게 열리고 닫히는 신호가 약해요. 큰 변동보다 다지는 시기예요.',
    'realDesc': '결혼생활의 실질 — 늘 최우선인 자리(일지)',
    'realTag': '진짜 곁에 남는 사람',
    'settle': '안정(안착)',
    'sub': '타고난 배우자 자리를 두 축으로 봐요 — 끌리는 이상형과, 실제로 곁에 남는 사람.',
    'timeline': '끌림 vs 안정 — 인연 흐름',
    'title': '이상형과 진짜 인연',
  },
  traits: {
    'detail': '내 사주 깊이 보기',
  },
  wealth: {
    'flow': '재물 인생 흐름',
    'generating': '타고난 재물 그릇과 흐름을 읽는 중…',
    'howEarn': '돈이 들어오는 결',
    'partner': '혼자 vs 함께',
    'remedy': '재물 지킴·개운',
    'sub': '타고난 재물 그릇과 유형, 언제 크게 들어오고 어떻게 지키는지까지 짚어 드려요',
    'timing': '재물 시기',
    'title': '재물 딥리포트',
    'type': '재물 유형',
    'vessel': '재물 그릇',
  },
  yieojim: {
    'express': '마음은 이는데 정착까진 약한 해',
    'mine': '내가 먼저 다가가 이어지기 좋은 해',
    'mineNone': '다음 10년엔 약해요 — 내가 먼저 표현해 다가가는 힘(식상)이 원국에 옅어, 특정 시기(그 기운이 들어올 때)에 집중돼요.',
    'note': '※ 참고 경향이에요. 실제 인연은 만나는 사람에 따라 달라져요. 어느 쪽이든 최종적으로 이어지려면 ‘인연 자리’가 열리는 해가 열쇠예요.',
    'popular': '관심·인기는 오지만 정착까진 약한 해',
    'sub': '짝사랑이든 대시든, 실제로 이어지려면 ‘인연 자리(배우자궁)’가 그때 열려 있어야 해요.',
    'theirs': '좋은 인연이 다가와 이어지기 좋은 해',
    'theirsNone': '다음 10년엔 인연이 다가와 정착까지 이어지는 뚜렷한 시기가 약해요.',
    'title': '인연이 이어지는 시기',
  },
};
