// app/src/copy/ja.ts — 日本語 UI 文言。キーは ko.ts と一致させること。
export const ja = {
  ny: {
    samjaeNone: '三災なし',
    samjaeNoneSub: '来年は三災に入らない年です',
    samjaeDeul: '入る三災',
    samjaeDeulSub: '三災が入り始める年です',
    samjaeNul: '留まる三災',
    samjaeNulSub: '三災の真ん中を通る年です',
    samjaeNal: '出る三災',
    samjaeNalSub: '三災が退く年です',
    toneOpen: '上昇',
    toneMild: '無難',
    toneCare: '用心',
    capOpen: '来年は自分の質とよく合う気が入る流れです。準備したものを広げるのに良い年です。',
    capMild: '来年は大きな起伏なく無難に流れる方です。自分のペースで固めていくとよいです。',
    capCare: '来年は力を内に集めて固めるのに良い年です。無理な拡張より中身を整えてみてください。',
    manage: '三災は避ける年ではなく、体・関係・暮らしを見ながら中身を固める年として見ます。',
    upsell: '三災は同じ干支の人みんなの話です。あなた本来の一年は、四柱の八文字で計算し直す必要があります。',
    bokA: 'この年が名ばかりの',
    bokB: '福三災',
    bokC: 'なのか、実際に気をつけることがある年なのかは、深い読みではっきり示します。',
    gaugeTitle: '来年の気が自分に合う度合い',
    keywordTitle: '来年のキーワード プレビュー',
    goodMonths: '来年の良い月',
    calNote: '曲線が高い月に気がよく通じます(濃く塗られた点)。何に良いかは深い読みで月ごとに示します。',
    calNoteNone: '来年の良い月は、深い読みで月ごとにはっきり示します。',
    freeB: '来年の大きな気・三災・良い月',
    paidB: '来年の十二か月を財・愛情・仕事・健康に分け、開運法と福/悪三災まで',
  },
  cp: {
    genAsk: '{{rel}}の相性の読みを作りますか？',
    genFree: '追加費用なしで作られます。',
    genCost: 'この関係には{{n}} 運が必要です。',
    ziweiCompat: '紫微の相性',
    compat: '相性',
    relHintPrem: '関係ごとに別の読みです',
    relHint: '関係ごとに別々に読みます — 選んだ関係だけ{{n}} 運かかります',
    sigSeason: '季節の相補',
    sigJaegwan: '相手 = 自分の{{g}}',
    sigFill: '欠けを補う',
    sigSpouse: '配偶者宮',
    tapHint: '作用をタップすると、上の二つの命式で該当する文字が強調されます。',
    noCross: '二つの命式の間に、直接の合・沖・刑・害はありません。',
    me: '自分',
    other: '相手',
    yearN: '{{y}}年',
  },
  sd: {
    posMonth: '社会生活で自然に惹かれる質',
    posYear: '家・育った背景と繋がる像',
    posHour: '人生の後半・家庭で描く像',
    posFallback: '惹かれる異性像',
    noStar: 'はっきりした理想像のサインは弱いです',
    gungOnly: '実際の縁が中心',
    gungOnlyDesc: 'はっきりした理想像(配偶者星)が原局に表れません — 実際にそばに残る人(日支)の方が大きな軸です。',
    match: '惹かれた先が結実',
    matchDesc: '惹かれる理想像と実際にそばに残る人が、ほぼ同じ質です。最初の惹かれがそのまま続きやすいです。',
    clash: '正面衝突型',
    clashDesc: '理想像と実際の配偶者が正面から対比します。関係の間ずっと緊張があり、大きく心を決める時期が来ます。',
    friction: 'じわりと擦れ違う型',
    frictionDesc: '表向きは無難でも質が微妙にずれ、長く一緒にいるほど疲れが溜まりやすいです。話し方を先に合わせておくのが処方です。',
    split: 'トラック分離型',
    splitDesc: '恋愛の初めに惹かれる像と、結婚まで行く像が別の質のことがあります。惹かれと定着を分けて見る目が必要です。',
    neutral: 'はっきりした対比なし',
    neutralDesc: '理想像と実際の縁の間に、大きなずれのサインは弱いです。',
    lblEvent: '変曲点',
    lblActive: '惹かれが活性',
    lblResolve: '縁の整理',
    lblSettle: '安定・定着',
    lblConfirm: '関係の確定',
    elder: '年上傾向',
    elderDesc: '自分より年上の縁に心が傾く傾向があります。',
    younger: '年下・世話をする側の傾向',
    youngerDesc: '年下、あるいは自分が世話をする側の縁に傾く傾向があります。',
    band0: 'ほぼ一致',
    band1: '軽いずれ',
    band2: 'じわりとしたずれ',
    band3: 'じわりとした緊張',
    band4: '強い対比',
  },
  rt: {
    partRoot: '根',
    subRoot: '生まれ持った土台',
    partStem: '茎',
    subStem: '育った場',
    partFlower: '花',
    subFlower: '今の自分',
    partFruit: '実',
    subFruit: '結んでいく実り',
    tier0: '浮いています',
    tier1: '根が浅いです',
    tier2: '根があります',
    tier3: '根がしっかりしています',
    tier4: '根がとても深いです',
    head3: '生まれ持った気が、とてもしっかり根を張っています',
    sub3: 'たいていの揺れには大きく振り回されない力です。',
    head2: '気がしっかりと据わっている方です',
    sub2: '中心が立っているので、押し進める力があります。',
    head1: '気がやわらかく柔軟な方です',
    sub1: '周りの流れをよく読み、合わせていく力があります。',
    head0: '気が軽く柔軟で、変化によく合わせていけます',
    sub0: '枠に縛られず、状況に合わせて流れる質です。',
    lead: '生まれ持った気が、どれだけしっかり根を張っているか',
    leadSub: '根が深いほど揺れが少なくなります。四つの位置の根の強さを先に描いてみました。',
    legend: 'バーが長いほど、表に出た気が奥の根までしっかり届いています。短ければ表面に浮いた気です。',
    countA: '{{n}}箇所のうち',
    countB: '{{n}}箇所',
    countC: 'が奥の根に届いています。',
    tuNote: '生まれた時刻が不明なため、実(時)の位置は外しました。',
    freeB: '四つの位置の根の強さ',
    freeC: 'を一目で見られます。',
    paidB: 'それぞれの根が人生で何を意味するか、表と奥の差、弱い根を強く育てる方法',
  },
  ct: {
    bandOrg: '組織型',
    bandHybrid: 'ハイブリッド型',
    bandPro: '専門家・フリーランス型',
    bandIndep: '独立事業型',
    headOrg: '生まれ持った気は「組織」の中で光る質です',
    headHybrid: '組織と自分の事業、両方の質を併せ持つ柔軟型です',
    headPro: '専門性を武器に独り立ちしやすい質です',
    headIndep: '生まれ持った気は「自分の事業」に近い質です',
    subOrg: '体系と所属の中で信頼を積み上げるとき力が出ます。どちらが優れているかではなく、自分に合う質がこちらだという意味です。',
    subHybrid: '状況によって組織にも自分の事業にも進めます。一方に寄せなくてよいことが、むしろ強みです。',
    subPro: '組織に頼るより、自分の専門性で場を作るときうまくいきます。組織での経験を足場に独り立ちへ繋げるとよいです。',
    subIndep: '自分の場を直接率いるとき、最も自分らしくいられます。どちらが優れているかではなく、生まれ持った傾向がこちらだという意味です。',
    bizCreative: '新しいものを作り、自分を表す力',
    bizWealth: '直接ぶつかって現実の成果を作る力',
    bizIndep: '自ら場を率いる独立心',
    bizNone: '自分主導で動く力',
    orgStructure: '組織と体系の中で位置を築く力',
    orgStability: '安定と信頼を着実に積む力',
    orgNone: '枠の中で着実に積み上げる力',
    bothLine: '事業家の側には{{biz}}、組織の側には{{org}}が、どちらもあります。',
    lead: '生まれ持った気が「自分の事業」寄りか「組織」寄りか',
    leadSub: '天秤で先に描いてみました。詳しい話は下で開けます。',
    riskA: '生まれ持った器は「自分の事業」に向きますが、今の構えでは実行段階で',
    riskB: '構造を固める準備',
    riskC: 'が必要な質です。だから天秤が中央寄りになります。',
    partnerA: '一人よりも',
    partnerB: '共同事業・共同投資',
    partnerC: 'では、持分・役割をはっきりさせておくと問題が少なくなります。',
    freeB: '自分の傾向の重心(事業家↔会社員)',
    freeC: 'が見られます。',
    paidB: '自分に合う職種・起業に良い時期・組織でうまく馴染む方法',
    biz: '事業家',
    org: '会社員',
    endBiz: '自分の事業・独立',
    endOrg: '組織・安定',
  },
  ss: {
    fromLuck: '運から入る',
    fromLuckLong: '運から入る — 原局にはない(大運・歳運で働く)',
    fromLuckNoNatal: '運から入る(原局にはない)',
    noChart: '命式の情報がありません。',
    intro: '神殺は四柱に色を添える補助的な指標です(中心は構造・格局)。吉凶を断じるより、強みとして活かす筋・気をつける筋を理解する軸として見ます。基準の文字が原局にあれば✓(位置)、なければ大運・歳運で働きます。',
    gilsin: '吉神',
    gilsinDesc: '助け・福禄・貴人の質 — 苦しい時にほどいてくれる気。',
    teuksu: '特殊煞',
    teuksuDesc: '強い色 — 専門性・魅力・決断のように両面を持つ気(使い方次第)。',
    twelveDesc: '各柱の地支を年・月・日・時支の4基準すべてで算出します(基準によって名が変わります)。',
    byBase: '{{bases}}基準',
    note: '※ 神殺は補助的な指標です。深い読み(領域別)は構造・格局・用神と併せて見ます。',
  },
  tr: {
    evMove: '引っ越し',
    evJob: '転職',
    evFound: '起業',
    evWed: '結婚',
    evDivorce: '離婚',
    evLoss: '投資の損失',
    evIllness: '病気',
    evAccident: '事故',
    lead: '生まれた時刻がわからなくても、人生の出来事から時(じ)を絞り込みます。出来事を足すほど正確になります。',
    birthLabel: '生年月日(新暦)',
    birthPh: '例: 19940316(数字だけでも大丈夫です)',
    sexLabel: '性別',
    placeLabel: '出生地',
    eventLabel: '人生の出来事(年+種類)',
    yearPh: '年(例: 2023)',
    addEvent: '出来事を追加',
    run: '候補を絞る',
    payHint: '一度支払えば、出来事を足しながら何度でも絞り込めます。',
    sigDirect: '入力した出来事が、この時刻の気とそのまま通じます',
    sigMove: '引っ越し・移動の多い流れとよく合います',
    sigHealth: '健康・体の変化の時期と合致します',
    sigAnchor: 'その年に起きた出来事の変動と噛み合います',
    sigJohu: '季節の気の釣り合いがよく取れた時刻です',
    sigHapchung: '文字どうしが引き合いぶつかる形が、出来事と合います',
    headConfirmed: '第一候補まで絞れました',
    headShortlist: '有力候補2〜3個まで絞れました',
    headOpen: 'まだ確定は難しいです — 出来事をもう少し足してください',
    disc: '※ 出来事が多いほど正確になります。推定結果であり、正確な読みは時を確定してから原局全体で見ます。',
  },
  jr: {
    colorMetal: '端正な白・銀',
    capOpen: '今、職・合格の扉が大きく開く流れです。願書・面接・転職を準備すると流れに乗りやすいです。',
    capWarming: '職・合格の扉が少しずつ開いています。資格・書類を先に整えておけば、開く時を逃しません。',
    capQuiet: '今は扉が静かです。焦るより、実力・資格を固めて次の流れに備えるのに良い時です。',
    sigGwan: '職・席の気が入ってきます',
    sigIn: '資格・合格の気が支えます',
    sigSiksang: '実力を見せる気が助けます',
    sigJae: '結実・報酬の気が伴います',
    sigNone: '今は気が静かです',
    partGwan: '職・席が開く気',
    partIn: '資格・試験・書類を支える気',
    partSiksang: '面接・実務で実力を見せる気',
    partJae: '努力が結実・報酬に繋がる気',
    bodyParts: '今の流れには{{parts}}が一緒に入っています。準備した分だけ機会を掴みやすい時です。',
    bodyNatal: '今は特定の気が大きく際立ってはいませんが、生まれ持った器に職・資格の土台があります。実力を固めて流れが開く時に備えるとよいです。',
    bodyQuiet: '今は職・資格の気が穏やかです。焦るより方向を整えて力を蓄えれば、次の流れで扉が開きます。',
    teaserDow: '応募・面接に力をくれる曜日',
    teaserColor: '合格・面接に力をくれる色',
    pressLabel: '今は就職より、圧と試される時期です',
    pressBody: '今の流れは、席(職)を開く気より自分を試す圧の質が強いです。無理に押すより、この圧を資格・専門性として消化しておけば、次の流れで扉はより大きく開きます。',
    gaugeTitle: '就職の扉が開いている度合い',
    nowTitle: '今の就職運の質',
    gaeunTitle: '就職開運プレビュー',
    locked: '良い方角・残りの色と曜日・応募と面接の実践法は深い読みで',
    freeB: '可能性・有利な時期',
    paidB: '合格戦略・合う職種・具体的な開運法・転職のタイミング',
  },
  cr: {
    capOpen: '今、その人と繋がる流れが大きく開いています。気持ちがあるなら、自然に近づいてみてください。',
    capWarming: '繋がる流れが少しずつ温まっています。急ぐより、流れが熟す月を狙って気持ちを少し表してみてください。',
    capQuiet: '今は流れが穏やかです。焦るより、自分を整えて惹かれ合う時に備えるとよいです。',
    dohwaOpen: '今、惹かれる力が強く回る流れです',
    dohwaBond: '今、縁が結ばれようとする流れです',
    dohwaFriction: '今、少しすれ違いながら動く流れです',
    dohwaCalm: '今は静かな流れです',
    dohwaOpenSub: 'ときめきもきっかけも強く立つ時期です。気持ちを表せば通じやすいです。',
    dohwaBondSub: '互いに近づこうとする流れです。軽く近づけば自然に繋がりやすいです。',
    dohwaFrictionSub: '押して引く流れです。焦りより余裕をもって近づくと、流れが和らぎます。',
    dohwaCalmSub: '惹かれる力はまだ控えめです。無理せず自分を整えて、次の流れを待ちます。',
    charmBorn: '生まれつきの惹きつける力があります',
    charmSubtle: 'じわりと沁みる魅力です',
    charmBornSub: '落ち着いた雰囲気で人を引く魅力があり、気持ちを表すと相手が惹かれやすいです。',
    charmSubtleSub: '華やかというより徐々に沁みる魅力なので、よく顔を合わせて心地よさを重ねると心が開きます。',
    teaserDow: '近づくのに良い曜日',
    teaserColor: '近づくのに良い色',
    gaugeTitle: 'その人と繋がる可能性',
    signalTitle: '惹かれるサイン',
    gaeunTitle: '近づく開運プレビュー',
    locked: '良い方角・残りの色と曜日・近づく具体的な方法は深い読みで',
    freeB: '可能性・時期・近づくタイミング',
    paidB: 'その人の心・近づき方・繋がる理由',
  },
  bd: {
    title: 'この情報で命式を作りますか？',
    noDate: '(生年月日が読めませんでした)',
    timeUnknown: '時刻不明',
    whyPlace: '生まれた場所は真太陽時の補正に使います — これがないと時柱が変わることがあります。',
    unknown: 'わからない',
    solar: '新暦',
    lunar: '旧暦',
    male: '男性',
    female: '女性',
    placePh: '例) ソウル・釜山・ミラノ',
    making: '作成中…',
    make: '命式を作る',
    fillAbove: '上で埋まっていないものを選んでください。',
    fDate: '生年月日',
    fTime: '生まれた時刻',
    fCal: '新暦/旧暦',
    fSex: '性別',
    fPlace: '生まれた場所',
  },
  rg: {
    me: '自分',
    workMoney: '仕事・お金',
    relation: '関係',
    growth: '成長',
    money: 'お金',
    workHealth: '仕事・健康',
    etc: 'その他',
    adminReset: '読みをリセット(管理者)',
    adminResetAsk: 'この読みを削除して、作り直せるようにしますか？',
    reset: 'リセット',
    resetFail: 'リセットに失敗',
    admin: '管理者',
    resetDone: 'リセットしました。もう一度開くか生成すると、新しく作られます。',
    coinN: '{{n}} 運',
    loading: '読みを読み込み中…',
    toList: '一覧へ',
  },
  rr: {
    dirN: '北',
    dirS: '南',
    dirE: '東',
    dirW: '西',
    dirNear: '近い場所',
    seasonW: '冬',
    seasonSu: '夏',
    seasonSp: '春',
    seasonA: '秋',
    colorWood: '澄んだ青緑',
    colorFire: '温かな赤',
    colorEarth: 'やわらかな黄・ベージュ',
    colorMetal: '澄んだ白・銀',
    colorWater: '深い紺',
    dowThu: '木曜日',
    dowTue: '火曜日',
    dowSat: '土曜日',
    dowFri: '金曜日',
    dowWed: '水曜日',
    toneOpen: '開いています',
    toneWarming: '少しずつ開きます',
    toneQuiet: '今は静かです',
    capOpen: '昔の縁とまた繋がる扉が開いている流れです。気持ちがあるなら、今こそ素直に伝えてみてください。',
    capWarming: '扉が少しずつ開いています。急ぐより、機が熟す時期を狙ってみてください。',
    capQuiet: '今は扉が静かです。無理な連絡より、自分を整えて時を待つのがよいです。',
    gungOpen: '今、開く流れです',
    gungBond: '今、結ばれる流れです',
    gungFriction: '今、少しぶつかりながら動く流れです',
    gungCalm: '今は静かな流れです',
    gungOpenSub: '縁の座が開く時期です。再び向き合うきっかけが生まれやすいです。',
    gungBondSub: '縁の座が繋がろうとする流れです。関係を結び直すのに良い時です。',
    gungFrictionSub: '座が揺れながら動きます。感情より落ち着いて近づくと、流れが和らぎます。',
    gungCalmSub: '座はまだ静かです。無理に開くより、自分を満たして次の流れを待ちます。',
    teaserDow: '縁が開く曜日',
    teaserColor: '縁を呼ぶ色',
    gaugeTitle: '再会の扉が開いている度合い',
    seatTitle: '縁の座',
    dirTitle: '縁の気の方角・季節',
    dirBodyA: 'あなたの縁の気は',
    dirBodyB: 'に熟し、',
    dirBodyC: 'の方角の気とよく通じます。',
    gaeunTitle: '連絡の開運プレビュー',
    locked: '良い方角・残りの色と曜日・具体的な実践法は深い読みで',
    freeA: '無料では',
    freeB: '可能性・時期・方角',
    freeC: 'まで見られます。',
    paidA: '深い読みでは',
    paidB: '相手の心・具体的な開運法・再び繋がる理由',
    paidC: 'まで読み解きます。',
  },
  adult: { title: 'アダルト会話', row: '満19歳以上です', sub: '相性や親密さの話をぼかさずに話します。' },
  screen: {
    shared: '共有された鑑定',
    register: '命式の登録',
    coinhistory: '決済・チャージ履歴',
    charts: '万年暦',
    moment: 'モーメント',
    light: 'かんたん鑑定',
    biorhythm: 'バイオリズム',
    coins: '運のチャージ',
    market: 'マーケット',
  },
  appName: 'ニウンネウン',
  tagline: '自分と他人を理解するAIの羅針盤',
  // 홈 카드 개인화 티저 — ko 와 동일 키(계산=homeTeaser.ts). ※ newyear.keyword 값 자체는 엔진이 한국어로 산출.
  teaser: {
    career: '事業家型 {{biz}}% · 組織型 {{org}}%',
    newyear: '今年のキーワード · {{keyword}}',
    flow: '現在 {{n}}番目の区間 · 転換点 {{turns}}回',
    crush: '{{year}}年 {{months}}月 · 惹かれる流れ',
    reunion: '{{year}}年 {{months}}月 · 連絡が届きやすい',
    job: '{{years}}年 · 門が開く年',
    raw: '{{text}}', // image·talent·mission — 文言はエンジン(lib/content/elementPhrases)が韓国語で算出しそのまま挿入(既存 newyear.keyword と同方式・3言語同値)
  },
  onb: {
    skip: 'スキップ',  next: '次へ', start: '私の分析を始める',
    t1: 'AIが分析する「私」',
    b1: 'ニウンネウンは占いアプリではありません。四柱推命をエンジンに、あなたがどんな人かを分析する自己理解ツールです。',
    t2: 'あなただけの命式を計算します',
    b2: '生年月日時を精密な万歳暦（真太陽時・時代補正）で計算し、誰とも同じでないあなただけの分析を作ります。',
    t3: 'こんなことがわかります',
    l1: '私はどんな人か — 性格・強み', l2: 'なぜ関係が繰り返すのか', l3: 'どんな仕事が合うか', l4: '今年何を準備するか',
    t4: 'こんなふうに分析します', pvBadge: '例', pvType: 'テト型', pvScale: 'テト 63%', pvLine: '決断力があり主導的。ただ、時には休む余裕が大きな力になります。', pvNote: '生年月日時を入れるだけであなただけの分析が出ます',
  },
  // ★App Store 4.3(スパム/重複)対応 — 「計算されている(computed)」を可視化(ComputedNote が参照)。
  computed: {
    title: 'あなたの生年月日から計算した個人の命式',
    body: '真太陽時・経度・歴史的なサマータイムまで補正して万歳暦を計算し、40あまりの古典ルールをこの命式に適用します。誰とも同じでない結果です。',
    badge: '私の生年月日から計算',
    more: '蔵干・冲・合・刑、神殺、大運(運の流れ)まで計算し、四柱推命と紫微斗数の二つの伝統を照らし合わせて検証します。',
  },
  menu: { typematch: 'タイプ対タイプ', typematchDesc: '相手の生年月日なしで日柱だけで照らす',  mycard: '私のカード', mycardDesc: '自分のタイプを一枚に', 
    relationmap: '関係地図', relationmapDesc: '登録した人が自分にとってどんな質か、一枚で',
    'taemong': '胎夢の解説', 'taemongDesc': '子を待つ心を、夢に出たもので読む', 'taemongTileDesc': '龍·虎·鯉… 胎夢の象徴を無料で',
    'egenteto': 'エゲン・テト傾向',
    lookback: '振り返り', lookbackDesc: 'その日の運勢と自分の記録を並べて',
    myeongsik: '命式登録', myeongsikDesc: '命式の登録·管理',
    manse: '万歳暦', manseDesc: '日付別四柱·チャート管理', timeResolve: '生まれた時刻さがし', timeResolveDesc: '時刻不明でも出来事から推論',
    ziwei: '紫微斗数', ziweiDesc: '命盤·12宮の星',
    taro: 'タロット', taroDesc: '今日のカード',
    today: '今日の運勢', todayDesc: '毎日変わる日運', month: '今月の運勢', monthDesc: '今月の分野別の流れ',
    compatMarriage: '結婚の相性', compatMarriageDesc: '生涯добро共に歩める相手か', compatCoworkerDesc: '一緒に働くとどうなるか', compatCoworker: '同僚との相性', compatSenior: '目上との相性', compatSeniorDesc: '上司・メンターとの噛み合い', compatBusiness: '共同事業の相性', compatBusinessDesc: '一緒に稼ぐとどこで分かれるか', compatFamily: '家族の相性', compatFamilyDesc: '親・兄弟との間合い', compatFriend: '友人との相性', compatFriendDesc: '長く続く相手かを見る', compat: '相性', compatDesc: '関係力学の深い分析',
    premium: 'プレミアム鑑定', premiumDesc: '深い通変·全領域', premiumTag: 'プレミアム',
    timeline: '人生タイムライン', timelineDesc: '10〜100歳の時期別の流れ',
    pet: 'うちの子', petDesc: 'うちの子の生まれもった特徴', love: '私の恋愛の流れ', loveDesc: '理想のタイプ·出会う人を詳しく',
    lifegraph: '人生グラフ', lifegraphDesc: '大運別の人生の流れ曲線·転換点',
    newyear: '新年運勢', newyearDesc: '今年の総合·月別·三災',
    roots: '命式の根', rootsDesc: '表に出た自分·秘めた力·本当の強さ',
    image: '映る自分', imageDesc: '他人に見える第一印象·雰囲気',
    impression: '人が見る私', impressionDesc: '第一印象から深い仲まで映る私',
    mission: '私の使命', missionDesc: '何のために生まれたか',
    persona: '性格タイプ', personaDesc: '四柱で見る私の16タイプ', egen: 'エゲン vs テト', attach: 'アタッチメント', mbti: '四柱MBTI', traits: '私の特徴', selfAnalysis: '自己分析', selfAnalysisDesc: '性格·気質·五行バランスをまとめて分析', relationPattern: '関係パターン', relationPatternDesc: 'なぜ関係が繰り返すか — 生まれ持った関係の質', personal: 'パーソナル五行', personalDesc: '五行に合うカラー·コーデ·メイク·車の色', gem: '私の四柱宝石', gemDesc: '誕生石は実はあなたに合わない — あなたを活かす本当の宝石', sokgunghap: '相性(夜)', sokgunghapDesc: '二人の性的相性 (成人·遊び)', community: 'コミュニティ', communityDesc: '四柱·恋愛·悩みを分かち合う場所', joseonjob: '朝鮮時代の職業', lovestyle: '恋愛スタイル', bok: '生まれ持つ福', pastlife: '前世物語', healing: '私の癒し方',
    taegil: '択日', country: '私が暮らしやすい場所', countryDesc: '気運に合う国·気候', taegilDesc: '結婚・引越し・契約の吉日',
    luck: '今日の幸運', luckDesc: '幸運の色·方角·数字',
    zodiac: '干支·星座', zodiacDesc: '今日の干支·星座運勢',
    name: '名前占い', nameDesc: '名前の五行の流れ',
    dream: '夢占い', dreamDesc: 'キーワードで探す',
    dayPillar: '日柱論', dayPillarDesc: '生まれた日でみる気質', career: '起業家の私 vs 会社員の私', careerDesc: '独立と組織、二つの道', gaeun: 'あなたの開運法', gaeunDesc: '今の運に合わせて運を活かす', followupDesc: '占いにもう一つ質問', talent: '私の生まれ持った才能', celeb: '私に似た芸能人', celebDesc: '俳優·アイドルの四柱と比べる楽しみ', talentDesc: '才能·向く道·お金の扱い方', numerology: '数秘術', numerologyDesc: '数で見る人生の方向·才能', astrology: '星座·占星術', astrologyDesc: '星座 + ネイタルチャート、二つの視点',
    child: '子どもの縁', childDesc: '子との縁·気質·親としての私', future10: '10年後の私', future10Desc: '大運·歳運で描く10年後', reunion: '復縁', reunionDesc: '元の縁が再び開く時期·可能性', crisis: '関係の山場', crisisDesc: '揺れる時期を構造で — 占いではなく座と力で', crush: '片思い·ご縁運', crushDesc: '想いが届くか·惹かれる人の質·近づく時期', job: '就職·転職運', jobDesc: '就職·転職·合格·試験が動きやすい時期', jobfit: '私に合う職業', jobfitDesc: '生まれ持った適性で合う職業·惹かれと能力の差', wealth: '財運ディープレポート', wealthDesc: '生まれ持った財の器·タイプ·大きく入る時期と守り方', reunionAsk: '復縁できる？', reunionAskDesc: '無料で見る復縁の可能性·連絡に良い月', crushAsk: 'あの人と結ばれる？', crushAskDesc: '無料で見る魅力·ご縁が高まる月', jobAsk: '就職はいつ？', jobAskDesc: '無料で見る就職·合格運が開く時期',
    saju: '四柱推命', sajuDesc: '鑑定·タイムライン·相性', ziweiHub: '紫微斗数', ziweiHubDesc: '命盤·運限·相性',
    secLove: '恋愛', secLoveDesc: '相性・縁・心が通じる時期',
    secToday: '運勢', secTodayDesc: '今日・今月・今年の流れ',
    secSelf: '自己分析', secSelfDesc: '性格・気質・人からの見え方',
    secWork: '仕事・財', secWorkDesc: '適性・就職・財の器',
    secHidden: 'もっと見る', secHiddenDesc: 'おすすめから出会うコンテンツ',
    chipLove: '恋愛', chipToday: '運勢', chipSelf: '自分', chipWork: '仕事', chipHidden: 'もっと',
    secLife: 'ライフ', secLifeDesc: 'タロット・紫微・気軽な読み物',
    secTool: 'ツール', secToolDesc: '万年暦で自分で調べる',
    chipLife: 'ライフ', chipTool: 'ツール',
    chipAll: 'すべて',
    secContent: '人気', // ★ショートカット行(テーマ軸の外)
    // (旧)価格軸のラベル — テーマ軸再編で未使用。戻せるように残す。
    secFree: '今日・命式', secPremium: '自分を理解する', secSpecial: 'スペシャル', secDeep: '自分を知る', secLight: '気軽に',
    viewCard: 'カード', viewList: 'リスト', // ホーム表示切替
    todayTileDesc: '今日一日の流れ', monthTileDesc: '今月の流れ', newyearTileDesc: '今年のキーワード・12か月', personaTileDesc: '性格タイプ', taegilTileDesc: '良い日選び', luckTileDesc: '今日の幸運', zodiacTileDesc: '干支・星座', nameTileDesc: '名前の響き', dreamTileDesc: '夢占い', egenTileDesc: '私はエゲン？テト？', attachDesc: '命式とアンケートを並べて', mbtiTileDesc: '四柱で見るMBTI', joseonjobTileDesc: '四柱で見る朝鮮の職業', lovestyleTileDesc: '私の恋愛細胞は？', bokTileDesc: '私の福は？', pastlifeTileDesc: '私の前世は？', healingTileDesc: '私に合う休み方は？',
    secPremiumDesc: 'あなたはどんな人か — 四柱·紫微で深く', secContentDesc: 'AIが丁寧に解く深い鑑定', secHotDesc: '最近よく見られているものだけ', secDeepDesc: '自分をより深く見つめる', secLightDesc: '気軽に楽しむ運勢',
  },
  bug: {
    title: 'バグ報告', send: '送信',
    desc: '不便だった点やおかしな動きを教えてください。どの画面で何をしたときに起きたかを書いていただけると、修正がぐっと早くなります。',
    what: '何が起きましたか？',
    placeholder: '例）相性占いを押したら画面が回り続けます',
    contact: '返信先（任意）', contactHint: 'メールなど — 空欄でも大丈夫です',
    autoInfo: 'アプリのバージョンと端末の種類も一緒に送られます（原因調査にのみ使用します）。',
    doneTitle: 'ご報告ありがとうございます',
    doneBody: 'いただいた内容は開発者が直接確認しています。数日以内に修正いたします。',
    failTitle: '送信できませんでした',
    failBody: 'しばらくしてからもう一度お試しください。うまくいかない場合は下記の宛先へお送りください。',
  },
  relmapCard: { title: '関係地図', lead: '{{name}}さんは{{role}}です', more: '地図で全部見る ›' },
  relmap: {
    mapCap: '地図には各役割ごとに近い{{n}}人を描いています — 残り{{r}}人は下の一覧に。',
    joinedTitle: '新しく入りました', joinedBody: '{{n}}人が地図に加わりました。',
    invite: '招待リンクを送る', inviting: 'リンクを作成中…',
    inviteNote: '友だちがリンクを開いて生年月日を入れると、あなたの地図に加わります。リンクは7日で閉じます。',
    shareMsg: '私の関係地図に席をひとつどう？ 生年月日だけでいいよ',
    needLoginTitle: 'ログインが必要です',
    needLoginBody: '友だちが入力した情報はあなたのアカウントに届くため、招待リンクはログイン後に作成できます。',
    title: '関係地図', me: '私', count: '{{n}}人', hint: '近いほど相性の良い人',
    tapHint: '点を押すと、その人とあなたの相性が開きます。',
    list: '合う順', summary: 'あなたの地図はこんな形です',
    emptyOthers: 'まだ自分ひとりです。家族や友人の生年月日を加えると、その人が自分にとってどんな質の人かが地図に浮かびます。',
    emptyMe: 'まず自分の命式を登録してください。関係を見る基準ができます。',
    addFriend: '人を追加', addMe: '自分の命式を登録',
    giving: '自分が注ぐ側の多い構成です。世話のしがいはありますが、受け取る場所もひとつは要ります。',
    taking: '満たしてくれる人が多い構成です。受け取った分を流す先を作ると、気が滞りません。',
    balanced: '与える気と受け取る気が均等に巡る構成です。どちらにも偏らないので、関係で消耗しにくいでしょう。',
    lacking: 'あなたの命式には{{el}}の気がありません——その気を持つ人が特に貴重です。',
    adjusted: '生まれた日は{{from}}ですが、命式全体に{{to}}の気が偏っているため、そちらで見ています。',
    caution: '気をつけたいこと', advice: 'こう付き合うと良いです',
    more: '地図をもっと埋めるには',
    moreBody: '人が増えるほど関係の質がはっきりします。まだ入れていない人がいれば、生年月日だけですぐ位置が決まります。',
  },
  lang: { title: '言語', pick: '言語を選ぶ', auto: '自動', autoNote: '端末の言語 · 今は {{l}}', uiEnglish: '画面の文字は English', hint: '画面の文字と鑑定文をまとめて切り替えます。' },
  splash: { tagline: '五つの気がつながり\n今日の私を読む' },
  mycard: { axisIlju: '日柱', axisPersona: '性格タイプ', axisMbti: 'MBTI', axisEgen: 'エゲン・テト', axisBok: '生まれ持った福', teto: 'テト', egen: 'エゲン', both: '半々', tetoScore: 'テト {{n}}点', title: '私のカード', lead: 'タイプは入口です。一枠を押すと、その軸を計算した本文へ入ります。', more: '詳しく ›', noChart: '先に命式を登録してください。', register: '命式を登録', foot: '同じタイプでも大運・強弱が違えば本文は変わります。タイプは入口、文章はあなたのものです。' },
  typematch: { tagStemHap: '天干の合', tagSaeng: '気の相生', tagBrHap: '地支の合', tagSamhap: '三合', tagChung: '日支の沖', title: 'タイプ対タイプ', lead: '相手が日柱の二文字を言ってくれれば十分です。生年月日がなくても照らせます。', me: '自分', pick: '相手の日柱を選ぶ', none: '二文字の間に合・沖がかかりません。良し悪しではなく、この軸では特別な引きも衝突も出ないという意味です。', limit: 'これは日柱の二文字だけを見たものです。生まれた時間・月まで見ればずっと正確になります。', goCompat: '生年月日で正確な相性を見る', noChart: '先に自分の命式を登録してください。' },
  // 만세력 화면 — ★명리 **용어는 한자 그대로**, 설명만 그 언어로(Boss 2026-08-27)
  ms: {
    lunar: '旧暦',
    timeUnknown: '時刻不明',
    approx: '推定',
    placeUnknown: '出生地不明',
    tabNatal: '原局・運勢',
    tabElem: '五行・强弱',
    tabIlju: '日柱論',
    tabZiwei: '紫微斗数',
    ageN: '{{n}}歳',
    ageFull: '満{{n}}歳',
    monthN: '{{n}}月',
    samhyeong: '三刑',
    three: '3字',
    tierHi: '強',
    tierMid: '中',
    tierLo: '弱',
    showHanja: '漢 漢字',
    showHangeul: '가 ハングル',
    brief: '簡略',
    detail: '詳細',
    byPillar: '柱ごと',
    selectAll: 'すべて選択',
    unselectAll: 'すべて解除',
    coreGyeok: '中心の格',
    repElem: '代表の五行',
    repTengod: '代表の十星(格)',
    gangyakAxis: '强弱の軸',
    allyPower: '味方の勢い',
    strengthMore: '{{a}}・{{b}}をくわしく ›',
    problemFix: '課題と対処',
    pickPoint: '時点',
    strongest: '最強',
    todayLuck: '今日の運を見る',
    viewCols: '横に見る',
    viewNest: '入れ子図',
    luckWord: '運',
    countSuffix: '件',
    collapse: '▲ 閉じる',
    byStrength: '作用の強い順 — 沖・合 強 / 刑・剋 中 / 害・破 弱',
    daeunsu: '大運数',
    tapDaeun: '(タップでその歳運を開く)',
    tapReflect: '(タップで上の命式に反映)',
    tapReflectDay: '(タップで日運を反映)',
    dayCal: '{{y}}年{{m}}月の日辰カレンダー',
    dow: '日,月,火,水,木,金,土',
    today: '今日',
    myChart: '自分の命式',
    ziweiIntro: '四柱とは別の体系です。生まれた時刻で十二の宮(命宮・財帛・官禄・夫妻など)に星を配し、人生の各領域に入る気を見ます。四柱を補う形で交差参照します。',
    bureau: '局',
    ziweiFlow: '紫微斗数の流れ',
    ziweiFlowSub: '大限(10年)・その時期の天干が起こす四化',
    noteTendency: '* 傾向の目安です。正確な読みは原局全体で見ます。',
    eumYangSkew: '陰陽の偏り',
    strongLead: 'ここまで強いと',
    useIt: '活かし方',
    balanced: '偏りが大きくなく、無難です。',
    hannan: '寒暖(調候)',
    joseup: '燥湿',
    warm: '暖',
    cold: '寒',
    wet: '湿',
    dry: '燥',
    elemSkew: '五行の偏り',
    strongEl: '{{el}}が強い',
    noteSkew: '* 偏りの目安です(対処=開運)。正確な読みは原局全体で見ます。', mine: '自分の型', pro: '強み', con: '注意', dir: '方向 (用神)', tabNatalDesc: '八字(年・月・日・時の八文字)と、その中に隠れた気(支藏干)、文字どうしの合・沖・刑・害・破、神殺、そして大運・歳運・月運・日運の流れまで、ひとつの画面で見られます。', tabElemDesc: '自分の文字が木・火・土・金・水のどれに偏っているか、それが自分にとってどんな役割(十星)か、そして日干が強いか弱いか、何で釣り合いを取ればよいかを一緒に見ます。', tabIljuDesc: '生まれた日の干支(日柱)から見る気質です。日干は自分自身、日支は自分が立つ場所であり配偶者宮でもあるため、性格・恋愛・仕事の質がここによく表れます。六十干支の全体は日柱の画面で見られます。', tabZiweiDesc: '四柱とは別の体系です。生まれた時刻で十二の宮(命宮・財帛・官禄・夫妻など)に星を配し、人生の各領域にどんな気が入るかを見ます。四柱を補う形で交差参照します(時刻が正確でないと精度が落ちます)。', strongTitle: '身強(しんきょう)', weakTitle: '身弱(しんじゃく)', strongWhat: '日干の根が深く、比劫(仲間)と印星(支え)が受けている構えです。自分の考えがはっきりしていて、推進力と独立心があります。', strongGood: '主導的で危機に強く、自分の力で押し切る突破力とリーダーシップがあります。', strongCare: '力が過ぎると独善・頑固に流れ、周りと折り合いをつけにくくなることがあります。', strongKey: '食傷(表現)・財星(財)・官星(責任)へ力を逃がして釣り合いを取るのが鍵です。仕事・財・人間関係・責任に力を使うとき、成果が大きくなります。', weakWhat: '日干が弱く、食傷・財星・官星へ気を出していく構えです。柔軟で繊細、環境によく合わせます。', weakGood: '協調・調整が得意で適応力があり、周りの助けや流れを生かすのが上手です。', weakCare: '力が抜けすぎると依存的・優柔不断になり、自信が弱くなることがあります。', weakKey: '印星(学び・休息)と比劫(味方)で補うのが鍵です。学び・休み・自分の側にいる人を通して力を満たすとき安定します。', expand: '▼ 開く', skewLead: 'こう偏ると', remedy: '対処(開運)', tgSkew: '気(十星)の偏り' },
  person: { iShare: 'この友だちに自分の命式を見せる', iShareOn: '今この友だちはあなたの命式を見られます。', iShareOff: '今は見えていません。', message: 'メッセージを送る', me: '私の命式', mine: '私の命式', friend: '友だち', tabChart: '命式', tabCompat: '相性', tabTalk: '会話', notShared: 'まだ命式を公開していません。', gone: '友だち一覧にいない人です。', noMe: 'まず自分の命式を登録してください。', noChart: '見られる命式がありません。', noCompat: 'まだ相性を出せません。', needMine: '自分の命式を登録すると、この人との相性が見られます。', openManse: '万年暦で詳しく見る', openCompat: '相性を詳しく見る', talkLead: 'この人を会話に呼ぶと、相談員がこの命式も一緒に見て答えます。', mention: '会話で @{{name}} を呼ぶ' },
  common: { close: '閉じる', send: '送信', save: '保存',
    'later': '後で',        // 나중에 — 유도 알림의 취소 쪽(대화 운 부족 등)
    'more': '詳しく',
    retryLaterNoCharge: 'しばらくしてからもう一度お試しください。woon は消費されていません。',
    'add': '追加',
    'confirm': '確認',
    'delete': '削除',
    'edit': '編集',
    'retry': '再試行',
    'retryLater': 'しばらくしてからもう一度お試しください。',
    'tapToClose': 'タップして閉じる',
    back: '← 戻る', login: 'ログイン', signup: '新規登録', logout: 'ログアウト', loggingOut: 'ログアウト中…',
    comingSoon: '準備中です。', error: 'エラー', loginOptional: 'ログイン / 新規登録（有料·保存機能用 — 任意）',
    cancel: 'キャンセル', none: 'なし',
    llmBusy: '今は鑑定の生成が一時的に難しいようです。しばらくしてからもう一度お試しください。',
    llmMaking: '同じ鑑定をただいま作成中です。少し経ってからご確認ください。',
    genFailed: '鑑定を読み込めませんでした。しばらくしてからもう一度お試しください。',
  },
  auth: {
    privacyTalk: '会話は続きから読めるように保存されます。AIの学習には使わず、他の人は見られません。いつでも削除できます。',
    'login': 'ログイン',
    signin: 'ログイン', signupTitle: '新規登録', email: 'メール', password: 'パスワード（6文字以上）',
    toSignup: 'アカウントがありませんか？  新規登録', toSignin: 'すでにアカウントをお持ちですか？  ログイン',
    needInput: 'メールとパスワードを入力してください。', signupDone: '確認メールを送信しました。認証後にログインしてください。',
    or: 'または', google: 'Googleで続ける', apple: 'Appleで続ける', naver: 'Naverで続ける', processing: 'ログイン処理中…',
    subtitle: '四柱推命と紫微斗数を組み合わせた解釈', note: 'ログインは任意です。端末を変えても命式と利用券を引き継ぐには連携してください。',
    failedTitle: 'ログインに失敗しました',
  },
  register: {
    solarAdjust: '居住地補正 {{sign}}{{min}}分 → 実際 {{time}}({{siji}}の刻)',
    dstApplied: 'サマータイム適用',
    tzBasis: '基準', needDate: '生年月日8桁を入力してください。', next: '次へ', prev: '戻る', step0Desc: '正確な分析のために情報を入力してください。', step1Desc: '生年月日を入力してください。旧暦の場合は旧暦を選んでください。', step2Desc: '生まれた時間がわかるとより正確です。わからなければ飛ばして大丈夫です。', step3Desc: '生まれた場所を選ぶと、その地域の実際の太陽時に合わせます。', stepTitle: '四柱情報の入力',
    placeHintNone: '地域ごとに日の出が違うため、時柱が変わることがあります。選ばない場合は韓国の平均で計算します。',
    placeHintSet: 'この地域の真太陽時で生まれた時刻を合わせます。',
    'pickCategory': 'カテゴリーを選ぶ',
    'catDelHint': 'カテゴリーを削除すると、その命式は「その他」に移動します。「その他」は削除できません。',
    'catDeleteTitle': 'カテゴリー削除',
    'editDone': '完了',
    'exactTime': '正確な時刻がわかります（出生地の経度で真太陽時に補正）',
    'hour24': '時（0〜23）', 'hourHint': '{{h}}時 = {{hint}}',
    'invalidDateTitle': '生年月日をご確認ください',
    'minute': '分',
    'newCategory': '新しいカテゴリー',
    'newCategoryPh': '新しいカテゴリー名',
    'orSijin': 'または時辰（2時間）だけわかるとき',
    'placeSearchBlocked': '地域検索が一時的に制限されています。30秒ほど後にもう一度お試しください。',
    'placeSearchFailed': '地域検索を読み込めませんでした。接続をご確認ください。',
    name: '名前·愛称', namePh: '例：キムOO / 本人',
    birthDate: '生年月日 (YYYY-MM-DD)', birthDatePh: '1990-03-15',
    birthTime: '出生時刻 (HH:mm、不明なら空欄)', birthTimePh: '07:10',
    calendar: '新暦 / 旧暦', solar: '新暦', lunar: '旧暦', normalMonth: '平月', leapMonth: '閏月',
    sex: '性別', male: '男', female: '女',
    birthPlace: '出生地', birthPlacePh: 'タップして都市検索',
    relation: '関係', submit: '命式計算 · 登録',
    birthTimeSijin: '出生時刻（時辰）', timeUnknown: '不明', selfLabel: '本人', makeRep: 'メイン命式に設定',
    relationCustom: '直接入力', relationCustomPh: '関係を入力（例：上司）',
    ctxTitle: 'あなたの状況（任意）', ctxDesc: '入力するとこの命式の鑑定がより正確になります。空欄でも構いません。',
    ctxSit: '今の状況は？', ctxSitDesc: '選ぶとその状況の言葉で鑑定されます',
    sitStudy: '受験・学生', sitWork: '会社員', sitBiz: '事業・自営', sitFree: 'フリーランス',
    sitHome: '主婦・育児', sitSeek: '求職中', sitRetire: '退職', sitEtc: 'その他',
    ctxJob: '職業', ctxJobPh: '例：デザイナー／自営業／学生／会社員',
    ctxRel: '交際状況', ctxRelSingle: '未婚', ctxRelDating: '交際中', ctxRelMarried: '既婚', ctxRelOther: 'その他',
    ctxConcern: '最近の関心·悩み', ctxConcernPh: '例：転職、新しい縁、健康管理',
    ctxNote: 'メモ', ctxNotePh: '鑑定に反映してほしいことを自由に',
    selfExistsTitle: '本人の命式が既にあります', selfExistsMsg: '本人の命式は1つだけです。今の本人の命式を「その他」に移し、この命式を本人として登録しますか？', selfReplace: '本人にする',
    birthPlaceSearch: '都市·地域を検索', birthPlaceSearchPh: '例：ソウル、東京', useAsIs: "'{{q}}' をそのまま使用",
    limitTitle: '無料登録の上限', limitMsg: '無料プランは命式を{{limit}}件まで登録できます。\n広告を見れば1件追加、プロにアップグレードすれば無制限です。',
    upgrade: 'プロにアップグレード', usage: '命式 {{count}}/{{limit}}',
    watchAdAdd: '広告を見て1件追加', adNotFinished: '広告を最後まで見ると1件追加されます。',
  },
  myeongsik: {
    palja: '八字', dayMaster: '日干', strength: '身強弱指標', pattern: '格局', patternRevealed: '顕現', patternHidden: '潜伏',
    stages: '十二運星', interactions: '合冲刑害', sinsal: '神殺·空亡', gongmang: '空亡',
    noHit: '原局hitなし', ziwei: '紫微斗数', lifePalace: '命宮',
    readingBtn: '領域別鑑定を見る →', noChart: 'チャート情報がありません。',
    root: '通根', hidden: '蔵干',
    luck: '大運·歳運', daewoon: '大運', sewoon: '歳運', elements: '五行分布',
    합: '合', 충: '冲', 형: '刑', 해: '害', 파: '破', 극: '剋',
    sinsalHint: '基準の地支が原局にあれば✓(柱)、なければ大運·歳運で作動', ssLuck: '運で', dayPillar: '日柱',
    sinsalDetail: '神殺·空亡をくわしく →',
  },
  reading: {
    langChipA11y: '鑑定の言語を変える', langSheetHint: '画面の文字はそのまま、鑑定の本文だけ変わります。すでにある鑑定は残り、もう一度お支払いいただくことはありません。',
    'lockedNote': '上のボタンで開くとすべてご覧いただけます。',
    'lockedTitle': 'この命式の解説は運で開きます',
    'pastYearBadge': 'この解説は{{y}}年の歳運を基準に書かれています — 再生成すると今年の流れが反映されます。',
    'recommend': 'こんなコンテンツもおすすめです',
    'renew': '🔄 最新の通変で再生成',
    'sajuTitle': '四柱推命の解説',
    title: '全領域鑑定 · プレミアム', sub: '16領域すべてを一度に深く精密な通変。（命式は無料）',
    runAll: '全体を見る（{{count}}件）', progress: '‘{{current}}’ 鑑定中… ({{done}}/{{total}})', generating: '鑑定をていねいに描いています…', saveFail: 'チャートの保存に失敗しました。', refreshStale: '最新の解釈に更新', refreshDeniedTitle: '更新の上限', refreshDenied: 'この鑑定は最大{{cap}}回まで更新できます。',
    ziweiTitle: '紫微斗数 十二宮 · プレミアム', ziweiSub: '十二宮を一度に統合通変。（命盤は無料）',
    timelineTitle: '人生タイムライン · プレミアム', timelineSub: '10〜100歳を10年ごとに、各時期の流れを読み解きます。',
    bannerPremium: '購読中 — 無制限通変', bannerTrial: '🎁 初回鑑定が無料！',
    bannerGated: '領域選択で広告または購読により通変が開きます',
    base: '本質', past: 'これまで', overlay: '現在', future: 'これから', remedy: '処方',
    premiumAlert: 'プレミアム通変', premiumAlertMsg: '{{price}}決済で深い通変を見られます。',
    payPerUse: '{{price}} 決済', bannerPerUse: '✨ 最初の分野のみプレビューです — 全体は{{price}}', bannerUnlocked: '✨ 購入済み — 全体の鑑定を生成できます',
    askTitle: 'もっと質問する', askPh: 'この鑑定についてもっと聞いてみましょう',
    askSend: '質問', askFree: '無料質問あと{{n}}回', askPaid: '無料質問を使い切りました — 追加は1回{{price}}',
    askPremiumTitle: 'プレミアム限定', askPremiumMsg: 'プレミアムなら領域ごとに2回まで無料で追加質問できます。',
    askPremiumCta: 'プレミアムでもっと聞く', askPayTitle: '追加質問', askPayMsg: '無料質問を使い切りました。1回{{price}}で追加しますか？',
    askPayBtn: '{{price}} 決済', payPending: '準備中',
  },
  compat: {
    owned: '✓ 保有',
    'stillMaking': 'もうすぐです — 届き次第すぐお見せします。',
    'comeBackLater': 'まだ作成中です。少ししてこの画面をもう一度開くと結果が表示されます。',
    'genConfirm': '作成',
    'genCta': 'この関係の解説を作る',
    'genTitle': '解説を作る',
    'otherPick': '相手を選ぶ · 新しい相手を登録',
    'scoreHarmony': '調和',
    'scoreTension': '緊張',
    'step1': '① 誰と見ますか？',
    'step2': '② どんな間柄ですか？',
    'step3year': '③ いつで見ますか？',
    'wizPickShort': 'タップして選択',
    'yearPick': '年を選択',
    otherInfo: '相手情報（同意が必要）', otherDatePh: '相手の生年月日 1992-07-03',
    otherTimePh: '出生時刻（不明なら空欄）',
    dayRelation: '日干関係', harmonyTension: '調和 {{h}} · 緊張 {{t}}',
    usefulGod: '用神相補', crossInter: '交差合冲',
    needChart: '相性を見るにはまず命式を登録してください。', registerMyChart: '命式を登録',
    mySlot: '私の命式', otherSlot: '相手の命式', change: '変更', orDirect: 'または相手を直接入力',
    registerOther: '相手の命式を登録', registerOtherTitle: '相手の命式を登録', registerOtherSubmit: 'この命式で相性を見る',
    yearAll: '全体',
    analyze: '相性を見る', generating: 'お二人の相性を読み解き中…', noReading: '生成できませんでした。もう一度お試しください。',
    secBase: '二人の基本的な噛み合い', secDynamic: '合うところ · ぶつかるところ', secAdvice: 'こう育てましょう',
    detailToggle: '文字の作用をくわしく',
    premiumTitle: 'プレミアム限定', premiumMsg: '相性鑑定はプレミアムで5名まで無料です。',
    payTitle: '相性を追加', payMsg: '無料5名を使い切りました。この方との相性を1回₩2,500で見ますか？', payBtn: '₩2,500 決済',
    rel: { friend: '知人·友達', family: '家族', crush: '片思い·脈あり', love: '恋愛', marriage: '結婚', coworker: '職場の同僚', senior: '目上·メンター', business: '共同事業', staff: '部下·社員', invest: '投資パートナー' },
  },
  category: {
    성격내면: '性格·内面', 취업운: '就職運', 직장운: '職場運', 사업운: '事業運',
    금전소득운: '金銭·収入', 투자편재운: '投資運', 재물손재: '財物·損失', 연애운: '恋愛運',
    결혼배우자운: '結婚·配偶者', 대인사회성: '対人関係', 부모운: '両親運', 형제운: '兄弟運',
    자식운: '子女運', 건강: '健康', 학업자기계발: '学業·自己啓発', 이동환경: '移動·環境',
  },
  today: { hourTitle: '時間帯の流れ', hourSub: '同じ一日でも時間ごとに質が違います', hourBest: '最も進みやすい時 · {{ko}} {{range}}', hourCare: '一拍おくとよい時 · {{ko}} {{range}}', hourNow: '今', hourFoot: '今日の日柱と命式から計算した質であり、良し悪しの判定ではありません。低く出た時間は急がないほうがよい、という意味で見てください。', 
    'areaSoon': 'この分野の解説は次の運勢から追加されます。',
    today: '今日', tomorrow: '明日', energyTomorrow: '明日の気運', weekdaysShort: '日,月,火,水,木,金,土',
    dayPillar: '今日の気運', note: '毎日0時に変わる今日の流れを、あなたの命式と合わせて読み解きます — より深い鑑定はプレミアムで。',
    areas: '分野別の運勢', area_general: '総合', area_work: '仕事', area_money: '財運', area_invest: '投資', area_love: '恋愛', area_health: '健康',
    needChart: '命式を登録すると、今日の流れをあなたに合わせて分野別に読み解きます。', registerBtn: '命式を登録',
    more: '分野別にくわしく見る →',
    genFail: '占い結果の作成に失敗しました。しばらくしてからもう一度お試しください。', title: '今日の運勢', heroSub: '今日一日の流れを見てみましょう', generating: '今日の流れを読み解いています…', gateTitle: '今日の運勢を見る', gateDesc: 'あなたの生まれ持った性質に、今の大きな流れ・今年・今日の雰囲気を重ねて、今日起こりそうなことと対処法をお伝えします。', seePremium: '今日の運勢を見る', seeAd: '広告を見て無料で見る', adFail: '広告を読み込めませんでした。しばらくして再度お試しいただくか、プレミアムで広告なしでご覧いただけます。',
  },
  settings: { readingLanguage: '鑑定の言語', readingLanguageHint: '画面の文字はそのままで、鑑定の本文だけ選んだ言語で読めます。すでに見た鑑定はそのまま残ります。', readingLangAuto: 'アプリの言語に合わせる', myRecords: '私の記録', community: 'コミュニティ', nickPh: 'ニックネーム (2~12字、空欄=自動匿名)', nickBad: '使用できない単語があります。', nickLen: 'ニックネームは2~12字です。', nickDone: '保存済み', showIlju: '日柱バッジを表示', iljuHint: '投稿の横に生まれた日の二文字だけ表示されます。生年月日は分かりません。',
    privacyHead: 'プライバシー',
    'accent': 'テーマの色',
    'accentAuto': '自動（日干）',
    'accentDesc': '代表命式の日干の五行に合わせて画面の色が変わります。自分で選ぶこともできます。',
    'accentGold': 'ゴールド',
    'coins': '運',
    'loadingOff': 'オフ',
    'loadingScreen': 'ローディング画面',
    'loadingVideoOff': 'アプリ名のみ',
    'loadingVideoOn': 'トラの映像',
    'loginBenefit': 'ログインすると購入したコンテンツが他の端末や再インストール後も引き継がれます（任意）',
    'notif': '通知',
    'notifDaily': '毎日の運勢通知',
    'notifTalk': '相談家からのお知らせ',
    'notifTalkOn': 'オン · 大きな流れが変わる時にノ先生が知らせます',
    'notifTalkOff': 'オフ · タップでオン',
    'notifDenied': 'オフ · タップして端末の設定でオンに',
    'notifDeniedMsg': '通知を受け取るには、端末の設定でニウンネウンの通知をオンにしてください。',
    'notifNA': 'この端末では利用できません',
    'notifOff': 'オフ · タップしてオンに',
    'notifOn': 'オン · 毎日午前9時',
    'notifOnMsg': '通知はオンです。オフにするには端末の設定から変更できます。',
    'notifUnavailable': 'この端末では通知を利用できません。',
    'openSettings': '設定を開く',
    'readingVideo': '解説のローディング映像',
    'readingVideoOff': 'シンプル（映像なし）',
    'readingVideoOn': 'テーマ映像',
    'restore': '購入を復元',
    'restoreDone': '購入が復元されました。',
    'restoreFail': '購入の復元に失敗しました。しばらくしてからもう一度お試しください。',
    'restoreNone': '復元する購入履歴がありません。',
    'restorePending': '購入を確認しました。サーバーへの反映に少し時間がかかる場合があります — しばらくしてからご確認ください。',
    'restoring': '復元中…',
    'themeRestart': 'アプリを再起動すると適用されます。',
    homeOrder: 'ホームの並び順', homeOrderNote: 'ホーム画面に表示される順番です。上下に移動できます。', homeOrderReset: '既定の順番に戻す',
    account: 'アカウント', loginCta: 'ログイン / 新規登録', premium: 'プレミアム',
    premiumActive: '✓ プレミアム適用中', premiumBuy: '買い切りプレミアム', premiumDesc: '今後追加分も含む全プレミアムコンテンツが無料 · 広告なし · 一度の購入で永久 · 有料コンテンツの再鑑定30%割引(一般10%)', 
    premiumOkTitle: 'プレミアム', premiumOk: 'プレミアムが適用されました。', premiumTitle: 'プレミアム',
    deleteAccount: 'アカウント削除',
    delTitle: 'アカウント削除', delMsg: 'アカウントと全データ（命式・鑑定・パス）が永久に削除されます。元に戻せません。', delConfirm: '続ける',
    delTitle2: '本当に削除しますか？', delMsg2: 'この操作は元に戻せません。', delFinal: '完全に削除',
    delFail: '削除に失敗しました。後ほど再試行してください。', delDoneTitle: '削除完了', delDone: 'アカウントとデータを削除しました。', deleting: 'アカウントを削除中…',
    fontSize: '文字サイズ', size_sm: '小', size_md: '中', size_lg: '大', size_xl: '特大',
    appInfo: 'アプリ情報', version: 'バージョン', terms: '利用規約', privacy: 'プライバシーポリシー', license: 'オープンソースライセンス', bugReport: 'バグ報告 · お問い合わせ', bugReportFail: 'メールアプリを開けませんでした。下記アドレスにお送りください。',
    preview: 'プレビュー — 通変はこのサイズで表示されます。鑑定·今日の運勢·相性の本文に反映されます。',
    language: '言語', 
    coupon: 'クーポン入力', couponPh: 'クーポンコード入力', couponRedeem: '登録', couponHave: '保有利用券',
    couponOkTitle: '登録完了', couponOk: '無料利用券が適用されました。その機能を無料でご利用いただけます。',
    couponFailTitle: '登録失敗',
    couponErr_invalid: '無効なコードです。', couponErr_expired: '期限切れのクーポンです。',
    couponErr_exhausted: '利用上限に達したクーポンです。', couponErr_already: '使用済みのクーポンです。', couponErr_auth: 'ログインが必要です。',
  },
  timeline: {
    'readThis': 'この時期の解説を見る',
    decades: '10年ごと', years: '年ごと', pickDecade: '時期を選ぶ', pickYear: '年を選ぶ', thisYear: '今年', now: '現在',
    catGeneral: '総合', catWork: '仕事', catMoney: '金運', catLove: '恋愛', catHealth: '健康',
    catSocial: '人間関係', catGrowth: '学び', catMove: '移動', months: '月別の流れ', monthUnit: '月',
    generating: 'この時期を読み解き中…', tapToRead: '時期や年を選ぶと、その流れを読み解きます。',
    premiumTitle: 'プレミアム限定', premiumMsg: '人生タイムラインはプレミアムで時期ごとに読み解きます。',
    lockedTitle: 'ロック中の時期', lockedSub: '現在の大運と今年は無料、ほかの時期はパスでカテゴリ別に詳しく読み解きます。',
    unlock: 'この時期を開く', unlockTitle: 'この時期を開く',
    unlockMsg: 'タイムラインパスでこの時期をカテゴリ別に詳しく読み解きます。(パスは設定のクーポンで取得・都度課金は準備中)',
    buy5: '歳運5回 {{price}}', buy10: 'この大運まるごと(10年) {{price}}', // 歳運(세운) バンドル — ロックカードの購入ボタン(daniel 07-23)
    freeBadge: '無料', usedCredit: 'パスで開きました',
  },
  premiumHub: {
    sub: '何を見ますか?',
    sajuReading: '原局の鑑定', sajuReadingDesc: '性格·金運·恋愛·仕事など16領域の深い通変',
    ziweiReading: '命盤の鑑定', ziweiReadingDesc: '十二宮 + 運限(大限)·四化で見る時期ごとの流れ',
  },
  pet: {
    title: 'うちの子', sub: 'うちの子の生まれもった結を軽く見てみましょう。',
    add: '新しい子', name: '名前', namePh: '例: コン', typeLabel: 'どんな子ですか?',
    birth: '生年月日 (YYYY-MM-DD)', time: '生まれた時刻', timeOptional: '— 不明でもOK',
    timePick: '時辰を選ぶ（子の刻·丑の刻…）', timeUnknownChk: '時刻不明',
    timeHint: '時刻が不明なら大きな結だけ見ます(時間帯の鑑定は省きます)。',
    save: '特徴を見る', empty: 'まだ登録された子がいません。',
    delete: '命式を削除', deleteTitle: '削除', deleteMsg: 'この命式を削除しますか?',
    invalidTitle: 'ご確認ください', invalidDate: '生年月日を YYYY-MM-DD で入力してください。',
    type: { dog: '犬', cat: '猫', rabbit: 'うさぎ', hamster: 'ハムスター', bird: '鳥', fish: '魚', reptile: '爬虫類', other: 'その他' },
  },
  love: {
    'genDelayed': '解説の生成が遅れています。しばらくしてからもう一度お試しください。',
    'needZiwei': 'この命式では愛情の流れを読めません。紫微との交差分析には正確な出生時刻が必要です。',
    title: '私の恋愛の流れ', sub: '四柱推命と紫微斗数を両方クロスして、理想のタイプから実際に出会う人まで詳しく読み解きます。',
    generating: '二つの命盤をクロスして恋愛の結を読み解き中…',
    gateDesc: '理想のタイプ、実際に出会う人の第一印象·性格·行動·習慣、出会い方と時期まで — 四柱推命と紫微斗数のクロスで詳細に。',
    see: '{{price}}で詳しく見る', cacheNote: '一度見ればずっと保存されます（再課金なし）。',
    gateTitle: '私の恋愛の流れ', gateMsg: 'まだパスがありません。設定でクーポンを登録するか、決済機能は近日公開です。({{price}})',
    idealType: '私の理想のタイプ', appearance: '出会う人の第一印象·イメージ', personality: 'その人の性格·内面',
    behavior: 'その人の行動·話し方·習慣', ageGap: 'その人との年の差', howWeMeet: 'どこで·どう出会うか', elementMatch: '相性の良い気の順位', dynamic: '二人の惹かれ合いと相性', iLoveMore: '私がより好きな恋愛', theyLoveMore: '相手がより好きな恋愛',
    timing: '恋が深まる時期', cautionPartner: '特に気をつけたい相手', caution: '気をつけること', advice: '良い縁を育てる方法', needPay: 'woon が必要です。もう一度お試しください。',
  },
  month: {
    'aiDesc': '生まれ持った四柱に、今の大きな流れ・今年・今月の気を重ね、今月起こりうることと対処までAIがより深く読み解きます。',
    'aiLogin': 'ログインするとAIが今月の流れをより深く読み解きます。',
    'aiTitle': 'AI精密解説',
    'thisMonth': '今月', title: '今月の運勢', monthPillar: '今月の気', flowTitle: '今月の流れ（上旬·中旬·下旬）', note: '今月の大きな流れです。具体的な日は今日の運勢で。', heroSub: '今月のめぐりで読む流れ', generating: '今月の流れを読み解いています…', gateTitle: '今月の運勢を見る', gateDesc: '生まれ持った気質に、いまの大きな流れ・今年・今月のめぐりを重ねて、今月起こりそうなことと対処の仕方をお伝えします。', seePremium: '今月の運勢を見る' },
  nav: { back: '戻る', admin: '管理者', costs: 'コスト・収益', home: '友だち', chats: 'チャット', fortune: '運勢', readings: '鑑定', my: 'マイ',
         contents: '占い', community: 'コミュニティ', coach: 'ガイド', market: 'マーケット' },
  profile: { title: 'マイプロフィール', namePh: '名前', pick: '写真を変更', clear: '写真を削除',
    pickCover: '背景を変更',
    clearCover: '背景を削除',
    coverTooLarge: '4MB以下の画像のみ',
    saved: '保存しました', saveFail: '保存できませんでした', tooLarge: '2MB以下の写真のみアップロードできます',
    hint: '空欄にすると命式の名前が表示されます。', mobileSoon: '写真の変更は次のアップデートで対応します。今はウェブで変更できます。' },
  fcompat: { gone: '友だちリストにいません。',
    notShared: '{{name}}さんはまだ命式を公開していません。\n相手が「友だちに命式を見せる」をオンにすると見られます。',
    noMe: '先に自分の命式を登録すると相性が見られます。', chart: '{{name}}さんの命式' },
  friends: { title: '友だち', myCode: '私の友だちコード', codeHint: 'このコードを教えると相手が追加できます。',
    addByCode: 'コードで追加', codePh: '友だちコード6桁', add: '申請', pending: '保留中', mates: '友だち',
    empty: 'まだ友だちがいません。\n上のコードで追加してみましょう。', noName: '名前なし',
    sent: '申請を送りました。相手が承認すると友だちになります。', bothSent: 'お互いに申請しました。友だちになりました！',
    already: 'すでに申請済みか友だちです。', self: '自分のコードです。', notfound: 'そのコードは見つかりませんでした。',
    needLogin: 'ログインが必要です。', needLoginBody: 'ログインすると友だちを追加できます。', failed: '今は処理できませんでした。',
    accept: '承認', waiting: '承認待ち', gotRequest: '友だち申請が届きました',
    canSee: '命式・相性を見る ›', notShared: 'まだ命式を公開していません',
    consentTitle: '友だちに命式を見せる',
    consentBody: 'オンにすると友だちがあなたの四柱（八字）と相性を見られます。\n八字から生年月日を추定できるため、信頼できる人にだけ公開してください。\nいつでもオフにでき、오프にすると即座に非表示になります。',
    consentOn: '友だちに命式が見えます。', consentOff: '誰にも見えなくなりました。' },
  // ── オープンチャット ─────────────────────────────────────────────────────
  room: { alone: '自分だけの部屋', this: 'この会話',
    someone: '誰か', ph: 'メッセージを入力',
    aiCount: 'AI {{n}}人',
    gone: 'この部屋は存在しないか、入れません。',
    failSend: '送信できませんでした。少し後にもう一度お試しください。',
    slow: '返事が遅れています。少し後に再読み込みしてください。',
  },
  rooms: {
    title: 'オープンチャット', solo: '自分の会議室', open: 'オープンチャット',
    soloSub: '自分 + AI 複数', openSub: '複数人 + AI',
    phTitle: '部屋の名前（例：転職の悩み）', phTopic: '何について話しますか？（任意）',
    pick: '誰を呼びますか', cost: '一度発言するごとに最大{{n}}人が答えます。',
    making: '作成中…', public: '公開リストに載せる', make: '部屋を作る',
    mine: '自分の部屋', publicList: '参加できる部屋', aiN: 'AI {{n}}人',
    noPublic: 'まだ開いている部屋がありません。最初の部屋を作ってみましょう。',
  },
  time: { am: '午前', pm: '午後', },
  chats: { pin: '上に固定', unpin: '固定を解除', leave: '退出', leaveAsk: '「{{name}}」から退出しますか？会話も一緒に消えます。', now: 'たった今', minAgo: '{{n}}分前', hourAgo: '{{n}}時間前', yesterday: '昨日', dayAgo: '{{n}}日前',
    empty: 'まだ会話がありません。\n連絡先から友だちを選んでください。', needLogin: 'ログインすると会話がここに残ります。',
    noTitle: '会話を続けましょう', turns: '{{n}}ターン' },
  lookback: { title: '振り返り', sub2: '今日の一つを実行した日々です。', needLogin: 'ログインすると記録が保存され、ここで見返せます。', empty2: 'まだ記録がありません。今日の運勢の下の「今日の一つ」を実行してチェックしてみてください。', goToday: '今日の運勢を見る', summary: '評価した{{rated}}日のうち{{hit}}日を「当たった」とされました', streak: 'これまで{{n}}日、今日の一つを実行しました', myNote: '私の記録', missionDone: '✓ その日の一つを実行しました' },
  contents: {
    sub: '見たいテーマを選んでください',
    searchPlaceholder: '何が気になりますか？',
    searchResult: '検索結果 {{n}}件',
    searchEmpty: '見つかりませんでした。\n別の言葉でお試しください。',
  },
  todayEnergy: { kicker: '今日の気運', point: '点', more: '今日の運勢を詳しく' },
  persona120: {
    kicker: '私の性格タイプ', count: '120種のうち', more: '詳しく見る',
    title: '私の性格タイプ', sub: '日干10 × 月支12 = 120タイプのうち私は',
    empty: '命式を登録すると120タイプの中からあなたのタイプをお見せします。',
    axisStem: '私という素材', axisSeason: '私が置かれた季節', axisGyeok: '人生の重心',
  },
  market: {
    'emptyTopic': 'このテーマのコンテンツは準備中です。別のテーマをお選びください。',
    'hotSection': '🔥 人気',
    'open': '開く',
    'retentionNote': '購入した解説は購入日から1年間保管され、1年を過ぎると自動的に削除されます。その後もう一度見るには再購入が必要です。',
    'sectionIncluded': '✦ 運で開く',
    'sectionIncludedSub': '下の解説は運で一つずつ開けます。命式ごとに別々に開きます。',
    'sectionIndividual': '◆ 個別購入専用',
    'sectionIndividualSub': '下の項目は一つずつ個別に購入します。', intro: '適用する命式を選んでから、見たい鑑定をタップしてください。', applyTo: '適用する命式', openApply: '開く', noChart: '保存された命式がありません', have: '保有 {{n}}枚', owned: '保有', notOwned: '未保有', buy: '購入', note: '鑑定は命式ごとに保存されます。無料チケット（クーポン）は下で登録。', doneTitle: '購入完了', doneMsg: 'チケットが付与されました。', payPending: '決済準備中', buyFailTitle: '購入失敗' },
  dayPillar: {
    'fullChartNote': '※ 日柱論は「生まれた日（日柱）」だけで見る大きな傾向です。正確な解説は命式全体を合わせて見る必要があります。',
    's_match': '相性の良い日柱',
    's_stress': 'ストレス解消',
    title: '日柱論', sub: '生まれた日の干支（日柱）でみる、生まれもった気質です。',
    male: '男性', female: '女性', mine: '私の日柱', browseAll: '日柱60すべて', dayGroup: '日', tapHint: '日柱をタップすると詳しい解説が開きます。', mineList: '私の命式の日柱', noChart: '登録された命式がありません。先に命式を登録してください。',
    catAll: 'すべて', s_overview: '概要', s_personality: '性格', s_love: '恋愛·結婚', s_career: '仕事·財運', s_male: '男性', s_female: '女性', s_advice: 'アドバイス', s_live: '人生のコツ',
    disclaimer: '日柱論は生まれもった気質の一面にすぎません。正確な鑑定は日柱だけでなく、年·月·時の柱や合冲·用神まで、命式全体を合わせてみる必要があります。',
  },
  purchase: {
    syncTitle: '他の端末でも使うには',
    syncMsg: 'チャージした運はこの端末に保存されています。ログインすると端末を変えてもそのまま引き継げます。後から設定でいつでも可能です。',
    syncLater: 'あとで',
    loginTitle: 'ログインが必要です', loginMsg: '購入履歴をアカウントに保存すると、別の端末や再インストール後もそのまま使えます。ログインしますか？', loginCta: 'ログイン',
    restore: '購入を復元', restored: '購入を復元しました。', restoreNone: '復元する購入がありません。', restorePending: '購入を確認しました。反映まで少しかかることがあります — しばらくしてからもう一度ご確認ください。', preparing: '決済はまもなく公開されます。',
  },
  offline: { title: 'オフライン', msg: 'インターネットに接続されていません。保存済みは見られますが、新しい鑑定は接続後に可能です。', banner: 'オフライン — 保存済みのみ' },
  taro: { draw: 'カードを引く', reshuffle: '引き直す', reversed: '逆位置' },
  manse: {
    'catDeleteTitle': 'カテゴリー削除',
    'newCategoryPh': '新しいカテゴリー名',
    'catDelNote': 'カテゴリーを削除しても命式は消えません —「その他」に移動します。',
    'deleteTitle': '命式の削除',
    'viewManse': '万年暦を見る', 'changeCategory': 'カテゴリ変更', empty: '登録された命式がありません。', myChart: '命式', searchChart: '名前で探す' },
  sinsal: { 도화: '桃花', 역마: '駅馬', 화개: '華蓋', 천을귀인: '天乙貴人', 문창: '文昌', 양인: '羊刃', 홍염: '紅艶', 괴강: '魁罡', 백호: '白虎' },
  special: {
    'freeBasics2': 'まずは無料で — ビッグ3＋用神',
    'goMarketBtn': 'ストアへ ›',
    'ownedBoughtV2': '購入済み · いつでも見返せます',
    'ownedResumeSub': '生成が中断されました。追加のお支払いなしで続きを作成します',
    'ownedResumeTitle': 'お支払いは完了しています — 残るは解説だけです',
    'ownedTitle': 'すでに開いている解説です',
    'preparingPayment': '決済の準備中…',
    'priceMissing': '現在このコンテンツは開けません。しばらくしてからもう一度お試しください。',
    'resumeCta': '続けて解説を作る',
    'viewCta': '解説を見る',
    'working': '処理中…', previewHead: 'こんなことが分かります', unlock: 'woonで開く', couponHint: 'woonで開けます', couponOnly: 'woonで開けます。マーケットでチャージできます。', needPay: 'woon が必要です。もう一度お試しください。', needPayMsg: 'woon が必要です。今すぐ woon で開くか、マーケットでチャージできます。', buyNow: '今すぐ購入', goMarket: 'マーケットで見る', unlockCta: '購入して見る', unlockHint: 'woonで開けます' },
  roots: { title: '命式の根', sub: '表に出た自分·秘めた力·本当に揺るがない強さを読み解きます', generating: '根をたどっています…', summary: 'ひと目で', surface: '表に出た自分', depth: '秘めた力', strength: '本当の強さ', gap: '表と内の違い', advice: '伸ばし方' },
  image: { title: '映る自分', sub: '他人に映る第一印象·雰囲気·関係の中の自分', generating: '映る印象を描いています…', summary: 'ひと目で', firstImpression: '第一印象', persona: '表に出るイメージ', inRelationship: '関係の中の自分', charm: '魅力ポイント', gap: '表と内', advice: '見せ方' },
  mission: { title: '私の使命', sub: '生まれ持った器と才能で見る、何のために生まれたか', generating: '使命を読んでいます…', summary: 'ひと目で', coreNature: '生まれ持った本質', calling: '私の使命', strengths: '才能·武器', howToRealize: '実現の道', successWay: '成功の仕方', careers: '向く仕事·職務', environment: '輝く環境', lifeTheme: '人生のテーマ', crossInsight: '共に示す方向', advice: '使命の生き方' },
  talent: { title: '私の生まれ持った才能', sub: '何を持って生まれたか、好きな事·すべき事のどちらで輝くか、お金をどう扱うか', generating: '才能を読んでいます…', summary: 'ひと目で', talent: '生まれ持った才能', drive: '好きな事 vs すべき事', money: 'お金の扱い方', howToUse: '才能の活かし方', careers: '輝く分野', advice: 'ひとこと' },
  numerology: {
    'birthday': '誕生数 — 生まれ持った才能',
    'empty': '命式を登録すると生年月日から数秘術をお見せします。',
    'master': '✦ マスターナンバー（11・22・33）保有 — 潜在力が大きい分、扱いの難しい数です。',
    'note': '※ ピタゴラス数秘術（西洋の標準）で算出しています。名前による数（表現数・魂の数）は今後追加されます。',
    'personalYear': 'パーソナルイヤー — 今年の流れ', title: '数秘術', sub: '生年月日の数で見る人生の方向·才能·今年の流れ', generating: '数を読んでいます…', summary: 'ひと目で', lifePath: '生命数 — 人生の方向', innerYou: '内面と外見', talent: '才能', thisYear: '今年の流れ', advice: 'ひとこと' },
  astrology: {
    'numCore': '数で見た私',
    'numGroup': '🔢 数秘術 — 生年月日の数で見る私',
    'numLove': '数秘術で見る関係',
    'numYear': '今年の数',
    'sub2': '星座（太陽）・占星術（ネイタル）・数秘術（生命数）をまとめて — 三つの視点で深く読み解きます', title: '星座·占星術', sub: '星座(太陽星座)とネイタルチャートを一度に — 二つの視点で', generating: '星を読んでいます…', signGroup: '⭐ 星座 — 太陽星座で見る私', signSummary: '私の太陽星座', signTraits: '性格', signLove: '恋愛スタイル', signStrength: '強み', natalGroup: '🔭 占星術 — ネイタルで見る私', big3: '太陽·月·上昇', natalLove: '愛·欲求', natalWork: '仕事', strength: '強み', challenge: '課題', advice: 'ひとこと' },
  future10: { title: '10年後の私', sub: '大運·歳運で見る10年後の私と、今からの準備', gen: '10年後を描いています…', bigPicture: '10年後の全体像', career: 'キャリア·成果', wealth: '金運·資産の流れ', relation: '関係·家庭', health: '健康の管理軸', growth: '成長·内面の変化', prepare: '今から備えること' },
  child: { title: '子どもの縁', sub: '命式で見る子との縁·気質·親としての私', gen: '子との縁を見ています…', solo: '私だけ', couple: '配偶者と', pickSpouse: '配偶者を選択', coupleHint: '配偶者の命式を選ぶと、二人の命式で子との縁を一緒に見ます', needSpouse: '先に配偶者の命式を登録してください', bigPicture: '子との縁の全体像', childNature: '子どもの気質', asParent: '親としての私', coupleCross: '夫婦の子との縁', communication: 'コミュニケーション', timing: '時期の流れ', talent: '子どもの才能', health: '健康の管理軸', remedy: '開運·処方' },
  life: { genFail: '作成に失敗しました。少し時間をおいてからもう一度お試しください。', gateTitle: '人生グラフ', generating: '人生の流れを描いています…', yongsin: 'あなたに必要なエネルギー', focus: 'フォーカス', hint: '曲線上の点をタップすると、その時期を詳しく見られます。', peak: '最も輝く時期', caution: '足場を固めて気をつける時期', advice: '一生を通じての心がけ', gateDesc: '上の曲線の各時期がなぜそうなるのか、今どう動けばいいか、輝く時期の活かし方と厳しい時期の乗り越え方まで深くお伝えします。', pv1: '各時期がなぜ上下するのか', pv2: '今の時期に何をすればいいか', pv3: '最も輝く時期の活かし方', pv4: '気をつける時期の乗り越え方', pv5: '一生を通じて守る人生の方向', see: '人生グラフを見る', seePaid: '人生グラフを見る（₩3,900）' },
  newyear: {
    'remedy': '今年の開運法',
    'strategy': '今年の対応戦略',
    'thisYearSelf': '今年の私',
    'timing': '今年の良い時期',
    'yearNature': '今年はどんな年', title: '新年の運勢', generating: '今年一年を読み解いています…', heroSub: '今年一年の大きな流れをひと目で', keyword: '今年のキーワード', lucky: '今年のラッキーポイント', halves: '上半期・下半期', months: '月ごとのカレンダー', samjaeAdvice: '今年とくに気をつけたいこと', resolution: '今年はこんなふうに', gateDesc: '今年のキーワードから分野ごとの運勢、12か月のカレンダー、新年の抱負まで、まとめてお届けします。', pv1: '今年のキーワード', pv2: '分野ごとの運勢8つ', pv3: '12か月のカレンダー', pv4: '上半期・下半期の流れ', pv5: '今年固めたいこと・新年の抱負', see: '新年の運勢を見る', seePaid: '新年の運勢を見る（₩9,900）', },
  taegil: { title: '日取り — 良い日を探す', sub: '予定していることを選ぶと、これからの3か月のカレンダーから、あなたにぴったりの日を色で示します。', best: 'とても良い', good: '良い', tapHint: '色のついた日をタップしてみてください', },  zodiac: { title: '干支・星座の今日の運勢', animal: '干支', sign: '星座', mine: 'あなたの運勢', },
  name: { title: '名前占い', sub: '名前の音が持つ響きから、あなたの雰囲気を読み解きます。', placeholder: 'ハングルで名前を入力してください', noHangul: 'ハングルで名前を入力してください。', },
  taemong: {
    'secSymbols': '夢に出てきたもの',
    'secStory': 'この夢が語ること',
    'secChild': '伝えられてきたところでは',
    'secKeep': 'この夢の残し方',
    'secTradition': 'こんな話もあります',
    'title': '胎夢の解説',
    'sub': '子を待つ心を、夢に出たもので読む',
    'guard': '胎夢は古くから伝わる物語です。子の性別や健康を教えるものではありません — それは医療の領域です。',
    'dictTitle': '夢に何が出てきましたか？',
    'dictPh': '龍 · 虎 · 鯉 · 桃 …',
    'noHit': '辞典にない象徴です。無料で調べましょうか？',
    'lookup': '「{{kw}}」を調べる（無料）',
    'aiTitle': 'AI胎夢の解説',
    'aiSub': '夢の全体を物語として書いてください — 複数の象徴が混ざっていても、辞典になくても一緒に読み解きます。',
    'aiPh': '誰が見た夢か、何が出てきてどうしたか …',
    'aiCta': '胎夢の解説を受ける',
    'tooShort': '夢の話をもう少し書いてください。',
    'fail': '解説を読み込めませんでした。しばらくしてからもう一度お試しください。',
  },
  dream: {
    'aiBtn': 'AI夢占いを受ける（₩300）',
    'aiPh': '夢で見たこと・体験したことを詳しく…',
    'aiSub': '複雑な夢は物語として書いてみてください — 辞典になくても、複数の象徴が混ざっていても読み解きます。',
    'aiTitle': 'AI夢占い',
    'buy5': '運を使う',
    'buyBundle': '夢占いを5運で見ますか？',
    'needCredit': '今は開けません。しばらくしてからもう一度お試しください。', fail: '夢の意味を読み込めませんでした。しばらくしてからもう一度お試しください。', title: '夢占い', sub: '夢に出てきたものを検索してみましょう。', placeholder: '例：豚、ヘビ、水…', generating: 'AIが夢を読み解いています…', notInDict: '辞書にない夢です。AIの夢占いを受けてみましょう。', aiSee: 'AIの夢占いを見る', history: '過去の夢占い' },
  luck: { title: '今日の幸運', todayEnergy: '今日の気分', color: 'ラッキーカラー', direction: 'ラッキーな方角', numbers: 'ラッキーナンバー', item: 'ラッキーアイテム', weakHead: 'あなたを支えてくれる色', weakTail: ' — あなたに不足しがちな気分なので、そばに置くとバランスが整いますよ。', },
  renewal: { title: '最新の内容で読み直す', msg: 'この占いから1年が過ぎました。\n\n{{pct}}%割引の{{coins}} woonで、今の時点で読み直します。（保有{{have}} woon）', later: 'あとで', go: '読み直す', needTitle: '運が少し足りません', needMsg: '読み直しには{{need}}運がかかります。今は{{have}}運あります。' },
  assist: { title: 'ウォニ', sub: '見たいものを教えてください。そこまでご案内します。', label: 'ガイド', hello: '何をご覧になりますか？ 三つから選んでも、そのまま話しかけても大丈夫です。', egLabel: 'こんな風に言っても大丈夫', miss: 'まだその言葉は分かりませんでした。下から選んでいただければすぐご案内します。', placeholder: '何を見たいですか？', reset: '↺ 最初から', send: '送信', },
  coach: { title: 'AI自己理解コーチ', sub: '自分について気になることを聞いてください。あなたの四柱で答えます。', coachLabel: 'コーチ', thinking: 'あなたの四柱を見ています…', placeholder: '自分について聞く', send: '送信', needChart: 'まず命式を登録してください。', registerBtn: '命式を登録', loadFail: '命式を読み込めませんでした。少し時間をおいてお試しください。', gateTitle: '今日の無料質問を使い切りました', gateDesc: '無料では1日{{count}}回まで聞けます。プレミアムなら制限なくコーチと話せます。', gateCta: 'プレミアムを見る', q1: '私はどんな人ですか？', q2: 'なぜ私の関係は似たように繰り返すのでしょう？', q3: '私の強みをどう活かせばいいですか？', q4: '最近の私の流れはどうですか？' },
  selfHero: { kicker: '私はどんな人か', emptyTitle: 'あなたを分析します', emptySub: '生年月日時を入れると四柱エンジンが性格·気質·強みを分析します', emptyCta: '+ 私を分析する', more: '性向分析を詳しく見る ›' },
  personal: {
    'toneCap': '私のパーソナルカラー', title: 'パーソナル五行', sub: '五行に合うカラー·コーデ·メイク·車の色', activate: '私を活かす色', balance: '補うと良い色', yongsin: '（私に必要な気）', cody: 'コーデ', makeup: 'メイク', car: '車の色', empty: '命式を登録すると五行に合う色を見つけます', emptyCta: '+ 命式登録', expertNote: '※ パーソナル五行は四柱の五行をもとにした参考提案です。実際のパーソナルカラー診断やスタイリングは専門家にご相談ください。' },
  // R-GEM v0.1 — 私の四柱宝石(★daniel 検収スロット: sub·note 文言)
  gem: { title: '私の四柱宝石', birthstoneTitle: '誕生石にはどんな意味が', sub: '誕生石は実はあなたに合わない — あなたを活かす本当の宝石', empty: '命式を登録すると合う宝石を見つけます', emptyCta: '+ 命式登録' },
  timeResolve: {
    'title': '生まれた時刻を探す', yearRange: '年をもう一度ご確認ください（例：1990〜今年）。', yearFuture: '未来の年は入力できません。', removeEvent: '出来事を削除' },
  sok: { title: '相性(夜)', sub: '二人の性的相性を四柱で — 大人の遊び', gateTitle: '成人(19歳以上)コンテンツ', gateDesc: '二人の性的相性を四柱で読み解く成人向けコンテンツです。遊びとしてお楽しみください。', gateConfirm: '19歳以上です · 開始', pickPartner: '相手を選ぶ', newPartner: '新しい相手', registerSubmit: 'この相手で見る', spouseLabel: '配偶者宮の相性', adviceLabel: 'もっと良くする方法', kiss: 'キス相性', bed: '夜の相性', styleLabel: '二人のケミスタイル', pickHint: 'タップして相手を選択', noPartner: '保存された相手がいません。新しい相手を入力してください。', disclaimer: '※ 四柱で見る遊びコンテンツです。実際の関係は二人が作ります。成人(19歳以上)限定。' },
  community: { searchPh: '投稿タイトルで検索', views: '閲覧', sortRecommend: 'おすすめ', sortPopular: '人気', writeBox: '今日の悩みや質問を書いてみましょう ✨', daily: '今日の日運', dailyTalk: '話に加わる', p1: 'とても良い', p2: '良い', p3: '普通', p4: 'いまいち', p5: 'つらい', pollMine: '投票完了！人が集まると統計が見えます。', pollStat: '{{total}}人参加 · 最多選択 {{top}}%', all: '全体', cat: { love: '恋愛', career: '仕事・進路', wealth: '金運', daily: '日常', free: '自由', tarot: 'タロット', ziwei: '紫微斗数' }, empty: '最初の投稿をどうぞ。', profanity: '不適切な表現が含まれています。修正して再投稿してください。', write: '投稿', post: '投稿', titlePh: 'タイトル', bodyPh: '内容を入力 (暴言·差別·性的表現は禁止)', eulaTitle: 'コミュニティ利用規約', eulaBody: '暴言·差別·嫌がらせ·違法·性的/わいせつなコンテンツは禁止です。違反時は投稿削除·利用制限されることがあります。通報されたコンテンツは24時間以内に確認·対応します。不適切なユーザーはブロックできます。', eulaAgree: '同意して投稿', comments: 'コメント', noComments: '最初のコメントをどうぞ。', commentPh: 'コメント入力 (マナーを守って)', send: '登録', report: '通報', block: 'ブロック', reportTitle: '通報する', reportDesc: '理由を選択してください。通報は24時間以内に確認します。', rAbuse: '暴言·差別·嫌がらせ', rSexual: '性的/違法コンテンツ', rSpam: 'スパム·広告', reported: '通報を受付', reportedDesc: '確認して対応します。ありがとうございます。', reportFail: '通報に失敗しました。', blockTitle: 'このユーザーをブロック', blockDesc: 'ブロックするとこのユーザーの投稿·コメントが表示されなくなります。', blocked: 'ブロックしました', blockFail: 'ブロックに失敗しました。', delTitle: '削除しますか？', gone: '削除されたか表示できない投稿です。', loginTitle: 'ログインが必要です', loginDesc: '投稿はログイン後に利用できます。閲覧はログインなしでそのまま可能です。', goLogin: 'ログイン', attach: '自分の命式を添付', attachNone: '「本人」として登録された命式がありません。添付なしで投稿できます。', attachOff: '添付しない', attachLuck: '大運・歳運も一緒に公開', attachWarn: '原局の八文字がこの投稿を見る全員に公開されます。八文字から生年月日を逆算できるため、確認のうえ投稿してください。', needTitle: 'タイトルを入力してください。', needBody: '内容を入力してください。', posting: '投稿中…', errSession: 'ログインが必要です。再ログイン後にお試しください。', errNet: '通信環境を確認して再度お試しください。', errPost: '投稿できませんでした。しばらくして再度お試しください。' },
  egen: { title: 'エゲン vs テト', heroSub: '四柱で見るエゲン·テト傾向', tetoPower: 'テト力', typeTeto: 'テト型', typeEgen: 'エゲン型', typeBalanced: 'バランス型', scaleEgen: 'エゲン', scaleTeto: 'テト', secPersonality: '生まれ持った傾向', secRelationship: '恋愛·関係で', secNowTrend: '最近の流れ', needChart: 'まず命式を登録してください。', registerBtn: '命式を登録', gateTitle: '私の傾向の解説を見る', gateDesc: 'スコアに合わせて、あなたの傾向が普段·恋愛·今の流れでどう表れるかを気軽に解説します。', seeAd: '広告を見て無料で見る', seePremium: '解説を見る', generating: '傾向を分析しています…', genFail: '解説を読み込めませんでした。しばらくしてからもう一度お試しください。', adFail: '広告を読み込めませんでした。しばらくしてからもう一度お試しいただくか、プレミアムで広告なしでご覧いただけます。', },
  crisis: { title: '関係の山場', heroSub: '揺れる時期を構造で見ます — 占いではなく座と力で', frameTitle: '別れるかどうかは言いません', frameBody: '関係が終わるかを当てる画面ではありません。命式の配偶者の座にどんな力がどこから掛かっているか、どの年にその座が動くかを見ます。決めるのはその後で、それは命式ではなく二人がします。', needChart: '命式を登録するとこの画面が埋まります。', chartFail: 'この命式では計算できませんでした。', secStrength: '① 揺らす力はどこから来るか', gungLine: '配偶者の座 = 日支 {{gung}}', chungFrom: ' · {{from}}支から掛かります', gradeBreaking: 'すぐ隣から強く揺らす力が掛かっています。この座は揺れれば揺れたなりに表に出ます。', gradeShaking: '揺れはあっても座そのものは押されません。', gradeEven: '双方の力が近く、どちらが勝つとは言いにくい形です。', gradeNone: 'この座を揺らす力は原局に掛かっていません。', remedyBreaking: '揺れている最中に関係を定義し直すと、もっと揺れます。決定を先送りし、生活のリズムを守るほうが得です。', remedyEven: 'どちらも勝てない綱引きなので、勝とうとするほど長引きます。先に口を開いたほうが勝ちます。', remedyCalm: '今の構造に急ぎの火はありません。関係を試す選択を、わざわざ今つくらなくて大丈夫です。', secRivalry: '② 争う形があるか', rivalryWealth: '天干で同じ字が二つ、一つを巡って争う形があり、その対象が財星です。人であれ取り分であれ「分けにくいもの」が関係に入ると、質が表に出ます。', rivalryYes: '天干で同じ字が二つ、一つを巡って争う形があります。誰かが割り込むという意味ではなく、一つを巡って力が割れる構造がもともとあるという意味です。', rivalryNo: '一つを巡って力が割れる形は原局にありません。関係が揺れるなら別のところから来ます。', rivalryRemedy: 'この構造を「誰かのせい」で読むと必ず外れます。分けられないものを先に決めておくと、争う場所が減ります。', rivalryRemedyNo: '三角関係を先回りして心配する場ではありません。', secBond: '③ くっついているか、名ばかりか', bondYes: '配偶者の座がすぐ隣と結ばれています。離れていても切れにくい質です。', bondNo: '配偶者の座をつなぎ止める字が隣にありません。続くかどうかは構造より二人がつくる側です。', frictionYes: 'ただし摩擦（刑）も一緒に掛かっており、近いほどぶつかる箇所が出ます。', frictionRemedy: 'ぶつかる場所がいつも同じなら、それは出来事ではなく質です。その一つだけ決め事にすれば、あとは静かになります。', bondRemedy: 'つなぎ止める力が弱いほど、約束と反復がその役を代わります。', secTiming: '④ どの年にその座が動くか', timingQuiet: 'これから八年、配偶者の座に触れる年はありません。静かな区間です。', yOpen: '座が開きます — 動きが入る年', yBond: '座が結ばれます — 結び目ができる年', yFriction: '摩擦が回る年', timingRemedy: '「開く」は別れるという意味ではありません。その座に動きが入るという意味で、出会いも整理も同じ扉から来ます。その年に大きな決定を集めないだけで、たいてい通り過ぎます。', disclaimer: 'この画面は構造と時期を見る参考であり、関係の結末を予測しません。今とてもつらいなら、命式より先に身近な人や専門家に話してみることをおすすめします。' },
  attach: { title: 'アタッチメント — 命式とアンケート', heroSub: '同じ関係のパターンを二つの言葉で見ます', frameTitle: '二つの結果は別のものを見ています', frameBody: 'アンケートは今この時期の状態を測り、命式は生まれ持った構造の質を見ます。だから二つの値は違うことがあり、その違いこそ読みどころです — 構造は距離を取る側なのに今は楽なら、その間に何かを自分で身につけたということです。', secChart: '① 命式が指す質', secSurvey: '② 今の私（12問）', secCompare: '③ 二つを並べて見る', axisAnx: '不安 — 離れないか気にする側', axisAvo: '回避 — 距離を取る側', axisAnxShort: '不安', axisAvoShort: '回避', anxLow: '揺れにくい', anxHigh: '気にかける', avoLow: '近さが楽', avoHigh: '距離を取る', capTitle: '日干が{{target}}を担えるか', capFrame: '関係での距離感は、関係を担う余裕があるかで分かれます。男性の命式は正財、女性の命式は正官の座を見ます。', capAxis: '担う力', capLow: '手一杯 · 距離を取る', capHigh: '余裕がある · 楽である', capEdge: '両端へ遠ざかるほど関係は揺れやすくなります。どこからをそう見るかはまだ決めていないため、タイプ名を付けず位置だけをお見せします。', capAbsent: 'この命式には{{target}}が表に出ていません。そうした命式の読み方はまだ確認中のため、上の位置はゆるやかな参考としてご覧ください。', sideSelf: '余裕側', sideLoad: '負担側', cmpAnxNone: '不安の行はアンケート結果のみです。命式側は「関係を担う余裕があるか」までを述べており、それを不安に置き換える読み方はまだ確認していません。', basisHead: 'この点数を押したもの', basisNone: 'この軸を押す構造は目立ちません。', needChart: '命式を登録するとこの部分も出ます。アンケートだけ先にしても大丈夫です。', chartFail: 'この命式では計算できませんでした。', surveySub: '身近な人との関係を思い浮かべてお答えください。正解はありません。', progress: '{{n}} / {{total}} 問', compareLocked: '12問すべて答えるとここで並べて表示します。', soloGap: '「一人が楽」の側が高く、「近づくと落ち着かない」の側が低く出ました。自分で解決する力が大きい場合もこうなるので、二つの筋を分けて見るとよいです。', hypo: '見る座（男性は正財・女性は正官）と読み方は相談の専門家がくださったとおりです。ただし「担える」を何で測るかはまだ確認中のため、根拠の項目をすべて同じ重さにしています（v1）。確認でき次第、再計算して反映します。', disclaimer: 'この結果は自己理解のための参考であり、心理診断ではありません。関係や気持ちの困りごとが日常に影響しているなら、専門家に相談することをおすすめします。', consent: 'この回答をアタッチメントモデル改善の研究に匿名で使うことに同意します（任意・同意しなくても結果はそのまま見られます）', consentNote: '送るのはアンケートの回答と命式から計算した指標だけです。生年月日時は端末から出ません。', saveBtn: '研究に回答を送る', saving: '送信中…', saved: '送りました。ありがとうございます', saveFail: '送れませんでした。もう一度', },
  joseonjob: { shareLead: '朝鮮時代の私の職業', traits: '生まれ持った強み', share: '私の職業をシェア', detail: '私の四柱をくわしく見る（プレミアム）' },
  lovestyle: { shareLead: '私の恋愛スタイル', inLove: '恋愛では', tip: 'これを足すと', share: '恋愛スタイルをシェア', detail: '私の恋愛の流れをくわしく見る' },
  bok: { shareLead: '私の福', how: '福を育てる方法', share: '福をシェア', detail: '私の四柱をくわしく見る（プレミアム）' },
  pastlife: { shareLead: '私の前世', hint: '今のあなたへ', share: '前世をシェア', detail: '私の四柱をくわしく見る（プレミアム）' },
  healing: {
    'deficit': '最も弱い気（参考）', shareLead: '私の癒し方', recharge: '私の充電方法', nourish: '満たすと良い気', release: '手放すと良い気', color: '癒しの色', place: '癒しの空間', food: '添えると良い', mind: '心への一言', elemLead: '私の気', share: '癒し方をシェア', },
  bio: {
    'kicker': 'バイオリズム',
    'note': '※ 四柱推命とは無関係の参考リズムです。0付近は調子が変わる転換日です。',
    'sub': '今日の身体・感情・知性のリズム',
  },
  career: {
    'gateDesc': '二つの道でどう輝き、どこで詰まるのか、生まれ持った重心と時期まで読み解きます。',
    'generating': '二つの道を読み解いています…',
    'sub': '命式と大運・歳運から、独立と組織の二つの道を読み解きます',
    'title': '起業家の私 vs 会社員の私',
  },
  celeb: {
    'compare': '日干・五行の比較',
    'funNote': '楽しみとして',
    'matchHead': '似ている点',
    'myTenGod': '私の十神構造まとめ',
    'reasons': '共通する構造',
    'sub': '私の四柱と似た人物さがし',
    'title': '私に似た芸能人',
    'topLabel': '私と最も似ている人物',
  },
  coins: { title: '運のチャージ', titleSub: '運をチャージして、見たい鑑定を開きましょう。', bonusAny: 'チャージ時に自動適用', bonusNote: '大きいクーポンから自動で使われます。お支払い金額は変わりません。', bonusTitle: 'お持ちのボーナス', failTitle: 'チャージできませんでした',
    useHead: '運でできること',
    useTalk: '· 相談員とのチャット — {{cost}}運で{{turns}}ターン',
    useReading: '· 四柱推命・相性・タロットの鑑定 — 価格は内容ごとに異なり、開く前に表示されます',
    useNote: '無料の{{free}}ターンは毎日補充されます。運は失効しません。',
    spendMsg: '{{cost}} woon を使って鑑定を始めますか？\n保有 {{have}} → 使用後 {{after}}',
    'balFail': '残高を読み込めませんでした',
    'balance': '保有する運',
    'charge': '運をチャージ',
    'chargeCta': '運をチャージ',
    'donePending': '決済が完了しました。残高への反映に少し時間がかかる場合があります。',
    'doneTitle': 'チャージしました',
    'needLoginDesc': 'チャージした運はアカウントに保管されます。ログインすれば端末を変えてもそのまま残ります。',
    'needLoginTitle': 'ログインが必要です',
    'needTitle': '運が少し足りません',
    'note': '· 運はすべての有料解説に使えます。\n· チャージした運はアカウントに保管されます — 端末を変えてもそのままです。\n· 運に有効期限はありません。',
    'packs': '運をチャージ',
    'spend': '運を使う',
  },
  country: {
    'needChart': 'まず命式を登録してください。',
    'sub': '生まれ持った気（調候）を補ってくれる気候・方位の国をご案内します',
    'title': '私が暮らしやすい場所',
  },
  crush: {
    'caution': '気をつける点',
    'generating': '惹かれる気と縁の流れを読んでいます…',
    'howToApproach': '近づき方',
    'myCharm': '今の私の魅力',
    'sub': '今の私の魅力と、片思い・良い雰囲気が深まりやすい時期、近づき方をご案内します',
    'timing': '思いが深まる時期',
    'title': '片思いの縁',
    'whoLikesMe': '私に惹かれる人',
  },
  crushAsk: {
    'cta': '深い片思いの解説を見る',
    'q': 'あの人とつながる？',
    'sub': '片思いや良い雰囲気が深まり、心が通じやすい月を無料で先にご案内します',
  },
  gaeun: {
    'gateDesc': '今の運に何が来るのかを見て、財・人間関係・健康を活かす実践と厄払いまでご案内します。',
    'generating': '今の運に合った開運法を探しています…',
    'sub': '今の運（大運・歳運）に合わせて運を活かす具体的な方法をご案内します',
    'title': 'オーダーメイド開運法',
  },
  fav: {
    'empty': 'まだお気に入りがありません。',
    'emptySub': 'カードの ♡ を押すとここに集まります。',
  },
  notify: {
    'empty': 'お知らせはありません。',
    'failed': 'お知らせを読み込めませんでした。',
    'title': 'お知らせ',
  },
  readingTab: { all: '全体', nature: '性向', love: '恋愛', work: '仕事', money: '財運', life: '人生',
    h1: '1. 私の四柱', h2: '2. 私を作る五つの気', h3: '3. 私はどんな人でしょう？', more: '詳しく見る', empty: 'このテーマはまだ作成されていません。' },
  my: { chats: '会話履歴', teachers: 'お気に入りの先生', posts: '書いた投稿', comments: 'コメントと返信', useHistory: 'ウン利用履歴', subs: 'サブスク管理', notifySet: '通知設定', account: 'アカウントとセキュリティ', support: 'カスタマーセンター', woonCard: 'マイ ウン', walletLink: 'ウンチャージ / 利用履歴', statusDefault: '今日もいいことがありますように ✨', editProfile: 'プロフィール編集', needLogin: 'ログインすると活動履歴が見られます。', noPosts: 'まだ書いた投稿がありません。', noComments: 'まだコメントがありません。', deletedPost: '削除された投稿', noTeachers: 'お気に入りの先生がまだいません。\n友だちリストで星を押してみてください。', grpAct: 'マイ活動', grpWoon: 'ウン管理', grpSet: '設定', charts: 'マイ命式',
    loginTitle: 'ログインして続きを',
    loginSub: 'Google・Appleで始めるとアカウントも作られます。購入した内容とチャットが他の端末や再インストール後も引き継がれます。',
    loginCta: 'ログイン・新規登録',
    'fav': 'お気に入り',
    'readings': '鑑定履歴',
    'charge': '運をチャージ',
    'coach': '相談履歴',
    'coupon': 'クーポン',
    'helloGuest': 'こんにちは',
    'helloName': 'こんにちは、{{name}}さん',
    'helloSub': '運を管理して、より良い一日にしましょう。',
    'history': '決済・チャージ履歴',
    'settings': '設定とプライバシー',
    'wallet': '私の運ウォレット',
    'walletSub': '運は鑑定や相談に使えます。',
    'woon': '運',
  },
  analyzed: { done: '分析が完了しました！', ilju: '日柱', is: 'です。', next: '私の命式を見る', sub: 'あなたの四柱を確認してみましょう。', you: 'あなたは' },
  coinHistory: {
    adFreeForever: '広告非表示（永久）',
    kindCoach: 'パルジャアシスタント',
    kindFuture10: '10年の流れ',
    kindQaTopup: 'テスト付与',
    coinPack: '{{n}} 運',
    adFree: '広告非表示 {{d}}日',
    kindTalk: '相談員とのチャット',
    kindReading: '四柱推命の鑑定',
    rPurchaseWhat: '{{what}} チャージ',
    rPurchase: '運のチャージ',
    rSpendWhat: '{{what}}に使用',
    rSpend: '運の使用',
    rRefundWhat: '{{what}} 返金',
    rRefund: '返金',
    rGift: '贈られた運',
    rMigrate: '以前の残高の引継ぎ',
    'charge': 'チャージ',
    'empty': 'まだ履歴がありません。',
    'failed': '履歴を読み込めませんでした。',
    'use': '使用',
  },
  myReadings: {
    'empty': 'まだ作成した鑑定がありません。',
    'failed': '鑑定を読み込めませんでした。',
    'goPick': '運勢を見に行く',
  },
  banner: {
    'kicker': '今日のおすすめ',
    'loveT': '今、あなたに\n近づいている\n縁があります。',
    'loveS': '見過ごすには\n強い流れです。',
    'loveC': '縁を確かめる',
    'moneyT': 'あなたの器は\nどれくらい？',
    'moneyS': '大きさは生まれつき、\n満ちる時は別です。',
    'moneyC': '器を見る',
    'selfT': 'あなたは結局\nどんな人？',
    'selfS': '性格も気質も\n生まれた場所があります。',
    'selfC': '自分を知る',
    'flowT': '十年後の自分は\n今と違う？',
    'flowS': '流れが変わる年は\nもう決まっています。',
    'flowC': '流れを見る',
    'funT': '今日ひとつだけ\n軽く見ますか？',
    'funS': '重くなく、\n今日の分だけ。',
    'funC': '軽く見る',
  },
  freeDraw: {
    'title': '無料タロット一枚引き',
    'sub': '今日の運をカード一枚で確かめてみましょう。',
    'cta': 'はじめる',
  },
  talk: { spentPack: '{{n}}運 使用 · {{k}}ターン分', packLast: 'このまとめはここまでです。次のお話から運がかかります。', searchPh: '名前で検索', favShort: 'お気に入り', unfavShort: '解除',
    'greetHi': 'こんにちは。{{name}}です。',
    'greetWhat': '{{what}}を見ています。何が気になりますか？',
    'greetAsk': '何が気になりますか？',
    'noFlow': '今日の流れは少し後にもう一度見ますね。',
    'guideHere': 'ここで詳しく見られます。',
    'guideNone': '今はご案内できるものがありません。',
    'handoff': 'それは{{who}}に伺ってみますね。',
    'handoffCtx': 'これまでのお話はそのままお伝えします。',
    'listTitle': '相談',
    'kindVirtual': '案内',
    'kindLive': '相談の先生',
    'typing': '入力中',
    'inputHint': '何でも聞いてください',
    'send': '送信',
    'delAsk': 'この会話を削除しますか？元に戻せません。',
    'delOk': '削除',
    'pickChat': '左から会話を選んでください',
    'pickOne': '会話がありません',
    'liveSoon': 'もうすぐお話しできます。準備中です。',
    'blockHi': '{{what}}をお持ちしました。',
    'friends': '友だち',
    'favorites': 'お気に入り',
    'filter': { all: 'すべて', teacher: '先生', friend: '友だち', recent: '最近' },
    'officialBadge': '公式',
    'groupTeacher': '✦ 先生',
    'groupTeacherSub': '実際の相談家の観法に沿って答えます。',
    'loginNudge': 'ログインすると命式と鑑定がアカウントに保存されます。',
    'loginNudgeSub': '今はこの端末だけにあります — アプリを消すと戻せません。',
    'loginNudgeCta': 'ログイン',
    'briefTail': '皆さんの運はどうなるでしょう？ご自身の命式で見ると、今月がどんな月かわかります。',
    'groupFriend': '✦ 一緒にいると良い友だち',
    'contents': 'コンテンツ',
    'more': 'もっと見る',
    'collapse': '閉じる',
    'fav': 'お気に入りに追加',
    'unfav': 'お気に入りから外す',
    'friendsCount': '友だち {{n}}人',
    'search': '友だち検索',
    'searchEmpty': '見つかりませんでした。',
    'meNoChart': '命式登録',
    'needLoginBubble': '{{name}}です。お話を続けるにはログインが必要です。命式を見ないと、きちんとお答えできないんです。',
    'needLoginTitle': 'ログインが必要です',
    'needLoginMsg': 'ログインすると命式を保存して、相談家と続けてお話できます。',
    'liveGreet': 'こんにちは。{{name}}です。何が気になりますか？',
    'chartMade': '命式を作りました。これからはこの四柱で見ますね。',
    'chartMakeFail': '命式を作る',
    'chartMakeFailBody': '今は作れませんでした。しばらくしてからもう一度お試しください。',
    'overFree': '本日の無料チャットはここまでです。ここからは運が使われます。',
    // ★運の消費を示す一行（吹き出しではなく中央・小さい文字）。数字はサーバーの値だけを使う
    'spent': '運{{n}}を使用',
    'freeLeft': '本日の無料チャットはあと{{n}}回です。',
    'needCoinsTitle': '運が少し足りません',
    'needCoinsMsg': 'もう少しお話しするには{{cost}}運がかかります。今は{{have}}運あります。',
    'needCoinsMsgNoBal': 'もう少しお話しするには{{cost}}運がかかります。',
  },
  home: {
    'bonusLead': 'チャージ時に自動で使われます',
    'bonusTitle': '届いた特典',
    'bonusTitleName': '{{name}}さんに届いた特典',
    'bonusUntil': '{{date}}まで使えます。',
    'freeTrio': '無料で試してみましょう',
    'freeTrioSub': '登録なしで今すぐ見られるもの',
    'greeting': '{{name}}さん、ようこそ',
    'seeMore': '見に行く',
    'lightCta': '軽く見る',
    'monthTitle': '今月の運勢',
    'monthNoChart': '今月の流れも命式が必要です',
    'monthLoading': '今月の流れを見ています',
    'manseSub': '私の四柱命式をすべて見る',
    'noChartCta': '+ 命式を登録',
    'noChartSub2': '生年月日だけで性格タイプと日柱がすぐ見られます。登録も保存もしません。',
    'noChartTitle': 'AIが分析する私 — ここから',
    'quickRegister': '命式を登録',
    'quickRegisterSub': '家族・恋人・友人の命式を追加します',
  },
  impression: {
    'gapBig': '外から見える姿と、知ってからの姿がかなり違います。最初はわからない意外な魅力がある人です。',
    'gapSmall': '外から見える姿と内面が比較的一貫しています。見えるままに信頼できる人です。',
    'inner': '知ってみると — 本当の私',
    'note': '※ 天干（外に表れる気）の流れが人に映るイメージ、月支（生まれ持った座）の気が知ってからの本当の姿です。',
    'outer': '外から見える私',
    'sub': '外から見える姿と、知ってみると違う本当の私',
    'title': '人が見る私の印象',
  },
  job: {
    'bestField': '合う職種・環境',
    'flow': '就職・転職の流れ',
    'generating': '就職・合格の気と流れを読んでいます…',
    'passLuck': '合格・試験運',
    'sub': '就職・転職・合格・試験がうまくいく流れと時期、合う職種や準備の仕方をご案内します',
    'timing': '良い時期',
    'tips': '準備のヒント',
    'title': '就職・転職運',
  },
  jobAsk: {
    'cta': '深い就職の解説を見る',
    'q': '就職・転職、いつうまくいく？',
    'sub': '就職・転職・合格の扉が開きやすい時期を無料で先にご案内します',
  },
  jobfit: {
    'ability': '実際に得意なこと',
    'archetype': '私の職業タイプ',
    'gap': '惹かれることと能力の差',
    'generating': '生まれ持った適性と合う職業を読んでいます…',
    'jobs': '合う仕事',
    'luckMap': '職業の人生の流れ',
    'preference': '惹かれること（能力ではない）',
    'recognition': '認められ方・舞台',
    'sub': '生まれ持った適性からどんな職業が合うのか、惹かれることと能力の差まで読み解きます',
    'title': '私に合う職業',
    'workEnv': '合う職場',
    'workMode': '働き方・モード',
    'yongsinFit': 'ふさわしい方向',
  },
  login: {
    'go': 'ログイン',
    'needContentMsg': 'このコンテンツを見るにはログインしてください。ログインすると購入と解説がアカウントに安全に保存されます。',
    'needTitle': 'ログインが必要です',
  },
  mbti: {
    'empty': '命式を登録すると四柱推命で見たMBTIをお見せします。',
    'note': '※ 四柱の構造（蔵干・現在の運を含む）から見た傾向のため、時期によって少しずつ変わります。心理検査のMBTIとは異なる場合があります。',
    'sub': '私の四柱構造から読み解いた傾向タイプ',
    'title': '四柱推命で見る私のMBTI',
  },
  mod: {
    'empty': '通報されたコンテンツはありません。',
    'hide': '非表示',
    'restore': '復元',
    'sub': '通報されたコンテンツを確認して非表示または復元します。（通報5回以上は自動で非表示）',
    'title': '通報管理',
  },
  net: {
    'errMsg': 'しばらくしてからもう一度お試しください。続く場合は少し後にもう一度開いてください。',
    'errTitle': '接続に問題があります',
  },
  relPattern: {
    'attraction': '魅力・縁の密度',
    'compatCta': '特定の相手との相性が気になるなら →',
    'drawnTo': '繰り返し惹かれる人の質',
    'dynamic': '私の関係の力学',
    'footNote': '※ 配偶者宮（日支）・縁星・桃花など命式の構造を四柱エンジンで計算した端末内分析です。予言ではなく、自分を理解するための参考です。',
    'kicker': '四柱エンジンで見る関係心理',
    'myStyle': '関係における私のあり方',
    'sub': 'なぜ似た関係が繰り返されるのでしょう？相性占いではなく、生まれ持った四柱の構造から繰り返される関係の質を読み解きます。',
    'title': '私の関係パターン',
    'titleSuffix': 'さんの関係パターン',
  },
  reunion: {
    'addDesc': '昔の縁の命式と今の悩みを加えると、二人の四柱を合わせて悩みに沿って読み解きます。空欄なら私の流れだけで見ます。',
    'addTitle': '一緒に読み解きます（任意）',
    'afterReunion': 'また会うとしたら',
    'caution': '振り返ると良い点',
    'changeBuy': '購入して変更',
    'changeConfirmBuy': '相手を変えると最初から読み直します。運が少しかかりますが、進めますか？',
    'changeConfirmCredit': 'お持ちの復縁運1回分で相手を変えて読み直します。変更しますか？',
    'changeConfirmPremium': '相手を変えるとその人で新しく読み解きます。変更しますか？',
    'changeGo': '変更',
    'concernLabel': '今の悩み',
    'concernPh': '今どんな状況・悩みなのか書いていただくと一緒に読み解きます',
    'generating': '再びつながる縁の流れを読んでいます…',
    'otherAdd': '昔の縁の生年月日を入力',
    'otherAnon': '昔の縁',
    'otherChange': '相手を変える（新しく読む）',
    'otherLabel': '昔の縁の命式',
    'otherLockedNote': '相手を変えるには新しく読み解く必要があります。',
    'otherPrivacy2': '※ 相手の情報はこの復縁の解説にのみ使われます。変更するまでこの端末にのみロックして保管され、命式一覧には残りません。同意を得た場合のみ入力してください。',
    'possibility': '再びつながる縁かどうか',
    'registerOtherSubmit': 'この命式で一緒に読む',
    'registerOtherTitle': '昔の縁の命式を入力',
    'remedy': '復縁を開く方法',
    'sub': '昔の縁と再びつながる可能性と、連絡が届きやすい時期をご案内します',
    'theirResponse': 'その時の相手の気持ち',
    'timing': '連絡が届きやすい時期',
    'title': '復縁運',
  },
  reunionAsk: {
    'cta': '深い復縁の解説を見る',
    'q': '復縁、また戻れる？',
    'sub': '昔の縁と再びつながる可能性・時期・方向を無料でご案内します',
  },
  selfAnalysis: {
    'elements': '五行バランス — 私を成す五つの気',
    'footNote': '※ すべて四柱エンジン（万年暦）で計算した端末内分析です。予言ではなく、自分を理解するための参考です。',
    'kicker': '四柱エンジンが分析した私',
    'more': '詳しく見る ›',
    'strengths': '強みと気質を詳しく',
    'sub': '生まれ持った四柱をエンジンで計算した五つの自己分析 — 占いではなく、自分を理解するための指標です。',
    'title': '私の分析',
    'titleSuffix': 'さんの分析',
  },
  signup: {
    'body': '購入した利用券と解説は、今お使いの一時アカウントに紐づいています。アプリを削除したり端末を変えると取り戻すのが難しくなります。アカウントを連携しておけばそのまま引き継げます。',
    'cta': 'アカウントを連携',
    'note': '連携しなくても今のまま使い続けられます。',
    'title': '今見た解説、この端末にしか残っていません',
  },
  signupPrompt: {
    'cta': 'アカウント連携',
    'later': '後で',
    'msg': '現在は一時アカウントのため、アプリを削除したり端末を変えると購入した利用券と解説を取り戻すのが難しくなります。連携しなくても引き続きご覧いただけます。',
    'title': 'アカウントを連携するとこの解説が安全に保管されます',
  },
  spouseDual: {
    'ageHint': '年齢層のヒント',
    'ageNote': '※ 傾向にすぎません。実際の相手の四柱があれば相性が優先します。',
    'funnel': 'より具体的な理想像・実際の縁・時期の解説は下の愛情リーディングでご確認ください。',
    'gap': '対比',
    'idealTag': '惹かれる理想像',
    'ignite': '惹かれ（発動）',
    'match': '一致',
    'noFlow': '今後8年間は配偶者の座が大きく開閉する兆しが弱いです。大きな変動より固める時期です。',
    'realDesc': '結婚生活の実質 — 常に最優先の座（日支）',
    'realTag': '本当にそばに残る人',
    'settle': '安定（安着）',
    'sub': '生まれ持った配偶者の座を二つの軸で見ます — 惹かれる理想像と、実際にそばに残る人。',
    'timeline': '惹かれ vs 安定 — 縁の流れ',
    'title': '理想像と本当の縁',
  },
  traits: {
    'detail': '私の四柱を深く見る',
  },
  wealth: {
    'flow': '財の人生の流れ',
    'generating': '生まれ持った財の器と流れを読んでいます…',
    'howEarn': 'お金が入ってくる質',
    'partner': '一人 vs 一緒に',
    'remedy': '財の守り・開運',
    'sub': '生まれ持った財の器とタイプ、いつ大きく入り、どう守るのかまでご案内します',
    'timing': '財の時期',
    'title': '財のディープレポート',
    'type': '財のタイプ',
    'vessel': '財の器',
  },
  yieojim: {
    'express': '心は動くが定着までは弱い年',
    'mine': '自分から近づいてつながりやすい年',
    'mineNone': '今後10年は弱めです — 自分から表現して近づく力（食傷）が命式に薄く、特定の時期（その気が入るとき）に集中します。',
    'note': '※ 参考の傾向です。実際の縁は出会う人によって変わります。いずれにせよ最終的につながるには「縁の座」が開く年が鍵です。',
    'popular': '関心・人気は来るが定着までは弱い年',
    'sub': '片思いでもアプローチでも、実際につながるには「縁の座（配偶者宮）」がその時に開いている必要があります。',
    'theirs': '良い縁が近づいてつながりやすい年',
    'theirsNone': '今後10年は縁が近づいて定着まで至る明確な時期が弱めです。',
    'title': '縁がつながる時期',
  },
};
