// app/src/copy/ko.ts — ★앱에 보이는 **한국어 문구 전부**가 여기 있습니다(기획자 편집용)
// ═══════════════════════════════════════════════════════════════════════════
// daniel 2026-08-03: "기획자가 앱 내부에서 사용하는 제목·소제목·내용·문구·멘트들
//                     다 직접 수정할 수 있게 한 곳에 모아줘"
//
// ■ 어떻게 고치나
//   따옴표 안의 글자만 바꾸면 됩니다. **키(콜론 왼쪽)는 절대 바꾸지 마세요** — 화면이 그 키로 문구를 찾습니다.
//     예)  genCta: '이 관계 풀이 만들기'      ← '…' 안만 수정
//   `{{n}}` 처럼 중괄호 두 개는 **숫자·이름이 들어갈 자리**입니다. 그대로 두세요(지우면 값이 안 나옵니다).
//   `\n` 은 줄바꿈입니다.
//
// ■ 여기 없는 문구도 있습니다(일부러 그렇습니다)
//   · 타로 78장 뜻 · 일주론 60갑자 · 명리 용어 사전 · 꿈 사전 · 오늘의 운세 룰 —
//     이건 UI 문구가 아니라 **콘텐츠 데이터**라, 각 도메인 파일에 둡니다
//     (lib/tarot.ts · lib/engine/dayPillar.ts · lib/content/*). 여기로 옮기면 오히려 찾기 어려워집니다.
//   · 화면에 직접 박힌 문구가 아직 일부 남아 있습니다 — 발견하면 여기로 옮기고 있습니다.
//
// ⚠️영어(en.ts)·일본어(ja.ts)는 **키가 같아야** 합니다. 여기서 키를 추가/삭제하면 그쪽도 같이 해야 합니다.
// ═══════════════════════════════════════════════════════════════════════════
export const ko = {
  cb: {
    elemWood: '새로 벌이고 키워 가는',
    elemFire: '밝게 드러내고 열정을 내는',
    elemEarth: '품고 안정시키는',
    elemMetal: '분명하게 맺고 결단하는',
    elemWater: '유연하게 흐르며 지혜로운',
    resDefault: '타고난 기운을 견주면 닮은 결이 은근히 보여요.',
    resIljuExact: '타고난 뿌리 자리가 통째로 겹쳐요. 기질의 결이 유독 많이 닮은 사이예요.',
    resIlganSame: '중심을 이루는 기운이 같아요. 세상을 대하는 태도의 뿌리가 닮았을 수 있어요.',
    resIlganElem: '둘 다 {{w}} 기운이 중심이에요. 비슷한 결로 움직이는 편이에요.',
    resIlganElemNo: '중심 기운의 결이 닮았어요.',
    resDominant: '두 분 모두 {{w}} 기운이 가장 도드라져요. 닮은 에너지를 타고났어요.',
    resDominantNo: '가장 강한 기운이 같아요.',
    resOhaeng: '타고난 기운의 조합이 비슷해요. 삶을 대하는 결에 공통점이 생기기 쉬워요.',
    resTengod: '사람을 대하고 일을 풀어가는 방식의 결이 닮았어요.',
    resDefault2: '기운을 견주면 닮은 면이 은근히 보여요.',
    searchPh: '이름으로 찾기 (예: 아이유)',
    searching: '찾는 중…',
    searchResult: '‘{{q}}’ 검색 결과 {{n}}명',
    trendHint: '요즘 많이 찾아본 순으로 보여 드려요',
    tapCompare: '탭하면 이 인물과 나를 자세히 비교해 볼 수 있어요 ›',
    noChartTitle: '명식을 등록하면 나와 가장 닮은 인물을 찾아드려요',
    noChartTx: '내 생년월일시로 사주를 먼저 등록해 주세요 ›',
    rankNote: '나와 닮은 순서로 16인 전원의 순위·유사도를 무료로 공개해요. 카드를 탭하면 그 인물과 나를 자세히 비교해 볼 수 있어요.',
    disc2: '출생 시각 미상이라 시주 제외. 투자·정치 판단의 근거가 아닙니다.',
  },
  af: {
    forever: '영구',
    today: '오늘까지',
    daysLeft: '{{n}}일 남음',
    days: '{{n}}일',
    daysFor: '{{n}}일간',
    foreverAdv: '영구히',
    title: '광고 제거',
    buyAsk: '{{n}} 운을 사용해 광고를 {{span}} 없앨까요?',
    use: '사용',
    slow: '네트워크 응답이 늦어요. 운은 차감되지 않았어요.',
    done: '광고가 사라졌어요',
    already: '이미 영구 이용 중이에요.',
    doneMsg: '이제 {{span}} 광고가 보이지 않아요.',
    needCoins: '운이 부족해요',
    buyFail: '구매를 처리하지 못했어요. 운은 차감되지 않았어요.',
    on: '광고 없이 보고 있어요',
    note: '하단 배너가 사라지고, 이달의 운세·명식 추가·콘텐츠 진입에서 광고를 보지 않아도 바로 열려요. 기간제는 남은 기간 뒤에 이어붙어요.',
  },
  lg: {
    flowUp: '기운이 차오르며 올라서는 흐름이에요',
    flowEven: '큰 기복 없이 고르게 흐르는 때예요',
    flowIn: '힘을 안으로 다지며 다음을 준비하는 흐름이에요',
    lead: '당신 삶의 큰 흐름 곡선이에요',
    leadSub: '오르내림과 전환점을 미리 그려 봤어요. 각 시기의 자세한 이야기는 아래에서 열 수 있어요.',
    nowFlow: '지금 흐름',
    peak: '가장 빛나는 때',
    around: '{{a}}~{{b}}세 무렵',
    turns: '큰 전환점',
    flat: '비교적 고른 흐름이에요',
    turnN: '삶의 방향이 크게 바뀌는 지점 {{n}}곳',
    gentle: '완만하게 이어지는 흐름',
    freeB: '삶의 큰 흐름과 전환점',
    freeC: '을 곡선으로 볼 수 있어요.',
    paidB: '각 시기가 왜 그런지, 지금 무엇을 하면 좋은지, 전성기 활용법과 어려운 때 대처법',
  },
  jf: {
    bandIndep: '독립형',
    bizCreative: '아이디어를 내고 표현하는 결',
    bizWealth: '직접 부딪혀 성과를 만드는 결',
    bizIndep: '스스로 주도하고 개척하는 결',
    bizNone: '자기 주도로 움직이는 결',
    orgStructure: '체계를 세우고 조율하는 결',
    orgStability: '배우고 전문성을 쌓아가는 결',
    orgNone: '틀 안에서 꾸준히 쌓아가는 결',
    lead: '타고난 적성으로 어떤 결이 강한지',
    leadSub: '먼저 무료로 짚어 봤어요. 어울리는 직업까지는 아래에서 열 수 있어요.',
    cardCap: '타고난 적성 강점',
    bandCap: '일하는 결',
    funB: '적성 강점',
    funC: ' 미리보기예요 · 전체 풀이에선 이 결에 ',
    funD: '어울리는 직종',
    funE: ', 끌림과 능력의 간극, 직업 인생 흐름까지 짚어 드려요.',
  },
  wt: {
    tiltStable: '차곡차곡 모으고 지키는 결',
    tiltExpansive: '크게 벌이고 굴리는 결',
    tiltMixed: '모으는 결과 굴리는 결을 겸비',
    tiltWeak: '그릇부터 키우면 재물이 따라오는 결',
    subStable: '한 걸음씩 쌓아 안정적으로 불리는 힘이 있어요.',
    subExpansive: '기회를 보면 과감히 움직여 판을 키우는 힘이 있어요.',
    subMixed: '지킬 땐 지키고 벌일 땐 벌이는 균형 감각이 있어요.',
    subWeak: '지금은 버는 것보다 실력·바탕을 쌓을수록 재물이 붙는 때예요.',
    lead: '타고난 재물 밑그림을 무료로 짚어 봤어요',
    leadSub: '재물 그릇 크기·언제 크게 들어오는지·지키는 법은 아래에서 열 수 있어요.',
    capTilt: '재물 성향',
    capMake: '버는 힘',
    makeSelf: '직접 만들어 파는 힘',
    makeRoll: '자원을 굴리고 운용하는 힘',
    makeSelfSub: '아이디어·결과물을 만들어 그걸로 버는 통로가 열려 있어요.',
    makeRollSub: '이미 있는 자원·기회를 굴리고 운용해 버는 결이에요.',
    funA: '지금은 ',
    funB: '재물 밑그림',
    funC: ' 미리보기예요 · 전체 풀이에선 ',
    funD: '재물 그릇 크기',
    funE: ', 언제 크게 들어오는지, 새지 않게 지키는 법까지 짚어 드려요.',
  },
  f10: {
    flowUp: '기운이 차오르는 흐름',
    flowEven: '고르게 무르익는 흐름',
    flowIn: '안으로 다지는 흐름',
    toneRipe: '무르익음',
    toneBuild: '다지는 시기',
    dirUp: '지금보다 나에게 힘이 되는 기운이 더 크게 들어오는 방향이에요.',
    dirIn: '지금의 무르익은 기운을 안으로 다지며 실속을 챙기는 방향이에요.',
    dirEven: '지금의 좋은 결이 10년 뒤에도 고르게 이어지는 흐름이에요.',
    capOpen: '10년 뒤엔 나에게 힘이 되는 기운이 크게 들어오는 흐름이에요. 지금부터 방향을 잡아두면 그때 활짝 펴기 좋아요.',
    capRipe: '10년 뒤엔 흐름이 서서히 무르익어요. 지금 씨앗을 심어두면 그때 결실로 이어지기 좋아요.',
    capBuild: '10년 뒤엔 안으로 힘을 다지는 시기예요. 무리하기보다 기초를 탄탄히 해두면 그다음이 든든해져요.',
    lead: '10년 뒤 당신이 어떤 흐름에 들어서는지',
    leadSub: '지금과 무엇이 달라지는지, 큰 흐름을 미리 그려 봤어요. 그때의 자세한 이야기는 아래에서 열 수 있어요.',
    now: '지금',
    in10: '10년 뒤',
    ageRange: '{{a}}~{{b}}세',
    gaugeTitle: '10년 뒤, 기운이 나와 맞는 정도',
    nudge: '큰 방향을 지금 잡아둘수록 10년 뒤가 한결 수월해져요.',
    freeB: '10년 뒤 큰 흐름과 나와 맞는 정도',
    paidB: '그때 무엇이 구체적으로 달라지는지, 지금부터 무엇을 준비하면 좋은지',
  },
  lt: {
    errFormat: '생년월일을 YYYY-MM-DD 로 입력해 주세요.',
    errCalc: '계산에 실패했어요. 날짜를 다시 확인해 주세요.',
    sub: '생년월일만 알려주면 바로 볼 수 있어요. 가입도, 저장도 안 해요.',
    again: '다시 보기',
    go: '바로 보기',
    persona: '나의 성격유형',
    share: '친구에게 보내기',
    myIlju: '나의 일주',
    moreH: '태어난 시간까지 넣으면 더 정확해져요',
    moreBody: '여기까지는 태어난 날만으로 볼 수 있는 부분이에요. 오늘의 기운·궁합·시기 흐름은 태어난 시간이 있어야 제대로 나와요.',
    moreCta: '정확하게 보기 ›',
    moreNote: '지금 넣은 생년월일은 그대로 옮겨 담아요 — 다시 안 물어봐요.',
  },
  ny: {
    samjaeNone: '삼재 없음',
    samjaeNoneSub: '내년은 삼재에 들지 않는 해예요',
    samjaeDeul: '들삼재',
    samjaeDeulSub: '삼재가 들어오기 시작하는 해예요',
    samjaeNul: '눌삼재',
    samjaeNulSub: '삼재 한가운데를 지나는 해예요',
    samjaeNal: '날삼재',
    samjaeNalSub: '삼재가 물러나는 해예요',
    toneOpen: '상승세',
    toneMild: '무난',
    toneCare: '조심',
    capOpen: '내년은 나와 결이 잘 맞는 기운이 들어오는 흐름이에요. 준비한 걸 펼치기 좋아요.',
    capMild: '내년은 큰 기복 없이 무난하게 흐르는 편이에요. 나만의 속도로 다져 가면 좋아요.',
    capCare: '내년은 힘을 안으로 모으며 다지기 좋은 해예요. 무리한 확장보다 내실을 챙겨 보세요.',
    manage: '삼재는 피하는 해가 아니라, 몸·관계·살림을 살피며 내실을 다지는 해로 봐요.',
    upsell: '삼재는 같은 띠 모두의 이야기예요. 당신의 진짜 한 해는 사주 여덟 글자로 다시 계산해야 해요.',
    bokA: '이 해가 이름뿐인 ',
    bokB: '복삼재',
    bokC: '인지, 실제로 챙길 게 있는 해인지는 깊은 풀이에서 콕 짚어 드려요.',
    gaugeTitle: '내년 기운이 나와 맞는 정도',
    keywordTitle: '내년 키워드 미리보기',
    goodMonths: '내년 좋은 달',
    calNote: '곡선이 높은 달에 기운이 나와 잘 통해요(진하게 찬 점). 어떤 일에 좋은지는 깊은 풀이에서 달별로 짚어 드려요.',
    calNoteNone: '내년 좋은 달은 깊은 풀이에서 달별로 콕 짚어 드려요.',
    freeB: '내년 큰 기운 · 삼재 · 좋은 달',
    paidB: '내년 열두 달을 재물·애정·직업·건강으로 나눠, 개운법과 복/악삼재까지',
  },
  cp: {
    genAsk: '{{rel}} 궁합 풀이를 만들까요?',
    genFree: '추가 비용 없이 생성돼요.',
    genCost: '이 관계는 {{n}} 운이 필요해요.',
    ziweiCompat: '자미 궁합',
    compat: '궁합',
    relHintPrem: '관계마다 별도 풀이예요',
    relHint: '관계마다 별도로 풀어 드려요 — 고른 관계만 {{n}} 운이 들어요',
    sigSeason: '계절 상보',
    sigJaegwan: '상대 = 내 {{g}}',
    sigFill: '결핍 보완',
    sigSpouse: '배우자궁',
    tapHint: '작용을 탭하면 위 두 명식에서 해당 글자가 강조됩니다.',
    noCross: '두 명식 간 직접 합충형해가 없습니다.',
    me: '나',
    other: '상대',
    yearN: '{{y}}년',
  },
  sd: {
    posMonth: '사회생활에서 자연스럽게 끌리는 결',
    posYear: '집안·자라온 배경과 이어진 상',
    posHour: '삶의 후반·가정에서 그리는 상',
    posFallback: '끌리는 이성상',
    noStar: '뚜렷한 이상형 신호는 약해요',
    gungOnly: '실제 인연 중심',
    gungOnlyDesc: '뚜렷한 이상형(배우자성)이 원국에 드러나지 않아요 — 실제로 곁에 남는 사람(일지)이 더 큰 축이에요.',
    match: '끌림이 곧 결실',
    matchDesc: '끌리는 이상형과 실제 곁에 남는 사람이 거의 같은 결이에요. 첫 끌림이 그대로 이어지기 쉬워요.',
    clash: '정면충돌형',
    clashDesc: '이상형과 실제 배우자가 정면으로 대비돼요. 관계 내내 긴장이 있고, 크게 마음을 정해야 하는 시기가 옵니다.',
    friction: '은근한 갈등형',
    frictionDesc: '겉으로는 무난해도 결이 은근히 어긋나, 오래 함께할수록 피로가 쌓이기 쉬워요. 소통 방식을 미리 맞추는 게 처방.',
    split: '트랙 분리형',
    splitDesc: '연애 초반 끌린 상과 결혼까지 가는 상이 다른 결일 수 있어요. 끌림과 정착을 따로 보는 눈이 필요해요.',
    neutral: '뚜렷한 대비 없음',
    neutralDesc: '이상형과 실제 인연 사이에 큰 어긋남 신호는 약해요.',
    lblEvent: '변곡점',
    lblActive: '끌림 활성',
    lblResolve: '인연 정리',
    lblSettle: '안정 정착',
    lblConfirm: '관계 확정',
    elder: '연상 경향',
    elderDesc: '나보다 나이가 있는(연상) 인연에 마음이 기우는 경향이 있어요.',
    younger: '연하·케어 포지션 경향',
    youngerDesc: '연하이거나, 내가 챙겨주는 포지션의 인연에 기우는 경향이 있어요.',
    band0: '거의 일치',
    band1: '가벼운 어긋남',
    band2: '은근한 어긋남',
    band3: '은근한 긴장',
    band4: '강한 대비',
  },
  rt: {
    partRoot: '뿌리',
    subRoot: '타고난 바탕',
    partStem: '줄기',
    subStem: '자라온 터전',
    partFlower: '꽃',
    subFlower: '지금의 나',
    partFruit: '열매',
    subFruit: '맺어갈 결실',
    tier0: '떠 있어요',
    tier1: '뿌리가 얕아요',
    tier2: '뿌리가 있어요',
    tier3: '뿌리가 단단해요',
    tier4: '뿌리가 아주 깊어요',
    head3: '타고난 기운이 아주 단단히 뿌리내렸어요',
    sub3: '웬만한 흔들림엔 크게 휘둘리지 않는 힘이에요.',
    head2: '기운이 단단하게 자리 잡은 편이에요',
    sub2: '중심이 서 있어 밀어붙이는 힘이 있어요.',
    head1: '기운이 부드럽고 유연한 편이에요',
    sub1: '주변 흐름을 잘 읽고 맞춰가는 힘이 있어요.',
    head0: '기운이 가볍고 유연해서 변화에 잘 맞춰가요',
    sub0: '틀에 얽매이지 않고 상황에 맞춰 흐르는 결이에요.',
    lead: '타고난 기운이 얼마나 단단히 뿌리내렸는지',
    leadSub: '뿌리가 깊을수록 흔들림이 적어요. 네 자리의 뿌리 강도를 미리 그려 봤어요.',
    legend: '막대가 길수록 겉으로 드러난 기운이 속뿌리까지 단단히 닿아 있어요. 짧으면 겉에만 떠 있는 기운이에요.',
    countA: '{{n}}자리 중 ',
    countB: '{{n}}곳',
    countC: '이 속뿌리에 닿아 있어요.',
    tuNote: '태어난 시각을 몰라 열매(시) 자리는 뺐어요.',
    freeB: '네 자리의 뿌리 강도',
    freeC: '를 한눈에 볼 수 있어요.',
    paidB: '각 뿌리가 삶에서 무엇을 뜻하는지, 겉과 속의 차이, 약한 뿌리를 단단히 키우는 법',
  },
  ct: {
    bandOrg: '조직형',
    bandHybrid: '하이브리드형',
    bandPro: '전문가·프리랜서형',
    bandIndep: '독립사업형',
    headOrg: '타고난 기운이 \'조직\' 안에서 빛나는 결이에요',
    headHybrid: '조직과 내 사업, 두 결을 함께 지닌 유연형이에요',
    headPro: '전문성을 무기로 홀로서기 좋은 결이에요',
    headIndep: '타고난 기운이 \'내 사업\'에 가까운 결이에요',
    subOrg: '체계와 소속 안에서 신뢰를 쌓아 올릴 때 힘이 나요. 어느 쪽이 더 낫고 못하고가 아니라, 나에게 맞는 결이 이쪽이라는 뜻이에요.',
    subHybrid: '상황에 따라 조직으로도, 내 사업으로도 갈 수 있어요. 한쪽으로만 몰지 않아도 되는 게 오히려 강점이에요.',
    subPro: '조직에 기대기보다 나만의 전문성으로 자리를 만들 때 잘 풀려요. 조직 경험을 발판 삼아 홀로서기로 이어가기 좋아요.',
    subIndep: '내 판을 직접 이끌 때 가장 나다워요. 다만 어느 쪽이 우월한 게 아니라, 타고난 성향이 이쪽이라는 의미예요.',
    bizCreative: '새로운 걸 만들고 나를 표현하는 힘',
    bizWealth: '직접 부딪혀 현실 성과를 만드는 힘',
    bizIndep: '스스로 판을 이끄는 독립심',
    bizNone: '자기 주도로 움직이는 힘',
    orgStructure: '조직과 체계 안에서 자리를 잡는 힘',
    orgStability: '안정과 신뢰를 차곡차곡 쌓는 힘',
    orgNone: '틀 안에서 꾸준히 쌓아가는 힘',
    bothLine: '사업가 쪽으로는 {{biz}}, 조직 쪽으로는 {{org}}이 함께 있어요.',
    lead: '타고난 기운이 \'내 사업\'에 가까운지 \'조직\'에 가까운지',
    leadSub: '양팔저울로 미리 그려 봤어요. 자세한 이야기는 아래에서 열 수 있어요.',
    riskA: '타고난 그릇은 \'내 사업\'에 어울리지만, 지금 짜임새로는 실행 단계에서 ',
    riskB: '구조를 다지는 준비',
    riskC: '가 필요한 결이에요. 그래서 저울이 중앙 쪽에 가까워요.',
    partnerA: '혼자보다 ',
    partnerB: '동업·공동투자',
    partnerC: '에서는 지분·역할을 또렷이 해두면 탈이 적어요.',
    freeB: '내 성향의 무게추(사업가↔직장인)',
    freeC: '를 볼 수 있어요.',
    paidB: '나에게 맞는 직종·창업하기 좋은 시기·조직에서 잘 적응하는 법',
    biz: '사업가',
    org: '직장인',
    endBiz: '내 사업·독립',
    endOrg: '조직·안정',
  },
  ss: {
    fromLuck: '운에서 들어옴',
    fromLuckLong: '운에서 들어옴 — 원국에 없음 (대운·세운에서 작동)',
    fromLuckNoNatal: '운에서 들어옴 (원국에 없음)',
    noChart: '명식 정보가 없습니다.',
    intro: '신살은 사주에 색채를 더하는 보조 지표입니다(구조·격국이 중심). 길흉을 단정하기보다, 강점으로 살리고 조심할 결을 이해하는 축으로 봅니다. 기준 글자가 원국에 있으면 ✓(자리), 없으면 대운·세운에서 작동합니다.',
    gilsin: '길신',
    gilsinDesc: '도움·복록·귀인의 결 — 어려울 때 풀어 주는 기운.',
    teuksu: '특수살',
    teuksuDesc: '강한 색채 — 전문성·매력·결단처럼 양면을 가진 기운(쓰기 나름).',
    twelveDesc: '각 기둥의 지지를 년·월·일·시지 4기준 전부로 산출(기준에 따라 이름이 달라집니다).',
    byBase: '{{bases}} 기준',
    note: '※ 신살은 보조 지표입니다. 깊은 통변(영역별 풀이)은 구조·격국·용신과 함께 봅니다.',
  },
  tr: {
    evMove: '이사',
    evJob: '이직',
    evFound: '창업',
    evWed: '결혼',
    evDivorce: '이혼',
    evLoss: '투자손실',
    evIllness: '질병',
    evAccident: '사고',
    lead: '태어난 시간을 몰라도, 인생 사건으로 시(時)를 좁혀 드려요. 사건을 더 넣을수록 정확해져요.',
    birthLabel: '생년월일 (양력)',
    birthPh: '예: 19940316 (숫자만 입력해도 돼요)',
    sexLabel: '성별',
    placeLabel: '출생지',
    eventLabel: '인생 사건 (연도 + 유형)',
    yearPh: '연도 (예: 2023)',
    addEvent: '사건 추가',
    run: '후보 좁히기',
    payHint: '한 번 결제하면 사건을 더 넣어가며 계속 좁혀볼 수 있어요.',
    sigDirect: '입력한 인생 사건이 이 시간의 기운과 바로 통해요',
    sigMove: '이사·이동이 잦은 흐름과 잘 맞아요',
    sigHealth: '건강·몸의 변화 시기와 들어맞아요',
    sigAnchor: '그 해 겪은 사건의 변동과 맞아떨어져요',
    sigJohu: '계절 기운의 균형이 잘 맞는 시간이에요',
    sigHapchung: '글자들이 끌고 부딪히는 모양이 사건과 맞아요',
    headConfirmed: '1순위로 좁혀졌어요',
    headShortlist: '유력 후보 2~3개로 좁혔어요',
    headOpen: '아직 확정이 어려워요 — 사건을 더 넣어 주세요',
    disc: '※ 사건이 많을수록 정확해져요. 추정 결과이며, 정확한 풀이는 시를 확정한 뒤 원국 전체로 봅니다.',
  },
  jr: {
    colorMetal: '단정한 흰·은빛',
    capOpen: '지금 직장·합격의 문이 활짝 열리는 흐름이에요. 원서·면접·이직을 준비하면 흐름을 타기 좋아요.',
    capWarming: '직장·합격의 문이 서서히 열리는 중이에요. 자격·서류를 미리 갖춰 두면 열리는 때를 놓치지 않아요.',
    capQuiet: '지금은 문이 잠잠한 편이에요. 조급해하기보다 실력·자격을 다지며 다음 흐름을 준비하기 좋은 때예요.',
    sigGwan: '직장·자리의 기운이 들어와요',
    sigIn: '자격·합격의 기운이 받쳐 줘요',
    sigSiksang: '실력을 보여줄 기운이 도와요',
    sigJae: '결실·보상의 기운이 함께해요',
    sigNone: '지금은 기운이 조용한 편이에요',
    partGwan: '직장·자리가 열리는 기운',
    partIn: '자격·시험·서류를 뒷받침하는 기운',
    partSiksang: '면접·실무에서 실력을 보여줄 기운',
    partJae: '노력이 결실·보상으로 이어질 기운',
    bodyParts: '지금 흐름에는 {{parts}}이 함께 들어와 있어요. 준비해 둔 만큼 기회를 잡기 좋은 때예요.',
    bodyNatal: '지금은 특정 기운이 크게 도드라지진 않지만, 타고난 그릇에 직장·자격의 바탕이 자리해 있어요. 실력을 다지며 흐름이 열리는 때를 준비하면 좋아요.',
    bodyQuiet: '지금은 직장·자격의 기운이 잔잔한 편이에요. 조급해하기보다 방향을 정비하고 실력을 쌓아 두면 다음 흐름에서 문이 열려요.',
    teaserDow: '지원·면접에 힘을 주는 요일',
    teaserColor: '합격·면접에 힘을 주는 색',
    pressLabel: '지금은 취업보다 압박·시험대의 시기예요',
    pressBody: '지금 흐름은 자리(직장)를 여는 기운보다 나를 시험하는 압박의 결이 강해요. 무리해서 밀어붙이기보다, 이 압박을 자격·전문성으로 소화해 두면(살을 다스려 힘으로) 다음 흐름에서 문이 더 크게 열려요.',
    gaugeTitle: '취업 문이 열린 정도',
    nowTitle: '지금 취업 운의 결',
    gaeunTitle: '취업 개운 미리보기',
    locked: '좋은 방위 · 나머지 색·요일 · 지원·면접 실천법은 깊은 풀이에서',
    freeB: '가능성·유리한 시기',
    paidB: '합격 전략·맞는 직종·구체 개운법·이직 타이밍',
  },
  cr: {
    capOpen: '지금 그 사람과 이어질 흐름이 활짝 열려 있어요. 마음이 있다면 자연스럽게 다가가 보세요.',
    capWarming: '이어질 흐름이 서서히 데워지고 있어요. 서두르기보다 결이 무르익는 달을 노려 마음을 살짝 표현해 보세요.',
    capQuiet: '지금은 흐름이 차분한 편이에요. 조급해하기보다 나를 가꾸며 끌림이 도는 때를 준비하면 좋아요.',
    dohwaOpen: '지금 끌림이 강하게 도는 결이에요',
    dohwaBond: '지금 인연이 맺히려는 결이에요',
    dohwaFriction: '지금 살짝 엇갈리며 움직이는 결이에요',
    dohwaCalm: '지금은 조용한 결이에요',
    dohwaOpenSub: '설렘과 계기가 강하게 이는 시기예요. 마음을 표현하면 통하기 쉬워요.',
    dohwaBondSub: '서로 가까워지려는 결이에요. 가볍게 다가가면 자연스럽게 이어지기 좋아요.',
    dohwaFrictionSub: '밀고 당기는 결이에요. 조급함보다 여유로 다가가면 흐름이 부드러워져요.',
    dohwaCalmSub: '끌림이 아직 은근해요. 무리하기보다 나를 가꾸며 다음 흐름을 기다려요.',
    charmBorn: '타고난 끌림(매력)이 있어요',
    charmSubtle: '은근하게 스며드는 매력이에요',
    charmBornSub: '은은한 분위기로 사람을 끄는 매력이 있어, 마음을 표현하면 상대가 끌리기 쉬워요.',
    charmSubtleSub: '화려하기보다 서서히 스며드는 매력이라, 자주 마주치며 편안함을 쌓으면 마음이 열려요.',
    teaserDow: '다가가기 좋은 요일',
    teaserColor: '다가가기 좋은 색',
    gaugeTitle: '그 사람과 이어질 가능성',
    signalTitle: '끌림 신호',
    gaeunTitle: '다가가기 개운 미리보기',
    locked: '좋은 방위 · 나머지 색·요일 · 다가가는 구체 실천법은 깊은 풀이에서',
    freeB: '가능성·시기·다가갈 타이밍',
    paidB: '그 사람 마음·다가가는 법·이어질 이유',
  },
  notice: { hideDay: '하루 동안 보지 않기' },
  bd: {
    title: '이 정보로 명식을 만들까요?',
    noDate: '(생년월일을 못 읽었어요)',
    fromChat: '대화에서 추가',
    timeUnknown: '시각 모름',
    whyPlace: '태어난 곳은 진태양시 보정에 쓰여요 — 이게 없으면 시주가 달라질 수 있어요.',
    unknown: '모름',
    solar: '양력',
    lunar: '음력',
    male: '남성',
    female: '여성',
    placePh: '예) 서울 · 부산 · 밀라노',
    making: '만드는 중…',
    make: '명식 만들기',
    fillAbove: '위에서 못 채운 것을 골라 주세요.',
    fDate: '생년월일',
    fTime: '태어난 시각',
    fCal: '양력/음력',
    fSex: '성별',
    fPlace: '태어난 곳',
  },
  rg: {
    me: '나',
    workMoney: '일·돈',
    relation: '관계',
    growth: '성장',
    money: '돈',
    workHealth: '일·건강',
    etc: '기타',
    adminReset: '풀이 초기화 (관리자)',
    adminResetAsk: '이 풀이를 삭제하고 다시 생성할 수 있게 초기화할까요?',
    reset: '초기화',
    resetFail: '초기화 실패',
    admin: '관리자',
    resetDone: '초기화했어요. 다시 열거나 생성하면 새로 만들어져요.',
    coinN: '{{n}} 운',
    loading: '풀이를 불러오는 중…',
    toList: '목록으로',
  },
  rr: {
    dirN: '북쪽',
    dirS: '남쪽',
    dirE: '동쪽',
    dirW: '서쪽',
    dirNear: '가까운 곳',
    seasonW: '겨울',
    seasonSu: '여름',
    seasonSp: '봄',
    seasonA: '가을',
    colorWood: '맑은 청록빛',
    colorFire: '따뜻한 붉은빛',
    colorEarth: '포근한 노란·베이지빛',
    colorMetal: '맑은 흰·은빛',
    colorWater: '깊은 남색빛',
    dowThu: '목요일',
    dowTue: '화요일',
    dowSat: '토요일',
    dowFri: '금요일',
    dowWed: '수요일',
    toneOpen: '열려 있어요',
    toneWarming: '서서히 열려요',
    toneQuiet: '지금은 조용해요',
    capOpen: '옛 인연과 다시 이어질 문이 열려 있는 흐름이에요. 마음이 있다면 지금 진심을 전해 보세요.',
    capWarming: '문이 조금씩 열리는 중이에요. 서두르기보다 결이 무르익는 시기를 노려 보세요.',
    capQuiet: '지금은 문이 잠잠한 편이에요. 무리한 연락보다 나를 가꾸며 때를 기다리는 게 좋아요.',
    gungOpen: '지금 열리는 결이에요',
    gungBond: '지금 맺히는 결이에요',
    gungFriction: '지금 살짝 부딪히며 움직이는 결이에요',
    gungCalm: '지금은 잠잠한 결이에요',
    gungOpenSub: '인연의 자리가 열리는 시기예요. 다시 마주할 계기가 생기기 쉬워요.',
    gungBondSub: '인연의 자리가 이어지려는 결이에요. 관계를 다시 매듭짓기 좋은 때예요.',
    gungFrictionSub: '자리가 흔들리며 움직여요. 감정보다 차분함으로 다가가면 결이 부드러워져요.',
    gungCalmSub: '자리가 아직 고요해요. 억지로 열기보다 나를 채우며 다음 흐름을 기다려요.',
    teaserDow: '인연이 열리는 요일',
    teaserColor: '인연을 부르는 색',
    gaugeTitle: '재회의 문이 열린 정도',
    seatTitle: '인연의 자리',
    dirTitle: '인연 기운의 방향·계절',
    dirBodyA: '당신의 인연 기운은 ',
    dirBodyB: '에 무르익고, ',
    dirBodyC: ' 방향의 기운과 잘 통해요.',
    gaeunTitle: '연락 개운 미리보기',
    locked: '좋은 방위 · 나머지 색·요일 · 구체 실천법은 깊은 풀이에서',
    freeA: '무료로는 ',
    freeB: '가능성·시기·방향',
    freeC: '까지 볼 수 있어요.',
    paidA: '깊은 풀이에선 ',
    paidB: '상대의 마음·구체 개운법·다시 이어질 이유',
    paidC: '까지 짚어 드려요.',
  },
  capture: { start: '캡쳐', save: '저장', saving: '만드는 중…', pickHint: '담을 정리를 골라 주세요', saved: '저장했어요', savedMsg: '이미지로 남겼어요.', fail: '저장하지 못했어요', failMsg: '잠시 후 다시 시도해 주세요.' },
  crop: { title: '사진을 칸에 맞춰 주세요', sub: '끌어서 옮기고 − ＋ 로 크기를 맞춰요. 보이는 그대로 저장돼요.', working: '자르는 중…', use: '이대로 쓰기' },
  speech: { title: "말투", row: "반말로 대화하기", sub: "끄면 존댓말로 이야기해요. 언제든 바꿀 수 있어요.", failTitle: "저장하지 못했어요", failMsg: "잠시 뒤 다시 시도해 주세요." },
  pay: { working: "결제를 확인하고 있어요…", okTitle: "충전됐어요", okMsg: "{{coins}} 운이 들어왔어요.", failTitle: "충전하지 못했어요", failMsg: "결제를 확인하지 못했어요.", canceled: "결제가 취소됐어요.", back: "충전 화면으로" },
  chat: { today: "오늘", yesterday: "어제", },
  adult: { needVerifyTitle: '본인인증이 필요해요', needVerifyMsg: '만 19세 이상인지 확인한 뒤에 켤 수 있어요.', verifySoon: '본인인증을 준비하고 있어요. 조금만 기다려 주세요.', title: '성인 대화', row: '만 19세 이상입니다', sub: '켜면 속궁합·애정 이야기를 에두르지 않고 나눠요.' },
  screen: {
    shared: '공유받은 풀이',
    register: '차트 등록',
    coinhistory: '결제/충전 내역',
    charts: '만세력',
    moment: '모먼트',
    light: '가볍게 보기',
    biorhythm: '바이오리듬',
    coins: '운 충전',
    market: '마켓',
  },
  shared: { title: '공유받은 풀이', loading: '풀이 불러오는 중…', notFound: '이 공유 링크의 풀이를 찾을 수 없어요.', goMine: '내 운세 보러 가기 ›', alsoMine: '나도 내 운세 보기 ›', foot: '{{app}} · 사주·자미두수·타로 운세' },
  chartPick: { fromFriend: "친구", friendLockTitle: "친구 명식은 고칠 수 없어요", friendLockMsg: "친구가 공개한 명식을 담아 온 것이라 생년월일이 넘어오지 않아요. 지우고 다시 담을 수는 있어요.", self: "본인", rep: "대표", title: '어떤 명식을 볼까요?', why: '고른 명식으로 이 대화를 이어 갑니다. 나중에 바꿀 수도 있어요.', new: '직접 입력', all: '전체 {{n}}개 보기', fold: '접기' },
  appInvite: { title: '앱에서 더 편하게', sub: '알림·오늘의 운세는 앱에서 바로 받아볼 수 있어요.', open: '앱으로' },
  appName: '니운내운',
  tagline: '나와 타인을 이해하는 AI 나침반',
  // 홈 카드 개인화 티저 — 대표 명식으로 계산한 '내 얘기' 한 줄(계산=lib/content/homeTeaser.ts, 문구=여기).
  //   카드의 정적 설명(menu.*Desc) 자리를 이 문장이 대체한다(명식 없으면 정적 설명으로 폴백).
  teaser: {
    career: '사업가형 {{biz}}% · 조직형 {{org}}%',
    newyear: '올해 키워드 · {{keyword}}',
    flow: '지금 {{n}}번째 구간 · 전환점 {{turns}}번',
    crush: '{{year}}년 {{months}}월 · 끌림이 도는 달',
    reunion: '{{year}}년 {{months}}월 · 연락이 닿기 좋은 달',
    job: '{{years}}년 · 문이 열리는 해',
    raw: '{{text}}', // image·talent·mission — 문구 자체를 엔진(lib/content/elementPhrases)이 한국어로 산출해 그대로 꽂는다(3언어 동일 값 — 기존 newyear.keyword와 동일 방식)
  },
  // ★첫 실행 온보딩(App Store 4.3: '운세앱'→'AI 자기이해 도구' 인상 전환) — 신규 설치 1회.
  onb: {
    skip: '건너뛰기', next: '다음', start: '내 분석 시작하기',
    t1: "AI가 분석하는 '나'",
    b1: '니운내운은 운세 앱이 아닙니다. 사주를 엔진으로, 당신이 어떤 사람인지 분석하는 자기이해 도구입니다.',
    t2: '당신만의 명식을 계산합니다',
    b2: '생년월일시를 정밀 만세력(진태양시·시대보정)으로 계산해, 누구와도 같지 않은 당신만의 분석을 만듭니다.',
    t3: '이런 걸 알게 됩니다',
    l1: '나는 어떤 사람인가 — 성격·강점', l2: '왜 내 관계는 반복되는가', l3: '어떤 일이 나에게 맞는가', l4: '올해 무엇을 준비할까',
    t4: '이렇게 분석해 드려요', pvBadge: '예시', pvType: '테토형', pvScale: '테토 63%', pvLine: '결단력 있고 주도적. 다만 가끔은 쉬어가는 여유가 큰 힘이 돼요.', pvNote: '생년월일시만 넣으면 당신만의 분석이 나와요',
  },
  // ★App Store 4.3(스팸/중복) 대응 — '계산됨(computed)' 가시화(ComputedNote 컴포넌트가 참조).
  //   이 앱 분석이 제네릭 호로스코프가 아니라 유저 생년월일로 알고리즘 계산된 개인 결과임을 화면에서 바로 보이게.
  computed: {
    title: '당신의 생년월일로 계산한 개인 명식',
    body: '진태양시·경도·역사적 서머타임까지 보정해 만세력을 계산하고, 40여 개 고전 규칙을 이 명식에 적용해요. 누구와도 같지 않은 결과예요.',
    badge: '내 생년월일로 계산됨',
    more: '지장간·충·합·형, 신살, 대운(운의 흐름)까지 계산하고, 사주와 자미두수 두 전통을 교차검증해요.',
  },
  menu: { typematch: '유형 대 유형', typematchDesc: '상대 생일 없이 일주로 짧게 대조',  mycard: '나의 카드', mycardDesc: '내 유형을 한 장에 모아 보기', 
    relationmap: '관계 지도', relationmapDesc: '내가 등록한 사람들이 나에게 어떤 결인지 한 장으로',
    'taemong': '태몽 풀이', 'taemongDesc': '꿈에 나온 것으로 읽는, 아이를 기다리는 마음', 'taemongTileDesc': '용·호랑이·잉어… 태몽 상징을 무료로',
    'egenteto': '에겐·테토 성향',
    lookback: '되돌아보기', lookbackDesc: '그날 운세와 내 기록을 나란히',
    myeongsik: '명식 등록', myeongsikDesc: '생년월일로 내 명식 등록·관리',
    manse: '만세력', manseDesc: '날짜별 사주·차트 관리', timeResolve: '태어난 시 찾기', timeResolveDesc: '시간 몰라도 인생 사건으로 시를 추론',
    ziwei: '자미두수', ziweiDesc: '명반·12궁 성요 풀이',
    taro: '타로', taroDesc: '카드로 보는 오늘',
    today: '오늘의 운세', todayDesc: '매일 바뀌는 일운',
    month: '이달의 운세', monthDesc: '이번 달 분야별 흐름',
    compatMarriage: '결혼 궁합', compatMarriageDesc: '평생을 같이 갈 수 있는 사이인가', compatCoworker: '직장 동료 궁합', compatCoworkerDesc: '같이 일하면 어떤 결이 나오나', compatSenior: '윗사람 궁합', compatSeniorDesc: '상사·멘토와 어떻게 맞물리나', compatBusiness: '동업 궁합', compatBusinessDesc: '같이 벌면 어디서 갈리나', compatFamily: '가족 궁합', compatFamilyDesc: '부모·형제와의 결과 거리', compatFriend: '친구 궁합', compatFriendDesc: '오래 갈 사이인지 견줘 보기', compat: '궁합', compatDesc: '관계역학 딥 분석',
    premium: '깊은 풀이', premiumDesc: '딥 통변·전 영역', premiumTag: '운',
    timeline: '인생 타임라인', timelineDesc: '10~100세 시기별 흐름',
    pet: '나의 반려동물', petDesc: '우리 아이의 타고난 특징',
    love: '나의 애정흐름', loveDesc: '이상형·만날 사람 디테일 분석',
    lifegraph: '인생 그래프', lifegraphDesc: '대운별 인생 흐름 곡선·전환점',
    newyear: '신년운세', newyearDesc: '올해 종합·달별·삼재',
    roots: '명식의 뿌리', rootsDesc: '드러난 나·품은 힘·진짜 단단한 기운',
    image: '비치는 나', imageDesc: '남에게 보이는 첫인상·분위기',
    impression: '사람들이 보는 나', impressionDesc: '첫인상부터 깊은 사이까지 비치는 나',
    mission: '나의 사명', missionDesc: '무엇을 위해 태어났는지',
    persona: '성격유형', personaDesc: '사주로 보는 나의 16유형', egen: '에겐 vs 테토', attach: '애착유형', mbti: '사주 MBTI', traits: '나의 특징', selfAnalysis: '나 분석', selfAnalysisDesc: '성격·기질·오행 밸런스를 한눈에 종합 분석', relationPattern: '관계 패턴', relationPatternDesc: '왜 내 관계는 반복되는가 — 타고난 관계의 결', personal: '퍼스널 오행', personalDesc: '내 오행에 맞는 컬러·코디·메이크업·자동차 색', gem: '내 사주 보석', gemDesc: '생일 보석은 사실 나와 안 맞아요 — 나를 살리는 진짜 보석', sokgunghap: '속궁합', sokgunghapDesc: '두 사람의 성적 궁합 (성인·재미)', community: '커뮤니티', communityDesc: '사주·연애·고민을 함께 나누는 공간', joseonjob: '조선시대 직업', lovestyle: '연애 스타일', bok: '타고난 복', pastlife: '전생 이야기', healing: '나만의 힐링 방법',
    taegil: '택일', country: '내가 살기 좋은 곳', countryDesc: '내 기운에 맞는 나라·기후', taegilDesc: '결혼·이사·계약 좋은 날',
    luck: '오늘의 행운', luckDesc: '행운의 색·방향·숫자',
    zodiac: '띠·별자리', zodiacDesc: '오늘의 띠·별자리 운세',
    name: '이름풀이', nameDesc: '이름 속 오행의 결',
    dream: '꿈해몽', dreamDesc: '꿈 키워드로 찾기',
    dayPillar: '일주론', dayPillarDesc: '태어난 날로 보는 나의 기질', career: '사업가의 나', careerDesc: '사업가 vs 직장인, 두 길 풀이', gaeun: '맞춤 개운법', gaeunDesc: '지금 운에 맞춰 운을 살리는 법', followupDesc: '풀이에 더 묻고 싶은 한 가지', talent: '나의 타고난 재능', celeb: '나와 닮은 연예인', celebDesc: '배우·아이돌 사주와 나를 견주는 재미', talentDesc: '재능·좋아하는 일·돈 다루는 법', numerology: '수비학', numerologyDesc: '수로 보는 인생 방향·재능', astrology: '별자리·점성술', astrologyDesc: '내 별자리 + 네이탈 차트, 두 관점 깊이 풀이',
    child: '자식운', childDesc: '자녀 인연·기질·부모로서의 나', future10: '10년 뒤 나의 모습', future10Desc: '대운·세운으로 그리는 10년 뒤', reunion: '재회운', reunionDesc: '옛 인연과 다시 이어질 시기·가능성', crisis: '관계의 고비', crisisDesc: '흔들리는 시기를 구조로 — 점이 아니라 자리와 힘으로', crush: '짝사랑 인연운', crushDesc: '내 마음이 닿을지·끌릴 사람의 결·다가갈 시기', job: '취업·이직운', jobDesc: '취업·이직·합격·시험이 잘 풀리는 시기', jobfit: '나에게 어울리는 직업', jobfitDesc: '타고난 적성으로 어울리는 직업·끌림과 능력의 간극', wealth: '재물 딥리포트', wealthDesc: '타고난 재물 그릇·유형·언제 크게 들어오고 어떻게 지키는지', reunionAsk: '재회 가능할까?', reunionAskDesc: '무료로 보는 재회 가능성·연락 좋은 달', crushAsk: '그 사람과 이어질까?', crushAskDesc: '무료로 보는 매력·썸이 무르익는 달', jobAsk: '취업 언제 될까?', jobAskDesc: '무료로 보는 취업·합격운 열리는 시기',
    saju: '사주', sajuDesc: '원국·타임라인·궁합', ziweiHub: '자미두수', ziweiHubDesc: '명반·운한·궁합',
    // 상단 카테고리 칩(짧은 라벨) — 섹션 제목은 길어 칩엔 안 맞는다(daniel 08-06)
    // ★2026-08-06(2차) daniel 확정 — 노출 카테고리 4개 + 숨겨진 콘텐츠(추천으로만 도달)
    secLove: '연애', secLoveDesc: '궁합 · 인연 · 마음이 닿는 때',
    secToday: '오늘의 운세', secTodayDesc: '오늘 · 이달 · 올해의 흐름',
    secSelf: '나 분석', secSelfDesc: '성격 · 기질 · 남에게 비치는 나',
    secWork: '직업·재물', secWorkDesc: '적성 · 취업 · 재물 그릇',
    secHidden: '더 보기', secHiddenDesc: '추천으로 만나는 콘텐츠',
    chipLove: '연애', chipToday: '운세', chipSelf: '나', chipWork: '직업·재물', chipHidden: '더 보기',
    secLife: '라이프', secLifeDesc: '타로 · 자미 · 가볍게 즐기는 이야기',
    secTool: '도구', secToolDesc: '만세력으로 직접 찾아보기',
    chipLife: '라이프', chipTool: '도구',
    chipAll: '전체',
    secContent: '인기', // ★숏컷 섹션(주제 축 밖) — 최상단 한 줄
    // (구) 가격·체계 축 라벨 — 주제 축 재편으로 미사용. 되돌릴 때를 위해 남겨 둠(3개 언어 동일).
    secFree: '오늘·명식', secPremium: '나를 이해하기', secSpecial: '스페셜', secDeep: '나에 대해 알기', secLight: '가볍게 보기',
    viewCard: '카드', viewList: '리스트', // 홈 보기 방식 토글(daniel)
    todayTileDesc: '오늘 하루 흐름', monthTileDesc: '이번 달 흐름', newyearTileDesc: '올해 키워드·열두 달', personaTileDesc: '사주 성격유형', taegilTileDesc: '좋은 날 택일', luckTileDesc: '오늘의 행운', zodiacTileDesc: '띠·별자리 운세', nameTileDesc: '이름 소리 오행', dreamTileDesc: '꿈 해몽', egenTileDesc: '내 사주는 에겐? 테토?', attachDesc: '명식과 설문을 나란히', mbtiTileDesc: '사주로 보는 내 MBTI', joseonjobTileDesc: '내 사주로 보는 조선시대 직업', lovestyleTileDesc: '내 연애 세포는?', bokTileDesc: '내 타고난 복은?', pastlifeTileDesc: '나의 전생은?', healingTileDesc: '나에게 맞는 쉼은?',
    // ★secHotDesc 는 '요즘 가장 많이 찾는 질문 — 무료로 확인하고 더 깊이 봐요' 였다(08-06 폐기).
    //   지금 인기 섹션 첫 카드가 **유료** 재물 딥리포트라 '무료로 확인하고'가 사실과 달랐다.
    secPremiumDesc: '나는 어떤 사람인지 — 사주·자미로 깊이 분석해요', secContentDesc: 'AI가 정밀하게 풀어주는 깊은 콘텐츠', secHotDesc: '요즘 많이 보는 것만 모았어요', secDeepDesc: '나를 더 깊이 들여다보는 분석', secLightDesc: '가볍게 즐기는 오늘의 재미',
  },
  bug: {
    title: '버그 제보', send: '보내기',
    desc: '불편했던 점이나 이상하게 동작한 부분을 알려 주세요. 어떤 화면에서 무엇을 했을 때 그랬는지 적어 주시면 훨씬 빨리 고칠 수 있어요.',
    what: '무슨 일이 있었나요?',
    placeholder: '예) 궁합 풀이를 눌렀는데 화면이 계속 돌기만 해요',
    contact: '답장 받을 곳 (선택)', contactHint: '이메일 등 — 비워 두셔도 됩니다',
    autoInfo: '앱 버전·기기 종류가 함께 전송돼요(문제를 찾는 데만 씁니다).',
    doneTitle: '제보해 주셔서 감사합니다',
    doneBody: '보내주신 내용은 개발자가 직접 확인하고 있어요. 빠른 수일 내에 수정하겠습니다.',
    failTitle: '보내지 못했어요',
    failBody: '잠시 후 다시 시도해 주세요. 계속 안 되면 아래 주소로 보내 주셔도 됩니다.',
  },
  relmapCard: { title: '관계 지도', lead: '{{name}}님은 {{role}}이에요', more: '지도에서 전부 보기 ›' },
  relmap: {
    mapCap: '지도에는 자리마다 가까운 {{n}}명을 그렸어요 — 나머지 {{r}}명은 아래 목록에 있어요.',
    joinedTitle: '새로 들어왔어요', joinedBody: '{{n}}명이 지도에 자리를 잡았어요.',
    invite: '초대 링크 보내기', inviting: '링크 만드는 중…',
    inviteNote: '친구가 링크를 열어 생년월일을 넣으면 내 지도에 자리를 잡아요. 링크는 7일 뒤 닫혀요.',
    shareMsg: '내 관계 지도에 자리 하나 맡아 줘 — 생년월일만 넣으면 돼',
    needLoginTitle: '로그인이 필요해요',
    needLoginBody: '친구가 넣은 정보를 내 계정으로 받아야 해서, 초대 링크는 로그인 후에 만들 수 있어요.',
    title: '관계 지도', me: '나', count: '{{n}}명', hint: '가까울수록 케미가 잘 맞는 사람',
    tapHint: '점을 누르면 그 사람과 나의 궁합이 열려요.',
    list: '잘 맞는 순', summary: '내 지도는 이런 모양이에요',
    emptyOthers: '아직 나 혼자예요. 가족·친구의 생년월일을 더하면 그 사람이 나에게 어떤 결의 사람인지 지도에 떠요.',
    emptyMe: '먼저 내 명식을 등록해 주세요. 그래야 관계를 볼 기준이 생겨요.',
    addFriend: '사람 추가하기', addMe: '내 명식 등록하기',
    giving: '내가 쏟는 쪽이 더 많은 구성이에요. 챙기는 보람은 크지만, 받는 자리도 하나쯤 있어야 오래갑니다.',
    taking: '나를 채워주는 사람이 많은 구성이에요. 받은 만큼 흘려보낼 곳을 만들면 기운이 고이지 않아요.',
    balanced: '주고받는 기운이 고르게 도는 구성이에요. 어느 한쪽으로 쏠리지 않아 관계에서 크게 지치지 않습니다.',
    lacking: '내 사주엔 {{el}} 기운이 없어요 — 그 기운을 가진 사람이 특히 귀합니다.',
    adjusted: '태어난 날은 {{from}}이지만 사주 전체에 {{to}} 기운이 몰려 있어, 그쪽으로 봤어요.',
    caution: '조심할 점', advice: '이렇게 지내면 좋아요',
    more: '지도를 더 채우려면',
    moreBody: '사람이 늘수록 내 관계의 결이 또렷해져요. 아직 안 넣은 사람이 있다면 생년월일만으로 바로 자리를 잡습니다.',
  },
  lang: { title: '언어', pick: '언어 고르기', auto: '자동', autoNote: '기기 언어 · 지금은 {{l}}', uiEnglish: '화면 글자는 English', hint: '화면 글자와 풀이 본문을 함께 바꿔요.' },
  splash: { tagline: '다섯 기운이 이어\n오늘의 나를 읽다' },
  mycard: { axisIlju: '일주', axisPersona: '성격유형', axisMbti: 'MBTI', axisEgen: '에겐·테토', axisBok: '타고난 복', teto: '테토', egen: '에겐', both: '반반', tetoScore: '테토 {{n}}점', title: '나의 카드', lead: '유형은 입구예요. 한 칸을 누르면 그 축을 계산한 본문으로 들어가요.', more: '자세히 ›', noChart: '명식을 먼저 등록해 주세요.', register: '명식 등록하기', foot: '같은 유형이어도 대운·강약이 다르면 본문은 다르게 나와요. 유형은 입구일 뿐, 글은 당신 것이에요.' },
  typematch: { tagStemHap: '천간 합', tagSaeng: '기운 상생', tagBrHap: '지지 합', tagSamhap: '삼합', tagChung: '일지 충', title: '유형 대 유형', lead: '상대가 자기 일주 두 글자만 말해 주면 돼요. 생일을 몰라도 대조할 수 있어요.', me: '나', pick: '상대의 일주를 고르세요', none: '두 글자 사이에 걸리는 합·충이 없어요. 좋고 나쁨이 아니라, 이 축에서는 특별한 끌림도 부딪힘도 안 잡힌다는 뜻이에요.', limit: '이건 일주 두 글자만 본 거예요. 태어난 시간·달까지 보면 훨씬 정확해요.', goCompat: '생일로 정확한 궁합 보기', noChart: '내 명식을 먼저 등록해 주세요.' },
  // 만세력 화면 — ★명리 **용어는 한자 그대로**, 설명만 그 언어로(Boss 2026-08-27)
  ms: {
    aiCall: 'AI 선생님 부르기',
    aiCallSub: '고르면 입력칸에 이름이 들어가요. 묻고 싶은 말을 이어서 쓰면 그 선생님이 답해요.',
    // ★「글자 바꿔 보기」 — 원국 여덟 글자를 충·합 짝으로 갈아 끼운 «가정» 명식(Boss 2026-09-01)
    swapOff: '원국',
    swapView: '보기',
    swapBuyTitle: '글자 바꿔 보기',
    swapBuyMsg: '이 명식의 여덟 글자를 충·합 짝으로 바꿔 보는 기능이에요. {{coins}} 운으로 이 명식에 한 번만 열면 계속 볼 수 있어요.',
    swapBuyOk: '{{coins}} 운으로 열기',
    swapNoteChung: '지금은 여덟 글자를 각자의 충(沖) 짝으로 바꿔 본 가정이에요. 실제 명식이 아니고, 십신·지장간도 바뀐 글자를 따라간 값이에요.',
    swapNoteHap: '지금은 여덟 글자를 각자의 합(合) 짝으로 바꿔 본 가정이에요. 실제 명식이 아니고, 십신·지장간도 바뀐 글자를 따라간 값이에요.',
    lunar: '음력',
    timeUnknown: '시 미상',
    approx: '추정',
    placeUnknown: '출생지 미상',
    tabNatal: '원국·운세',
    tabElem: '오행·강약',
    tabIlju: '일주론',
    tabZiwei: '자미두수',
    ageN: '{{n}}세',
    ageFull: '만 {{n}}세',
    monthN: '{{n}}월',
    samhyeong: '삼형',
    three: '3자',
    tierHi: '강',
    tierMid: '중',
    tierLo: '약',
    showHanja: '漢 한자',
    showHangeul: '가 한글',
    brief: '간략히',
    detail: '상세 분석',
    byPillar: '자리별 적중',
    selectAll: '전체 선택',
    unselectAll: '전체 해제',
    coreGyeok: '핵심 격',
    repElem: '대표 오행',
    repTengod: '대표 십성(격)',
    gangyakAxis: '강약축',
    allyPower: '우호세력',
    strengthMore: '{{a}}·{{b}} 특징 자세히 보기 ›',
    problemFix: '문제점·대응법',
    pickPoint: '시점',
    strongest: '최강',
    todayLuck: '오늘 기준 현재운세 보기',
    viewCols: '옆으로 보기',
    viewNest: '벤다이어그램',
    luckWord: '운',
    countSuffix: '개',
    collapse: '▲ 접기',
    byStrength: '작용이 강한 순 — 충·합 강 / 형·극 중 / 해·파 약',
    daeunsu: '대운수',
    tapDaeun: '(탭하면 그 대운의 세운 펼침)',
    tapReflect: '(탭하면 위 명식에 반영)',
    tapReflectDay: '(탭하면 위 명식에 일운 반영)',
    dayCal: '{{y}}년 {{m}}월 일진 달력',
    dow: '일,월,화,수,목,금,토',
    today: '오늘',
    myChart: '내 명식',
    ziweiIntro: '사주와는 별개의 운명 체계예요. 태어난 시각으로 열두 자리(명궁·재물·관록·배우자 등)에 별을 배치해, 삶의 각 영역에 드는 기운을 봅니다. 사주를 보조해 교차로 참고해요.',
    bureau: '국',
    ziweiFlow: '자미두수 운흐름',
    ziweiFlowSub: '대한(10년) · 그 시기 천간이 일으키는 비성사화',
    noteTendency: '* 경향 안내예요. 정확한 풀이는 원국 전체로 봐야 합니다.',
    eumYangSkew: '음양 쏠림',
    strongLead: '이렇게 강하면',
    useIt: '살리는 법',
    balanced: '치우침이 크지 않아 무난해요.',
    hannan: '한난(조후)',
    joseup: '조습',
    warm: '따뜻',
    cold: '차가움',
    wet: '습함',
    dry: '건조',
    elemSkew: '오행 쏠림',
    strongEl: '{{el}} 강함',
    noteSkew: '* 쏠림 경향 안내예요(대응법=개운법). 정확한 풀이는 원국 전체로 봐야 합니다.', mine: '내 유형', pro: '강점', con: '주의', dir: '방향 (用神)', tabNatalDesc: '팔자(연·월·일·시 여덟 글자)와 숨은 기운(지장간), 글자끼리의 합·충·형·해·파 관계·신살·길성, 그리고 대운·세운·월운·일운으로 보는 시기별 흐름(운세)까지 한자리에서 봐요.', tabElemDesc: '내 글자들이 목·화·토·금·수 다섯 기운 중 무엇에 쏠렸는지·그게 나에게 어떤 역할(십성)인지, 그리고 내 힘(일간)이 강한지 약한지·무엇으로 균형을 잡으면 좋은지 함께 봐요.', tabIljuDesc: '태어난 날의 간지(일주)로 보는 나의 기질이에요. 일간은 나 자신, 일지는 내가 딛고 선 자리이자 배우자궁이라, 성격·연애·직업의 결이 여기서 많이 드러나요. 60갑자 전체는 일주론 화면에서 볼 수 있어요.', tabZiweiDesc: '사주와는 별개의 운명 체계예요. 태어난 시각으로 열두 자리(명궁·재물·관록·배우자 등)에 여러 별을 배치해, 삶의 각 영역에 어떤 기운이 드는지 봅니다. 사주를 보조해 교차로 참고해요(시각을 알아야 정확).', strongTitle: '신강 (身強)', weakTitle: '신약 (身弱)', strongWhat: '일간이 뿌리 깊고 비겁·인성이 받쳐주는 사주. 자기 주관이 뚜렷하고 추진력·독립심이 강합니다.', strongGood: '주도적이고 위기에 강하며, 자기 힘으로 밀어붙이는 돌파력과 리더십이 있습니다.', strongCare: '힘이 과하면 독선·고집으로 흐르고 주변과 타협이 어려울 수 있습니다.', strongKey: '식상·재성·관성으로 힘을 덜어 균형 잡는 게 관건 — 일·재물·관계·책임에 힘을 쓸 때 성취가 큽니다.', weakWhat: '일간이 약하고 식상·재성·관성에 기운을 내주는 사주. 유연하고 섬세하며 환경에 잘 맞춥니다.', weakGood: '협조·조율에 능하고 적응력이 좋아, 주변의 도움과 흐름을 활용하는 데 강합니다.', weakCare: '힘이 너무 빠지면 의존적이거나 우유부단해지고 자신감이 약해질 수 있습니다.', weakKey: '인성·비겁으로 보강하는 게 관건 — 배움·휴식·내 편(동료)을 통해 힘을 채울 때 안정됩니다.', expand: '▼ 펼쳐 보기', skewLead: '이렇게 쏠리면', remedy: '대응법(개운)', tgSkew: '기운(십성) 쏠림' },
  person: { iShare: '내 명식을 이 친구에게 보여주기', iShareOn: '지금 이 친구는 내 명식을 볼 수 있어요.', iShareOff: '지금은 이 친구에게 안 보여요.', message: '메시지 보내기', me: '내 명식', mine: '내 명식', friend: '친구', tabChart: '명식', tabCompat: '관계', tabTalk: '대화', notShared: '아직 명식을 공개하지 않았어요.', gone: '친구 목록에 없는 사람이에요.', noMe: '내 명식을 먼저 등록해 주세요.', noChart: '볼 수 있는 명식이 없어요.', noCompat: '아직 궁합을 낼 수 없어요.', needMine: '내 명식을 등록하면 이 사람과의 궁합을 볼 수 있어요.', openManse: '만세력에서 자세히 보기', openCompat: '궁합 자세히 보기', talkLead: '이 사람을 대화에서 부르면, 상담가가 이 명식을 함께 보고 답해요.', mention: '대화에서 @{{name}} 부르기' },
  common: { needChart: '내 명식을 먼저 등록해 주세요.', loading: '올리는 중…', close: '닫기', send: '보내기', save: '저장',
    'later': '나중에',        // 나중에 — 유도 알림의 취소 쪽(대화 운 부족 등)
    retryLaterNoCharge: '잠시 후 다시 시도해 주세요. 운은 차감되지 않았어요.',
    'add': '추가',
    'more': '자세히',
    'confirm': '확인',
    'delete': '삭제',
    'edit': '수정',
    'retry': '다시 시도',
    'retryLater': '잠시 후 다시 시도해 주세요.',
    'tapToClose': '탭하여 닫기',
    back: '← 뒤로', login: '로그인', signup: '회원가입', logout: '로그아웃', loggingOut: '로그아웃 중…',
    comingSoon: '준비 중입니다.', error: '오류', loginOptional: '로그인 / 회원가입 (유료·저장 기능용 — 선택)',
    cancel: '취소', none: '없음',
    llmBusy: '지금 통변 생성이 일시적으로 어려워요. 잠시 후 다시 시도해 주세요.', // 방어: LLM 일시적 불가(사용량 한도·혼잡)
    llmMaking: '같은 풀이가 이미 만들어지는 중이에요. 잠시 후 다시 확인해 주세요.', // 생성 단일화(2026-08-01): 실패가 아니라 진행 중 — 재시도를 권하지 않는다
    genFailed: '풀이를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',           // 방어: 일반 생성 실패(원문 숨김)
  },
  auth: {
    privacyTalk: '대화는 이어보기를 위해 저장돼요. AI 학습에 쓰지 않고, 다른 사람이 볼 수 없어요. 언제든 지울 수 있어요.',
    'login': '로그인',
    signin: '로그인', signupTitle: '회원가입', email: '이메일', password: '비밀번호 (6자 이상)',
    toSignup: '계정이 없으신가요?  회원가입', toSignin: '이미 계정이 있으신가요?  로그인',
    needInput: '이메일과 비밀번호를 입력하세요.', signupDone: '확인 메일이 발송됐습니다. 메일 인증 후 로그인하세요.',
    or: '또는', google: 'Google로 계속하기', apple: 'Apple로 계속하기', naver: '네이버로 계속하기', processing: '로그인 처리 중…',
    subtitle: '사주와 자미두수를 결합한 복합적인 해석', note: '로그인은 선택이에요. 기기를 바꿔도 명식과 이용권을 그대로 쓰려면 연결해 주세요.',
    failedTitle: '로그인에 실패했어요',
  },
  register: {
    solarAdjust: '거주지 보정 {{sign}}{{min}}분 → 실제 {{time}} ({{siji}}시)',
    dstApplied: '서머타임 적용',
    tzBasis: '기준', needDate: '생년월일 8자리를 입력해 주세요.', next: '다음', prev: '이전', step0Desc: '정확한 분석을 위해 정보를 입력해주세요.', step1Desc: '태어난 날짜를 알려주세요. 음력이면 음력으로 골라 주세요.', step2Desc: '태어난 시간을 알면 더 정확해요. 모르면 그대로 넘어가도 괜찮아요.', step3Desc: '태어난 곳을 고르면 그 지역의 실제 태양시로 맞춰요.', stepTitle: '사주 정보 입력',
    placeHintNone: '지역마다 해 뜨는 시각이 달라 태어난 시가 갈릴 수 있어요. 고르지 않으면 한국 평균으로 계산해요.',
    placeHintSet: '이 지역의 실제 태양시로 태어난 시를 맞춥니다.',
    'pickCategory': '카테고리 선택',
    'catDelHint': '카테고리를 지우면 그 명식들은 ‘기타’로 옮겨져요. ‘기타’는 지울 수 없어요.',
    'catDeleteTitle': '카테고리 삭제',
    'editDone': '완료',
    'exactTime': '정확한 시각을 알아요 (출생지 경도로 진태양시 보정)',
    'hour24': '시(0~23)', 'hourHint': '{{h}}시 = {{hint}}',
    'invalidDateTitle': '생년월일을 확인해 주세요',
    'minute': '분',
    'newCategory': '새 카테고리',
    'newCategoryPh': '새 카테고리 이름',
    'orSijin': '또는 시진(2시간)만 알 때',
    'placeSearchBlocked': '지역 검색이 잠시 제한됐어요. 30초쯤 뒤에 다시 시도해 주세요.',
    'placeSearchFailed': '지역 검색을 불러오지 못했어요. 연결을 확인해 주세요.',
    name: '이름·별칭', namePh: '예: 김OO / 본인',
    birthDate: '생년월일 (YYYY-MM-DD)', birthDatePh: '1990-03-15',
    birthTime: '태어난 시각 (HH:mm, 모르면 비움)', birthTimePh: '07:10',
    calendar: '양력 / 음력', solar: '양', lunar: '음', normalMonth: '평달', leapMonth: '윤달',
    sex: '성별', male: '남', female: '여',
    birthPlace: '출생지', birthPlacePh: '탭하여 도시 검색',
    relation: '관계', submit: '명식 계산 · 등록',
    birthTimeSijin: '태어난 시각 (시진)', timeUnknown: '모름', selfLabel: '본인', makeRep: '이 명식을 대표로 설정',
    relationCustom: '직접 입력', relationCustomPh: '관계를 직접 입력 (예: 직장 상사)',
    ctxTitle: '내 상황 알려주기 (선택)', ctxDesc: '입력하면 이 명식의 풀이가 더 정확해져요. 비워둬도 됩니다.',
    ctxSit: '지금 어떤 상황인가요', ctxSitDesc: '골라두면 풀이가 그 상황의 말로 쓰여요',
    sitStudy: '수험·학생', sitWork: '직장', sitBiz: '사업·자영업', sitFree: '프리랜서',
    sitHome: '주부·육아', sitSeek: '구직 중', sitRetire: '은퇴', sitEtc: '그 외',
    ctxJob: '하는 일', ctxJobPh: '예: 디자이너 / 자영업 / 학생 / 회사원',
    ctxRel: '관계 상태', ctxRelSingle: '미혼', ctxRelDating: '연애 중', ctxRelMarried: '기혼', ctxRelOther: '기타',
    ctxConcern: '요즘 관심·고민', ctxConcernPh: '예: 이직 고민, 새 인연, 건강 관리',
    ctxNote: '자유 메모', ctxNotePh: '풀이에 참고했으면 하는 내용을 자유롭게', contact: '연락처 (선택)', contactHint: '충전·결제 안내와 계정 복구에 써요. 명식 풀이에는 쓰이지 않아요.', contactEmailPh: '이메일', contactPhonePh: '휴대폰 번호', contactNotify: '충전·혜택 안내 받기',
    selfExistsTitle: '본인 명식이 이미 있어요', selfExistsMsg: "본인 명식은 하나만 둘 수 있어요. 기존 본인 명식은 '기타'로 옮기고 이 명식을 본인으로 등록할까요?", selfReplace: '본인으로 등록',
    birthPlaceSearch: '도시·지역 검색', birthPlaceSearchPh: '예: 서울, 부산, Tokyo', useAsIs: "'{{q}}' 그대로 사용",
    limitTitle: '무료 등록 한도', limitMsg: '무료 플랜은 명식을 {{limit}}개까지 등록할 수 있어요.\n광고를 보면 1개 더 추가하거나, 프로로 업그레이드하면 무제한이에요.',
    upgrade: '프로 업그레이드', usage: '명식 {{count}}/{{limit}}',
    watchAdAdd: '광고 보고 1개 추가', adNotFinished: '광고를 끝까지 봐야 1개 추가돼요.',
  },
  myeongsik: {
    palja: '팔자', dayMaster: '일간', strength: '신강약 지표', pattern: '격국', patternRevealed: '드러남', patternHidden: '잠복',
    stages: '12운성', interactions: '합충형해', sinsal: '신살·공망', gongmang: '공망',
    noHit: '원국 hit 없음', ziwei: '자미두수', lifePalace: '명궁',
    readingBtn: '영역별 풀이 보기 →', noChart: '차트 정보가 없습니다.',
    root: '통근', hidden: '지장간',
    luck: '대운·세운', daewoon: '대운', sewoon: '세운', elements: '오행 분포',
    합: '합', 충: '충', 형: '형', 해: '해', 파: '파', 극: '극',
    sinsalHint: '기준 글자가 원국에 있으면 ✓(자리), 없으면 대운·세운에서 작동', ssLuck: '운에서', dayPillar: '일주',
    sinsalDetail: '신살·공망 자세히 보기 →',
  },
  reading: {
    langChipA11y: '풀이 언어 바꾸기', langSheetHint: '화면 글자는 그대로 두고 풀이 본문만 바꿔요. 이미 본 풀이는 남아 있고, 다시 결제하지 않아요.',
    'lockedNote': '위 버튼으로 열어 전부 보실 수 있어요.',
    'lockedTitle': '이 명식의 풀이는 운으로 열려요',
    'pastYearBadge': '이 풀이는 {{y}}년 운(세운) 기준으로 쓰였어요 — 올해 흐름은 재통변하면 새로 반영돼요.',
    'recommend': '이런 콘텐츠도 좋아하실 거예요',
    'renew': '🔄 최신 통변으로 재통변',
    'sajuTitle': '사주 풀이',
    title: '전 영역 풀이', sub: '16개 전 영역을 한 번에 딥·정밀 통변해 드립니다. (명식은 무료)',
    runAll: '전체 풀이 보기 ({{count}}개)', progress: '‘{{current}}’ 풀이 중… ({{done}}/{{total}})', generating: '풀이를 정성껏 그리는 중…', saveFail: '명식 저장에 실패했어요. 잠시 후 다시 시도해 주세요.', refreshStale: '최신 해석으로 갱신', refreshDeniedTitle: '갱신 한도', refreshDenied: '이 풀이는 최대 {{cap}}번까지 갱신할 수 있어요.',
    ziweiTitle: '자미두수 12궁 풀이', ziweiSub: '명반 12궁을 한 번에 통합 통변해 드립니다. (명반은 무료)',
    timelineTitle: '인생 타임라인', timelineSub: '10~100세를 10년 단위로, 시기마다 어떤 흐름인지 풀어 드립니다.',
    bannerPremium: '구독 중 — 무제한 통변', bannerTrial: '🎁 첫 통변 1회 무료 체험!',
    bannerGated: '영역 선택 시 광고 또는 구독으로 통변이 열립니다',
    base: '타고난 바탕', past: '지나온 흐름', overlay: '지금의 흐름', future: '앞날·다가올 흐름', remedy: '이렇게 해보세요',
    premiumAlert: '깊은 통변', premiumAlertMsg: '건당 {{price}} 결제로 깊은 통변을 봅니다.',
    payPerUse: '{{price}} 결제', bannerPerUse: '✨ 첫 분야만 미리보기예요 — 전체 풀이는 {{price}}', bannerUnlocked: '✨ 결제 완료 — 전체 풀이를 생성해요',
    askTitle: '더 궁금한 점 물어보기', askPh: '이 풀이에서 더 궁금한 점을 물어보세요',
    askSend: '질문', askFree: '무료 질문 {{n}}회 남음', askPaid: '무료 질문을 다 썼어요 — 추가 질문은 건당 {{price}}',
    askPremiumTitle: '더 물어보기', askPremiumMsg: '이 풀이에 대해 더 궁금한 점을 물어볼 수 있어요.',
    askPremiumCta: '운으로 더 물어보기', askPayTitle: '추가 질문', askPayMsg: '무료 질문을 다 쓰셨어요. 건당 {{price}}으로 더 물어보시겠어요?',
    askPayBtn: '{{price}} 결제', payPending: '준비 중',
  },
  compat: {
    owned: '✓ 보유',
    'stillMaking': '거의 다 됐어요 — 결과가 오면 바로 보여 드릴게요.',
    'comeBackLater': '아직 만드는 중이에요. 잠시 후 이 화면을 다시 열면 결과가 보입니다.',
    'genConfirm': '생성',
    'genCta': '이 관계 풀이 만들기',
    'genTitle': '풀이 만들기',
    'otherPick': '상대 선택 · 새 상대 등록',
    'scoreHarmony': '조화',
    'scoreTension': '긴장',
    'step1': '① 누구와 볼까요?',
    'step2': '② 어떤 사이인가요?',
    'step3year': '③ 언제로 볼까요?',
    'wizPickShort': '탭해서 선택',
    'yearPick': '년도 선택',
    otherInfo: '상대 정보 (동의 필요 — 규칙8)', otherDatePh: '상대 생년월일 1992-07-03',
    otherTimePh: '태어난 시각 (모르면 비움)',
    dayRelation: '일간 관계', harmonyTension: '조화 {{h}} · 긴장 {{t}}',
    usefulGod: '용신 상보', crossInter: '교차 합충',
    needChart: '궁합을 보려면 먼저 내 명식을 등록하세요.', registerMyChart: '명식 등록',
    mySlot: '내 명식', otherSlot: '상대 명식', change: '변경', orDirect: '또는 상대를 직접 입력',
    registerOther: '상대 명식 등록', registerOtherTitle: '상대 명식 등록', registerOtherSubmit: '이 명식으로 궁합 보기',
    yearAll: '전체',
    analyze: '궁합 풀이 보기', generating: '두 분의 궁합을 풀이하는 중…', noReading: '풀이를 생성하지 못했어요. 다시 시도해 주세요.',
    secBase: '두 사람의 기본 결', secDynamic: '잘 맞는 점 · 부딪히는 점', secAdvice: '이렇게 가꿔 보세요',
    detailToggle: '글자 작용 자세히 보기',
    premiumTitle: '궁합 풀이', premiumMsg: '관계마다 따로 풀어 드려요. 운으로 열 수 있어요.',
    payTitle: '궁합 추가', payMsg: '무료 5명을 다 보셨어요. 이 분과의 궁합을 건당 ₩2,500으로 보시겠어요?', payBtn: '₩2,500 결제',
    rel: { friend: '지인·친구', family: '가족', crush: '썸·짝사랑', love: '연애', marriage: '결혼', coworker: '직장 동료', senior: '윗사람·멘토', business: '동업', staff: '직원·부하', invest: '투자 파트너' },
  },
  category: {
    성격내면: '성격·내면', 취업운: '취업운', 직장운: '직장운', 사업운: '사업운',
    금전소득운: '금전·소득운', 투자편재운: '투자운', 재물손재: '재물·손재', 연애운: '연애운',
    결혼배우자운: '결혼·배우자', 대인사회성: '대인관계', 부모운: '부모운', 형제운: '형제운',
    자식운: '자식운', 건강: '건강', 학업자기계발: '학업·자기계발', 이동환경: '이동·환경',
  },
  today: { hourTitle: '시간대별 흐름', hourSub: '같은 하루도 시간마다 결이 다릅니다', hourBest: '가장 잘 풀리는 때 · {{ko}} {{range}}', hourCare: '한 박자 늦추면 좋은 때 · {{ko}} {{range}}', hourNow: '지금', hourFoot: '오늘 일진과 내 명식으로 계산한 결이고, 좋고 나쁨의 판정이 아닙니다. 낮게 나온 때는 서두르지 않는 편이 낫다는 뜻으로 봐 주세요.', 
    'areaSoon': '이 분야 풀이는 다음 운세부터 채워져요.',
    today: '오늘', tomorrow: '내일', energyTomorrow: '내일의 기운', weekdaysShort: '일,월,화,수,목,금,토',
    // ★daniel 2026-08-06 — 홈 카드 제목 '오늘의 기운' → '오늘의 운세'
    //   (luck.todayEnergy 의 '오늘의 기운'은 **오행 기운**을 뜻하므로 건드리지 않는다)
    dayPillar: '오늘의 운세', note: '매일 자정에 바뀌는 오늘의 흐름이에요. 내 사주와 엮어 풀어 드려요 — 더 깊은 맞춤 풀이는 풀이 탭에서.',
    areas: '분야별 풀이', area_general: '통합', area_work: '직업', area_money: '재물', area_invest: '투자', area_love: '애정', area_health: '건강',
    needChart: '내 명식을 등록하면 오늘의 흐름을 나에게 맞춰 분야별로 풀어 드려요.', registerBtn: '명식 등록하기',
    more: '분야별로 자세히 보기 →',
    genFail: '풀이 생성에 실패했어요. 잠시 후 다시 시도해 주세요.', title: '오늘의 운세', heroSub: '오늘 일진으로 보는 하루 흐름', generating: '오늘의 흐름을 풀어내는 중…', gateTitle: '오늘의 운세 보기', gateDesc: '타고난 사주에 지금의 큰 흐름·올해·오늘 기운을 더해, 오늘 생길 수 있는 일과 대처를 풀어 드려요.', seePremium: '오늘의 운세 보기', seeAd: '광고 보고 무료로 보기', adFail: '광고를 불러오지 못했어요. 잠시 후 다시 시도하거나, 운으로 광고를 없앨 수 있어요.',
  },
  settings: { readingLanguage: '풀이 언어', readingLanguageHint: '화면 글자는 그대로 두고, 풀이 본문만 고른 언어로 봐요. 이미 본 풀이는 그대로 남아 있어요.', readingLangAuto: '앱 언어와 같게', myRecords: '내 기록', community: '커뮤니티', nickPh: '닉네임 (2~12자, 비우면 자동 익명이름)', nickBad: '사용할 수 없는 단어가 있어요.', nickLen: '닉네임은 2~12자예요.', nickDone: '저장됨', showIlju: '내 일주 뱃지 보이기', iljuHint: '글·댓글 옆에 태어난 날의 두 글자만 표시돼요. 생년월일은 알 수 없어요.',
    privacyHead: '개인정보',
    'accent': '테마 색',
    'accentAuto': '자동(일간)',
    'accentDesc': '대표명식 일간의 오행에 맞춰 화면 색이 달라져요. 직접 고를 수도 있어요.',
    'accentGold': '골드',
    'coins': '운',
    'loadingOff': '끄기',
    'loadingScreen': '로딩 화면',
    'loadingVideoOff': '앱 이름만',
    'loadingVideoOn': '호랑이 영상',
    'loginBenefit': '로그인하면 구매한 콘텐츠가 다른 기기·재설치에서도 이어져요 (선택)',
    'notif': '알림',
    'notifDaily': '매일 오늘의 운세 알림',
    'notifTalk': '상담가가 보내는 알림',
    'notifTalkOn': '켜짐 · 큰 흐름이 바뀔 때 노쌤이 먼저 알려줘요',
    'notifTalkOff': '꺼짐 · 눌러서 켜기',
    'notifDenied': '꺼짐 · 눌러서 기기 설정에서 켜기',
    'notifDeniedMsg': '알림을 받으려면 기기 설정에서 니운내운 알림을 켜 주세요.',
    'notifNA': '이 기기에서 사용 불가',
    'notifOff': '꺼짐 · 눌러서 켜기',
    'notifOn': '켜짐 · 매일 오전 9시',
    'notifOnMsg': '알림이 켜져 있어요. 끄려면 기기 설정에서 바꿀 수 있어요.',
    'notifUnavailable': '이 기기에서는 알림을 사용할 수 없어요.',
    'openSettings': '설정 열기',
    'readingVideo': '풀이 로딩 영상',
    'readingVideoOff': '심플(영상 없이)',
    'readingVideoOn': '테마 영상',
    'restore': '구매 복원',
    'restoreDone': '구매가 복원되었습니다.',
    'restoreFail': '구매 복원에 실패했어요. 잠시 후 다시 시도해 주세요.',
    'restoreNone': '복원할 구매 내역이 없습니다.',
    'restorePending': '구매가 확인됐어요. 서버 반영까지 잠시 걸릴 수 있어요 — 잠시 후 다시 확인해 주세요.',
    'restoring': '복원 중…',
    'themeRestart': '앱을 다시 켜면 적용돼요.',
    homeOrder: '홈 배치 순서', homeOrderNote: '홈 화면에 보이는 순서예요. 위/아래로 옮겨 보세요.', homeOrderReset: '기본 순서로 되돌리기',
    account: '계정', loginCta: '로그인 / 회원가입', premium: '운',
    premiumActive: '✓ 보유 중', premiumBuy: '운 충전', premiumDesc: '운으로 원하는 풀이만 골라 열어요 · 유효기간 없음', 
    premiumOkTitle: '충전 완료', premiumOk: '운이 충전됐어요.', premiumTitle: '운',
    deleteAccount: '계정 삭제',
    delTitle: '계정 삭제', delMsg: '계정과 모든 데이터(명식·풀이·이용권)가 영구 삭제됩니다. 되돌릴 수 없어요.', delConfirm: '삭제 진행',
    delTitle2: '정말 삭제할까요?', delMsg2: '이 작업은 되돌릴 수 없습니다.', delFinal: '영구 삭제',
    delFail: '삭제에 실패했어요. 잠시 후 다시 시도해 주세요.', delDoneTitle: '삭제 완료', delDone: '계정과 데이터가 삭제됐어요.', deleting: '계정을 삭제하는 중…',
    fontSize: '글자 크기', size_base: '기본', size_md: '중간', size_lg: '크게', size_xl: '아주 크게',
    appInfo: '앱 정보', version: '버전', terms: '이용약관', privacy: '개인정보처리방침', license: '오픈소스 라이선스', bugReport: '버그 제보 · 문의', bugReportFail: '메일 앱을 열 수 없어요. 아래 주소로 보내 주세요.',
    preview: '미리보기 — 통변은 이 크기로 보입니다. 설정한 크기는 풀이·오늘의 운세·궁합 본문에 바로 반영돼요.',
    language: '언어', 
    coupon: '쿠폰 입력', couponPh: '쿠폰 코드 입력', couponRedeem: '등록', couponHave: '보유 이용권',
    couponOkTitle: '등록 완료', couponOk: '무료 이용권이 적용됐어요. 해당 기능을 무료로 이용할 수 있어요.',
    couponFailTitle: '등록 실패',
    couponErr_invalid: '유효하지 않은 코드예요.', couponErr_expired: '만료된 쿠폰이에요.',
    couponErr_exhausted: '사용 한도가 끝난 쿠폰이에요.', couponErr_already: '이미 사용한 쿠폰이에요.', couponErr_auth: '로그인이 필요해요.',
  },
  timeline: {
    'readThis': '이 시기 풀이 보기',
    decades: '10년 단위 (대운)', years: '연도별', pickDecade: '시기 선택', pickYear: '연도 선택', thisYear: '올해', now: '지금',
    catGeneral: '통합', catWork: '직업', catMoney: '재물', catLove: '애정', catHealth: '건강',
    catSocial: '대인', catGrowth: '배움', catMove: '이동', months: '월별 흐름', monthUnit: '월',
    generating: '이 시기를 풀이하는 중…', tapToRead: '시기나 연도를 선택하면 그 흐름을 풀어 드려요.',
    premiumTitle: '인생 타임라인', premiumMsg: '10~100세를 시기별로 풀어 드려요. 운으로 열 수 있어요.',
    lockedTitle: '잠긴 시기', lockedSub: '현재 대운과 올해는 무료, 다른 시기는 이용권으로 열어 카테고리별로 자세히 풀어 드려요.',
    unlock: '이 시기 열기', unlockTitle: '이 시기 열기',
    unlockMsg: '타임라인 이용권으로 이 시기를 카테고리별로 자세히 풀어 드려요. (이용권은 설정에서 쿠폰 등록 · 건당 결제 준비 중)',
    buy5: '세운 5개 {{price}}', buy10: '이 대운 전체(10년) {{price}}', // 세운 번들(daniel 07-23) — 잠긴 시기 락 카드 구매 버튼. price=CREDIT_KINDS 실가 주입
    freeBadge: '무료', usedCredit: '이용권으로 열었어요',
  },
  premiumHub: {
    sub: '무엇을 볼까요?',
    sajuReading: '원국 풀이', sajuReadingDesc: '성격·재물·연애·직업 등 16영역 깊은 통변',
    ziweiReading: '명반 풀이', ziweiReadingDesc: '12궁 + 운한(대한)·사화로 보는 시기별 흐름',
  },
  pet: {
    title: '나의 반려동물', sub: '우리 아이의 타고난 결을 가볍게 살펴봐요.',
    add: '새 아이', name: '이름', namePh: '예: 콩이', typeLabel: '어떤 아이예요?',
    birth: '생년월일 (YYYY-MM-DD)', time: '태어난 시각', timeOptional: '— 몰라도 돼요',
    timePick: '시진 선택 (자시·축시…)', timeUnknownChk: '시간 모름',
    timeHint: '시각을 모르면 큰 결만 봐요(시간대 풀이는 빼요).',
    save: '특징 보기', empty: '아직 등록된 아이가 없어요.',
    delete: '명식 삭제', deleteTitle: '삭제', deleteMsg: '이 명식을 삭제할까요?',
    invalidTitle: '확인해 주세요', invalidDate: '생년월일을 YYYY-MM-DD 로 입력해 주세요.',
    type: { dog: '강아지', cat: '고양이', rabbit: '토끼', hamster: '햄스터', bird: '새', fish: '물고기', reptile: '파충류', other: '기타' },
  },
  love: {
    'genDelayed': '풀이 생성이 지연되고 있어요. 잠시 후 다시 시도해 주세요.',
    'needZiwei': '이 명식으로는 애정 흐름을 풀 수 없어요. 태어난 시가 정확해야 자미 교차 분석이 가능합니다.',
    title: '나의 애정흐름', sub: '사주와 자미두수를 둘 다 교차해, 이상형부터 실제 만날 사람까지 아주 자세히 풀어 드려요.',
    generating: '두 명반을 교차해 애정의 결을 풀이하는 중…',
    gateDesc: '이상형, 실제 만나게 되는 사람의 첫인상·성격·행동·습관, 어떻게 만나는지와 시기까지 — 사주와 자미두수를 교차해 아주 디테일하게.',
    see: '{{price}}로 자세히 보기', cacheNote: '한 번 보면 계속 저장돼요 (다시 결제 없음).',
    gateTitle: '나의 애정흐름', gateMsg: '아직 이용권이 없어요. 설정에서 쿠폰을 등록하거나, 결제 기능이 곧 열려요. ({{price}})',
    idealType: '나의 이상형', appearance: '실제 만날 사람의 첫인상·이미지', personality: '그 사람의 성격·내면',
    behavior: '그 사람의 행동·말투·습관', ageGap: '그 사람과의 나이 차이', howWeMeet: '어떻게·어디서 만나게 될까', elementMatch: '나와 잘 맞는 상대의 기운 순위', dynamic: '둘 사이의 끌림과 호흡', iLoveMore: '내가 더 좋아하는 연애', theyLoveMore: '상대가 더 좋아하는 연애',
    timing: '애정이 무르익는 시기', cautionPartner: '특히 조심할 상대', caution: '조심할 점', advice: '좋은 인연을 가꾸는 법', needPay: '운이 필요해요. 다시 시도해 주세요.',
  },
  month: {
    'aiDesc': '타고난 사주에 지금의 큰 흐름·올해·이번 달 기운을 더해, 이달 생길 수 있는 일과 대처까지 AI가 더 깊게 풀어 드려요.',
    'aiLogin': '로그인하면 AI가 이번 달 흐름을 더 깊게 풀어 드려요.',
    'aiTitle': 'AI 정밀 풀이',
    'thisMonth': '이번 달', title: '이달의 운세', monthPillar: '이번 달 기운', flowTitle: '이번 달 흐름 (상순·중순·하순)', note: '이번 달의 큰 흐름이에요. 구체적인 날은 오늘의 운세에서 봐요.', heroSub: '이번 달 월건으로 보는 흐름', generating: '이번 달 흐름을 풀어내는 중…', gateTitle: '이달의 운세 보기', gateDesc: '타고난 사주에 지금의 큰 흐름·올해·이번 달 기운을 더해, 이달 생길 수 있는 일과 대처를 풀어 드려요.', seePremium: '이달의 운세 보기' },
  nav: { back: '뒤로', admin: '관리자', costs: '비용·수익 분석', home: '운친구', chats: '운대화', fortune: '운세', readings: '풀이', my: '내 운',
         // ↓ 탭에서는 빠졌지만 마이페이지 메뉴·설정이 계속 쓰는 이름들(2026-08-18 4탭 전환)
         contents: '풀이', community: '운광장', coach: '우니', market: '마켓' },
  profile: { cover: '배경', photo: '프로필 사진', title: '내 프로필', namePh: '이름', pick: '사진 바꾸기', clear: '사진 지우기',
    pickCover: '배경 바꾸기',
    coverHint: "프로필 창에 보이는 그대로예요.",
    clearCover: '배경 지우기',
    coverTooLarge: '4MB 이하 사진만 올릴 수 있어요',
    saved: '저장했어요', saveFail: '저장하지 못했어요', tooLarge: '2MB 이하 사진만 올릴 수 있어요',
    hint: '비워 두면 명식 이름으로 표시돼요.', mobileSoon: '사진 바꾸기는 다음 업데이트에서 열려요. 지금은 웹에서 바꿀 수 있어요.' },
  fcompat: { save: "내 목록에 담기", saved: "담았어요", gone: '친구 목록에 없는 사람이에요.',
    notShared: '{{name}}님이 아직 명식을 열지 않았어요.\n상대가 「친구에게 내 명식 보여주기」를 켜면 볼 수 있어요.',
    noMe: '내 명식을 먼저 등록해야 궁합을 볼 수 있어요.', chart: '{{name}}님의 명식' },
  friends: { title: '친구', myCode: '내 친구 코드', codeHint: '이 코드를 알려주면 상대가 나를 추가할 수 있어요.',
    addByCode: '코드로 추가', codePh: '친구 코드 6자리', add: '신청', pending: '대기 중', mates: '내 친구',
    empty: '아직 친구가 없어요.\n위에서 코드로 추가해 보세요.', noName: '이름 없음',
    sent: '신청을 보냈어요. 상대가 수락하면 친구가 돼요.', bothSent: '서로 신청했네요. 바로 친구가 됐어요!',
    already: '이미 신청했거나 친구예요.', self: '내 코드예요.', notfound: '그런 코드를 찾지 못했어요.',
    needLogin: '로그인이 필요해요.', needLoginBody: '로그인하면 친구를 추가할 수 있어요.', failed: '지금은 처리하지 못했어요.',
    accept: '수락', waiting: '수락을 기다리는 중', gotRequest: '친구 신청이 왔어요',
    canSee: '명식·궁합 보기 ›', notShared: '아직 명식을 열지 않았어요',
    consentTitle: '친구에게 내 명식 보여주기',
    consentBody: '켜면 친구가 내 사주 원국(여덟 글자)과 궁합을 볼 수 있어요.\n여덟 글자로 생년월일을 되짚을 수 있으니, 믿는 사람에게만 열어 주세요.\n언제든 끌 수 있고, 끄면 바로 안 보여요.',
    consentOn: '친구에게 명식이 보여요.', consentOff: '이제 아무에게도 안 보여요.' },
  // ── 오픈채팅방 (Boss 2026-08-21) ──────────────────────────────────────────
  room: { alone: '나 혼자 있는 방', this: '이 대화',
    someone: '누군가', ph: '메시지를 입력하세요',
    aiCount: 'AI {{n}}명',
    gone: '없는 방이거나 들어갈 수 없는 방이에요.',
    failSend: '보내지 못했어요. 잠시 뒤 다시 시도해 주세요.',
    slow: '답이 늦어요. 잠시 뒤 새로고침해 주세요.',
  },
  rooms: {
    title: '오픈채팅', solo: '내 회의실', open: '오픈채팅',
    soloSub: '나 + AI 여럿', openSub: '여러 사람 + AI',
    phTitle: '방 이름 (예: 이직 고민방)', phTopic: '무슨 이야기를 하나요? (선택)',
    pick: '누구를 부를까요', cost: '한 번 말할 때마다 최대 {{n}}명이 답해요.',
    making: '만드는 중…', public: '공개 목록에 띄우기', make: '방 만들기',
    mine: '내 방', publicList: '들어갈 수 있는 방', aiN: 'AI {{n}}명',
    noPublic: '아직 열린 방이 없어요. 첫 방을 만들어 보세요.',
  },
  time: { am: '오전', pm: '오후', },
  chats: { leaveWarn: '나눈 이야기 전체가 지워지고, 되돌릴 수 없어요.', gateTitle: '대화는 로그인 후 이용할 수 있어요', gateDesc: '나눈 이야기가 계정에 남아요. 기기를 바꿔도 이어서 볼 수 있어요.', pin: '상단고정', unpin: '고정 해제', leave: '나가기', leaveAsk: '「{{name}}」 방을 나갈까요?', now: '방금', minAgo: '{{n}}분 전', hourAgo: '{{n}}시간 전', yesterday: '어제', dayAgo: '{{n}}일 전',
    empty: '아직 나눈 이야기가 없어요.\n연락처에서 친구를 눌러 보세요.', needLogin: '로그인하면 나눈 이야기가 여기 쌓여요.',
    noTitle: '대화를 이어가 보세요', turns: '{{n}}턴' },
  lookback: { title: '되돌아보기', sub2: '오늘의 한 가지를 해낸 날들이에요.', needLogin: '로그인하면 기록이 계정에 저장되고 여기서 다시 볼 수 있어요.', empty2: '아직 기록이 없어요. 오늘의 운세 아래 "오늘의 한 가지"를 해내고 체크해 보세요.', goToday: '오늘의 운세 보기', summary: '평가한 {{rated}}일 중 {{hit}}일을 "맞았다"고 하셨어요', streak: '지금까지 {{n}}일, 오늘의 한 가지를 해내셨어요', myNote: '내 기록', missionDone: '✓ 그날의 한 가지를 했어요' },
  contents: { // 하단탭 '풀이'(콘텐츠 목록) 화면
    sub: '보고 싶은 주제를 골라 보세요',
    searchPlaceholder: '무엇이 궁금하세요?',   // 검색창(daniel 08-06) — 이름·설명 부분일치
    searchResult: '검색 결과 {{n}}개',
    searchEmpty: '찾는 내용이 없어요.\n다른 낱말로 찾아보세요.',
  },
  // 오늘 기운 카드(홈 주인공 ② · daniel 07-18). ⚠️유형명·근거 본문은 dailyFortune.ts 가 만들며 현재 한국어 고정.
  todayEnergy: { kicker: '오늘의 기운', point: '점', more: '오늘 운세 자세히' },
  // 성격유형 120종(홈 주인공 · daniel 07-18). ⚠️유형명·요약 본문은 engine/personaType.ts 가 만들며 현재 한국어 고정 —
  //   여기 키는 UI 라벨만 다국어. 본문 다국어화는 엔진 어휘 테이블(22항목) 번역이 선행돼야 한다(백로그).
  persona120: {
    kicker: '120가지 유형 중 나는 어떤 유형일까', count: '120종 중', more: '자세히 보기',
    title: '120가지 유형 중 나는 어떤 유형일까', sub: '일간 10 × 월지 12로 나눈 120가지 결',
    empty: '명식을 등록하면 120가지 중 내 유형을 보여드려요.',
    axisStem: '나라는 재료', axisSeason: '내가 놓인 계절', axisGyeok: '삶의 무게중심',
  },
  market: {
    'emptyTopic': '이 주제의 콘텐츠가 준비 중이에요. 다른 주제를 골라 보세요.',
    'hotSection': '🔥 인기',
    'open': '열기',
    'retentionNote': '구매한 풀이는 구매일로부터 1년간 보유되며, 1년이 지나면 자동 삭제됩니다. 이후 다시 보려면 재구매가 필요해요.',
    'sectionIncluded': '✦ 운으로 열기',
    'sectionIncludedSub': '아래 풀이는 운으로 하나씩 열 수 있어요. 명식마다 따로 열립니다.',
    'sectionIndividual': '◆ 개별 구매 전용',
    'sectionIndividualSub': '아래 항목은 하나씩 따로 구매해요.', intro: '운으로 열 명식을 고른 뒤, 보고 싶은 풀이를 누르세요.', applyTo: '적용할 명식', openApply: '열기', noChart: '저장된 명식이 없어요', have: '보유 {{n}}장', owned: '보유', notOwned: '미보유', buy: '구매', note: '풀이는 명식별로 저장돼요. 무료 쿠폰은 아래에서 등록하세요.', doneTitle: '구매 완료', doneMsg: '운이 지급되었어요.', payPending: '결제 준비 중', buyFailTitle: '구매 실패' },
  dayPillar: {
    'fullChartNote': '※ 일주론은 ‘태어난 날(일주)’ 하나로 보는 큰 경향이에요. 정확한 풀이는 사주 전체(원국)를 함께 봐야 해요.',
    's_match': '잘 맞는 일주',
    's_stress': '스트레스 해소',
    title: '일주론', sub: '태어난 날의 간지(일주)로 보는 타고난 기질이에요.',
    male: '남자', female: '여자', mine: '내 일주', browseAll: '전체 일주 60', dayGroup: '일주', tapHint: '일주를 탭하면 상세 풀이가 펼쳐져요.', mineList: '내 명식 일주', noChart: '등록된 명식이 없어요. 명식을 먼저 등록하세요.',
    catAll: '전체', s_overview: '개요', s_personality: '성격', s_love: '연애·결혼', s_career: '직업·재물', s_male: '남성', s_female: '여성', s_advice: '조언', s_live: '인생 꿀팁',
    disclaimer: '일주론은 타고난 기질의 한 단면일 뿐이에요. 정확한 풀이는 일주만이 아니라 연·월·시 기둥과 합충·용신까지 사주원국 전체를 함께 봐야 해요.',
  },
  purchase: {
    syncTitle: '다른 기기에서도 쓰시려면',
    syncMsg: '충전한 운은 이 기기에 저장돼 있어요. 로그인하면 기기를 바꿔도 그대로 이어집니다. 지금 안 하셔도 언제든 설정에서 하실 수 있어요.',
    syncLater: '나중에',
    loginTitle: '로그인이 필요해요', loginMsg: '구매 내역을 계정에 저장해, 다른 기기나 앱을 다시 깔아도 그대로 쓸 수 있어요. 로그인하시겠어요?', loginCta: '로그인',
    restore: '구매 복원', restored: '구매를 복원했어요.', restoreNone: '복원할 구매가 없어요.', restorePending: '구매가 확인됐어요. 서버 반영까지 잠시 걸릴 수 있어요 — 잠시 후 다시 확인해 주세요.', preparing: '결제가 곧 열려요.',
  },
  offline: { title: '오프라인', msg: '인터넷에 연결돼 있지 않아요. 저장된 내용은 볼 수 있지만, 새 풀이는 연결된 뒤에 가능해요.', banner: '오프라인 — 저장된 내용만 볼 수 있어요' },
  taro: { draw: '카드 뽑기', reshuffle: '다시 뽑기', reversed: '역방향' },
  manse: { reorderWeb: '▲▼ 로 순서를 바꿀 수 있어요', reorderApp: '명식을 길게 눌러 끌면 순서가 바뀌어요', findHour: '태어난 시 찾기', findHourSub: '시각을 모르면 사건으로 좁혀요',
    'catDeleteTitle': '카테고리 삭제',
    'newCategoryPh': '새 카테고리 이름',
    'catDelNote': '카테고리를 지워도 명식은 지워지지 않아요 — ‘기타’로 옮겨져요.',
    // ★대표 명식 칸(Boss 2026-08-28 "위에 칸따로 만들어서 알수있게")
    'repChart': '대표 명식',
    // ⚠️만세력(보기 전용)은 대표를 바꾸지 않는다 — 「대표」라 적으면 바꾼 줄 오해한다
    'viewingChart': '지금 보는 명식',
    'deleteTitle': '명식 삭제',
    'viewManse': '만세력 보기', 'changeCategory': '카테고리 변경', empty: '등록된 명식이 없습니다.', myChart: '명식', searchChart: '이름으로 찾기' },
  sinsal: { 도화: '도화', 역마: '역마', 화개: '화개', 천을귀인: '천을귀인', 문창: '문창', 양인: '양인', 홍염: '홍염', 괴강: '괴강', 백호: '백호' },
  special: {
    'freeBasics2': '먼저 무료로 — 빅3 + 생명수',
    'goMarketBtn': '상점으로 이동 ›',
    'ownedBoughtV2': '구매 완료 · 언제든 다시 볼 수 있어요',
    'ownedResumeSub': '생성이 중단됐어요. 추가 결제 없이 이어서 만들어 드려요',
    'ownedResumeTitle': '결제는 끝났어요 — 풀이만 남았어요',
    'ownedTitle': '이미 열려 있는 풀이예요',
    'preparingPayment': '결제 준비 중…',
    'priceMissing': '지금은 이 콘텐츠를 열 수 없어요. 잠시 후 다시 시도해 주세요.',
    'resumeCta': '이어서 풀이 만들기',
    'viewCta': '풀이 보기',
    'working': '진행 중…', previewHead: '이런 걸 풀어드려요', unlock: '운으로 열기', couponHint: '운으로 열 수 있어요', couponOnly: '운으로 열 수 있어요. 마켓에서 운을 충전할 수 있어요.', needPay: '운이 필요해요. 다시 시도해 주세요.', needPayMsg: '운이 필요해요. 지금 운으로 열거나, 마켓에서 충전할 수 있어요.', buyNow: '바로 구매', goMarket: '마켓에서 보기', unlockCta: '구매하고 보기', unlockHint: '운으로 열려요' },
  roots: { title: '명식의 뿌리', sub: '겉으로 드러난 나와 속에 품은 힘, 그리고 진짜 단단한 기운을 짚어 드려요', generating: '뿌리를 더듬는 중…', summary: '한눈에', surface: '드러난 나', depth: '속에 품은 힘', strength: '진짜 단단한 힘', gap: '겉과 속의 차이', advice: '이렇게 키워요' },
  image: { title: '비치는 나', sub: '남에게 비치는 첫인상과 분위기, 관계 속 내 모습을 짚어 드려요', generating: '비치는 인상을 그리는 중…', summary: '한눈에', firstImpression: '첫인상', persona: '드러나는 이미지', inRelationship: '관계 속 나', charm: '매력 포인트', gap: '겉과 속', advice: '이렇게 보여 주세요' },
  mission: { title: '나의 사명', sub: '타고난 그릇과 재능으로 본, 내가 무엇을 위해 태어났는지', generating: '타고난 사명을 읽는 중…', summary: '한눈에', coreNature: '타고난 본질', calling: '나의 소명', strengths: '타고난 무기', howToRealize: '펼치는 길', successWay: '성공하는 방식', careers: '어울리는 일·직무', environment: '빛나는 환경', lifeTheme: '인생 주제', crossInsight: '함께 가리키는 방향', advice: '사명을 살아내는 법' },
  talent: { title: '나의 타고난 재능', sub: '무엇을 타고났는지, 좋아하는 일·해야 하는 일 중 어디서 빛나는지, 돈을 어떻게 다뤄야 하는지', generating: '타고난 재능을 읽는 중…', summary: '한눈에', talent: '타고난 재능', drive: '좋아하는 일 vs 해야 하는 일', money: '돈을 다루는 법', howToUse: '재능을 살리는 법', careers: '빛나는 일·분야', advice: '한마디' },
  numerology: {
    'birthday': '생일수 — 타고난 재능',
    'empty': '명식을 등록하면 생년월일로 수비학을 보여드려요.',
    'master': '✦ 마스터수(11·22·33) 보유 — 잠재력이 큰 대신 다루기 까다로운 수예요.',
    'note': '※ 피타고리안 수비학(서양 표준)으로 산출했어요. 이름 기반 수(표현·영혼수)는 추후 추가됩니다.',
    'personalYear': '개인해 — 올해 흐름', title: '수비학', sub: '생년월일에 담긴 수로 보는 나의 인생 방향·재능·올해 흐름', generating: '타고난 수를 읽는 중…', summary: '한눈에', lifePath: '생명수 — 인생 방향', innerYou: '내면과 겉모습', talent: '타고난 재능', thisYear: '올해 흐름', advice: '한마디' },
  astrology: {
    'numCore': '수로 본 나',
    'numGroup': '🔢 수비학 — 생년월일의 수로 보는 나',
    'numLove': '수비학으로 본 관계',
    'numYear': '올해의 수',
    'sub2': '별자리(태양)·점성술(네이탈)·수비학(생명수)을 한 번에 — 세 관점으로 깊이 풀이', title: '별자리·점성술', sub: '내 별자리(태양별자리)와 점성술(네이탈 차트)을 한 번에 — 두 관점으로 깊이', generating: '별자리·점성술을 읽는 중…', signGroup: '⭐ 별자리 — 태양별자리로 보는 나', signSummary: '내 태양별자리', signTraits: '성격·기질', signLove: '연애 스타일', signStrength: '강점·매력', natalGroup: '🔭 점성술 — 네이탈 차트로 보는 나', big3: '태양·달·상승궁', natalLove: '사랑·욕구', natalWork: '일·성취', strength: '타고난 강점', challenge: '과제', advice: '한마디' },
  future10: { title: '10년 뒤 나의 모습', sub: '대운·세운으로 보는 10년 뒤의 나와 지금부터의 준비', gen: '10년 뒤를 그리는 중…', bigPicture: '10년 뒤 큰 그림', career: '커리어·성취', wealth: '재물·자산 흐름', relation: '관계·가정', health: '건강 관리축', growth: '성장·내면 변화', prepare: '지금부터 준비할 것' },
  child: { title: '자식운', sub: '원국으로 보는 자녀 인연·기질·부모로서의 나', gen: '자녀 인연을 살피는 중…', solo: '나 혼자 보기', couple: '배우자와 함께', pickSpouse: '배우자 명식 선택', coupleHint: '배우자 명식을 고르면 두 사람 명식으로 자녀 인연을 함께 봅니다', needSpouse: '배우자 명식을 먼저 등록해 주세요', bigPicture: '자녀 인연의 큰 그림', childNature: '자녀의 기질', asParent: '부모로서의 나', coupleCross: '부부 자녀 인연', communication: '소통·관계', timing: '시기 흐름', talent: '자녀의 재능', health: '건강 관리축', remedy: '개운·처방' },
  life: { genFail: '생성에 실패했어요. 잠시 후 다시 시도해 주세요.', gateTitle: '인생 그래프', generating: '인생 흐름을 그리는 중…', yongsin: '나에게 필요한 기운', focus: '집중', hint: '곡선의 점을 눌러 그 시기를 자세히 볼 수 있어요.', peak: '가장 빛나는 시기', caution: '다지고 조심할 시기', advice: '평생 이렇게', gateDesc: '위 곡선의 각 시기가 왜 그런지, 지금 무엇을 하면 좋은지, 전성기 활용법과 어려운 때 대처까지 깊이 풀어 드려요.', pv1: '각 시기가 왜 오르내리는지', pv2: '지금 시기에 무엇을 하면 좋은지', pv3: '가장 빛나는 시기를 살리는 법', pv4: '조심할 시기를 넘기는 법', pv5: '평생 지켜갈 삶의 방향', see: '인생 그래프 보기', seePaid: '인생 그래프 보기 (₩3,900)' },
  newyear: {
    'remedy': '올해 개운법',
    'strategy': '올해의 대응전략',
    'thisYearSelf': '올해의 나',
    'timing': '올해 좋은 시기',
    'yearNature': '올해는 어떤 해', title: '신년운세', generating: '올 한 해를 풀어내는 중…', heroSub: '올 한 해의 큰 흐름을 한눈에', keyword: '올해의 키워드', lucky: '올해의 행운 포인트', halves: '상반기 · 하반기', months: '달별 캘린더', samjaeAdvice: '올해 특히 챙길 점', resolution: '올해를 이렇게', gateDesc: '올해의 키워드부터 분야별 운, 열두 달 캘린더, 새해 다짐까지 한 번에 정리해 드려요.', pv1: '올해의 키워드', pv2: '분야별 운 8가지', pv3: '열두 달 캘린더', pv4: '상·하반기 흐름', pv5: '올해 다질 점·새해 다짐', see: '신년운세 보기', seePaid: '신년운세 보기 (₩9,900)', },
  taegil: { title: '택일 — 좋은 날 찾기', sub: '하려는 일을 고르면, 앞으로 석 달 달력에서 내 사주에 잘 맞는 날을 색으로 짚어 드려요.', best: '아주 좋음', good: '좋음', tapHint: '색칠된 날을 눌러 보세요', },  zodiac: { title: '띠·별자리 오늘운세', animal: '띠', sign: '별자리', mine: '내 운세', },
  name: { title: '이름풀이', sub: '이름 속 소리의 기운(오행)으로 결을 봐요.', placeholder: '한글 이름을 입력하세요', noHangul: '한글 이름을 입력해 주세요.', },
  taemong: {
    'secSymbols': '꿈에 나온 것들',
    'secStory': '이 꿈이 말하는 것',
    'secChild': '전해 내려오기로는',
    'secKeep': '이 꿈을 간직하는 법',
    'secTradition': '이런 이야기도 있어요',
    'title': '태몽 풀이',
    'sub': '꿈에 나온 것으로 읽는, 아이를 기다리는 마음',
    'guard': '태몽은 오래 전해 온 이야기예요. 아이의 성별이나 건강을 알려주지는 않아요 — 그건 의료의 영역이에요.',
    'dictTitle': '꿈에 무엇이 나왔나요?',
    'dictPh': '용 · 호랑이 · 잉어 · 복숭아 …',
    'noHit': '사전에 없는 상징이에요. 무료로 찾아 드릴까요?',
    'lookup': '‘{{kw}}’ 찾아보기 (무료)',
    'aiTitle': 'AI 태몽 풀이',
    'aiSub': '꿈 전체를 이야기로 적어 주세요 — 여러 상징이 섞여 있어도, 사전에 없어도 함께 읽어 드려요.',
    'aiPh': '누가 꾼 꿈인지, 무엇이 나왔고 어떻게 했는지 …',
    'aiCta': '태몽 풀이 받기',
    'tooShort': '꿈 이야기를 조금 더 적어 주세요.',
    'fail': '풀이를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
  },
  dream: {
    'aiBtn': 'AI 해몽 받기 (₩300)',
    'aiPh': '꿈에서 보거나 겪은 일을 자세히…',
    'aiSub': '복잡한 꿈은 이야기로 적어 보세요 — 사전에 없어도, 여러 상징이 섞여도 풀어 드려요.',
    'aiTitle': 'AI 꿈해몽',
    'buy5': '운 사용',
    'buyBundle': '꿈해몽을 5 운으로 볼까요?',
    'needCredit': '지금은 열 수 없어요. 잠시 후 다시 시도해 주세요.', fail: '해몽을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.', title: '꿈해몽', sub: '꿈에 나온 것을 검색해 보세요.', placeholder: '예: 돼지, 뱀, 물…', generating: 'AI가 해몽을 풀어내는 중…', notInDict: '사전에 없는 꿈이에요. AI 해몽을 받아보세요.', aiSee: 'AI 해몽 보기', history: '지난 꿈해몽' },
  luck: { title: '오늘의 행운', todayEnergy: '오늘의 기운', color: '행운의 색', direction: '행운의 방향', numbers: '행운의 숫자', item: '행운의 아이템', weakHead: '내게 보탬이 되는 색', weakTail: ' — 내 사주에 부족하기 쉬운 기운이라, 곁에 두면 균형이 살아나요.', },
  // 팔자 도우미(콘텐츠 안내 · API 0 · daniel 2026-07-30) — 종전 'AI 자기이해 코치'를 대체
  // 재통변(1년 경과 → 코인 결제 · daniel 2026-07-30)
  renewal: { title: '최신 통변으로 다시 받기', msg: '이 풀이를 받은 지 1년이 지났어요.\n\n{{pct}}% 할인된 {{coins}} 운으로 지금 시점 기준으로 다시 풀어 드려요.\n보유 {{have}} 운 → 사용 후 {{after}} 운', later: '다음에', go: '재통변하기', needTitle: '운이 조금 모자라요', needMsg: '재통변에는 {{need}} 운이 들어요. 지금 {{have}} 운 있어요.' },
  assist: { title: '우니', sub: '보고 싶은 걸 말해 주세요. 바로 그 자리로 데려다 드려요.', label: '우니', hello: '무엇을 보고 싶으세요? 세 가지 중에 고르셔도 되고, 그냥 편하게 말해 주셔도 돼요.', egLabel: '이렇게 말해도 알아들어요', miss: '제가 아직 그 말은 못 알아들었어요. 아래에서 골라 주시면 바로 안내해 드릴게요.', placeholder: '무엇을 보고 싶으세요?', reset: '↺ 처음으로', send: '보내기', },
  coach: { title: 'AI 자기이해 코치', sub: '나에 대해 궁금한 걸 물어보세요. 당신의 사주로 답해 드려요.', coachLabel: '코치', thinking: '당신의 사주를 살펴보는 중…', placeholder: '나에 대해 물어보세요', send: '보내기', needChart: '먼저 명식을 등록해 주세요.', registerBtn: '명식 등록하기', loadFail: '명식을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.', gateTitle: '오늘 무료 질문을 다 쓰셨어요', gateDesc: '무료로 하루 {{count}}번까지 물어볼 수 있어요. 운으로 더 대화할 수 있어요.', gateCta: '운 충전하기', q1: '나는 어떤 사람인가요?', q2: '왜 제 관계는 비슷하게 반복될까요?', q3: '제 강점을 어떻게 살리면 좋을까요?', q4: '요즘 제 흐름은 어떤가요?' },
  selfHero: { kicker: '나는 어떤 사람인가', emptyTitle: '나를 분석해 드릴게요', emptySub: '생년월일시를 넣으면 사주 엔진이 성격·기질·강점을 분석해요', emptyCta: '+ 나를 분석받기', more: '성향 분석 자세히 보기 ›' },
  personal: {
    'toneCap': '나의 퍼스널 컬러', title: '퍼스널 오행', sub: '내 오행에 맞는 컬러·코디·메이크업·자동차 색', activate: '나를 살리는 색', balance: '채우면 좋은 색', yongsin: ' (내게 필요한 기운)', cody: '코디', makeup: '메이크업', car: '자동차 색', empty: '명식을 등록하면 내 오행에 맞는 컬러를 찾아드려요', emptyCta: '+ 명식 등록', expertNote: '※ 퍼스널 오행은 사주 오행을 바탕으로 한 참고용 제안이에요. 실제 퍼스널컬러 진단·스타일링은 전문가와 상담해 보세요.' },
  // R-GEM v0.1 — 내 사주 보석(★daniel 검수 슬롯: sub·note 문구)
  gem: { title: '내 사주 보석', birthstoneTitle: '탄생석, 어떤 의미일까', sub: '생일 보석은 사실 나와 안 맞아요 — 나를 살리는 진짜 보석', empty: '명식을 등록하면 나에게 맞는 보석을 찾아드려요', emptyCta: '+ 명식 등록' },
  timeResolve: {
    'title': '태어난 시 찾기', yearRange: '연도를 다시 확인해 주세요(예: 1990~올해).', yearFuture: '미래 연도는 입력할 수 없어요.', removeEvent: '사건 삭제' },
  sok: { title: '속궁합', sub: '두 사람의 성적 궁합을 사주로 — 재미로 보는 성인 콘텐츠', gateTitle: '성인(19세 이상) 콘텐츠', gateDesc: '속궁합은 두 사람의 성적 궁합을 사주로 풀어보는 성인용 콘텐츠예요. 재미로만 즐겨 주세요.', gateConfirm: '만 19세 이상입니다 · 시작', pickPartner: '상대 선택', newPartner: '새 상대 입력', registerSubmit: '이 상대로 속궁합 보기', spouseLabel: '배우자궁 케미', adviceLabel: '더 좋아지는 법', kiss: '키스궁합', bed: '관계궁합', styleLabel: '두 사람의 케미 스타일', pickHint: '탭해서 상대 선택', noPartner: '저장된 상대가 없어요. 새 상대를 입력해 주세요.', disclaimer: '※ 사주로 보는 재미 콘텐츠예요. 실제 관계는 두 사람이 만들어갑니다. 성인(19세 이상) 전용.' },
  community: { photo: '사진 첨부', photoOff: '사진 없음', photoPick: '사진 고르기', photoWebOnly: '사진 첨부는 웹에서 할 수 있어요.', photoTooLarge: '4MB 이하 사진만 올릴 수 있어요', photoFail: '사진을 올리지 못했어요', photoWarn: '올린 사진은 이 글을 보는 모두에게 공개돼요. 얼굴·신분증·주소처럼 나를 알아볼 수 있는 것은 올리지 마세요.\n음란물·폭력·타인의 사진을 올리면 신고 즉시 계정이 정지될 수 있어요.', catAll: '전체', gateTitle: '운광장은 로그인 후 이용할 수 있어요', gateDesc: '함께 쓰는 자리라 누가 쓴 글인지 남아야 해요. 로그인하면 바로 볼 수 있어요.', searchPh: '글 제목으로 찾기', views: '조회', sortRecommend: '추천', sortPopular: '인기', writeBox: '오늘의 고민이나 질문을 남겨보세요 ✨', daily: '오늘의 일진', dailyTalk: '이야기 나누기', p1: '아주 좋음', p2: '좋음', p3: '보통', p4: '아쉬움', p5: '힘듦', pollMine: '참여 완료! 참여자가 모이면 통계가 보여요.', pollStat: '{{total}}명 참여 · 가장 많은 선택 {{top}}%', all: '전체', cat: { love: '연애', career: '직장·진로', wealth: '재물', daily: '일상', free: '자유', tarot: '타로', ziwei: '자미두수' }, empty: '첫 글을 남겨보세요.', profanity: '부적절한 표현이 포함돼 있어요. 수정 후 다시 올려 주세요.', write: '글쓰기', post: '올리기', titlePh: '제목', bodyPh: '내용을 입력하세요 (욕설·혐오·성적 콘텐츠 금지)', eulaTitle: '커뮤니티 이용약관', eulaBody: '욕설·혐오·괴롭힘·불법·성적/음란 콘텐츠는 금지됩니다. 위반 시 게시물 삭제·이용 제한될 수 있어요. 신고된 콘텐츠는 24시간 내 검토·조치됩니다. 부적절한 사용자는 차단할 수 있습니다.', eulaAgree: '동의하고 글쓰기', comments: '댓글', noComments: '첫 댓글을 남겨보세요.', commentPh: '댓글 입력', send: '등록', report: '신고', block: '차단', reportTitle: '신고하기', reportDesc: '사유를 선택하세요. 신고된 콘텐츠는 24시간 내 검토됩니다.', rAbuse: '욕설·혐오·괴롭힘', rSexual: '성적/불법 콘텐츠', rSpam: '스팸·광고', reported: '신고 접수됨', reportedDesc: '검토 후 조치할게요. 감사합니다.', reportFail: '신고에 실패했어요.', blockTitle: '이 사용자 차단', blockDesc: '차단하면 이 사용자의 글·댓글이 더 이상 보이지 않아요.', blocked: '차단했어요', blockFail: '차단에 실패했어요.', delTitle: '삭제할까요?', gone: '삭제되었거나 볼 수 없는 글이에요.', loginTitle: '로그인이 필요해요', loginDesc: '글쓰기는 로그인 후 이용할 수 있어요. 읽기는 로그인 없이 그대로 가능합니다.', goLogin: '로그인', attach: '내 명식 첨부', attachNone: '‘본인’으로 등록된 명식이 없어요. 첨부 없이 글을 올릴 수 있어요.', attachOff: '첨부 안 함', attachLuck: '대운·세운도 함께 공개', attachWarn: '원국 여덟 글자가 이 글을 보는 모두에게 공개돼요. 여덟 글자로 생년월일을 역산할 수 있으니 확인 후 올려 주세요.', needTitle: '제목을 입력해 주세요.', needBody: '내용을 입력해 주세요.', posting: '올리는 중…', errSession: '로그인이 필요해요. 다시 로그인 후 시도해 주세요.', errNet: '네트워크 연결을 확인하고 다시 시도해 주세요.', errPost: '올리지 못했어요. 잠시 후 다시 시도해 주세요.' },
  egen: { title: '에겐 vs 테토', heroSub: '내 사주로 보는 에겐·테토 성향', tetoPower: '테토력', typeTeto: '테토형', typeEgen: '에겐형', typeBalanced: '균형형', scaleEgen: '에겐', scaleTeto: '테토', secPersonality: '타고난 성향', secRelationship: '연애·관계에서', secNowTrend: '요즘 흐름', needChart: '먼저 명식을 등록해 주세요.', registerBtn: '명식 등록하기', gateTitle: '내 성향 설명 보기', gateDesc: '점수에 맞춰, 내 성향이 평소·연애·요즘 흐름에서 어떻게 드러나는지 가볍게 풀어 드려요.', seeAd: '광고 보고 무료로 보기', seePremium: '성향 설명 보기', generating: '성향을 분석하는 중…', genFail: '설명을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.', adFail: '광고를 불러오지 못했어요. 잠시 후 다시 시도하거나, 운으로 광고를 없앨 수 있어요.', },
  crisis: { title: '관계의 고비', heroSub: '흔들리는 시기를 구조로 봅니다 — 점이 아니라 자리와 힘으로', frameTitle: '헤어질지는 말하지 않습니다', frameBody: '관계가 끝날지 맞히는 화면이 아닙니다. 내 명식의 배우자 자리에 어떤 힘이 어디서 걸려 있고, 어느 해에 그 자리가 움직이는지를 봅니다. 결정은 그 다음이고, 그건 사주가 아니라 두 사람이 합니다.', needChart: '명식을 등록하면 이 화면이 채워집니다.', chartFail: '이 명식으로는 계산하지 못했습니다.', secStrength: '① 흔드는 힘이 어디서 오는가', gungLine: '배우자 자리 = 일지 {{gung}}', chungFrom: ' · {{from}}지에서 걸립니다', gradeBreaking: '가까운 자리에서 세게 흔드는 힘이 걸려 있습니다. 이 자리는 흔들리면 흔들리는 대로 티가 납니다.', gradeShaking: '흔들림은 있어도 자리 자체가 밀리지는 않습니다.', gradeEven: '양쪽 힘이 비슷해서, 어느 쪽이 이긴다고 말하기 어려운 형태입니다.', gradeNone: '자리를 흔드는 힘이 원국에 걸려 있지 않습니다.', remedyBreaking: '흔들릴 때 관계를 다시 정의하려 들면 더 흔들립니다. 결정을 미루고 생활의 리듬부터 지키는 편이 낫습니다.', remedyEven: '어느 쪽도 이기지 못하는 힘겨루기라, 이기려 할수록 길어집니다. 먼저 말을 꺼내는 쪽이 이깁니다.', remedyCalm: '지금 구조에는 급한 불이 없습니다. 관계를 시험하는 선택은 굳이 지금 만들지 않아도 됩니다.', secRivalry: '② 다투는 형태가 있는가', rivalryWealth: '천간에서 같은 글자 둘이 하나를 두고 다투는 형태가 있고, 그 대상이 재성입니다. 사람이든 몫이든 “나눠 갖기 어려운 것”이 관계 안에 들어오면 결이 드러납니다.', rivalryYes: '천간에서 같은 글자 둘이 하나를 두고 다투는 형태가 있습니다. 누가 끼어든다는 뜻이 아니라, 하나를 두고 힘이 갈리는 구조가 원래 있다는 뜻입니다.', rivalryNo: '하나를 두고 힘이 갈리는 형태는 원국에 없습니다. 관계가 흔들린다면 다른 데서 옵니다.', rivalryRemedy: '이 구조는 “누구 때문”으로 읽으면 반드시 틀립니다. 나눌 수 없는 것을 먼저 정해 두면 다툴 자리가 줄어듭니다.', rivalryRemedyNo: '삼각 구도를 미리 걱정할 자리는 아닙니다.', secBond: '③ 붙어 있는가, 이름뿐인가', bondYes: '배우자 자리가 바로 옆자리와 묶여 있습니다. 떨어져 있어도 잘 안 끊어지는 결입니다.', bondNo: '배우자 자리를 붙들어 두는 글자가 옆에 없습니다. 관계의 지속은 구조보다 두 사람이 만드는 쪽입니다.', frictionYes: '다만 마찰(형)이 함께 걸려 있어, 가까울수록 부딪히는 대목이 생깁니다.', frictionRemedy: '부딪히는 지점이 늘 같은 자리라면 그건 사건이 아니라 결입니다. 그 한 가지만 규칙으로 정해 두면 나머지는 조용해집니다.', bondRemedy: '붙들어 두는 힘이 약할수록 약속과 반복이 그 자리를 대신합니다.', secTiming: '④ 어느 해에 그 자리가 움직이는가', timingQuiet: '앞으로 여덟 해 동안 배우자 자리를 건드리는 해가 없습니다. 조용한 구간입니다.', yOpen: '자리가 열립니다 — 움직임이 들어오는 해', yBond: '자리가 묶입니다 — 매듭이 지어지는 해', yFriction: '마찰이 도는 해', timingRemedy: '“열린다”는 헤어진다는 뜻이 아닙니다. 그 자리에 움직임이 들어온다는 뜻이고, 만남도 정리도 같은 문으로 옵니다. 그 해에 큰 결정을 몰아 두지 않는 것만으로 대부분 지나갑니다.', disclaimer: '이 화면은 구조와 시기를 보는 참고 자료이고, 관계의 결말을 예측하지 않습니다. 지금 많이 힘드시다면 사주보다 먼저 곁의 사람이나 전문가와 이야기해 보시길 권합니다.' },
  attach: { title: '애착유형 — 명식과 설문 비교', heroSub: '같은 관계 패턴을 두 가지 언어로 봅니다', frameTitle: '두 결과는 서로 다른 것을 봅니다', frameBody: '설문은 지금 이 시기의 상태를 재고, 명식은 타고난 구조의 결을 봅니다. 그래서 두 값이 다를 수 있고, 다른 것이 오히려 읽을 거리입니다 — 구조는 거리를 두는 쪽인데 지금은 편안하다면, 그 사이에 무언가를 스스로 익힌 것입니다.', secChart: '① 명식이 가리키는 결', secSurvey: '② 지금의 나 (12문항)', secCompare: '③ 두 결과 나란히 보기', axisAnx: '불안 — 멀어질까 하는 쪽', axisAvo: '회피 — 거리를 두는 쪽', axisAnxShort: '불안', axisAvoShort: '회피', anxLow: '흔들리지 않는 편', anxHigh: '멀어질까 살피는 편', avoLow: '가까움이 편한 편', avoHigh: '거리를 두는 편', capTitle: '일간이 {{target}}을(를) 감당하는가', capFrame: '관계에서의 거리감은 내가 관계를 감당할 여유가 있는지에서 갈립니다. 남자 명식은 정재, 여자 명식은 정관 자리를 두고 봅니다.', capAxis: '감당', capLow: '버거운 쪽 · 거리를 둔다', capHigh: '여유 있는 쪽 · 편안하다', capEdge: '양쪽 끝으로 멀리 갈수록 관계가 흔들리기 쉬워집니다. 어디부터를 그렇게 볼지는 아직 정하지 않아, 유형 이름을 붙이지 않고 위치만 보여 드립니다.', capAbsent: '이 명식에는 {{target}}이(가) 겉으로 드러나 있지 않습니다. 그런 명식을 어떻게 읽을지는 아직 확인 중이라, 위 위치는 더 넉넉히 참고만 해 주세요.', sideSelf: '여유 쪽', sideLoad: '부담 쪽', cmpAnxNone: '불안 줄에는 설문 결과만 있습니다. 명식 쪽은 “관계를 감당할 여유가 있는가”까지를 말하고, 그것을 불안으로 바꿔 읽는 방법은 아직 확인하지 않았습니다.', basisHead: '이 점수를 민 것', basisNone: '이 축을 미는 구조가 뚜렷하지 않습니다.', needChart: '명식을 등록하면 이 부분이 함께 나옵니다. 설문만 먼저 해 보셔도 됩니다.', chartFail: '이 명식으로는 계산하지 못했습니다.', surveySub: '가까운 사람과의 관계를 떠올리며 답해 주세요. 정답은 없습니다.', progress: '{{n}} / {{total}} 문항', compareLocked: '12문항을 모두 답하면 여기에서 나란히 보여 드립니다.', soloGap: '‘혼자가 편하다’ 쪽은 높고 ‘가까워지면 불편하다’ 쪽은 낮게 나왔습니다. 스스로 해결하는 힘이 큰 경우에도 이렇게 나오니, 두 갈래를 따로 보시면 좋습니다.', hypo: '보는 자리(남자는 정재·여자는 정관)와 읽는 방법은 상담 전문가가 주신 그대로입니다. 다만 “감당한다”를 무엇으로 잴지는 아직 확인 중이라, 근거 항목을 모두 같은 무게로 두었습니다(v1). 확인되면 다시 계산해 반영합니다.', disclaimer: '이 결과는 자기이해를 돕는 참고 자료이고 심리 진단이 아닙니다. 관계나 마음의 어려움이 일상에 영향을 주고 있다면 전문가와 이야기해 보시길 권합니다.', consent: '이 응답을 애착 모델 개선 연구에 익명으로 사용하는 데 동의합니다 (선택 · 동의하지 않아도 결과는 그대로 보실 수 있습니다)', consentNote: '보내는 값은 설문 응답과 명식에서 계산된 지표뿐입니다. 생년월일시는 기기를 벗어나지 않습니다.', saveBtn: '연구에 응답 보내기', saving: '보내는 중…', saved: '보냈습니다. 고맙습니다', saveFail: '보내지 못했습니다. 다시 시도', },
  joseonjob: { shareLead: '조선시대 나의 직업', traits: '타고난 강점', share: '내 직업 공유하기', detail: '내 사주 깊이 보기' },
  lovestyle: { shareLead: '내 연애 스타일', inLove: '연애할 때', tip: '이런 점만 더하면', share: '내 연애 스타일 공유', detail: '내 애정 흐름 깊이 보기' },
  bok: { shareLead: '내 타고난 복', how: '복을 키우는 법', share: '내 복 공유하기', detail: '내 사주 깊이 보기' },
  pastlife: { shareLead: '나의 전생', hint: '지금의 당신에게', share: '내 전생 공유하기', detail: '내 사주 깊이 보기' },
  healing: {
    'deficit': '가장 적은 기운(참고)', shareLead: '나만의 힐링 방법', recharge: '나의 충전 방식', nourish: '채우면 좋은 기운', release: '비우면 좋은 기운', color: '힐링 색', place: '힐링 공간', food: '곁들이면 좋은', mind: '마음 한마디', elemLead: '내 기운', share: '내 힐링 방법 공유', },
  bio: {
    'kicker': '바이오리듬',
    'note': '※ 사주와 무관한 참고용 리듬이에요. 0 부근은 컨디션이 바뀌는 전환일.',
    'sub': '오늘의 신체·감정·지성 리듬',
  },
  career: {
    'gateDesc': '두 길에서 어떻게 빛나고 어디서 막히는지, 타고난 무게추와 시기까지 풀어 드려요.',
    'generating': '두 길을 풀어내는 중…',
    'sub': '명식과 대운·세운으로, 독립과 조직 두 길을 짚어 드려요',
    'title': '사업가의 나 vs 직장인의 나',
  },
  celeb: {
    'compare': '일간·오행 비교',
    'funNote': '재미로 보기',
    'matchHead': '닮은 점',
    'myTenGod': '내 십신 구조 요약',
    'reasons': '공통 구조',
    'sub': '내 사주와 닮은 인물 찾기',
    // ★제목을 내용에 맞춤(daniel 2026-08-07). 목록이 **한국 배우·아이돌**인데 제목만 '세계를 움직이는 사람들'이라
    //   들어와서 보는 것과 어긋났다(원래는 나폴레옹·모차르트 같은 역사 인물 16명이던 시절의 이름).
    'title': '나와 닮은 연예인',
    'topLabel': '나와 가장 닮은 인물',
  },
  coins: { packName: "{{coins}} 운", refundNotice: '결제 후 7일 이내, 사용하지 않은 운만 환불돼요. 이미 사용한 운은 환불되지 않아요.', refundPolicy: '취소·환불 정책', webSub: '스토어 수수료가 없어 같은 금액으로 운을 더 드려요.\n웹에서는 큰 화면으로 명식·관계 지도·대화를 한 번에 볼 수 있어요.', title: '운 충전', titleSub: '운을 충전하고 원하는 풀이를 열어 보세요.', bonusAny: '충전 시 자동 적용', bonusNote: '충전하면 큰 쿠폰부터 자동으로 쓰여요. 결제 금액은 그대로예요.', bonusTitle: '가진 보너스', failTitle: '충전하지 못했어요',
    useHead: '운으로 할 수 있는 것',
    useTalk: '· 상담가와 대화 — {{cost}}운이면 {{turns}}턴',
    useReading: '· 사주·궁합·타로 풀이 — 콘텐츠마다 값이 다르고, 열기 전에 보여 드려요',
    useNote: '무료 대화 {{free}}턴은 매일 다시 채워져요. 운은 사라지지 않아요.',
    spendMsg: '{{cost}} 운을 사용해 풀이를 시작할까요?\n보유 {{have}} 운 → 사용 후 {{after}} 운',
    'balFail': '잔액을 불러오지 못했어요',
    'balance': '보유 운',
    'charge': '운 충전하기',
    'chargeCta': '운 충전하기',
    'donePending': '결제가 완료됐어요. 잔액 반영이 잠시 걸릴 수 있어요.',
    'doneTitle': '충전됐어요',
    'needLoginDesc': '충전한 운은 계정에 보관돼요. 로그인해야 기기를 바꿔도 그대로 남습니다.',
    'needLoginTitle': '로그인이 필요해요',
    'needTitle': '운이 조금 모자라요',
    'note': '· 운은 모든 유료 풀이에 쓸 수 있어요.\\n· 충전한 운은 계정에 보관돼요 — 기기를 바꿔도 그대로예요.\\n· 운은 사용 기한이 없어요.',
    'packs': '운 충전하기',
    'spend': '운 사용',
  },
  country: {
    'needChart': '먼저 명식을 등록해 주세요.',
    'sub': '타고난 기운(조후)을 보완해 줄 기후·방위의 나라를 짚어 드려요',
    'title': '내가 살기 좋은 곳',
  },
  crush: {
    'caution': '조심할 점',
    'generating': '끌림의 기운과 인연의 흐름을 읽는 중…',
    'howToApproach': '다가가는 법',
    'myCharm': '지금 나의 매력',
    'sub': '지금 나의 매력과, 짝사랑·썸이 무르익기 좋은 시기, 다가가는 법을 짚어 드려요',
    'timing': '썸이 무르익는 시기',
    'title': '짝사랑 인연운',
    'whoLikesMe': '나에게 끌릴 사람',
  },
  crushAsk: {
    'cta': '깊은 짝사랑 풀이 보기',
    'q': '그 사람과 이어질까?',
    'sub': '짝사랑·썸이 무르익어 마음이 통하기 좋은 달을 무료로 미리 짚어 드려요',
  },
  gaeun: {
    'gateDesc': '지금 운에 무엇이 오는지 보고, 재물·관계·건강을 살리는 실천과 살풀이까지 짚어 드려요.',
    'generating': '지금 운에 맞는 개운법을 찾는 중…',
    'sub': '지금 운(대운·세운)에 맞춰 운을 살리는 구체적인 방법을 짚어 드려요',
    'title': '맞춤 개운법',
  },
  // ★시안 4탭(2026-08-18) — 마이페이지·결제 내역·풀이 보관함
  fav: {
    'empty': '아직 찜한 콘텐츠가 없어요.',
    'emptySub': '콘텐츠 카드의 ♡ 를 누르면 여기에 모여요.',
  },
  notify: { remove: '이 알림 지우기',
    'empty': '받은 알림이 없어요.',
    'failed': '알림을 불러오지 못했어요.',
    'title': '알림',
  },
  // 시안 p10·p11 풀이 본문 6탭
  readingTab: { all: '전체', nature: '성향', love: '연애', work: '직업', money: '재물', life: '인생',
    h1: '1. 나의 사주팔자', h2: '2. 나를 이루는 다섯 기운', h3: '3. 나는 어떤 사람일까요?', more: '자세히 보기', empty: '이 주제는 아직 만들어지지 않았어요.' },
  my: { chats: '대화 기록', teachers: '찜한 선생님', posts: '작성한 글', comments: '댓글과 답글', useHistory: '운 사용 내역', subs: '구독 관리', notifySet: '알림 설정', account: '계정 및 보안', support: '고객센터', woonCard: '내 운', walletLink: '운 충전 / 사용 내역', statusDefault: '오늘도 나에게 좋은 일이 가득하길 ✨', editProfile: '프로필 편집', needLogin: '로그인하면 내 활동을 볼 수 있어요.', noPosts: '아직 쓴 글이 없어요.', noComments: '아직 단 댓글이 없어요.', deletedPost: '삭제된 글', noTeachers: '아직 찜한 선생님이 없어요.\n친구목록에서 별을 눌러 보세요.', grpAct: '내 활동', grpWoon: '운 관리', grpSet: '설정', charts: '내 명식',
    loginTitle: '로그인하고 이어서 보세요',
    loginSub: '카카오·구글·애플로 시작하면 계정이 함께 만들어져요. 산 콘텐츠와 대화가 다른 기기·재설치에서도 이어집니다.',
    loginCta: '로그인 · 회원가입',
    'fav': '찜한 콘텐츠',
    'readings': '운세 기록',
    'charge': '운 충전하기',
    'coach': '상담 내역',
    'coupon': '쿠폰함',
    'helloGuest': '안녕하세요',
    'helloName': '안녕하세요, {{name}}님',
    'helloSub': '나의 운을 관리하고 더 나은 하루를 만들어보세요.',
    'history': '결제/충전 내역',
    'settings': '설정 및 개인정보',
    'wallet': '나의 운 지갑',
    'walletSub': '운은 다양한 상담과 콘텐츠에 사용돼요.',
    'woon': '운',
  },
  analyzed: { done: '분석이 완료되었어요!', ilju: '일주', is: '입니다.', next: '내 명식 보기', sub: '당신의 사주를 확인해 보세요.', you: '당신은' },
  coinHistory: {
    adFreeForever: '광고 제거 (평생)',
    kindCoach: '팔자 도우미',
    kindFuture10: '10년 흐름',
    kindQaTopup: '테스트 지급',
    coinPack: '{{n}} 운',
    adFree: '광고 제거 {{d}}일',
    kindTalk: '상담가 대화',
    kindReading: '사주 풀이',
    rPurchaseWhat: '{{what}} 충전',
    rPurchase: '운 충전',
    rSpendWhat: '{{what}}에 사용',
    rSpend: '운 사용',
    rRefundWhat: '{{what}} 환불',
    rRefund: '환불',
    rGift: '선물 받은 운',
    rTestRevert: "테스트 지급 회수",
    rCorrection: '잔액 바로잡기',
    rMigrate: '이전 잔액 이관',
    'charge': '운 충전',
    'empty': '아직 충전·사용 내역이 없어요.',
    'failed': '내역을 불러오지 못했어요.',
    'use': '운 사용',
  },
  myReadings: {
    'empty': '아직 만든 풀이가 없어요.',
    'failed': '풀이를 불러오지 못했어요.',
    'goPick': '운세 보러 가기',
  },
  banner: {
    'kicker': '오늘의 추천',
    'loveT': '지금 나에게\n들어오고 있는\n인연이 있어요.',
    'loveS': '그냥 지나치기엔\n꽤 강한 흐름이에요.',
    'loveC': '내 인연 확인하기',
    'moneyT': '내 재물 그릇은\n얼마나 클까요?',
    'moneyS': '타고난 크기와\n채워지는 때가 따로 있어요.',
    'moneyC': '내 그릇 보기',
    'selfT': '나는 결국\n어떤 사람일까요?',
    'selfS': '성격도 기질도\n타고난 자리가 있어요.',
    'selfC': '나 알아보기',
    'flowT': '십 년 뒤의 나는\n지금과 다를까요?',
    'flowS': '흐름이 바뀌는 해가\n이미 정해져 있어요.',
    'flowC': '내 흐름 보기',
    'funT': '오늘 하나만\n가볍게 볼까요?',
    'funS': '무겁지 않게,\n딱 오늘 것만.',
    'funC': '가볍게 보기',
  },
  freeDraw: {
    'title': '무료 타로 한 장 뽑기',
    'sub': '오늘의 운을 카드 한장으로 확인해보세요.',
    'cta': '시작하기',
  },
  talk: { netErr: "네트워크 오류예요. 연결을 확인하고 다시 보내 주세요.", sendErr: "보내지 못했어요. 잠시 뒤 다시 시도해 주세요.", lowBalance: '운이 {{have}}개 남았어요. 다음 이야기부터는 {{cost}}운이 필요해요.', pickedChart: '{{name}} 명식으로 볼게', inviteAsk: '{{name}} 님을 불러올까요?', inviteYes: '초대하기', handoffAsk: '{{name}} 님에게 연결해 드릴까요?', handoffYes: '연결하기', packLast: '이 묶음은 여기까지예요. 다음 이야기부터 운이 들어요.', searchPh: '이름으로 찾기', favShort: '즐겨찾기', unfavShort: '해제',
    'greetHi': '안녕하세요. {{name}}이에요.',
    'greetWhat': '{{what}} 쪽을 봐 드려요. 뭐가 궁금하세요?',
    'greetAsk': '뭐가 궁금하세요?',
    'noFlow': '오늘 흐름은 잠시 뒤에 다시 볼게요.',
    'guideHere': '이건 여기서 자세히 볼 수 있어요.',
    'guideNone': '지금은 안내해 드릴 게 없네요.',
    'handoff': '그건 {{who}}께 여쭤 볼게요.',
    'handoffCtx': '지금까지 얘기는 이어서 전해 드릴게요.',
    'listTitle': '상담',
    'kindVirtual': '안내 도우미',
    'kindLive': '상담 선생님',
    'typing': '입력 중',
    'inputHint': '무엇이든 물어보세요',
    'send': '보내기',
    'delAsk': '이 대화를 지울까요? 되돌릴 수 없어요.',
    'delOk': '지우기',
    'pickChat': '왼쪽에서 대화를 골라 주세요',
    'pickOne': '대화가 없습니다',
    'liveSoon': '곧 이야기 나눌 수 있어요. 준비 중이에요.',
    'blockHi': '{{what}} 가져왔어요.',
    'friends': '친구',
    'favorites': '즐겨찾기',
    'filter': { all: '전체', teacher: '선생님', friend: '친구' },   // ★'최근' 제거(Boss 2026-09-02)
    'officialBadge': '공식',
    'groupTeacher': '✦ 선생님',
    'groupTeacherSub': '실제 상담가의 관법을 따라 답해요.',
    'loginNudge': '로그인하면 명식과 풀이가 계정에 저장돼요.',
    'loginNudgeSub': '지금은 이 기기에만 있어요 — 앱을 지우면 되찾을 수 없어요.',
    'loginNudgeCta': '로그인',
    'briefTail': '여러분의 운은 어떻게 될까요? 회원님 명식으로 보면 이번 달이 어떤 달인지 알 수 있어요.',
    'groupFriend': '✦ 함께하면 좋은 친구들',
    'contents': '콘텐츠',
    'more': '더보기',
    'collapse': '접기',
    'fav': '즐겨찾기에 추가',
    'unfav': '즐겨찾기에서 빼기',
    'friendsCount': '친구 {{n}}명',
    'search': '친구 검색',
    'searchEmpty': '찾는 친구가 없어요.',
    'meNoChart': '명식 등록',
    'needLoginBubble': '{{name}}{{josa}}. 이야기를 이어가려면 로그인이 필요해요. 회원님 명식을 봐야 제대로 답해 드릴 수 있거든요.',
    'needLoginTitle': '로그인이 필요해요',
    'needLoginMsg': '로그인하면 명식을 저장하고 상담가와 이어서 이야기할 수 있어요.',
    'liveGreet': '안녕하세요. {{name}}{{josa}}. 무엇이 궁금하세요?',
    'chartMade': '명식을 만들었어요. 이제 이 사주로 봐 드릴게요.',
    'chartMakeFail': '명식 만들기',
    'chartMakeFailBody': '지금은 만들지 못했어요. 잠시 뒤 다시 시도해 주세요.',
    'overFree': '오늘 무료로 나눌 이야기는 여기까지예요. 이어서 하시면 운이 쓰여요.',
    // ★운 차감 «영수증» 한 줄(말풍선 아님 · 가운데 · 작은 글씨). 숫자는 **서버가 준 값**만 들어간다
    'spent': '{{n}}운 사용',
    'freeLeft': '오늘 무료 대화 {{n}}번 남았어요.',
    // 운 부족 — 충전 유도(Boss 2026-08-24). ★얼마 필요하고 얼마 있는지 **숫자로** 말한다.
    'needCoinsTitle': '운이 조금 모자라요',
    'needCoinsMsg': '조금 더 이야기 나누려면 {{cost}}운이 들어요. 지금 {{have}}운 있어요.',
    'needCoinsMsgNoBal': '조금 더 이야기 나누려면 {{cost}}운이 들어요.',
  },
  home: {
    'bonusLead': '충전할 때 자동으로 쓰여요',
    'bonusTitle': '도착한 혜택',
    'bonusTitleName': '{{name}}님께 도착한 혜택',
    'bonusUntil': '{{date}}까지 쓸 수 있어요.',
    'freeTrio': '무료로 체험해보세요!',
    'freeTrioSub': '가입 없이 지금 바로 볼 수 있는 것들',
    'greeting': '{{name}}님 반갑습니다.',
    'seeMore': '보러가기',
    'lightCta': '가볍게 보기',
    'monthTitle': '이달의 운세',
    'monthNoChart': '이번 달 흐름도 명식이 있어야 볼 수 있어요',
    'monthLoading': '이번 달 흐름을 보고 있어요',
    'manseSub': '내 사주 명식 전체 보기',
    'noChartCta': '+ 명식 등록',
    'noChartSub2': '생년월일만 넣으면 성격유형과 일주를 바로 볼 수 있어요. 가입도, 저장도 안 해요.',
    'noChartTitle': 'AI가 분석하는 나 — 여기서 시작',
    'quickRegister': '명식 등록',
    'quickRegisterSub': '가족·연인·친구의 명식을 추가해요',
  },
  impression: {
    'gapBig': '겉으로 비치는 모습과 알고 난 뒤의 모습이 꽤 달라요. 처음엔 몰랐던 반전 매력이 있는 사람이에요.',
    'gapSmall': '겉으로 비치는 모습과 속이 비교적 한결같아요. 보이는 그대로 믿음이 가는 사람이에요.',
    'inner': '막상 알고 보면 — 진짜 내 모습',
    'note': '※ 천간(밖으로 드러나는 기운)의 흐름이 남에게 비치는 이미지, 월지(타고난 자리)의 기운이 알고 보면 진짜 모습이에요.',
    'outer': '겉으로 비치는 나',
    'sub': '겉으로 비치는 모습과 알고 보면 다른 진짜 나',
    'title': '사람들이 보는 나의 인상',
  },
  job: {
    'bestField': '맞는 직종·환경',
    'flow': '취업·이직 흐름',
    'generating': '취업·합격의 기운과 흐름을 읽는 중…',
    'passLuck': '합격·시험운',
    'sub': '취업·이직·합격·시험이 잘 풀리는 흐름과 시기, 맞는 직종·준비 법을 짚어 드려요',
    'timing': '좋은 시기',
    'tips': '준비 팁',
    'title': '취업·이직운',
  },
  jobAsk: {
    'cta': '깊은 취업 풀이 보기',
    'q': '취업·이직, 언제 잘 풀릴까?',
    'sub': '취업·이직·합격의 문이 열리기 좋은 시기를 무료로 미리 짚어 드려요',
  },
  jobfit: {
    'ability': '실제 잘하는 것',
    'archetype': '나의 직업 유형',
    'gap': '끌림과 능력의 간극',
    'generating': '타고난 적성과 어울리는 직업을 읽는 중…',
    'jobs': '어울리는 일',
    'luckMap': '직업 인생 흐름',
    'preference': '끌리는 것 (능력 아님)',
    'recognition': '인정받는 법·무대',
    'sub': '타고난 적성으로 어떤 직업이 어울리는지, 끌림과 능력의 간극까지 짚어 드려요',
    'title': '나에게 어울리는 직업',
    'workEnv': '잘 맞는 일터',
    'workMode': '일하는 결·모드',
    'yongsinFit': '알맞은 방향',
  },
  login: {
    'go': '로그인',
    'needContentMsg': '이 콘텐츠를 보려면 로그인해 주세요. 로그인하면 구매·풀이가 계정에 안전하게 저장돼요.',
    'needTitle': '로그인이 필요해요',
  },
  mbti: {
    'empty': '명식을 등록하면 사주로 본 MBTI를 보여드려요.',
    'note': '※ 사주 구조(지장간·현재 운 포함)로 본 성향이라 시기에 따라 조금씩 달라져요. 심리검사 MBTI와 다를 수 있어요.',
    'sub': '내 사주 구조로 풀어본 성향 유형',
    'title': '사주로 보는 내 MBTI',
  },
  mod: {
    'empty': '신고된 콘텐츠가 없어요.',
    'hide': '숨기기',
    'restore': '복원',
    'sub': '신고된 콘텐츠를 검토하고 숨기거나 복원하세요. (신고 5회 이상은 자동 숨김)',
    'title': '신고 관리',
  },
  net: {
    'errMsg': '잠시 후 다시 시도해 주세요. 계속되면 잠시 뒤에 다시 열어 주세요.',
    'errTitle': '연결에 문제가 있어요',
  },
  relPattern: {
    'attraction': '매력·인연의 밀도',
    'compatCta': '특정 상대와의 궁합이 궁금하다면 →',
    'drawnTo': '반복해 끌리는 사람의 결',
    'dynamic': '나의 관계 역학',
    'footNote': '※ 배우자궁(일지)·인연星·도화 등 원국 구조를 사주 엔진으로 계산한 온디바이스 분석이에요. 예언이 아니라 나를 이해하는 참고예요.',
    'kicker': '사주 엔진으로 보는 관계 심리',
    'myStyle': '관계에서 나의 방식',
    'sub': '왜 비슷한 관계가 반복될까요? 궁합 운세가 아니라, 타고난 사주 구조에서 반복되는 관계의 결을 읽어요.',
    'title': '나의 관계 패턴',
    'titleSuffix': '님의 관계 패턴',
  },
  reunion: {
    'addDesc': '옛 인연의 명식과 지금의 고민을 더하면, 두 사람의 사주를 함께 보고 고민에 맞춰 풀어드려요. 비워 두면 나의 흐름만으로 봐요.',
    'addTitle': '함께 풀어드려요 (선택)',
    'afterReunion': '다시 만난다면',
    'caution': '되돌아보면 좋은 점',
    'changeBuy': '구매하고 바꾸기',
    'changeConfirmBuy': '상대를 바꾸면 처음부터 다시 풀어요. 운이 조금 들어가는데 괜찮으실까요?',
    'changeConfirmCredit': '가진 재회운 1회분으로 상대를 바꿔 새로 풀어요. 바꾸시겠어요?',
    'changeConfirmPremium': '상대를 바꾸면 그 사람으로 새로 풀어요. 바꾸시겠어요?',
    'changeGo': '바꾸기',
    'concernLabel': '지금의 고민',
    'concernPh': '지금 어떤 상황·고민인지 적어주시면 함께 풀어드려요',
    'generating': '다시 이어질 인연의 흐름을 읽는 중…',
    'otherAdd': '옛 인연 생년월일 입력',
    'otherAnon': '옛 인연',
    'otherChange': '상대 바꾸기(새로 풀기)',
    'otherLabel': '옛 인연의 명식',
    'otherLockedNote': '상대를 바꾸려면 새로 풀어야 해요.',
    'otherPrivacy2': '※ 상대 정보는 이 재회 풀이에만 쓰여요. 바꾸기 전까지 이 기기에만 잠겨 보관되고, 명식 목록엔 남지 않아요. 동의를 얻은 경우에만 입력해 주세요.',
    'possibility': '다시 이어질 인연인지',
    'registerOtherSubmit': '이 명식으로 함께 풀기',
    'registerOtherTitle': '옛 인연 명식 입력',
    'remedy': '재회를 여는 법',
    'sub': '옛 인연과 다시 이어질 가능성과, 연락이 닿기 좋은 시기를 짚어 드려요',
    'theirResponse': '그때 상대의 마음',
    'timing': '연락이 닿기 좋은 시기',
    'title': '재회운',
  },
  reunionAsk: {
    'cta': '깊은 재회 풀이 보기',
    'q': '재회, 다시 이어질까?',
    'sub': '옛 인연과 다시 이어질 가능성·시기·방향을 무료로 짚어 드려요',
  },
  selfAnalysis: {
    'elements': '오행 밸런스 — 나를 이루는 다섯 기운',
    'footNote': '※ 모두 사주 엔진(만세력)으로 계산한 온디바이스 분석이에요. 예언이 아니라 나를 이해하는 참고예요.',
    'kicker': '사주 엔진이 분석한 나',
    'more': '자세히 보기 ›',
    'strengths': '강점과 기질 자세히',
    'sub': '타고난 사주를 엔진으로 계산한 다섯 갈래 자기분석 — 운세가 아니라 나를 이해하는 지표예요.',
    'title': '나 분석',
    'titleSuffix': '님 분석',
  },
  signup: {
    'body': '구매한 이용권과 풀이는 지금 쓰는 임시 계정에 묶여 있어요. 앱을 지우거나 기기를 바꾸면 되찾기 어려워요. 계정을 연결해 두면 그대로 이어서 볼 수 있어요.',
    'cta': '계정 연결하기',
    'note': '연결하지 않아도 지금처럼 계속 이용할 수 있어요.',
    'title': '지금 본 풀이, 이 기기에만 남아 있어요',
  },
  signupPrompt: {
    'cta': '계정 연결',
    'later': '나중에',
    'msg': '지금은 임시 계정이라 앱을 지우거나 기기를 바꾸면 구매한 이용권과 풀이를 되찾기 어려워요. 연결하지 않아도 계속 보실 수 있어요.',
    'title': '계정을 연결하면 이 풀이가 안전하게 보관돼요',
  },
  spouseDual: {
    'ageHint': '나이대 힌트',
    'ageNote': '※ 경향일 뿐이에요. 실제 상대 사주가 있으면 궁합이 우선해요.',
    'funnel': '더 구체적인 이상형·실제 인연·시기 통변은 아래 애정 리딩에서 확인해요.',
    'gap': '대비',
    'idealTag': '끌리는 이상형',
    'ignite': '끌림(발동)',
    'match': '일치',
    'noFlow': '다음 8년간은 배우자 자리가 크게 열리고 닫히는 신호가 약해요. 큰 변동보다 다지는 시기예요.',
    'realDesc': '결혼생활의 실질 — 늘 최우선인 자리(일지)',
    'realTag': '진짜 곁에 남는 사람',
    'settle': '안정(안착)',
    'sub': '타고난 배우자 자리를 두 축으로 봐요 — 끌리는 이상형과, 실제로 곁에 남는 사람.',
    'timeline': '끌림 vs 안정 — 인연 흐름',
    'title': '이상형과 진짜 인연',
  },
  traits: {
    'detail': '내 사주 깊이 보기',
  },
  wealth: {
    'flow': '재물 인생 흐름',
    'generating': '타고난 재물 그릇과 흐름을 읽는 중…',
    'howEarn': '돈이 들어오는 결',
    'partner': '혼자 vs 함께',
    'remedy': '재물 지킴·개운',
    'sub': '타고난 재물 그릇과 유형, 언제 크게 들어오고 어떻게 지키는지까지 짚어 드려요',
    'timing': '재물 시기',
    'title': '재물 딥리포트',
    'type': '재물 유형',
    'vessel': '재물 그릇',
  },
  yieojim: {
    'express': '마음은 이는데 정착까진 약한 해',
    'mine': '내가 먼저 다가가 이어지기 좋은 해',
    'mineNone': '다음 10년엔 약해요 — 내가 먼저 표현해 다가가는 힘(식상)이 원국에 옅어, 특정 시기(그 기운이 들어올 때)에 집중돼요.',
    'note': '※ 참고 경향이에요. 실제 인연은 만나는 사람에 따라 달라져요. 어느 쪽이든 최종적으로 이어지려면 ‘인연 자리’가 열리는 해가 열쇠예요.',
    'popular': '관심·인기는 오지만 정착까진 약한 해',
    'sub': '짝사랑이든 대시든, 실제로 이어지려면 ‘인연 자리(배우자궁)’가 그때 열려 있어야 해요.',
    'theirs': '좋은 인연이 다가와 이어지기 좋은 해',
    'theirsNone': '다음 10년엔 인연이 다가와 정착까지 이어지는 뚜렷한 시기가 약해요.',
    'title': '인연이 이어지는 시기',
  },
};
