// app/src/lib/dreamDict.ts — 꿈해몽 사전(키워드 검색·다국어 ko/en/ja). 무료·온디바이스(API 0)·전통 해몽(통설).
// ─────────────────────────────────────────────────────────────────────────
// keywords = ko+en+ja 혼합(어느 언어로 검색해도 매칭). title/meaning = 언어별. §4: 흉몽도 전향적.
// ─────────────────────────────────────────────────────────────────────────
import { appLang } from '../i18n';

type Tri = { ko: string; en: string; ja: string };
export type DreamEntry = { keywords: string[]; title: Tri; meaning: Tri };
const L = (): 'ko' | 'en' | 'ja' => (appLang() as any) ?? 'ko';

export const DREAM_DICT: DreamEntry[] = [
  { keywords: ['돼지', 'pig', '豚', 'ぶた'], title: { ko: '돼지', en: 'Pig', ja: '豚' }, meaning: { ko: '재물과 복이 들어오는 대표 길몽이에요. 사업·금전운이 오르고 뜻밖의 수입을 기대해 볼 수 있어요.', en: 'A classic lucky dream of wealth and fortune coming in. Business and money luck rise, and unexpected income may follow.', ja: '財運と福が入る代表的な吉夢です。事業運・金運が上がり、思わぬ収入も期待できます。' } },
  { keywords: ['뱀', 'snake', '蛇', 'へび'], title: { ko: '뱀', en: 'Snake', ja: '蛇' }, meaning: { ko: '지혜·재물·인연을 상징해요. 품에 안거나 따라오면 임신·재물의 길몽, 물리면 오히려 기회로 보기도 해요.', en: 'A symbol of wisdom, wealth, and fate. Holding one or being followed signals pregnancy or wealth; even a bite can mean opportunity.', ja: '知恵·財·縁の象徴。抱いたり付いてくると妊娠·財の吉夢、噛まれてもむしろ好機と見ます。' } },
  { keywords: ['용', 'dragon', '龍', 'りゅう'], title: { ko: '용', en: 'Dragon', ja: '龍' }, meaning: { ko: '큰 성취·출세·귀한 인연의 최고 길몽이에요. 승천하는 용일수록 명예와 발전이 따라요.', en: 'The grandest lucky dream of great success, advancement, and noble ties. A rising dragon brings honor and growth.', ja: '大成·出世·貴縁の最高の吉夢。昇る龍ほど名誉と発展が伴います。' } },
  { keywords: ['호랑이', 'tiger', '虎', 'とら'], title: { ko: '호랑이', en: 'Tiger', ja: '虎' }, meaning: { ko: '권위·귀인·태몽의 상징이에요. 맞서 이기면 경쟁에서 앞서고, 품에 안으면 귀한 인연을 뜻해요.', en: 'A symbol of authority, a patron, or a conception dream. Beating it means winning competition; embracing it means a precious bond.', ja: '権威·貴人·胎夢の象徴。立ち向かい勝てば競争で優位、抱けば貴い縁を意味します。' } },
  { keywords: ['물', '강', '호수', 'water', 'river', '水', 'みず'], title: { ko: '물', en: 'Water', ja: '水' }, meaning: { ko: '맑은 물은 재물과 마음의 안정을, 넘치는 물은 큰 변화를 뜻해요. 흐림 없이 맑을수록 길해요.', en: 'Clear water means wealth and peace of mind; overflowing water means big change. The clearer, the more fortunate.', ja: '澄んだ水は財と心の安定、あふれる水は大きな変化を意味します。濁りなく澄むほど吉です。' } },
  { keywords: ['불', '화재', 'fire', '火', 'ひ'], title: { ko: '불', en: 'Fire', ja: '火' }, meaning: { ko: '활활 타오르는 불은 번성·재물의 길몽이에요. 두려움보다 기세가 강했다면 일이 크게 일어날 신호예요.', en: 'A blazing fire is a lucky dream of prosperity and wealth. If its force outweighed fear, big things are about to rise.', ja: '燃え盛る火は繁盛·財の吉夢。恐怖より勢いが強ければ、物事が大きく起こる兆しです。' } },
  { keywords: ['돈', '지폐', '금', '보석', 'money', 'gold', 'お金', '金'], title: { ko: '돈·재물', en: 'Money', ja: 'お金·財' }, meaning: { ko: '받거나 줍는 꿈은 재물운 상승이에요. 잃는 꿈은 오히려 지출 정리·새 기회의 신호로 봐요.', en: 'Receiving or finding money means rising wealth luck. Losing it signals clearing expenses or a fresh chance.', ja: '受け取る·拾う夢は金運上昇。失う夢はむしろ支出整理·新たな好機の兆しと見ます。' } },
  { keywords: ['똥', '대변', '오물', 'poop', '糞', 'うんち'], title: { ko: '똥', en: 'Feces', ja: '糞' }, meaning: { ko: '대표적 재물 길몽이에요. 몸에 묻거나 밟으면 뜻밖의 금전운이 따라요.', en: 'A classic lucky dream of wealth. Getting it on you or stepping in it brings unexpected money luck.', ja: '代表的な財の吉夢。体に付いたり踏むと、思わぬ金運が伴います。' } },
  { keywords: ['이빨', '이', '치아', 'teeth', 'tooth', '歯', 'は'], title: { ko: '이빨', en: 'Teeth', ja: '歯' }, meaning: { ko: '빠지는 꿈은 변화·정리의 신호예요. 걱정보다 묵은 일을 털고 새로 시작하는 때로 보면 좋아요.', en: 'Losing teeth signals change and clearing out. Rather than worry, see it as shedding the old and starting anew.', ja: '抜ける夢は変化·整理の兆し。心配より、古い事を片付け新しく始める時と見ましょう。' } },
  { keywords: ['죽음', '죽다', '시체', 'death', 'die', '死', 'しぬ'], title: { ko: '죽음', en: 'Death', ja: '死' }, meaning: { ko: '끝이 아니라 변화·재생을 뜻하는 길몽이에요. 낡은 것이 가고 새 국면이 열리는 신호예요.', en: 'Not an end but a lucky dream of change and rebirth. The old departs and a new chapter opens.', ja: '終わりではなく変化·再生を意味する吉夢。古いものが去り、新しい局面が開く兆しです。' } },
  { keywords: ['아기', '아이', '임신', 'baby', 'child', '赤ちゃん', '子供'], title: { ko: '아기·임신', en: 'Baby', ja: '赤ちゃん·妊娠' }, meaning: { ko: '새 시작·결실·태몽을 상징해요. 새 일이나 좋은 소식이 찾아올 수 있어요.', en: 'Symbolizes a new start, fruition, or a conception dream. New work or good news may arrive.', ja: '新たな始まり·結実·胎夢の象徴。新しい仕事や良い知らせが訪れるかも。' } },
  { keywords: ['결혼', '웨딩', 'wedding', 'marriage', '結婚'], title: { ko: '결혼', en: 'Wedding', ja: '結婚' }, meaning: { ko: '맺음·결실·새 인연을 뜻해요. 일의 매듭이 잘 지어지거나 좋은 협력이 생길 수 있어요.', en: 'Means union, fruition, and new ties. Matters may tie up well or good partnerships may form.', ja: '結び·結実·新縁を意味します。物事がうまくまとまり、良い協力が生まれるかも。' } },
  { keywords: ['피', '출혈', 'blood', '血', 'ち'], title: { ko: '피', en: 'Blood', ja: '血' }, meaning: { ko: '의외로 재물의 길몽이에요. 많이 흐를수록 큰 재물·기운의 변화를 뜻하기도 해요.', en: 'Surprisingly a lucky dream of wealth. The more it flows, the bigger the wealth or shift in energy.', ja: '意外にも財の吉夢。多く流れるほど大きな財·気の変化を意味することも。' } },
  { keywords: ['차', '자동차', '운전', 'car', 'driving', '車', 'くるま'], title: { ko: '자동차', en: 'Car', ja: '車' }, meaning: { ko: '내 삶의 방향·추진력을 상징해요. 잘 달리면 일이 순조롭고, 막히면 잠시 점검할 때예요.', en: 'Symbolizes your life direction and drive. Smooth driving means things flow; getting stuck means time to check in.', ja: '人生の方向·推進力の象徴。よく走れば順調、詰まれば点検の時です。' } },
  { keywords: ['산', '등산', 'mountain', '山', 'やま'], title: { ko: '산', en: 'Mountain', ja: '山' }, meaning: { ko: '목표·과정을 뜻해요. 오를수록 성취가 가까워지고, 정상에 서면 큰 결실의 신호예요.', en: 'Means a goal and its process. Climbing brings achievement closer; reaching the top signals great fruition.', ja: '目標·過程を意味します。登るほど成就が近づき、頂上に立てば大きな結実の兆し。' } },
  { keywords: ['꽃', '꽃밭', 'flower', '花', 'はな'], title: { ko: '꽃', en: 'Flower', ja: '花' }, meaning: { ko: '사랑·번영·좋은 소식을 상징해요. 활짝 핀 꽃일수록 기쁜 일이 따라요.', en: 'Symbolizes love, prosperity, and good news. The more it blooms, the more joy follows.', ja: '愛·繁栄·良い知らせの象徴。満開なほど嬉しい事が伴います。' } },
  { keywords: ['비', '소나기', 'rain', '雨', 'あめ'], title: { ko: '비', en: 'Rain', ja: '雨' }, meaning: { ko: '정화와 새 출발을 뜻해요. 비 온 뒤 맑아지듯 답답한 일이 풀리는 신호로 봐요.', en: 'Means cleansing and a fresh start. Like clearing skies after rain, stuck matters resolve.', ja: '浄化と新出発を意味します。雨上がりのように、滞った事が解ける兆し。' } },
  { keywords: ['눈', '설경', 'snow', '雪', 'ゆき'], title: { ko: '눈(雪)', en: 'Snow', ja: '雪' }, meaning: { ko: '깨끗한 정리·기다림을 상징해요. 쌓인 눈은 축적된 복, 녹는 눈은 묵은 일의 해소예요.', en: 'Symbolizes clean order and waiting. Piled snow is accumulated fortune; melting snow is the release of old matters.', ja: '清らかな整理·待ちの象徴。積もる雪は蓄えた福、溶ける雪は古い事の解消です。' } },
  { keywords: ['별', '달', '해', '태양', 'star', 'moon', 'sun', '星', '月', '太陽'], title: { ko: '해·달·별', en: 'Sun·Moon·Star', ja: '日·月·星' }, meaning: { ko: '명예·귀인·소망을 상징하는 길몽이에요. 밝게 빛날수록 좋은 기회와 인정이 따라요.', en: 'A lucky dream of honor, patrons, and wishes. The brighter they shine, the more opportunity and recognition follow.', ja: '名誉·貴人·願いを象徴する吉夢。明るく輝くほど好機と評価が伴います。' } },
  { keywords: ['물고기', '잉어', 'fish', 'carp', '魚', 'さかな'], title: { ko: '물고기', en: 'Fish', ja: '魚' }, meaning: { ko: '재물·태몽·기회를 뜻해요. 잡거나 품으면 금전운·좋은 소식이 따라요.', en: 'Means wealth, a conception dream, or opportunity. Catching or holding one brings money luck and good news.', ja: '財·胎夢·機会を意味します。捕る·抱くと金運·良い知らせが伴います。' } },
  { keywords: ['새', '독수리', '학', 'bird', '鳥', 'とり'], title: { ko: '새', en: 'Bird', ja: '鳥' }, meaning: { ko: '소식·자유·비상을 상징해요. 높이 나는 새는 발전을, 품에 든 새는 귀한 인연을 뜻해요.', en: 'Symbolizes news, freedom, and soaring. A high-flying bird means growth; one in your arms means a precious bond.', ja: '便り·自由·飛翔の象徴。高く飛ぶ鳥は発展、懐に入る鳥は貴い縁を意味します。' } },
  { keywords: ['개', '강아지', 'dog', '犬', 'いぬ'], title: { ko: '개', en: 'Dog', ja: '犬' }, meaning: { ko: '의리·도움·인연을 상징해요. 따르는 개는 든든한 조력자, 무는 개는 가까운 이와의 마찰 주의예요.', en: 'Symbolizes loyalty, help, and bonds. A following dog is a reliable ally; a biting dog warns of friction with someone close.', ja: '義理·助け·縁の象徴。懐く犬は頼れる味方、噛む犬は身近な人との摩擦に注意。' } },
  { keywords: ['고양이', 'cat', '猫', 'ねこ'], title: { ko: '고양이', en: 'Cat', ja: '猫' }, meaning: { ko: '예민함·은밀한 기운을 상징해요. 친근하면 좋은 인연, 사납다면 주변 관계를 살필 때예요.', en: 'Symbolizes sensitivity and subtle energy. Friendly means good ties; fierce means time to check your relationships.', ja: '繊細さ·密やかな気の象徴。なつけば良い縁、荒ければ周囲の関係を見直す時。' } },
  { keywords: ['벌레', '거미', '곤충', 'bug', 'spider', '虫', 'むし'], title: { ko: '벌레', en: 'Bug', ja: '虫' }, meaning: { ko: '작은 근심이나 정리할 일을 뜻해요. 잡거나 쫓으면 걱정거리가 해소되는 신호예요.', en: 'Means small worries or things to sort out. Catching or chasing them away signals worries resolving.', ja: '小さな心配や片付ける事を意味します。捕る·追い払うと悩みが解消する兆し。' } },
  { keywords: ['떨어지다', '추락', 'fall', '落ちる'], title: { ko: '떨어지는 꿈', en: 'Falling', ja: '落ちる夢' }, meaning: { ko: '긴장·전환의 신호예요. 두려움보다 새 단계로 넘어가는 과정으로 보면 마음이 가벼워져요.', en: 'A signal of tension and transition. Seeing it as crossing into a new stage—rather than fear—lightens the heart.', ja: '緊張·転換の兆し。恐れより、新段階へ移る過程と見れば心が軽くなります。' } },
  { keywords: ['쫓기다', '도망', 'chased', 'escape', '追われる'], title: { ko: '쫓기는 꿈', en: 'Being Chased', ja: '追われる夢' }, meaning: { ko: '미뤄둔 일·부담을 뜻해요. 마주해 해결하면 풀리니, 피하던 일을 정리할 때예요.', en: 'Means postponed tasks or burdens. Facing and solving them resolves it—time to sort out what you avoided.', ja: '先延ばしの事·負担を意味します。向き合えば解ける—避けた事を片付ける時。' } },
  { keywords: ['시험', '합격', 'exam', 'test', '試験'], title: { ko: '시험', en: 'Exam', ja: '試験' }, meaning: { ko: '평가·관문을 상징해요. 결과보다 준비·도전의 자세가 길흉을 가르니 차분히 임하면 좋아요.', en: 'Symbolizes evaluation and a gateway. Your readiness matters more than the result, so stay calm.', ja: '評価·関門の象徴。結果より準備·挑戦の姿勢が吉凶を分けるので、落ち着いて臨んで。' } },
  { keywords: ['집', '건물', '이사', 'house', 'home', '家', 'いえ'], title: { ko: '집', en: 'House', ja: '家' }, meaning: { ko: '나의 기반·안정을 상징해요. 새 집은 변화와 발전, 무너지면 기반을 다질 때라는 신호예요.', en: 'Symbolizes your foundation and stability. A new house means change and growth; collapse means time to shore up your base.', ja: '基盤·安定の象徴。新居は変化と発展、崩れれば基盤を固める時の兆し。' } },
  { keywords: ['반지', '목걸이', 'ring', 'necklace', '指輪'], title: { ko: '반지·장신구', en: 'Ring·Jewelry', ja: '指輪·装身具' }, meaning: { ko: '인연·약속·귀한 것을 뜻해요. 받으면 좋은 인연·소식이, 잃으면 관계를 돌볼 때예요.', en: 'Means bonds, promises, and precious things. Receiving brings good ties or news; losing means tend to a relationship.', ja: '縁·約束·貴い物を意味します。受け取れば良縁·便り、失えば関係を顧みる時。' } },
  { keywords: ['거울', 'mirror', '鏡', 'かがみ'], title: { ko: '거울', en: 'Mirror', ja: '鏡' }, meaning: { ko: '나를 비추는 성찰을 상징해요. 맑은 거울은 자기 이해와 좋은 변화의 신호예요.', en: 'Symbolizes self-reflection. A clear mirror signals self-understanding and good change.', ja: '自分を映す省察の象徴。澄んだ鏡は自己理解と良い変化の兆し。' } },
  { keywords: ['비행기', '여행', 'airplane', 'travel', '飛行機', '旅行'], title: { ko: '비행기·여행', en: 'Airplane·Travel', ja: '飛行機·旅行' }, meaning: { ko: '도약·새로운 도전을 뜻해요. 멀리 떠나는 꿈은 환경 변화와 큰 기회의 신호예요.', en: 'Means a leap and new challenge. Traveling far signals a change of setting and big opportunity.', ja: '飛躍·新たな挑戦を意味します。遠くへ発つ夢は環境変化と大きな機会の兆し。' } },
  { keywords: ['신발', '구두', 'shoes', '靴', 'くつ'], title: { ko: '신발', en: 'Shoes', ja: '靴' }, meaning: { ko: '동반자·기회·새 출발을 상징해요. 새 신발은 좋은 인연이나 새 일이 시작될 결이에요.', en: 'Symbolizes a companion, opportunity, and a fresh start. New shoes mean good ties or new work beginning.', ja: '伴侶·機会·新出発の象徴。新しい靴は良縁や新しい仕事が始まる兆し。' } },
  { keywords: ['머리카락', '머리', '미용실', 'hair', '髪', 'かみ'], title: { ko: '머리카락', en: 'Hair', ja: '髪' }, meaning: { ko: '생각·건강·자신감을 뜻해요. 자르는 꿈은 묵은 고민을 털고 가벼워지는 변화로 봐요.', en: 'Means thoughts, health, and confidence. Cutting it means shedding old worries and lightening up.', ja: '考え·健康·自信を意味します。切る夢は古い悩みを払い、軽くなる変化と見ます。' } },
  { keywords: ['옷', '한복', '드레스', 'clothes', 'dress', '服', 'ふく'], title: { ko: '옷', en: 'Clothes', ja: '服' }, meaning: { ko: '신분·역할·이미지를 상징해요. 새 옷·고운 옷은 인정·승진·좋은 자리의 길몽이에요.', en: 'Symbolizes status, role, and image. New or fine clothes are a lucky dream of recognition, promotion, or a good position.', ja: '身分·役割·イメージの象徴。新しい·美しい服は評価·昇進·良い地位の吉夢。' } },
  { keywords: ['책', '공부', 'book', 'study', '本', 'ほん'], title: { ko: '책', en: 'Book', ja: '本' }, meaning: { ko: '지식·기회·배움운을 뜻해요. 시험이나 새 일을 앞뒀다면 준비가 결실로 이어지는 신호예요.', en: 'Means knowledge, opportunity, and learning luck. Before an exam or new work, it signals preparation bearing fruit.', ja: '知識·機会·学びの運を意味します。試験や新しい仕事を控えるなら、準備が実る兆し。' } },
  { keywords: ['편지', '전화', '문자', '소식', 'letter', 'call', '手紙', '電話'], title: { ko: '소식', en: 'News', ja: '便り' }, meaning: { ko: '기다리던 연락·기회를 뜻해요. 반가운 소식이나 새로운 인연이 닿을 수 있어요.', en: 'Means an awaited message or chance. Welcome news or a new connection may reach you.', ja: '待っていた連絡·機会を意味します。嬉しい便りや新しい縁が届くかも。' } },
  { keywords: ['밥', '음식', '식사', 'food', 'meal', '食事', 'ごはん'], title: { ko: '음식', en: 'Food', ja: '食事' }, meaning: { ko: '재물·건강·정을 상징해요. 맛있게 먹는 꿈은 풍요와 좋은 컨디션의 길몽이에요.', en: 'Symbolizes wealth, health, and affection. Eating well is a lucky dream of abundance and good condition.', ja: '財·健康·情の象徴。美味しく食べる夢は豊かさと好調の吉夢。' } },
  { keywords: ['과일', '사과', '복숭아', 'fruit', '果物', 'くだもの'], title: { ko: '과일', en: 'Fruit', ja: '果物' }, meaning: { ko: '결실·성취·태몽을 뜻해요. 잘 익은 과일을 얻으면 노력의 보상이 따라요.', en: 'Means fruition, achievement, or a conception dream. Getting ripe fruit brings reward for your efforts.', ja: '結実·成就·胎夢を意味します。熟した果物を得れば努力の報いが伴います。' } },
  { keywords: ['술', '잔치', 'alcohol', 'party', '酒', 'さけ'], title: { ko: '술·잔치', en: 'Drinks·Feast', ja: '酒·宴' }, meaning: { ko: '인간관계·즐거움을 상징해요. 흥겨우면 좋은 인연, 과하면 말·관계를 살필 때예요.', en: 'Symbolizes relationships and joy. Festive means good ties; excess means watch your words and relations.', ja: '人間関係·楽しみの象徴。賑やかなら良縁、過ぎれば言葉·関係に注意。' } },
  { keywords: ['길', '도로', '갈림길', 'road', 'path', '道', 'みち'], title: { ko: '길', en: 'Road', ja: '道' }, meaning: { ko: '인생의 방향·선택을 뜻해요. 길이 트이면 일이 풀리고, 갈림길은 중요한 결정을 앞둔 신호예요.', en: 'Means life direction and choice. An open road means things flow; a fork signals a key decision ahead.', ja: '人生の方向·選択を意味します。道が開ければ順調、分かれ道は重要な決断の兆し。' } },
  { keywords: ['계단', '엘리베이터', 'stairs', '階段'], title: { ko: '계단', en: 'Stairs', ja: '階段' }, meaning: { ko: '단계·발전을 상징해요. 오르면 성장·승진, 내려가면 한 박자 정비할 때로 봐요.', en: 'Symbolizes steps and growth. Going up means growth or promotion; going down means time to regroup.', ja: '段階·発展の象徴。上れば成長·昇進、下れば一息整える時と見ます。' } },
  { keywords: ['다리', '교량', 'bridge', '橋', 'はし'], title: { ko: '다리(橋)', en: 'Bridge', ja: '橋' }, meaning: { ko: '연결·전환·인연을 뜻해요. 건너면 새 국면으로 넘어가는 좋은 변화의 신호예요.', en: 'Means connection, transition, and ties. Crossing it signals a good change into a new phase.', ja: '繋がり·転換·縁を意味します。渡れば新局面へ移る良い変化の兆し。' } },
  { keywords: ['우물', '샘', 'well', 'spring', '井戸'], title: { ko: '우물', en: 'Well', ja: '井戸' }, meaning: { ko: '재물·지혜의 원천을 상징해요. 맑은 물이 가득하면 꾸준한 재물복의 길몽이에요.', en: 'Symbolizes a source of wealth and wisdom. Full of clear water, it is a lucky dream of steady wealth.', ja: '財·知恵の源の象徴。澄んだ水が満ちれば、着実な財福の吉夢。' } },
  { keywords: ['도둑', '강도', 'thief', '泥棒'], title: { ko: '도둑', en: 'Thief', ja: '泥棒' }, meaning: { ko: '뜻밖의 변화를 뜻해요. 의외로 재물·기회가 들어오는 반대 해몽으로 보기도 해요.', en: 'Means unexpected change. By reverse reading, it can even mean wealth or opportunity coming in.', ja: '思わぬ変化を意味します。逆夢として、意外にも財·機会が入ると見ることも。' } },
  { keywords: ['경찰', '군인', 'police', 'soldier', '警察'], title: { ko: '경찰·군인', en: 'Police·Soldier', ja: '警察·軍人' }, meaning: { ko: '질서·보호·귀인을 상징해요. 도움을 받으면 든든한 조력자가 나타날 신호예요.', en: 'Symbolizes order, protection, and a patron. Receiving help signals a reliable ally appearing.', ja: '秩序·保護·貴人の象徴。助けられれば頼れる味方が現れる兆し。' } },
  { keywords: ['학교', '교실', 'school', '学校'], title: { ko: '학교', en: 'School', ja: '学校' }, meaning: { ko: '배움·관계·과거를 뜻해요. 새 배움이나 인연을 다시 잇는 계기가 생길 수 있어요.', en: 'Means learning, relationships, and the past. A chance for new learning or reconnecting may arise.', ja: '学び·関係·過去を意味します。新たな学びや縁を結び直す契機があるかも。' } },
  { keywords: ['시계', '시간', 'clock', 'time', '時計'], title: { ko: '시계', en: 'Clock', ja: '時計' }, meaning: { ko: '때·기회·결단을 상징해요. 지금이 무언가를 시작하거나 매듭지을 적기라는 신호예요.', en: 'Symbolizes timing, opportunity, and decision. It signals now is the time to start or wrap something up.', ja: '時·機会·決断の象徴。今が何かを始める·締めくくる好機という兆し。' } },
  { keywords: ['토하다', '구토', 'vomit', '吐く'], title: { ko: '토하는 꿈', en: 'Vomiting', ja: '吐く夢' }, meaning: { ko: '묵은 것을 비우는 정화를 뜻해요. 답답함·근심이 빠져나가 가벼워지는 길몽이에요.', en: 'Means a cleansing that empties out the old. A lucky dream of stuffiness and worry leaving, lightening you.', ja: '古いものを出す浄化を意味します。重さ·悩みが抜け、軽くなる吉夢。' } },
  { keywords: ['울다', '눈물', 'cry', 'tears', '泣く'], title: { ko: '우는 꿈', en: 'Crying', ja: '泣く夢' }, meaning: { ko: '쌓인 감정의 해소를 뜻해요. 실컷 울고 나면 막힌 일이 풀리는 좋은 신호로 봐요.', en: 'Means release of pent-up emotion. A good hard cry signals stuck matters opening up.', ja: '溜まった感情の解消を意味します。思い切り泣けば、滞った事が解ける良い兆し。' } },
  { keywords: ['싸우다', '싸움', '다툼', 'fight', '喧嘩'], title: { ko: '싸우는 꿈', en: 'Fighting', ja: '喧嘩の夢' }, meaning: { ko: '긴장의 해소·경쟁을 뜻해요. 이기면 일이 풀리고, 화해하면 관계가 깊어지는 결이에요.', en: 'Means release of tension and competition. Winning means things resolve; making up deepens the bond.', ja: '緊張の解消·競争を意味します。勝てば物事が解け、仲直りすれば関係が深まります。' } },
  { keywords: ['날다', '날아', '비행', '하늘', 'fly', 'flying', '飛ぶ', '空'], title: { ko: '하늘을 나는 꿈', en: 'Flying', ja: '空を飛ぶ夢' }, meaning: { ko: '자유·도약·성취욕을 뜻해요. 높이 날수록 목표에 가까워지고 자신감이 차오르는 신호예요.', en: 'Means freedom, a leap, and ambition. The higher you fly, the closer your goal and the more confidence rises.', ja: '自由·飛躍·向上心を意味します。高く飛ぶほど目標に近づき、自信が満ちる兆し。' } },
  { keywords: ['벌거벗', '나체', '알몸', 'naked', '裸'], title: { ko: '벌거벗은 꿈', en: 'Being Naked', ja: '裸の夢' }, meaning: { ko: '솔직함·새 출발을 뜻해요. 부끄럽더라도 있는 그대로 드러내며 새롭게 시작할 때라는 신호예요.', en: 'Means honesty and a fresh start. Even if embarrassing, it signals showing your true self and beginning anew.', ja: '率直さ·新出発を意味します。恥ずかしくとも、ありのままを見せ新しく始める時の兆し。' } },
  { keywords: ['바다', 'sea', 'ocean', '海', 'うみ'], title: { ko: '바다', en: 'Sea', ja: '海' }, meaning: { ko: '넓은 기회·감정의 흐름을 상징해요. 잔잔하면 안정, 파도가 크면 큰 변화와 도전의 때예요.', en: 'Symbolizes vast opportunity and the flow of emotion. Calm means stability; big waves mean change and challenge.', ja: '広い機会·感情の流れの象徴。穏やかなら安定、波が大きければ変化と挑戦の時。' } },
  { keywords: ['무지개', 'rainbow', '虹', 'にじ'], title: { ko: '무지개', en: 'Rainbow', ja: '虹' }, meaning: { ko: '행운·소망 성취의 길몽이에요. 오랜 바람이 이뤄지거나 좋은 소식이 따라와요.', en: 'A lucky dream of fortune and wishes fulfilled. A long-held hope may come true, or good news follows.', ja: '幸運·願望成就の吉夢。長年の願いが叶うか、良い知らせが続きます。' } },
  { keywords: ['번개', '천둥', '벼락', 'lightning', 'thunder', '雷'], title: { ko: '번개·천둥', en: 'Lightning·Thunder', ja: '雷' }, meaning: { ko: '큰 변화의 계기를 뜻해요. 놀랍지만 묵은 것을 깨고 새 국면이 열리는 강한 전환의 신호예요.', en: 'Means a trigger for big change. Startling but a strong turn—breaking the old and opening a new phase.', ja: '大きな変化の契機を意味します。驚くが、古きを破り新局面が開く強い転換の兆し。' } },
  { keywords: ['지진', 'earthquake', '地震'], title: { ko: '지진', en: 'Earthquake', ja: '地震' }, meaning: { ko: '기반이 흔들리는 변화를 뜻해요. 두렵더라도 낡은 틀을 재정비하고 더 단단해지는 계기로 봐요.', en: 'Means a foundation-shaking change. Though scary, see it as resetting the old frame and growing sturdier.', ja: '基盤が揺れる変化を意味します。怖くとも、古い枠を立て直し強くなる契機と見ます。' } },
  { keywords: ['사자', 'lion', 'ライオン', '獅子'], title: { ko: '사자', en: 'Lion', ja: 'ライオン' }, meaning: { ko: '권위·명예·리더십을 상징해요. 당당하게 앞에 서거나 인정받는 일이 따라올 수 있어요.', en: 'Symbolizes authority, honor, and leadership. Standing proud in front or being recognized may follow.', ja: '権威·名誉·リーダーシップの象徴。堂々と前に立つ·認められる事が伴うかも。' } },
  { keywords: ['곰', 'bear', '熊', 'くま'], title: { ko: '곰', en: 'Bear', ja: '熊' }, meaning: { ko: '든든함·인내·재물을 뜻해요. 묵직하게 버티며 큰 복을 품는 길몽으로 봐요.', en: 'Means dependability, patience, and wealth. A lucky dream of holding steady and embracing great fortune.', ja: '頼もしさ·忍耐·財を意味します。どっしり耐え、大きな福を抱く吉夢と見ます。' } },
  { keywords: ['코끼리', 'elephant', '象', 'ぞう'], title: { ko: '코끼리', en: 'Elephant', ja: '象' }, meaning: { ko: '큰 복·귀인·재물을 상징하는 길몽이에요. 든든한 도움이나 큰 기회가 들어올 수 있어요.', en: 'A lucky dream symbolizing great fortune, a patron, and wealth. Solid help or a big chance may come.', ja: '大きな福·貴人·財を象徴する吉夢。頼れる助けや大きな機会が入るかも。' } },
  { keywords: ['거북', '거북이', '자라', 'turtle', '亀', 'かめ'], title: { ko: '거북', en: 'Turtle', ja: '亀' }, meaning: { ko: '장수·재물·꾸준한 복을 뜻하는 대표 길몽이에요. 느려도 안정적으로 쌓이는 행운이에요.', en: 'A classic lucky dream of longevity, wealth, and steady fortune. Slow but stable luck building up.', ja: '長寿·財·着実な福を意味する代表的な吉夢。遅くとも安定して積もる幸運です。' } },
  { keywords: ['나비', 'butterfly', '蝶', 'ちょう'], title: { ko: '나비', en: 'Butterfly', ja: '蝶' }, meaning: { ko: '변화·자유·연애운을 상징해요. 새 인연이나 마음의 변화, 가벼운 설렘이 따라올 수 있어요.', en: 'Symbolizes change, freedom, and romance. A new bond, a shift of heart, or light excitement may follow.', ja: '変化·自由·恋愛運の象徴。新縁や心の変化、軽いときめきが伴うかも。' } },
  { keywords: ['말', '경마', '말타기', 'horse', '馬', 'うま'], title: { ko: '말', en: 'Horse', ja: '馬' }, meaning: { ko: '활동·이동·성취를 뜻해요. 힘차게 달리는 말은 일이 빠르게 풀리는 길몽이에요.', en: 'Means activity, movement, and achievement. A galloping horse is a lucky dream of things resolving fast.', ja: '活動·移動·成就を意味します。力強く走る馬は物事が速く運ぶ吉夢。' } },
  { keywords: ['소', '황소', 'ox', 'cow', '牛', 'うし'], title: { ko: '소', en: 'Ox', ja: '牛' }, meaning: { ko: '성실·재물·풍요를 상징해요. 부지런히 일군 결실이 쌓이는 든든한 길몽이에요.', en: 'Symbolizes diligence, wealth, and abundance. A solid lucky dream of diligently earned fruit piling up.', ja: '誠実·財·豊かさの象徴。勤勉に築いた実りが積もる頼もしい吉夢。' } },
  { keywords: ['임산부', '임신부', '배부른', 'pregnant', '妊婦'], title: { ko: '임산부', en: 'Pregnant Woman', ja: '妊婦' }, meaning: { ko: '결실·새 시작·풍요를 뜻해요. 새 일이나 좋은 소식이 무르익는 신호예요.', en: 'Means fruition, a new start, and abundance. New work or good news is ripening.', ja: '結実·新たな始まり·豊かさを意味します。新しい仕事や良い知らせが熟す兆し。' } },
  { keywords: ['노인', '할머니', '할아버지', '어르신', 'elder', '老人'], title: { ko: '노인', en: 'Elder', ja: '老人' }, meaning: { ko: '지혜·귀인·조상의 보살핌을 상징해요. 어려운 일에 도움이나 깨달음이 따라올 수 있어요.', en: 'Symbolizes wisdom, a patron, and ancestral care. Help or insight may come in hard times.', ja: '知恵·貴人·先祖の加護の象徴。困難に助けや気づきが伴うかも。' } },
  { keywords: ['옛애인', '전애인', '헤어진', 'ex', '元恋人'], title: { ko: '옛 인연', en: 'Past Love', ja: '昔の縁' }, meaning: { ko: '마음 정리·미련의 흐름을 뜻해요. 지난 감정을 매듭짓고 앞으로 나아갈 때라는 신호예요.', en: 'Means processing the heart and lingering feelings. A signal to tie off the past and move forward.', ja: '心の整理·未練の流れを意味します。過去の感情を結び、前へ進む時の兆し。' } },
  { keywords: ['연예인', '유명인', '스타', 'celebrity', '芸能人'], title: { ko: '연예인', en: 'Celebrity', ja: '芸能人' }, meaning: { ko: '인정 욕구·기회를 상징해요. 주목받거나 좋은 기회와 인연이 들어올 수 있어요.', en: 'Symbolizes a desire for recognition and opportunity. Attention or good chances and ties may come.', ja: '承認欲求·機会の象徴。注目を浴びたり、良い機会·縁が入るかも。' } },
  { keywords: ['배', '보트', '항해', '선박', 'boat', 'ship', '船', 'ふね'], title: { ko: '배(船)', en: 'Boat', ja: '船' }, meaning: { ko: '인생의 항로·목표를 뜻해요. 순항하면 일이 잘 풀리고, 목적지가 보이면 결실이 가까워요.', en: 'Means your life voyage and goal. Smooth sailing means things go well; sighting the destination means fruition is near.', ja: '人生の航路·目標を意味します。順調なら物事が運び、目的地が見えれば結実が近い。' } },
  { keywords: ['기차', '지하철', '전철', 'train', '電車', '汽車'], title: { ko: '기차', en: 'Train', ja: '電車' }, meaning: { ko: '정해진 길·인연의 흐름을 상징해요. 제때 타면 기회를 잡고, 놓쳐도 다음 기회가 와요.', en: 'Symbolizes a set path and the flow of fate. Boarding on time seizes a chance; missing it, another comes.', ja: '定まった道·縁の流れの象徴。間に合えば機会を掴み、逃しても次が来ます。' } },
  { keywords: ['무덤', '묘지', '조상', 'grave', 'tomb', '墓'], title: { ko: '무덤', en: 'Grave', ja: '墓' }, meaning: { ko: '의외로 재물·조상의 음덕을 뜻하는 길몽이에요. 든든한 뒷받침과 안정이 따라올 수 있어요.', en: 'Surprisingly a lucky dream of wealth and ancestral blessing. Solid support and stability may follow.', ja: '意外にも財·先祖の陰徳を意味する吉夢。頼れる後ろ盾と安定が伴うかも。' } },
  { keywords: ['화장실', '변기', 'toilet', 'restroom', 'トイレ'], title: { ko: '화장실', en: 'Toilet', ja: 'トイレ' }, meaning: { ko: '재물과 해소를 상징해요. 시원하게 비우는 꿈은 근심이 풀리고 금전운이 따르는 길몽이에요.', en: 'Symbolizes wealth and release. A relieving, emptying dream is a lucky one—worries ease and money luck follows.', ja: '財と解消の象徴。すっきり出す夢は悩みが解け金運が伴う吉夢。' } },
  { keywords: ['목욕', '샤워', '씻', 'bath', 'shower', '風呂'], title: { ko: '목욕', en: 'Bath', ja: '入浴' }, meaning: { ko: '정화·새 출발을 뜻해요. 깨끗이 씻는 꿈은 묵은 일이 정리되고 새 기운이 드는 신호예요.', en: 'Means cleansing and a fresh start. Washing clean signals old matters clearing and new energy entering.', ja: '浄化·新出発を意味します。きれいに洗う夢は古い事が片付き、新しい気が入る兆し。' } },
  { keywords: ['청소', '빨래', 'cleaning', 'laundry', '掃除'], title: { ko: '청소', en: 'Cleaning', ja: '掃除' }, meaning: { ko: '정리·새 기운을 상징해요. 깔끔히 치우는 꿈은 복잡한 일이 풀리고 운이 트이는 결이에요.', en: 'Symbolizes tidying and new energy. Cleaning up neatly means tangled matters resolving and luck opening.', ja: '整理·新しい気の象徴。きれいに片付ける夢は複雑な事が解け、運が開く流れ。' } },
  { keywords: ['떡', '잔치음식', 'rice cake', '餅'], title: { ko: '떡', en: 'Rice Cake', ja: '餅' }, meaning: { ko: '경사·재물·나눔을 뜻해요. 떡을 받거나 나누면 기쁜 일과 풍요가 따라오는 길몽이에요.', en: 'Means a happy event, wealth, and sharing. Receiving or sharing rice cake is a lucky dream of joy and abundance.', ja: '慶事·財·分かち合いを意味します。餅を受け取る·分けると喜び事と豊かさが伴う吉夢。' } },
  { keywords: ['칼', '가위', 'knife', 'blade', '刃物'], title: { ko: '칼', en: 'Knife', ja: '刃物' }, meaning: { ko: '결단·정리를 상징해요. 무섭다기보다 묵은 것을 끊고 분명히 매듭짓는 힘으로 봐요.', en: 'Symbolizes decision and clearing. Less scary, more the power to cut the old and firmly settle things.', ja: '決断·整理の象徴。怖いというより、古きを断ち明確に締めくくる力と見ます。' } },
  { keywords: ['늦다', '지각', '놓치', 'late', 'miss', '遅刻'], title: { ko: '늦는 꿈', en: 'Being Late', ja: '遅れる夢' }, meaning: { ko: '조급함·준비의 신호예요. 서두르기보다 한 박자 점검하면 중요한 걸 놓치지 않아요.', en: 'A signal of haste and preparation. Rather than rush, a beat of checking keeps you from missing what matters.', ja: '焦り·準備の兆し。急ぐより一息点検すれば、大事を逃しません。' } },
  { keywords: ['웃다', '웃음', 'laugh', 'smile', '笑う'], title: { ko: '웃는 꿈', en: 'Laughing', ja: '笑う夢' }, meaning: { ko: '기쁨·해소를 뜻해요. 환하게 웃는 꿈은 좋은 일과 마음의 여유가 따라오는 길몽이에요.', en: 'Means joy and release. Laughing brightly is a lucky dream of good things and ease of heart.', ja: '喜び·解消を意味します。明るく笑う夢は良い事と心の余裕が伴う吉夢。' } },
];

// 인기 키워드(칩) — 언어별 표시 + 검색
export const DREAM_POPULAR: Tri[] = [
  { ko: '돼지', en: 'Pig', ja: '豚' }, { ko: '뱀', en: 'Snake', ja: '蛇' }, { ko: '용', en: 'Dragon', ja: '龍' },
  { ko: '물', en: 'Water', ja: '水' }, { ko: '불', en: 'Fire', ja: '火' }, { ko: '돈', en: 'Money', ja: 'お金' },
  { ko: '이빨', en: 'Teeth', ja: '歯' }, { ko: '똥', en: 'Feces', ja: '糞' }, { ko: '아기', en: 'Baby', ja: '赤ちゃん' },
  { ko: '죽음', en: 'Death', ja: '死' }, { ko: '거북', en: 'Turtle', ja: '亀' }, { ko: '바다', en: 'Sea', ja: '海' },
  { ko: '날다', en: 'Flying', ja: '飛ぶ' }, { ko: '무지개', en: 'Rainbow', ja: '虹' },
];

/** 검색어(어느 언어든) → keywords 부분일치. title 도 매칭. */
export function searchDreams(q: string): DreamEntry[] {
  const s = q.trim().toLowerCase();
  if (!s) return [];
  const lang = L();
  return DREAM_DICT.filter((e) =>
    e.title[lang].toLowerCase().includes(s) ||
    e.keywords.some((k) => k.toLowerCase().includes(s) || s.includes(k.toLowerCase())),
  );
}

/** 항목의 현재 언어 제목·뜻. */
export function dreamTitle(e: DreamEntry): string { return e.title[L()]; }
export function dreamMeaning(e: DreamEntry): string { return e.meaning[L()]; }
/** 인기 칩의 현재 언어 라벨. */
export function popularLabel(p: Tri): string { return p[L()]; }
